
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  2 2025 09:51:20 IST (May  2 2025 04:21:20 UTC)

// Verification Directory fv/sram_sp_16384d_36w_16m_8b 

module sram_sp_16384d_36w_16m_8b(CLK, CEN, GWEN, A, D, WEN, Q);
  input CLK, CEN, GWEN;
  input [13:0] A;
  input [35:0] D, WEN;
  output [35:0] Q;
  wire CLK, CEN, GWEN;
  wire [13:0] A;
  wire [35:0] D, WEN;
  wire [35:0] Q;
  wire [35:0] q0;
  wire [35:0] q1;
  wire csb0, csb1, web0, web1;
  SPRAM_8192x36 u_bank0_my_sram(.CE (CLK), .OEB (1'b0), .CSB (csb0),
       .WEB (web0), .A (A[12:0]), .I (D), .O (q0));
  SPRAM_8192x36 u_bank1_my_sram(.CE (CLK), .OEB (1'b0), .CSB (csb1),
       .WEB (web1), .A (A[12:0]), .I (D), .O (q1));
  CLKMX2X6 g1049__2398(.A (q0[6]), .B (q1[6]), .S0 (A[13]), .Y (Q[6]));
  NAND2BX4 g1050__5107(.AN (csb1), .B (GWEN), .Y (web1));
  CLKMX2X6 g1051__6260(.A (q0[29]), .B (q1[29]), .S0 (A[13]), .Y
       (Q[29]));
  CLKMX2X6 g1052__4319(.A (q0[22]), .B (q1[22]), .S0 (A[13]), .Y
       (Q[22]));
  CLKMX2X6 g1053__8428(.A (q0[9]), .B (q1[9]), .S0 (A[13]), .Y (Q[9]));
  CLKMX2X6 g1054__5526(.A (q0[8]), .B (q1[8]), .S0 (A[13]), .Y (Q[8]));
  CLKMX2X6 g1055__6783(.A (q0[7]), .B (q1[7]), .S0 (A[13]), .Y (Q[7]));
  CLKMX2X6 g1056__3680(.A (q0[28]), .B (q1[28]), .S0 (A[13]), .Y
       (Q[28]));
  CLKMX2X6 g1057__1617(.A (q0[21]), .B (q1[21]), .S0 (A[13]), .Y
       (Q[21]));
  NAND2BX4 g1058__2802(.AN (csb0), .B (GWEN), .Y (web0));
  CLKMX2X6 g1059__1705(.A (q0[20]), .B (q1[20]), .S0 (A[13]), .Y
       (Q[20]));
  CLKMX2X6 g1060__5122(.A (q0[5]), .B (q1[5]), .S0 (A[13]), .Y (Q[5]));
  CLKMX2X6 g1061__8246(.A (q0[4]), .B (q1[4]), .S0 (A[13]), .Y (Q[4]));
  CLKMX2X6 g1062__7098(.A (q0[35]), .B (q1[35]), .S0 (A[13]), .Y
       (Q[35]));
  CLKMX2X6 g1063__6131(.A (q0[27]), .B (q1[27]), .S0 (A[13]), .Y
       (Q[27]));
  CLKMX2X6 g1064__1881(.A (q0[19]), .B (q1[19]), .S0 (A[13]), .Y
       (Q[19]));
  CLKMX2X6 g1065__5115(.A (q0[3]), .B (q1[3]), .S0 (A[13]), .Y (Q[3]));
  CLKMX2X6 g1066__7482(.A (q0[2]), .B (q1[2]), .S0 (A[13]), .Y (Q[2]));
  CLKMX2X6 g1067__4733(.A (q0[18]), .B (q1[18]), .S0 (A[13]), .Y
       (Q[18]));
  CLKMX2X6 g1068__6161(.A (q0[15]), .B (q1[15]), .S0 (A[13]), .Y
       (Q[15]));
  CLKMX2X6 g1069__9315(.A (q0[32]), .B (q1[32]), .S0 (A[13]), .Y
       (Q[32]));
  CLKMX2X6 g1070__9945(.A (q0[0]), .B (q1[0]), .S0 (A[13]), .Y (Q[0]));
  CLKMX2X6 g1071__2883(.A (q0[31]), .B (q1[31]), .S0 (A[13]), .Y
       (Q[31]));
  CLKMX2X6 g1072__2346(.A (q0[26]), .B (q1[26]), .S0 (A[13]), .Y
       (Q[26]));
  CLKMX2X6 g1073__1666(.A (q0[17]), .B (q1[17]), .S0 (A[13]), .Y
       (Q[17]));
  CLKMX2X6 g1074__7410(.A (q0[34]), .B (q1[34]), .S0 (A[13]), .Y
       (Q[34]));
  CLKMX2X6 g1075__6417(.A (q0[33]), .B (q1[33]), .S0 (A[13]), .Y
       (Q[33]));
  CLKMX2X6 g1076__5477(.A (q0[16]), .B (q1[16]), .S0 (A[13]), .Y
       (Q[16]));
  CLKMX2X6 g1077__2398(.A (q0[1]), .B (q1[1]), .S0 (A[13]), .Y (Q[1]));
  CLKMX2X6 g1078__5107(.A (q0[30]), .B (q1[30]), .S0 (A[13]), .Y
       (Q[30]));
  CLKMX2X6 g1079__6260(.A (q0[25]), .B (q1[25]), .S0 (A[13]), .Y
       (Q[25]));
  CLKMX2X6 g1080__4319(.A (q0[14]), .B (q1[14]), .S0 (A[13]), .Y
       (Q[14]));
  CLKMX2X6 g1081__8428(.A (q0[24]), .B (q1[24]), .S0 (A[13]), .Y
       (Q[24]));
  CLKMX2X6 g1082__5526(.A (q0[13]), .B (q1[13]), .S0 (A[13]), .Y
       (Q[13]));
  CLKMX2X6 g1083__6783(.A (q0[12]), .B (q1[12]), .S0 (A[13]), .Y
       (Q[12]));
  CLKMX2X6 g1084__3680(.A (q0[23]), .B (q1[23]), .S0 (A[13]), .Y
       (Q[23]));
  CLKMX2X6 g1085__1617(.A (q0[11]), .B (q1[11]), .S0 (A[13]), .Y
       (Q[11]));
  CLKMX2X6 g1086__2802(.A (q0[10]), .B (q1[10]), .S0 (A[13]), .Y
       (Q[10]));
  NAND2BX4 g1087__1705(.AN (CEN), .B (A[13]), .Y (csb1));
  OR2X2 g1088__5122(.A (A[13]), .B (CEN), .Y (csb0));
endmodule

