/* Generated by Tessent Shell 2022.4 at Tue Apr 22 17:35:10 IST 2025 */
module CLOCK(clk, reset, ena, pm, hh, mm, ss, scan_in_0, scan_out_0, scan_en);
  input  clk, reset, ena, scan_in_0, scan_en;
  output [7:0] hh, mm, ss;
  output pm, scan_out_0;

  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, 
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, 
       UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, 
       UNCONNECTED13, UNCONNECTED14, n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7, 
       n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19, 
       n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31, 
       n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43, 
       n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55, 
       n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67, 
       n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79, 
       n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91, 
       n_92, n_93, n_94, n_95, n_96, ts_lockup_latchn_clkc1_intno24_, 
       ts_pbuf_extsi25_;

  assign scan_out_0 = ts_lockup_latchn_clkc1_intno24_;
  SDFFR_X2 \H_reg_reg[6] (
      .CK(clk), .D(n_96), .RN(n_95), .SE(scan_en), .SI(ts_pbuf_extsi25_), .Q(hh[6]), 
      .QN(UNCONNECTED)
  );
  XOR2_X2 g2270__2398(
      .A(hh[6]), .B(n_92), .Z(n_96)
  );
  SDFFR_X1 \H_reg_reg[7] (
      .CK(clk), .D(n_94), .RN(n_95), .SE(scan_en), .SI(hh[6]), .Q(hh[7]), .QN(UNCONNECTED0)
  );
  SDFFR_X2 \H_reg_reg[5] (
      .CK(clk), .D(n_93), .RN(n_95), .SE(scan_en), .SI(hh[7]), .Q(hh[5]), .QN(UNCONNECTED1)
  );
  XNOR2_X1 g2274__5107(
      .A(n_89), .B(hh[7]), .ZN(n_94)
  );
  HA_X1 g2273__6260(
      .A(n_88), .B(hh[5]), .CO(n_92), .S(n_93)
  );
  SDFFR_X1 \M_reg_reg[7] (
      .CK(clk), .D(n_91), .RN(n_95), .SE(scan_en), .SI(hh[5]), .Q(mm[7]), .QN(UNCONNECTED2)
  );
  SDFFS_X2 \H_reg_reg[1] (
      .CK(clk), .D(n_90), .SE(scan_en), .SI(mm[7]), .SN(n_95), .Q(hh[1]), .QN(UNCONNECTED3)
  );
  SDFFR_X1 pm_reg_reg(
      .CK(clk), .D(n_86), .RN(n_95), .SE(scan_en), .SI(hh[1]), .Q(pm), .QN(UNCONNECTED4)
  );
  SDFFR_X2 \H_reg_reg[3] (
      .CK(clk), .D(n_84), .RN(n_95), .SE(scan_en), .SI(pm), .Q(hh[3]), .QN(n_43)
  );
  SDFFS_X2 \H_reg_reg[2] (
      .CK(clk), .D(n_85), .SE(scan_en), .SI(hh[3]), .SN(n_95), .Q(hh[2]), .QN(n_27)
  );
  SDFFR_X2 \M_reg_reg[3] (
      .CK(clk), .D(n_87), .RN(n_95), .SE(scan_en), .SI(hh[2]), .Q(mm[3]), .QN(n_2)
  );
  XOR2_X2 g2281__4319(
      .A(mm[7]), .B(n_78), .Z(n_91)
  );
  XOR2_X2 g2282__8428(
      .A(hh[1]), .B(n_76), .Z(n_90)
  );
  NAND3_X2 g2283__5526(
      .A1(n_88), .A2(hh[6]), .A3(hh[5]), .ZN(n_89)
  );
  SDFFR_X1 \H_reg_reg[4] (
      .CK(clk), .D(n_81), .RN(n_95), .SE(scan_en), .SI(mm[3]), .Q(hh[4]), .QN(UNCONNECTED5)
  );
  INV_X2 g2303(
      .A(n_80), .ZN(n_87)
  );
  XNOR2_X1 g2291__6783(
      .A(n_66), .B(pm), .ZN(n_86)
  );
  OAI22_X2 g2292__3680(
      .A1(n_65), .A2(n_83), .B1(n_82), .B2(n_27), .ZN(n_85)
  );
  OAI22_X2 g2293__1617(
      .A1(n_63), .A2(n_83), .B1(n_82), .B2(n_43), .ZN(n_84)
  );
  SDFFR_X2 \M_reg_reg[1] (
      .CK(clk), .D(n_69), .RN(n_95), .SE(scan_en), .SI(hh[4]), .Q(mm[1]), .QN(UNCONNECTED6)
  );
  SDFFR_X2 \S_reg_reg[5] (
      .CK(clk), .D(n_74), .RN(n_95), .SE(scan_en), .SI(mm[1]), .Q(ss[5]), .QN(UNCONNECTED7)
  );
  SDFFR_X2 \M_reg_reg[5] (
      .CK(clk), .D(n_75), .RN(n_95), .SE(scan_en), .SI(ss[5]), .Q(mm[5]), .QN(n_30)
  );
  SDFFR_X2 \M_reg_reg[4] (
      .CK(clk), .D(n_73), .RN(n_95), .SE(scan_en), .SI(mm[5]), .Q(mm[4]), .QN(n_22)
  );
  SDFFR_X1 \S_reg_reg[7] (
      .CK(clk), .D(n_71), .RN(n_95), .SE(scan_en), .SI(mm[4]), .Q(ss[7]), .QN(UNCONNECTED8)
  );
  SDFFR_X1 \M_reg_reg[6] (
      .CK(clk), .D(n_79), .RN(n_95), .SE(scan_en), .SI(ss[7]), .Q(mm[6]), .QN(UNCONNECTED9)
  );
  SDFFR_X2 \H_reg_reg[0] (
      .CK(clk), .D(n_77), .RN(n_95), .SE(scan_en), .SI(mm[6]), .Q(hh[0]), .QN(UNCONNECTED10)
  );
  SDFFR_X2 \S_reg_reg[3] (
      .CK(clk), .D(n_70), .RN(n_95), .SE(scan_en), .SI(hh[0]), .Q(ss[3]), .QN(n_0)
  );
  HA_X1 g2285__2802(
      .A(n_46), .B(hh[4]), .CO(n_88), .S(n_81)
  );
  AOI21_X2 g2305__1705(
      .A(n_68), .B1(n_54), .B2(mm[3]), .ZN(n_80)
  );
  SDFFR_X1 \M_reg_reg[2] (
      .CK(clk), .D(n_61), .RN(n_95), .SE(scan_en), .SI(ss[3]), .Q(mm[2]), .QN(n_60)
  );
  SDFFR_X2 \S_reg_reg[2] (
      .CK(clk), .D(n_59), .RN(n_95), .SE(scan_en), .SI(mm[2]), .Q(ss[2]), .QN(n_3)
  );
  SDFFR_X2 \S_reg_reg[4] (
      .CK(clk), .D(n_62), .RN(n_95), .SE(scan_en), .SI(ss[2]), .Q(ss[4]), .QN(n_19)
  );
  HA_X1 g2298__5122(
      .A(n_32), .B(mm[6]), .CO(n_78), .S(n_79)
  );
  HA_X1 g2297__8246(
      .A(n_82), .B(hh[0]), .CO(n_76), .S(n_77)
  );
  OAI22_X2 g2304__7098(
      .A1(n_72), .A2(n_25), .B1(n_48), .B2(n_30), .ZN(n_75)
  );
  OAI21_X2 g2306__6131(
      .A(n_57), .B1(n_41), .B2(n_21), .ZN(n_74)
  );
  OAI22_X2 g2307__1881(
      .A1(n_72), .A2(n_13), .B1(n_40), .B2(n_22), .ZN(n_73)
  );
  XOR2_X1 g2308__5115(
      .A(n_51), .B(ss[7]), .Z(n_71)
  );
  INV_X2 g2309(
      .A(n_67), .ZN(n_70)
  );
  XOR2_X2 g2294__7482(
      .A(mm[1]), .B(n_49), .Z(n_69)
  );
  NOR4_X1 g2327__4733(
      .A1(n_72), .A2(n_37), .A3(mm[3]), .A4(n_60), .ZN(n_68)
  );
  AOI21_X2 g2311__6161(
      .A(n_42), .B1(n_29), .B2(ss[3]), .ZN(n_67)
  );
  NAND2_X2 g2312__9315(
      .A1(n_64), .A2(n_14), .ZN(n_66)
  );
  SDFFR_X2 \M_reg_reg[0] (
      .CK(clk), .D(n_50), .RN(n_95), .SE(scan_en), .SI(ss[4]), .Q(mm[0]), .QN(UNCONNECTED11)
  );
  SDFFR_X1 \S_reg_reg[6] (
      .CK(clk), .D(n_52), .RN(n_95), .SE(scan_en), .SI(mm[0]), .Q(ss[6]), .QN(UNCONNECTED12)
  );
  AOI21_X2 g2318__9945(
      .A(n_64), .B1(n_47), .B2(hh[2]), .ZN(n_65)
  );
  AOI22_X2 g2316__2883(
      .A1(n_82), .A2(n_11), .B1(n_44), .B2(hh[3]), .ZN(n_63)
  );
  INV_X2 g2315(
      .A(n_58), .ZN(n_62)
  );
  OAI22_X2 g2320__2346(
      .A1(n_72), .A2(n_23), .B1(n_53), .B2(n_60), .ZN(n_61)
  );
  INV_X2 g2321(
      .A(n_55), .ZN(n_59)
  );
  AOI21_X2 g2317__1666(
      .A(n_35), .B1(n_56), .B2(ss[4]), .ZN(n_58)
  );
  OAI21_X2 g2319__7410(
      .A(ss[5]), .B1(n_56), .B2(n_19), .ZN(n_57)
  );
  AOI21_X2 g2324__6417(
      .A(n_34), .B1(n_16), .B2(ss[2]), .ZN(n_55)
  );
  OAI21_X2 g2325__5477(
      .A(n_53), .B1(n_26), .B2(mm[2]), .ZN(n_54)
  );
  HA_X1 g2322__2398(
      .A(n_18), .B(ss[6]), .CO(n_51), .S(n_52)
  );
  HA_X1 g2310__5107(
      .A(n_36), .B(mm[0]), .CO(n_49), .S(n_50)
  );
  AOI21_X2 g2328__6260(
      .A(n_39), .B1(n_38), .B2(n_31), .ZN(n_48)
  );
  NOR3_X2 g2329__4319(
      .A1(n_45), .A2(n_47), .A3(hh[2]), .ZN(n_64)
  );
  NOR3_X2 g2330__8428(
      .A1(n_45), .A2(n_44), .A3(n_43), .ZN(n_46)
  );
  NOR4_X1 g2338__5526(
      .A1(n_41), .A2(n_33), .A3(ss[3]), .A4(n_3), .ZN(n_42)
  );
  AOI21_X2 g2323__6783(
      .A(n_39), .B1(n_38), .B2(n_12), .ZN(n_40)
  );
  NOR2_X2 g2334__3680(
      .A1(n_39), .A2(n_37), .ZN(n_53)
  );
  INV_X2 g2331(
      .A(n_45), .ZN(n_82)
  );
  NAND2_X2 g2335__1617(
      .A1(n_36), .A2(n_38), .ZN(n_72)
  );
  NOR3_X1 g2337__2802(
      .A1(n_41), .A2(n_20), .A3(ss[4]), .ZN(n_35)
  );
  NOR3_X1 g2340__1705(
      .A1(n_41), .A2(n_33), .A3(ss[2]), .ZN(n_34)
  );
  NOR3_X2 g2341__5122(
      .A1(n_39), .A2(n_31), .A3(n_30), .ZN(n_32)
  );
  OAI21_X2 g2332__8246(
      .A(n_8), .B1(n_28), .B2(ss[2]), .ZN(n_29)
  );
  OAI21_X2 g2333__7098(
      .A(ena), .B1(n_28), .B2(n_17), .ZN(n_56)
  );
  NOR4_X2 g2347__6131(
      .A1(n_15), .A2(n_27), .A3(hh[1]), .A4(hh[0]), .ZN(n_83)
  );
  NAND2_X2 g2336__1881(
      .A1(n_36), .A2(n_26), .ZN(n_45)
  );
  SDFFR_X2 \S_reg_reg[1] (
      .CK(clk), .D(n_24), .RN(n_95), .SE(scan_en), .SI(ss[6]), .Q(ss[1]), .QN(UNCONNECTED13)
  );
  OR2_X2 g2342__5115(
      .A1(n_31), .A2(mm[5]), .ZN(n_25)
  );
  OR2_X4 g2343__7482(
      .A1(n_28), .A2(n_5), .ZN(n_41)
  );
  INV_X2 g2345(
      .A(n_26), .ZN(n_38)
  );
  INV_X2 g2346(
      .A(n_36), .ZN(n_39)
  );
  XOR2_X1 g2339__4733(
      .A(n_6), .B(ss[1]), .Z(n_24)
  );
  NOR4_X2 g2348__6161(
      .A1(n_4), .A2(n_23), .A3(n_22), .A4(n_30), .ZN(n_26)
  );
  OR3_X2 g2356__9315(
      .A1(n_20), .A2(ss[5]), .A3(n_19), .ZN(n_21)
  );
  AND4_X2 g2357__9945(
      .A1(n_17), .A2(ss[5]), .A3(ss[4]), .A4(ena), .ZN(n_18)
  );
  NOR3_X2 g2349__2883(
      .A1(n_16), .A2(n_10), .A3(n_9), .ZN(n_36)
  );
  INV_X2 g2350(
      .A(n_14), .ZN(n_15)
  );
  OR2_X2 g2352__2346(
      .A1(n_12), .A2(mm[4]), .ZN(n_13)
  );
  SDFFR_X2 \S_reg_reg[0] (
      .CK(clk), .D(n_7), .RN(n_95), .SE(scan_en), .SI(ss[1]), .Q(ss[0]), .QN(UNCONNECTED14)
  );
  NOR2_X1 g2355__1666(
      .A1(n_44), .A2(hh[3]), .ZN(n_11)
  );
  OR2_X2 g2354__7410(
      .A1(n_12), .A2(n_22), .ZN(n_31)
  );
  NOR3_X2 g2358__6417(
      .A1(n_10), .A2(n_33), .A3(n_9), .ZN(n_28)
  );
  NOR4_X2 g2353__5477(
      .A1(hh[6]), .A2(n_1), .A3(hh[5]), .A4(n_43), .ZN(n_14)
  );
  INV_X4 g2359(
      .A(n_8), .ZN(n_16)
  );
  INV_X1 g2363(
      .A(n_17), .ZN(n_20)
  );
  HA_X1 g2351__2398(
      .A(ss[0]), .B(ena), .CO(n_6), .S(n_7)
  );
  OR2_X2 g2360__5107(
      .A1(n_37), .A2(mm[2]), .ZN(n_23)
  );
  NOR2_X2 g2361__6260(
      .A1(n_33), .A2(n_5), .ZN(n_8)
  );
  OR2_X4 g2362__4319(
      .A1(n_47), .A2(n_27), .ZN(n_44)
  );
  OR3_X2 g2364__8428(
      .A1(mm[6]), .A2(mm[7]), .A3(n_2), .ZN(n_4)
  );
  NAND4_X2 g2365__5526(
      .A1(ss[3]), .A2(ss[4]), .A3(ss[5]), .A4(n_3), .ZN(n_10)
  );
  OR3_X2 g2366__6783(
      .A1(n_37), .A2(n_2), .A3(n_60), .ZN(n_12)
  );
  NOR3_X2 g2367__3680(
      .A1(n_33), .A2(n_3), .A3(n_0), .ZN(n_17)
  );
  NAND2_X2 g2369__1617(
      .A1(mm[0]), .A2(mm[1]), .ZN(n_37)
  );
  NAND2_X2 g2372__2802(
      .A1(ss[0]), .A2(ss[1]), .ZN(n_33)
  );
  OR2_X1 g2370__1705(
      .A1(hh[4]), .A2(hh[7]), .ZN(n_1)
  );
  OR2_X2 g2371__5122(
      .A1(ss[7]), .A2(ss[6]), .ZN(n_9)
  );
  NAND2_X2 g2368__8246(
      .A1(hh[0]), .A2(hh[1]), .ZN(n_47)
  );
  INV_X1 g2376(
      .A(ena), .ZN(n_5)
  );
  INV_X1 g2378(
      .A(reset), .ZN(n_95)
  );
  DLL_X2 ts_lockup_latchn_clkc1_intno24_i(
      .D(ss[0]), .GN(clk), .Q(ts_lockup_latchn_clkc1_intno24_)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi25_i(
      .A(scan_in_0), .Z(ts_pbuf_extsi25_)
  );
endmodule

