/* Generated by Tessent Shell 2022.4 at Fri May 16 10:23:57 IST 2025 */
module counter_16bit(clk, rst, Q, scan_in_0, scan_in_1, scan_out_0, scan_out_1, 
                     scan_en);
  input  clk, rst, scan_in_0, scan_in_1, scan_en;
  output [15:0] Q;
  output scan_out_0, scan_out_1;

  wire \Q[0]_85 , UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, 
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, 
       UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, 
       UNCONNECTED13, n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11, 
       n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23, 
       n_24, n_25, n_26, n_27, n_28, n_29, ts_lockup_latchn_clkc1_intno7_, 
       ts_lockup_latchn_clkc2_intno15_, ts_pbuf_extsi16_, ts_pbuf_extsi17_;

  assign scan_out_0 = ts_lockup_latchn_clkc1_intno7_;
  assign scan_out_1 = ts_lockup_latchn_clkc2_intno15_;
  SDFFR_X1 \Q_reg[15] (
      .CK(clk), .D(n_29), .RN(rst), .SE(scan_en), .SI(ts_pbuf_extsi16_), .Q(Q[15]), 
      .QN(UNCONNECTED)
  );
  XOR2_X2 g783__2398(
      .A(Q[15]), .B(n_27), .Z(n_29)
  );
  SDFFR_X1 \Q_reg[14] (
      .CK(clk), .D(n_28), .RN(rst), .SE(scan_en), .SI(Q[15]), .Q(Q[14]), .QN(UNCONNECTED0)
  );
  HA_X1 g785__5107(
      .A(n_25), .B(Q[14]), .CO(n_27), .S(n_28)
  );
  SDFFR_X1 \Q_reg[11] (
      .CK(clk), .D(n_24), .RN(rst), .SE(scan_en), .SI(Q[14]), .Q(Q[11]), .QN(UNCONNECTED1)
  );
  SDFFR_X1 \Q_reg[13] (
      .CK(clk), .D(n_26), .RN(rst), .SE(scan_en), .SI(Q[11]), .Q(Q[13]), .QN(UNCONNECTED2)
  );
  HA_X1 g789__6260(
      .A(n_20), .B(Q[13]), .CO(n_25), .S(n_26)
  );
  XOR2_X2 g788__4319(
      .A(Q[11]), .B(n_22), .Z(n_24)
  );
  SDFFR_X1 \Q_reg[10] (
      .CK(clk), .D(n_23), .RN(rst), .SE(scan_en), .SI(Q[13]), .Q(Q[10]), .QN(UNCONNECTED3)
  );
  SDFFR_X1 \Q_reg[12] (
      .CK(clk), .D(n_21), .RN(rst), .SE(scan_en), .SI(Q[10]), .Q(Q[12]), .QN(UNCONNECTED4)
  );
  HA_X1 g791__8428(
      .A(n_18), .B(Q[10]), .CO(n_22), .S(n_23)
  );
  HA_X1 g793__5526(
      .A(n_17), .B(Q[12]), .CO(n_20), .S(n_21)
  );
  SDFFR_X1 \Q_reg[9] (
      .CK(clk), .D(n_19), .RN(rst), .SE(scan_en), .SI(Q[12]), .Q(Q[9]), .QN(UNCONNECTED5)
  );
  HA_X1 g795__6783(
      .A(n_16), .B(Q[9]), .CO(n_18), .S(n_19)
  );
  AND4_X4 g797__3680(
      .A1(n_16), .A2(Q[11]), .A3(Q[10]), .A4(Q[9]), .ZN(n_17)
  );
  SDFFR_X1 \Q_reg[8] (
      .CK(clk), .D(n_15), .RN(rst), .SE(scan_en), .SI(Q[9]), .Q(Q[8]), .QN(UNCONNECTED6)
  );
  HA_X1 g798__1617(
      .A(n_13), .B(Q[8]), .CO(n_16), .S(n_15)
  );
  SDFFR_X1 \Q_reg[7] (
      .CK(clk), .D(n_14), .RN(rst), .SE(scan_en), .SI(ts_pbuf_extsi17_), .Q(Q[7]), 
      .QN(UNCONNECTED7)
  );
  HA_X1 g800__2802(
      .A(n_11), .B(Q[7]), .CO(n_13), .S(n_14)
  );
  SDFFR_X1 \Q_reg[6] (
      .CK(clk), .D(n_12), .RN(rst), .SE(scan_en), .SI(Q[7]), .Q(Q[6]), .QN(UNCONNECTED8)
  );
  HA_X1 g802__1705(
      .A(n_9), .B(Q[6]), .CO(n_11), .S(n_12)
  );
  SDFFR_X1 \Q_reg[5] (
      .CK(clk), .D(n_10), .RN(rst), .SE(scan_en), .SI(Q[6]), .Q(Q[5]), .QN(UNCONNECTED9)
  );
  HA_X1 g804__5122(
      .A(n_7), .B(Q[5]), .CO(n_9), .S(n_10)
  );
  SDFFR_X2 \Q_reg[4] (
      .CK(clk), .D(n_8), .RN(rst), .SE(scan_en), .SI(Q[5]), .Q(Q[4]), .QN(UNCONNECTED10)
  );
  HA_X1 g806__8246(
      .A(n_5), .B(Q[4]), .CO(n_7), .S(n_8)
  );
  SDFFR_X2 \Q_reg[3] (
      .CK(clk), .D(n_6), .RN(rst), .SE(scan_en), .SI(Q[4]), .Q(Q[3]), .QN(UNCONNECTED11)
  );
  HA_X1 g808__7098(
      .A(n_3), .B(Q[3]), .CO(n_5), .S(n_6)
  );
  SDFFR_X2 \Q_reg[2] (
      .CK(clk), .D(n_4), .RN(rst), .SE(scan_en), .SI(Q[3]), .Q(Q[2]), .QN(UNCONNECTED12)
  );
  HA_X1 g810__6131(
      .A(n_1), .B(Q[2]), .CO(n_3), .S(n_4)
  );
  SDFFR_X2 \Q_reg[1] (
      .CK(clk), .D(n_2), .RN(rst), .SE(scan_en), .SI(Q[2]), .Q(Q[1]), .QN(UNCONNECTED13)
  );
  HA_X1 g812__1881(
      .A(Q[1]), .B(Q[0]), .CO(n_1), .S(n_2)
  );
  SDFFR_X2 \Q_reg[0] (
      .CK(clk), .D(\Q[0]_85 ), .RN(rst), .SE(scan_en), .SI(Q[1]), .Q(Q[0]), .QN(\Q[0]_85 )
  );
  DLL_X2 ts_lockup_latchn_clkc1_intno7_i(
      .D(Q[8]), .GN(clk), .Q(ts_lockup_latchn_clkc1_intno7_)
  );
  DLL_X2 ts_lockup_latchn_clkc2_intno15_i(
      .D(Q[0]), .GN(clk), .Q(ts_lockup_latchn_clkc2_intno15_)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi16_i(
      .A(scan_in_0), .Z(ts_pbuf_extsi16_)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi17_i(
      .A(scan_in_1), .Z(ts_pbuf_extsi17_)
  );
endmodule

