/* Generated by Tessent Shell 2022.4 at Mon Apr 14 15:50:27 IST 2025 */
module D_FF_9(q, d, rst_n, clk, init_value);
  input  d, rst_n, clk, init_value;
  output q;

  wire UNCONNECTED3, n_0, n_1, n_2;

  DFFRS_X2 q_reg(
      .CK(clk), .D(d), .RN(n_1), .SN(n_2), .Q(q), .QN(UNCONNECTED3)
  );
  NAND2_X1 g37__1617(
      .A1(n_0), .A2(init_value), .ZN(n_2)
  );
  OR2_X1 g38__2802(
      .A1(rst_n), .A2(init_value), .ZN(n_1)
  );
  INV_X4 g39(
      .A(rst_n), .ZN(n_0)
  );
endmodule

module D_FF_10(q, d, rst_n, clk, init_value);
  input  d, rst_n, clk, init_value;
  output q;

  wire UNCONNECTED2, n_0, n_1, n_2;

  DFFRS_X2 q_reg(
      .CK(clk), .D(d), .RN(n_1), .SN(n_2), .Q(q), .QN(UNCONNECTED2)
  );
  NAND2_X1 g37__6783(
      .A1(n_0), .A2(init_value), .ZN(n_2)
  );
  OR2_X1 g38__3680(
      .A1(rst_n), .A2(init_value), .ZN(n_1)
  );
  INV_X4 g39(
      .A(rst_n), .ZN(n_0)
  );
endmodule

module D_FF_11(q, d, rst_n, clk, init_value, ts_sea0, ts_extsi6);
  input  d, rst_n, clk, init_value, ts_extsi6, ts_sea0;
  output q;

  wire UNCONNECTED1, n_0, n_1, n_2, ts_pbuf_extsi6_;

  SDFFRS_X1 q_reg(
      .CK(clk), .D(d), .RN(n_1), .SE(ts_sea0), .SI(ts_pbuf_extsi6_), .SN(n_2), 
      .Q(q), .QN(UNCONNECTED1)
  );
  NAND2_X1 g37__8428(
      .A1(n_0), .A2(init_value), .ZN(n_2)
  );
  OR2_X1 g38__5526(
      .A1(rst_n), .A2(init_value), .ZN(n_1)
  );
  INV_X4 g39(
      .A(rst_n), .ZN(n_0)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi6_i(
      .A(ts_extsi6), .Z(ts_pbuf_extsi6_)
  );
endmodule

module D_FF_12(q, d, rst_n, clk, init_value, ts_no5);
  input  d, rst_n, clk, init_value;
  output q, ts_no5;

  wire UNCONNECTED0, n_0, n_1, n_2;

  DFFRS_X2 q_reg(
      .CK(clk), .D(d), .RN(n_1), .SN(n_2), .Q(q), .QN(UNCONNECTED0)
  );
  NAND2_X1 g37__6260(
      .A1(n_0), .A2(init_value), .ZN(n_2)
  );
  OR2_X1 g38__4319(
      .A1(rst_n), .A2(init_value), .ZN(n_1)
  );
  INV_X4 g39(
      .A(rst_n), .ZN(n_0)
  );
  DLL_X2 ts_lockup_latchn_clkc1_intno5_i(
      .D(UNCONNECTED0), .GN(clk), .Q(ts_no5)
  );
endmodule

module D_FF(q, d, rst_n, clk, init_value);
  input  d, rst_n, clk, init_value;
  output q;

  wire UNCONNECTED, n_0, n_1, n_2;

  DFFRS_X2 q_reg(
      .CK(clk), .D(d), .RN(n_1), .SN(n_2), .Q(q), .QN(UNCONNECTED)
  );
  NAND2_X1 g37__2398(
      .A1(n_0), .A2(init_value), .ZN(n_2)
  );
  OR2_X1 g38__5107(
      .A1(rst_n), .A2(init_value), .ZN(n_1)
  );
  INV_X4 g39(
      .A(rst_n), .ZN(n_0)
  );
endmodule

module random_counter_lfsr(clk, rst_n, initialized_value, counter_random, ts_si, 
                           ts_so, scan_en);
  input  [4:0] initialized_value;
  input  [0:0] ts_si;
  input  clk, rst_n, scan_en;
  output [4:0] counter_random;
  output [0:0] ts_so;

  wire d_xor, ts_no5;

  assign ts_so = ts_no5;
  D_FF u0(
      .q(counter_random[0]), .d(counter_random[4]), .rst_n(rst_n), .clk(clk), .init_value(initialized_value[0])
  );
  D_FF_12 u1(
      .q(counter_random[1]), .d(counter_random[0]), .rst_n(rst_n), .clk(clk), .init_value(initialized_value[1]), 
      .ts_no5(ts_no5)
  );
  D_FF_11 u2(
      .q(counter_random[2]), .d(d_xor), .rst_n(rst_n), .clk(clk), .init_value(initialized_value[2]), 
      .ts_sea0(scan_en), .ts_extsi6(ts_si)
  );
  D_FF_10 u3(
      .q(counter_random[3]), .d(counter_random[2]), .rst_n(rst_n), .clk(clk), .init_value(initialized_value[3])
  );
  D_FF_9 u4(
      .q(counter_random[4]), .d(counter_random[3]), .rst_n(rst_n), .clk(clk), .init_value(initialized_value[4])
  );
  XOR2_X1 g13__1705(
      .A(counter_random[4]), .B(counter_random[1]), .Z(d_xor)
  );
endmodule

