
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  1 2025 15:52:45 IST (May  1 2025 10:22:45 UTC)

// Verification Directory fv/rf_2p_136d_74w_1m_4b 

module rf_2p_136d_74w_1m_4b(CLKA, CENA, AA, CLKB, CENB, AB, DB, QA);
  input CLKA, CENA, CLKB, CENB;
  input [7:0] AA, AB;
  input [73:0] DB;
  output [73:0] QA;
  wire CLKA, CENA, CLKB, CENB;
  wire [7:0] AA, AB;
  wire [73:0] DB;
  wire [73:0] QA;
  wire u_rd3_0_n_35, u_rd3_0_n_36, u_rd3_0_n_37, u_rd3_0_n_38,
       u_rd3_0_n_39, u_rd3_0_n_40, u_rd3_0_n_41, u_rd3_0_n_42;
  wire u_rd3_1_n_35, u_rd3_1_n_36, u_rd3_1_n_37, u_rd3_1_n_38,
       u_rd3_1_n_39, u_rd3_1_n_40, u_rd3_1_n_41, u_rd3_1_n_42;
  wire u_rd3_2_n_35, u_rd3_2_n_36, u_rd3_2_n_37, u_rd3_2_n_38,
       u_rd3_2_n_39, u_rd3_2_n_40, u_rd3_2_n_41, u_rd3_2_n_42;
  wire u_rd3_3_n_35, u_rd3_3_n_36, u_rd3_3_n_37, u_rd3_3_n_38,
       u_rd3_3_n_39, u_rd3_3_n_40, u_rd3_3_n_41, u_rd3_3_n_42;
  wire u_rd3_4_n_35, u_rd3_4_n_36, u_rd3_4_n_37, u_rd3_4_n_38,
       u_rd3_4_n_39, u_rd3_4_n_40, u_rd3_4_n_41, u_rd3_4_n_42;
  wire u_rd3_5_n_35, u_rd3_5_n_36, u_rd3_5_n_37, u_rd3_5_n_38,
       u_rd3_5_n_39, u_rd3_5_n_40, u_rd3_5_n_41, u_rd3_5_n_42;
  wire u_rd3_6_n_35, u_rd3_6_n_36, u_rd3_6_n_37, u_rd3_6_n_38,
       u_rd3_6_n_39, u_rd3_6_n_40, u_rd3_6_n_41, u_rd3_6_n_42;
  wire u_rd3_7_n_35, u_rd3_7_n_36, u_rd3_7_n_37, u_rd3_7_n_38,
       u_rd3_7_n_39, u_rd3_7_n_40, u_rd3_7_n_41, u_rd3_7_n_42;
  wire u_rd3_8_n_35, u_rd3_8_n_36, u_rd3_8_n_37, u_rd3_8_n_38,
       u_rd3_8_n_39, u_rd3_8_n_40, u_rd3_8_n_41, u_rd3_8_n_42;
  wire u_rd3_9_n_29, u_rd3_9_n_30, u_rd3_9_n_31, u_rd3_9_n_32,
       u_rd3_9_n_33, u_rd3_9_n_34, u_rd3_9_n_35, u_rd3_9_n_36;
  wire u_rd3_9_n_37, u_rd3_9_n_38, u_rd3_9_n_39, u_rd3_9_n_40,
       u_rd3_9_n_41, u_rd3_9_n_42;
  rd3_256x8 u_rd3_0_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[7:0]), .O1 (QA[7:0]), .O2 ({u_rd3_0_n_42,
       u_rd3_0_n_41, u_rd3_0_n_40, u_rd3_0_n_39, u_rd3_0_n_38,
       u_rd3_0_n_37, u_rd3_0_n_36, u_rd3_0_n_35}));
  rd3_256x8 u_rd3_1_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[15:8]), .O1 (QA[15:8]), .O2 ({u_rd3_1_n_42,
       u_rd3_1_n_41, u_rd3_1_n_40, u_rd3_1_n_39, u_rd3_1_n_38,
       u_rd3_1_n_37, u_rd3_1_n_36, u_rd3_1_n_35}));
  rd3_256x8 u_rd3_2_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[23:16]), .O1 (QA[23:16]), .O2 ({u_rd3_2_n_42,
       u_rd3_2_n_41, u_rd3_2_n_40, u_rd3_2_n_39, u_rd3_2_n_38,
       u_rd3_2_n_37, u_rd3_2_n_36, u_rd3_2_n_35}));
  rd3_256x8 u_rd3_3_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[31:24]), .O1 (QA[31:24]), .O2 ({u_rd3_3_n_42,
       u_rd3_3_n_41, u_rd3_3_n_40, u_rd3_3_n_39, u_rd3_3_n_38,
       u_rd3_3_n_37, u_rd3_3_n_36, u_rd3_3_n_35}));
  rd3_256x8 u_rd3_4_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[39:32]), .O1 (QA[39:32]), .O2 ({u_rd3_4_n_42,
       u_rd3_4_n_41, u_rd3_4_n_40, u_rd3_4_n_39, u_rd3_4_n_38,
       u_rd3_4_n_37, u_rd3_4_n_36, u_rd3_4_n_35}));
  rd3_256x8 u_rd3_5_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[47:40]), .O1 (QA[47:40]), .O2 ({u_rd3_5_n_42,
       u_rd3_5_n_41, u_rd3_5_n_40, u_rd3_5_n_39, u_rd3_5_n_38,
       u_rd3_5_n_37, u_rd3_5_n_36, u_rd3_5_n_35}));
  rd3_256x8 u_rd3_6_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[55:48]), .O1 (QA[55:48]), .O2 ({u_rd3_6_n_42,
       u_rd3_6_n_41, u_rd3_6_n_40, u_rd3_6_n_39, u_rd3_6_n_38,
       u_rd3_6_n_37, u_rd3_6_n_36, u_rd3_6_n_35}));
  rd3_256x8 u_rd3_7_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[63:56]), .O1 (QA[63:56]), .O2 ({u_rd3_7_n_42,
       u_rd3_7_n_41, u_rd3_7_n_40, u_rd3_7_n_39, u_rd3_7_n_38,
       u_rd3_7_n_37, u_rd3_7_n_36, u_rd3_7_n_35}));
  rd3_256x8 u_rd3_8_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 (DB[71:64]), .O1 (QA[71:64]), .O2 ({u_rd3_8_n_42,
       u_rd3_8_n_41, u_rd3_8_n_40, u_rd3_8_n_39, u_rd3_8_n_38,
       u_rd3_8_n_37, u_rd3_8_n_36, u_rd3_8_n_35}));
  rd3_256x8 u_rd3_9_u_dpram_256x8(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 ({7'b0, AA[0]}), .A2 ({7'b0, AB[0]}), .I1
       (8'b0), .I2 ({6'b0, DB[73:72]}), .O1 ({u_rd3_9_n_34,
       u_rd3_9_n_33, u_rd3_9_n_32, u_rd3_9_n_31, u_rd3_9_n_30,
       u_rd3_9_n_29, QA[73:72]}), .O2 ({u_rd3_9_n_42, u_rd3_9_n_41,
       u_rd3_9_n_40, u_rd3_9_n_39, u_rd3_9_n_38, u_rd3_9_n_37,
       u_rd3_9_n_36, u_rd3_9_n_35}));
endmodule

