
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 18:08:28 IST (Jun 13 2025 12:38:28 UTC)

// Verification Directory fv/can_register_syn 

module can_register_syn(data_in, data_out, we, clk, rst_sync);
  input [7:0] data_in;
  input we, clk, rst_sync;
  output [7:0] data_out;
  wire [7:0] data_in;
  wire we, clk, rst_sync;
  wire [7:0] data_out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16;
  DFF_X2 \data_out_reg[0] (.CK (clk), .D (n_14), .Q (data_out[0]), .QN
       (UNCONNECTED));
  DFF_X2 \data_out_reg[2] (.CK (clk), .D (n_11), .Q (data_out[2]), .QN
       (UNCONNECTED0));
  DFF_X2 \data_out_reg[3] (.CK (clk), .D (n_12), .Q (data_out[3]), .QN
       (UNCONNECTED1));
  DFF_X2 \data_out_reg[4] (.CK (clk), .D (n_13), .Q (data_out[4]), .QN
       (UNCONNECTED2));
  DFF_X2 \data_out_reg[1] (.CK (clk), .D (n_9), .Q (data_out[1]), .QN
       (UNCONNECTED3));
  DFF_X2 \data_out_reg[5] (.CK (clk), .D (n_15), .Q (data_out[5]), .QN
       (UNCONNECTED4));
  DFF_X2 \data_out_reg[6] (.CK (clk), .D (n_10), .Q (data_out[6]), .QN
       (UNCONNECTED5));
  DFF_X2 \data_out_reg[7] (.CK (clk), .D (n_16), .Q (data_out[7]), .QN
       (UNCONNECTED6));
  NOR2_X1 g32__2398(.A1 (n_1), .A2 (rst_sync), .ZN (n_16));
  NOR2_X1 g27__5107(.A1 (n_4), .A2 (rst_sync), .ZN (n_15));
  NOR2_X1 g31__6260(.A1 (n_3), .A2 (rst_sync), .ZN (n_14));
  NOR2_X1 g28__4319(.A1 (n_5), .A2 (rst_sync), .ZN (n_13));
  NOR2_X1 g29__8428(.A1 (n_2), .A2 (rst_sync), .ZN (n_12));
  NOR2_X1 g34__5526(.A1 (n_0), .A2 (rst_sync), .ZN (n_11));
  NOR2_X1 g33__6783(.A1 (n_8), .A2 (rst_sync), .ZN (n_10));
  NOR2_X1 g30__3680(.A1 (n_7), .A2 (rst_sync), .ZN (n_9));
  AOI22_X1 g40__1617(.A1 (data_out[6]), .A2 (n_6), .B1 (data_in[6]),
       .B2 (we), .ZN (n_8));
  AOI22_X1 g39__2802(.A1 (data_out[1]), .A2 (n_6), .B1 (data_in[1]),
       .B2 (we), .ZN (n_7));
  AOI22_X1 g38__1705(.A1 (data_out[4]), .A2 (n_6), .B1 (data_in[4]),
       .B2 (we), .ZN (n_5));
  AOI22_X1 g41__5122(.A1 (data_out[5]), .A2 (n_6), .B1 (data_in[5]),
       .B2 (we), .ZN (n_4));
  AOI22_X1 g36__8246(.A1 (data_out[0]), .A2 (n_6), .B1 (data_in[0]),
       .B2 (we), .ZN (n_3));
  AOI22_X1 g35__7098(.A1 (data_out[3]), .A2 (n_6), .B1 (data_in[3]),
       .B2 (we), .ZN (n_2));
  AOI22_X1 g42__6131(.A1 (data_out[7]), .A2 (n_6), .B1 (data_in[7]),
       .B2 (we), .ZN (n_1));
  AOI22_X1 g37__1881(.A1 (data_out[2]), .A2 (n_6), .B1 (data_in[2]),
       .B2 (we), .ZN (n_0));
  INV_X1 g43(.A (we), .ZN (n_6));
endmodule

