
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 17:42:06 IST (Jun 13 2025 12:12:06 UTC)

// Verification Directory fv/top 

module top(clock_24, clock_27, clock_50, ext_clock, scan_in,
     scan_enable, scan_out, key, sw, hex0, hex1, hex2, hex3, ledg,
     ledr, uart_txd, uart_rxd, dram_dq, dram_addr, dram_ldqm,
     dram_udqm, dram_we_n, dram_cas_n, dram_ras_n, dram_cs_n,
     dram_ba_0, dram_ba_1, dram_clk, dram_cke, fl_dq, fl_addr, fl_we_n,
     fl_rst_n, fl_oe_n, fl_ce_n, sram_dq, sram_addr, sram_ub_n,
     sram_lb_n, sram_we_n, sram_ce_n, sram_oe_n, sd_dat, sd_dat3,
     sd_cmd, sd_clk, i2c_sdat, i2c_sclk, ps2_dat, ps2_clk, tdi, tck,
     tcs, tdo, vga_hs, vga_vs, vga_r, vga_g, vga_b, aud_adclrck,
     aud_adcdat, aud_daclrck, aud_dacdat, aud_bclk, aud_xck, gpio_0,
     gpio_1);
  input [1:0] clock_24, clock_27;
  input clock_50, ext_clock, scan_in, scan_enable, uart_rxd, ps2_dat,
       ps2_clk, tdi, tck, tcs, aud_adcdat;
  input [3:0] key;
  input [9:0] sw;
  output scan_out, uart_txd, dram_ldqm, dram_udqm, dram_we_n,
       dram_cas_n, dram_ras_n, dram_cs_n, dram_ba_0, dram_ba_1,
       dram_clk, dram_cke, fl_we_n, fl_rst_n, fl_oe_n, fl_ce_n,
       sram_ub_n, sram_lb_n, sram_we_n, sram_ce_n, sram_oe_n, sd_clk,
       i2c_sclk, tdo, vga_hs, vga_vs, aud_dacdat, aud_xck;
  output [6:0] hex0, hex1, hex2, hex3;
  output [7:0] ledg;
  output [9:0] ledr;
  output [11:0] dram_addr;
  output [21:0] fl_addr;
  output [17:0] sram_addr;
  output [3:0] vga_r, vga_g, vga_b;
  inout [15:0] dram_dq, sram_dq;
  inout [7:0] fl_dq;
  inout sd_dat, sd_dat3, sd_cmd, i2c_sdat, aud_adclrck, aud_daclrck,
       aud_bclk;
  inout [35:0] gpio_0, gpio_1;
  wire [1:0] clock_24, clock_27;
  wire clock_50, ext_clock, scan_in, scan_enable, uart_rxd, ps2_dat,
       ps2_clk, tdi, tck, tcs, aud_adcdat;
  wire [3:0] key;
  wire [9:0] sw;
  wire scan_out, uart_txd, dram_ldqm, dram_udqm, dram_we_n, dram_cas_n,
       dram_ras_n, dram_cs_n, dram_ba_0, dram_ba_1, dram_clk, dram_cke,
       fl_we_n, fl_rst_n, fl_oe_n, fl_ce_n, sram_ub_n, sram_lb_n,
       sram_we_n, sram_ce_n, sram_oe_n, sd_clk, i2c_sclk, tdo, vga_hs,
       vga_vs, aud_dacdat, aud_xck;
  wire [6:0] hex0, hex1, hex2, hex3;
  wire [7:0] ledg;
  wire [9:0] ledr;
  wire [11:0] dram_addr;
  wire [21:0] fl_addr;
  wire [17:0] sram_addr;
  wire [3:0] vga_r, vga_g, vga_b;
  wire [15:0] dram_dq, sram_dq;
  wire [7:0] fl_dq;
  wire sd_dat, sd_dat3, sd_cmd, i2c_sdat, aud_adclrck, aud_daclrck,
       aud_bclk;
  wire [35:0] gpio_0, gpio_1;
  wire [1:2]
       i_test_harness_i_wb_async_mem_bridge_i_sync_mem_cs_n_resync;
  wire [1:2] i_sync_reset_resync;
  wire [1:3]
       i_test_harness_i_wb_async_mem_bridge_i_sync_mem_oe_n_resync;
  wire [24:0] counter;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27,
       i_test_harness_i_wb_async_mem_bridge_sync_mem_cs_n,
       i_test_harness_i_wb_async_mem_bridge_sync_mem_oe_n,
       inc_add_121_24_n_264;
  wire inc_add_121_24_n_266, inc_add_121_24_n_268,
       inc_add_121_24_n_270, inc_add_121_24_n_272,
       inc_add_121_24_n_274, inc_add_121_24_n_276,
       inc_add_121_24_n_278, inc_add_121_24_n_280;
  wire inc_add_121_24_n_282, inc_add_121_24_n_284,
       inc_add_121_24_n_286, inc_add_121_24_n_288,
       inc_add_121_24_n_290, inc_add_121_24_n_292,
       inc_add_121_24_n_294, inc_add_121_24_n_296;
  wire inc_add_121_24_n_298, inc_add_121_24_n_300,
       inc_add_121_24_n_302, inc_add_121_24_n_304,
       inc_add_121_24_n_306, inc_add_121_24_n_308, n_0, n_1;
  wire n_3, n_4, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, reset_switch;
  assign aud_xck = 1'b0;
  assign aud_dacdat = 1'b0;
  assign vga_b[0] = 1'b0;
  assign vga_b[1] = 1'b0;
  assign vga_b[2] = 1'b0;
  assign vga_b[3] = 1'b0;
  assign vga_g[0] = 1'b0;
  assign vga_g[1] = 1'b0;
  assign vga_g[2] = 1'b0;
  assign vga_g[3] = 1'b0;
  assign vga_r[0] = 1'b0;
  assign vga_r[1] = 1'b0;
  assign vga_r[2] = 1'b0;
  assign vga_r[3] = 1'b0;
  assign vga_vs = 1'b0;
  assign vga_hs = 1'b0;
  assign tdo = 1'b0;
  assign i2c_sclk = 1'b0;
  assign sd_clk = 1'b0;
  assign sram_oe_n = 1'b0;
  assign sram_ce_n = 1'b0;
  assign sram_we_n = 1'b0;
  assign sram_lb_n = 1'b0;
  assign sram_ub_n = 1'b0;
  assign sram_addr[0] = 1'b0;
  assign sram_addr[1] = 1'b0;
  assign sram_addr[2] = 1'b0;
  assign sram_addr[3] = 1'b0;
  assign sram_addr[4] = 1'b0;
  assign sram_addr[5] = 1'b0;
  assign sram_addr[6] = 1'b0;
  assign sram_addr[7] = 1'b0;
  assign sram_addr[8] = 1'b0;
  assign sram_addr[9] = 1'b0;
  assign sram_addr[10] = 1'b0;
  assign sram_addr[11] = 1'b0;
  assign sram_addr[12] = 1'b0;
  assign sram_addr[13] = 1'b0;
  assign sram_addr[14] = 1'b0;
  assign sram_addr[15] = 1'b0;
  assign sram_addr[16] = 1'b0;
  assign sram_addr[17] = 1'b0;
  assign fl_ce_n = 1'b0;
  assign fl_oe_n = 1'b0;
  assign fl_rst_n = 1'b0;
  assign fl_we_n = 1'b0;
  assign fl_addr[0] = 1'b0;
  assign fl_addr[1] = 1'b0;
  assign fl_addr[2] = 1'b0;
  assign fl_addr[3] = 1'b0;
  assign fl_addr[4] = 1'b0;
  assign fl_addr[5] = 1'b0;
  assign fl_addr[6] = 1'b0;
  assign fl_addr[7] = 1'b0;
  assign fl_addr[8] = 1'b0;
  assign fl_addr[9] = 1'b0;
  assign fl_addr[10] = 1'b0;
  assign fl_addr[11] = 1'b0;
  assign fl_addr[12] = 1'b0;
  assign fl_addr[13] = 1'b0;
  assign fl_addr[14] = 1'b0;
  assign fl_addr[15] = 1'b0;
  assign fl_addr[16] = 1'b0;
  assign fl_addr[17] = 1'b0;
  assign fl_addr[18] = 1'b0;
  assign fl_addr[19] = 1'b0;
  assign fl_addr[20] = 1'b0;
  assign fl_addr[21] = 1'b0;
  assign dram_cke = 1'b0;
  assign dram_clk = 1'b0;
  assign dram_ba_1 = 1'b0;
  assign dram_ba_0 = 1'b0;
  assign dram_cs_n = 1'b0;
  assign dram_ras_n = 1'b0;
  assign dram_cas_n = 1'b0;
  assign dram_we_n = 1'b0;
  assign dram_udqm = 1'b0;
  assign dram_ldqm = 1'b0;
  assign dram_addr[0] = 1'b0;
  assign dram_addr[1] = 1'b0;
  assign dram_addr[2] = 1'b0;
  assign dram_addr[3] = 1'b0;
  assign dram_addr[4] = 1'b0;
  assign dram_addr[5] = 1'b0;
  assign dram_addr[6] = 1'b0;
  assign dram_addr[7] = 1'b0;
  assign dram_addr[8] = 1'b0;
  assign dram_addr[9] = 1'b0;
  assign dram_addr[10] = 1'b0;
  assign dram_addr[11] = 1'b0;
  assign uart_txd = 1'b0;
  assign ledr[0] = 1'b0;
  assign ledr[1] = 1'b0;
  assign ledr[2] = 1'b0;
  assign ledr[3] = 1'b0;
  assign ledr[4] = 1'b0;
  assign ledr[5] = 1'b0;
  assign ledr[6] = 1'b0;
  assign ledr[7] = 1'b0;
  assign ledr[8] = 1'b0;
  assign ledr[9] = 1'b0;
  assign ledg[0] = sw[0];
  assign ledg[1] = sw[1];
  assign ledg[2] = sw[2];
  assign ledg[3] = sw[3];
  assign ledg[4] = sw[4];
  assign ledg[5] = sw[5];
  assign ledg[6] = sw[6];
  assign hex3[0] = 1'b1;
  assign hex3[1] = 1'b1;
  assign hex3[2] = 1'b1;
  assign hex3[3] = 1'b1;
  assign hex3[4] = 1'b1;
  assign hex3[5] = 1'b1;
  assign hex3[6] = 1'b1;
  assign hex2[0] = 1'b1;
  assign hex2[1] = 1'b1;
  assign hex2[2] = 1'b1;
  assign hex2[3] = 1'b1;
  assign hex2[4] = 1'b1;
  assign hex2[5] = 1'b1;
  assign hex2[6] = 1'b1;
  assign hex1[0] = 1'b1;
  assign hex1[1] = 1'b1;
  assign hex1[2] = 1'b1;
  assign hex1[3] = 1'b1;
  assign hex1[4] = 1'b1;
  assign hex1[5] = 1'b1;
  assign hex1[6] = 1'b1;
  assign hex0[0] = 1'b1;
  assign hex0[1] = 1'b1;
  assign hex0[2] = 1'b1;
  assign hex0[3] = 1'b1;
  assign hex0[4] = 1'b1;
  assign hex0[5] = 1'b1;
  assign hex0[6] = 1'b1;
  assign scan_out = 1'b0;
  INV_X1 g221(.A (key[0]), .ZN (n_4));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g99__2398(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[6]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g78__5107(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[28]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g79__6260(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[27]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g85__4319(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[20]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g101__8428(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[4]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g102__5526(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[3]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g86__6783(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[19]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g103__3680(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[2]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g104__1617(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[1]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g87__2802(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[18]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g105__1705(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[0]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g88__5122(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[17]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g80__8246(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[26]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g89__7098(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[16]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g100__6131(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[5]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g75__1881(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[31]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g84__5115(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[21]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g97__7482(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[8]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g96__4733(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[9]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g95__6161(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[10]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g94__9315(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[11]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g90__9945(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[15]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g7__2883(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[25]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g91__2346(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[14]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g92__1666(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[13]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g76__7410(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[30]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g81__6417(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[24]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g93__5477(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[12]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g82__2398(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[23]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g77__5107(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[29]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g83__6260(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[22]));
  TINV_X1 i_test_harness_i_wb_async_mem_bridge_g98__4319(.EN (n_3), .I
       (1'b1), .ZN (gpio_1[7]));
  OR2_X4 g227__8428(.A1
       (i_test_harness_i_wb_async_mem_bridge_sync_mem_cs_n), .A2
       (i_test_harness_i_wb_async_mem_bridge_sync_mem_oe_n), .ZN (n_3));
  DFF_X2
       \i_test_harness_i_wb_async_mem_bridge_i_sync_mem_cs_n_resync_reg[2]
       (.CK (clock_24[0]), .D
       (i_test_harness_i_wb_async_mem_bridge_i_sync_mem_cs_n_resync[1]),
       .Q (i_test_harness_i_wb_async_mem_bridge_sync_mem_cs_n), .QN
       (UNCONNECTED));
  DFF_X2 \i_sync_reset_resync_reg[2] (.CK (clock_24[0]), .D
       (i_sync_reset_resync[1]), .Q (reset_switch), .QN (n_1));
  DFF_X2
       \i_test_harness_i_wb_async_mem_bridge_i_sync_mem_oe_n_resync_reg[2]
       (.CK (clock_24[0]), .D
       (i_test_harness_i_wb_async_mem_bridge_i_sync_mem_oe_n_resync[1]),
       .Q (i_test_harness_i_wb_async_mem_bridge_sync_mem_oe_n), .QN
       (UNCONNECTED0));
  DFF_X2 \i_sync_reset_resync_reg[1] (.CK (clock_24[0]), .D (n_4), .Q
       (i_sync_reset_resync[1]), .QN (UNCONNECTED1));
  DFF_X2
       \i_test_harness_i_wb_async_mem_bridge_i_sync_mem_oe_n_resync_reg[1]
       (.CK (clock_24[0]), .D (gpio_0[30]), .Q
       (i_test_harness_i_wb_async_mem_bridge_i_sync_mem_oe_n_resync[1]),
       .QN (UNCONNECTED2));
  DFF_X2
       \i_test_harness_i_wb_async_mem_bridge_i_sync_mem_cs_n_resync_reg[1]
       (.CK (clock_24[0]), .D (gpio_0[24]), .Q
       (i_test_harness_i_wb_async_mem_bridge_i_sync_mem_cs_n_resync[1]),
       .QN (UNCONNECTED3));
  DFFR_X2 \counter_reg[15] (.RN (n_1), .CK (clock_24[0]), .D (n_134),
       .Q (counter[15]), .QN (UNCONNECTED4));
  DFFR_X2 \counter_reg[11] (.RN (n_1), .CK (clock_24[0]), .D (n_138),
       .Q (counter[11]), .QN (UNCONNECTED5));
  DFFR_X2 \counter_reg[12] (.RN (n_1), .CK (clock_24[0]), .D (n_137),
       .Q (counter[12]), .QN (UNCONNECTED6));
  DFFR_X2 \counter_reg[22] (.RN (n_1), .CK (clock_24[0]), .D (n_127),
       .Q (counter[22]), .QN (UNCONNECTED7));
  DFFR_X2 \counter_reg[13] (.RN (n_1), .CK (clock_24[0]), .D (n_136),
       .Q (counter[13]), .QN (UNCONNECTED8));
  DFFR_X2 \counter_reg[14] (.RN (n_1), .CK (clock_24[0]), .D (n_135),
       .Q (counter[14]), .QN (UNCONNECTED9));
  DFFR_X2 \counter_reg[20] (.RN (n_1), .CK (clock_24[0]), .D (n_129),
       .Q (counter[20]), .QN (UNCONNECTED10));
  DFFR_X2 \counter_reg[16] (.RN (n_1), .CK (clock_24[0]), .D (n_133),
       .Q (counter[16]), .QN (UNCONNECTED11));
  DFFR_X2 \counter_reg[17] (.RN (n_1), .CK (clock_24[0]), .D (n_132),
       .Q (counter[17]), .QN (UNCONNECTED12));
  DFFR_X2 \counter_reg[18] (.RN (n_1), .CK (clock_24[0]), .D (n_131),
       .Q (counter[18]), .QN (UNCONNECTED13));
  DFFR_X2 \counter_reg[19] (.RN (n_1), .CK (clock_24[0]), .D (n_130),
       .Q (counter[19]), .QN (UNCONNECTED14));
  DFFR_X2 \counter_reg[0] (.RN (n_1), .CK (clock_24[0]), .D (n_0), .Q
       (counter[0]), .QN (n_0));
  DFFR_X2 \counter_reg[21] (.RN (n_1), .CK (clock_24[0]), .D (n_128),
       .Q (counter[21]), .QN (UNCONNECTED15));
  DFFR_X2 \counter_reg[23] (.RN (n_1), .CK (clock_24[0]), .D (n_126),
       .Q (counter[23]), .QN (UNCONNECTED16));
  DFFR_X2 \counter_reg[24] (.RN (n_1), .CK (clock_24[0]), .D (n_125),
       .Q (ledg[7]), .QN (UNCONNECTED17));
  DFFR_X2 \counter_reg[10] (.RN (n_1), .CK (clock_24[0]), .D (n_139),
       .Q (counter[10]), .QN (UNCONNECTED18));
  DFFR_X2 \counter_reg[1] (.RN (n_1), .CK (clock_24[0]), .D (n_148), .Q
       (counter[1]), .QN (UNCONNECTED19));
  DFFR_X2 \counter_reg[2] (.RN (n_1), .CK (clock_24[0]), .D (n_147), .Q
       (counter[2]), .QN (UNCONNECTED20));
  DFFR_X2 \counter_reg[3] (.RN (n_1), .CK (clock_24[0]), .D (n_146), .Q
       (counter[3]), .QN (UNCONNECTED21));
  DFFR_X2 \counter_reg[4] (.RN (n_1), .CK (clock_24[0]), .D (n_145), .Q
       (counter[4]), .QN (UNCONNECTED22));
  DFFR_X2 \counter_reg[5] (.RN (n_1), .CK (clock_24[0]), .D (n_144), .Q
       (counter[5]), .QN (UNCONNECTED23));
  DFFR_X2 \counter_reg[6] (.RN (n_1), .CK (clock_24[0]), .D (n_143), .Q
       (counter[6]), .QN (UNCONNECTED24));
  DFFR_X2 \counter_reg[7] (.RN (n_1), .CK (clock_24[0]), .D (n_142), .Q
       (counter[7]), .QN (UNCONNECTED25));
  DFFR_X2 \counter_reg[8] (.RN (n_1), .CK (clock_24[0]), .D (n_141), .Q
       (counter[8]), .QN (UNCONNECTED26));
  DFFR_X2 \counter_reg[9] (.RN (n_1), .CK (clock_24[0]), .D (n_140), .Q
       (counter[9]), .QN (UNCONNECTED27));
  XOR2_X1 inc_add_121_24_g415__5526(.A (inc_add_121_24_n_264), .B
       (ledg[7]), .Z (n_125));
  HA_X1 inc_add_121_24_g416__6783(.A (inc_add_121_24_n_266), .B
       (counter[23]), .CO (inc_add_121_24_n_264), .S (n_126));
  HA_X1 inc_add_121_24_g417__3680(.A (inc_add_121_24_n_268), .B
       (counter[22]), .CO (inc_add_121_24_n_266), .S (n_127));
  HA_X1 inc_add_121_24_g418__1617(.A (inc_add_121_24_n_270), .B
       (counter[21]), .CO (inc_add_121_24_n_268), .S (n_128));
  HA_X1 inc_add_121_24_g419__2802(.A (inc_add_121_24_n_272), .B
       (counter[20]), .CO (inc_add_121_24_n_270), .S (n_129));
  HA_X1 inc_add_121_24_g420__1705(.A (inc_add_121_24_n_274), .B
       (counter[19]), .CO (inc_add_121_24_n_272), .S (n_130));
  HA_X1 inc_add_121_24_g421__5122(.A (inc_add_121_24_n_276), .B
       (counter[18]), .CO (inc_add_121_24_n_274), .S (n_131));
  HA_X1 inc_add_121_24_g422__8246(.A (inc_add_121_24_n_278), .B
       (counter[17]), .CO (inc_add_121_24_n_276), .S (n_132));
  HA_X1 inc_add_121_24_g423__7098(.A (inc_add_121_24_n_280), .B
       (counter[16]), .CO (inc_add_121_24_n_278), .S (n_133));
  HA_X1 inc_add_121_24_g424__6131(.A (inc_add_121_24_n_282), .B
       (counter[15]), .CO (inc_add_121_24_n_280), .S (n_134));
  HA_X1 inc_add_121_24_g425__1881(.A (inc_add_121_24_n_284), .B
       (counter[14]), .CO (inc_add_121_24_n_282), .S (n_135));
  HA_X1 inc_add_121_24_g426__5115(.A (inc_add_121_24_n_286), .B
       (counter[13]), .CO (inc_add_121_24_n_284), .S (n_136));
  HA_X1 inc_add_121_24_g427__7482(.A (inc_add_121_24_n_288), .B
       (counter[12]), .CO (inc_add_121_24_n_286), .S (n_137));
  HA_X1 inc_add_121_24_g428__4733(.A (inc_add_121_24_n_290), .B
       (counter[11]), .CO (inc_add_121_24_n_288), .S (n_138));
  HA_X1 inc_add_121_24_g429__6161(.A (inc_add_121_24_n_292), .B
       (counter[10]), .CO (inc_add_121_24_n_290), .S (n_139));
  HA_X1 inc_add_121_24_g430__9315(.A (inc_add_121_24_n_294), .B
       (counter[9]), .CO (inc_add_121_24_n_292), .S (n_140));
  HA_X1 inc_add_121_24_g431__9945(.A (inc_add_121_24_n_296), .B
       (counter[8]), .CO (inc_add_121_24_n_294), .S (n_141));
  HA_X1 inc_add_121_24_g432__2883(.A (inc_add_121_24_n_298), .B
       (counter[7]), .CO (inc_add_121_24_n_296), .S (n_142));
  HA_X1 inc_add_121_24_g433__2346(.A (inc_add_121_24_n_300), .B
       (counter[6]), .CO (inc_add_121_24_n_298), .S (n_143));
  HA_X1 inc_add_121_24_g434__1666(.A (inc_add_121_24_n_302), .B
       (counter[5]), .CO (inc_add_121_24_n_300), .S (n_144));
  HA_X1 inc_add_121_24_g435__7410(.A (inc_add_121_24_n_304), .B
       (counter[4]), .CO (inc_add_121_24_n_302), .S (n_145));
  HA_X1 inc_add_121_24_g436__6417(.A (inc_add_121_24_n_306), .B
       (counter[3]), .CO (inc_add_121_24_n_304), .S (n_146));
  HA_X1 inc_add_121_24_g437__5477(.A (inc_add_121_24_n_308), .B
       (counter[2]), .CO (inc_add_121_24_n_306), .S (n_147));
  HA_X1 inc_add_121_24_g438__2398(.A (counter[0]), .B (counter[1]), .CO
       (inc_add_121_24_n_308), .S (n_148));
endmodule

