###############################################################
#  Generated by:      Cadence Tempus 20.20-p001_1
#  OS:                Linux x86_64(Host ID APL10.kletech.ac.in)
#  Generated on:      Wed Apr  2 10:39:59 2025
#  Design:            vorca
#  Command:           save_design vorca
###############################################################
read_verilog ../Tech_files/vorca_fixed.v
read_lib ../Tech_files/slow.lib
set_top_module
create_clock -name sclk -period 5 [get_ports clk]
report_timing -path_group I2O -path_type full
report_path_groups -from all_inputs -to all_outputs
report_timing -from all_inputs -to all_outputs
report_timing -from test_si1 -to test_so1
get_time_unit
report_timing -machine_readable -max_paths 10000 -max_slack 0.75 -path_exceptions all -early > top.mtarpt
load_timing_debug_report -name default_report top.mtarpt
analyze_paths_by_basic_path_group -Input -> Output
analyze_paths_by_basic_path_group -predefined -h
analyze_paths_by_basic_path_group -help
analyze_paths_by_basic_path_group -predefined
analyze_paths_by_basic_path_group -master
analyze_paths_by_basic_path_group -master I2O
analyze_paths_by_basic_path_group
report_timing -path_group -from [all_inputs] -to [all_outputs]
set_delay_cal_mode -siAware true
set_si_mode -enable_delay_report true
set_si_mode -enable_glitch_report true
set_si_mode -enable_glitch_propagation true
set_global timing_pba_exhaustive_path_nworst_limit 2
set_global timing_path_based_exhaustive_max_paths_limit 1000
update_timing -full
report_timing
report_timing -max_paths 10000000 -retime path_slew_propagation -retime_mode exhaustive -max_slack 0.200 > epba_${DATE}.rpt
check_design -type timing -out_file reports_Apr02-10:39:21/check_design.rpt
check_timing -verbose > ${reportDir}/check_timing.rpt
report_analysis_coverage            > ${reportDir}/coverage.rpt
report_clocks                       > ${reportDir}/clocks.rpt
report_case_analysis                > ${reportDir}/case_analysis.rpt
report_inactive_arcs                > ${reportDir}/inactive_arcs.rpt
report_constraint -all_violators > reports_Apr02-10:39:21/allviol.rpt
report_analysis_summary                                         > ${reportDir}/analysis_summary.rpt
report_timing -path_type summary_slack_only -late -max_paths 5  > ${reportDir}/start_end_slack.rpt
report_timing -late   -max_paths 50 -nworst 1 -path_type full_clock -net  > ${reportDir}/worst_max_path.rpt
report_timing -early  -max_paths 50 -nworst 1 -path_type full_clock -net  > ${reportDir}/worst_min_path.rpt
report_timing -path_type end_slack_only                       > ${reportDir}/setup_1.rpt
report_timing -path_type end_slack_only  -early               > ${reportDir}/hold_1.rpt
report_timing -late    -max_paths 100                         > ${reportDir}/setup_100.rpt.gz
report_timing -early   -max_paths 100                         > ${reportDir}/hold_100.rpt.gz
report_timing -retime path_slew_propagation -max_paths 50 -nworst 1 -path_type full_clock    > ${reportDir}/pba_50_paths.rpt
save_design vorca
