
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 17:46:40 IST (Jun 13 2025 12:16:40 UTC)

// Verification Directory fv/ps2_host 

module ps2_host(sys_clk, sys_rst, ps2_clk, ps2_data, scan_in,
     scan_enable, scan_out, tx_data, send_req, busy, rx_data, ready,
     error);
  input sys_clk, sys_rst, scan_in, scan_enable, send_req;
  input [7:0] tx_data;
  output scan_out, busy, ready, error;
  output [7:0] rx_data;
  inout ps2_clk, ps2_data;
  wire sys_clk, sys_rst, scan_in, scan_enable, send_req;
  wire [7:0] tx_data;
  wire scan_out, busy, ready, error;
  wire [7:0] rx_data;
  wire ps2_clk, ps2_data;
  wire [11:0] ps2_host_tx_frame;
  wire [14:0] ps2_host_watchdog_watchdog_timer;
  wire [11:0] ps2_host_rx_frame;
  wire [1:0] ps2_host_clk_ctrl_ps2_clk_samples;
  wire [13:0] ps2_host_clk_ctrl_inhibit_timer;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_247, n_248, ps2_host_watchdog_watchdog_active;
  assign scan_out = 1'b0;
  DFF_X2 \ps2_host_tx_frame_reg[2] (.CK (sys_clk), .D (n_225), .Q
       (ps2_host_tx_frame[2]), .QN (UNCONNECTED));
  DFF_X2 \ps2_host_tx_frame_reg[1] (.CK (sys_clk), .D (n_232), .Q
       (ps2_host_tx_frame[1]), .QN (UNCONNECTED0));
  DFF_X2 \ps2_host_tx_frame_reg[9] (.CK (sys_clk), .D (n_233), .Q
       (ps2_host_tx_frame[9]), .QN (UNCONNECTED1));
  DFF_X2 \ps2_host_tx_frame_reg[8] (.CK (sys_clk), .D (n_226), .Q
       (ps2_host_tx_frame[8]), .QN (UNCONNECTED2));
  DFF_X2 \ps2_host_tx_frame_reg[5] (.CK (sys_clk), .D (n_229), .Q
       (ps2_host_tx_frame[5]), .QN (UNCONNECTED3));
  DFF_X2 \ps2_host_tx_frame_reg[6] (.CK (sys_clk), .D (n_228), .Q
       (ps2_host_tx_frame[6]), .QN (UNCONNECTED4));
  DFF_X2 \ps2_host_tx_frame_reg[7] (.CK (sys_clk), .D (n_227), .Q
       (ps2_host_tx_frame[7]), .QN (UNCONNECTED5));
  DFF_X2 \ps2_host_tx_frame_reg[3] (.CK (sys_clk), .D (n_231), .Q
       (ps2_host_tx_frame[3]), .QN (n_1));
  DFF_X2 \ps2_host_tx_frame_reg[4] (.CK (sys_clk), .D (n_230), .Q
       (ps2_host_tx_frame[4]), .QN (UNCONNECTED6));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[5] (.CK (sys_clk), .D
       (n_224), .Q (ps2_host_watchdog_watchdog_timer[5]), .QN
       (UNCONNECTED7));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[9] (.CK (sys_clk), .D
       (n_210), .Q (ps2_host_watchdog_watchdog_timer[9]), .QN
       (UNCONNECTED8));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[14] (.CK (sys_clk), .D
       (n_204), .Q (ps2_host_watchdog_watchdog_timer[14]), .QN
       (UNCONNECTED9));
  DFF_X2 \ps2_host_rx_frame_reg[1] (.CK (sys_clk), .D (n_203), .Q
       (ps2_host_rx_frame[1]), .QN (UNCONNECTED10));
  DFF_X2 \ps2_host_tx_frame_reg[11] (.CK (sys_clk), .D (n_207), .Q
       (ps2_host_tx_frame[11]), .QN (UNCONNECTED11));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[10] (.CK (sys_clk), .D
       (n_209), .Q (ps2_host_watchdog_watchdog_timer[10]), .QN
       (UNCONNECTED12));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[11] (.CK (sys_clk), .D
       (n_212), .Q (ps2_host_watchdog_watchdog_timer[11]), .QN
       (UNCONNECTED13));
  DFF_X2 \ps2_host_tx_frame_reg[10] (.CK (sys_clk), .D (n_200), .Q
       (ps2_host_tx_frame[10]), .QN (UNCONNECTED14));
  DFF_X2 \ps2_host_rx_frame_reg[9] (.CK (sys_clk), .D (n_195), .Q
       (ps2_host_rx_frame[9]), .QN (UNCONNECTED15));
  DFF_X2 \ps2_host_rx_frame_reg[10] (.CK (sys_clk), .D (n_206), .Q
       (ps2_host_rx_frame[10]), .QN (n_4));
  DFF_X2 \ps2_host_rx_frame_reg[6] (.CK (sys_clk), .D (n_198), .Q
       (ps2_host_rx_frame[6]), .QN (UNCONNECTED16));
  DFF_X2 \ps2_host_rx_frame_reg[7] (.CK (sys_clk), .D (n_197), .Q
       (ps2_host_rx_frame[7]), .QN (UNCONNECTED17));
  DFF_X2 \ps2_host_rx_frame_reg[4] (.CK (sys_clk), .D (n_208), .Q
       (ps2_host_rx_frame[4]), .QN (UNCONNECTED18));
  DFF_X2 \ps2_host_rx_frame_reg[2] (.CK (sys_clk), .D (n_202), .Q
       (ps2_host_rx_frame[2]), .QN (UNCONNECTED19));
  DFF_X2 \ps2_host_rx_frame_reg[8] (.CK (sys_clk), .D (n_196), .Q
       (ps2_host_rx_frame[8]), .QN (UNCONNECTED20));
  DFF_X2 \ps2_host_rx_frame_reg[5] (.CK (sys_clk), .D (n_199), .Q
       (ps2_host_rx_frame[5]), .QN (UNCONNECTED21));
  DFF_X2 \ps2_host_rx_frame_reg[3] (.CK (sys_clk), .D (n_201), .Q
       (ps2_host_rx_frame[3]), .QN (UNCONNECTED22));
  DFF_X2 \ps2_host_rx_frame_reg[11] (.CK (sys_clk), .D (n_194), .Q
       (ps2_host_rx_frame[11]), .QN (n_127));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[13] (.CK (sys_clk), .D
       (n_182), .Q (ps2_host_watchdog_watchdog_timer[13]), .QN
       (UNCONNECTED23));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[1] (.CK (sys_clk), .D
       (n_190), .Q (ps2_host_watchdog_watchdog_timer[1]), .QN
       (UNCONNECTED24));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[6] (.CK (sys_clk), .D
       (n_180), .Q (ps2_host_watchdog_watchdog_timer[6]), .QN
       (UNCONNECTED25));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[8] (.CK (sys_clk), .D
       (n_186), .Q (ps2_host_watchdog_watchdog_timer[8]), .QN
       (UNCONNECTED26));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[0] (.CK (sys_clk), .D
       (n_179), .Q (ps2_host_watchdog_watchdog_timer[0]), .QN
       (UNCONNECTED27));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[2] (.CK (sys_clk), .D
       (n_184), .Q (ps2_host_watchdog_watchdog_timer[2]), .QN
       (UNCONNECTED28));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[12] (.CK (sys_clk), .D
       (n_183), .Q (ps2_host_watchdog_watchdog_timer[12]), .QN (n_2));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[3] (.CK (sys_clk), .D
       (n_181), .Q (ps2_host_watchdog_watchdog_timer[3]), .QN (n_0));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[7] (.CK (sys_clk), .D
       (n_185), .Q (ps2_host_watchdog_watchdog_timer[7]), .QN (n_3));
  DFF_X2 \ps2_host_rx_frame_reg[0] (.CK (sys_clk), .D (n_187), .Q
       (ps2_host_rx_frame[0]), .QN (UNCONNECTED29));
  INV_X1 g919(.A (n_214), .ZN (n_233));
  INV_X1 g911(.A (n_193), .ZN (n_232));
  INV_X1 g913(.A (n_223), .ZN (n_231));
  INV_X1 g914(.A (n_222), .ZN (n_230));
  INV_X1 g915(.A (n_218), .ZN (n_229));
  INV_X1 g916(.A (n_217), .ZN (n_228));
  INV_X1 g917(.A (n_216), .ZN (n_227));
  INV_X1 g918(.A (n_215), .ZN (n_226));
  INV_X1 g912(.A (n_213), .ZN (n_225));
  DFF_X2 \ps2_host_watchdog_watchdog_timer_reg[4] (.CK (sys_clk), .D
       (n_189), .Q (ps2_host_watchdog_watchdog_timer[4]), .QN
       (UNCONNECTED30));
  NAND2_X1 g906__2398(.A1 (n_211), .A2 (n_101), .ZN (n_224));
  AOI222_X1 g945__5107(.A1 (n_221), .A2 (ps2_host_tx_frame[2]), .B1
       (n_220), .B2 (tx_data[6]), .C1 (n_219), .C2
       (ps2_host_tx_frame[3]), .ZN (n_223));
  AOI222_X1 g946__6260(.A1 (n_221), .A2 (ps2_host_tx_frame[3]), .B1
       (n_220), .B2 (tx_data[5]), .C1 (n_219), .C2
       (ps2_host_tx_frame[4]), .ZN (n_222));
  AOI222_X1 g947__4319(.A1 (n_221), .A2 (ps2_host_tx_frame[4]), .B1
       (n_220), .B2 (tx_data[4]), .C1 (n_219), .C2
       (ps2_host_tx_frame[5]), .ZN (n_218));
  AOI222_X1 g948__8428(.A1 (n_221), .A2 (ps2_host_tx_frame[5]), .B1
       (n_220), .B2 (tx_data[3]), .C1 (n_219), .C2
       (ps2_host_tx_frame[6]), .ZN (n_217));
  AOI222_X1 g949__5526(.A1 (n_221), .A2 (ps2_host_tx_frame[6]), .B1
       (n_220), .B2 (tx_data[2]), .C1 (n_219), .C2
       (ps2_host_tx_frame[7]), .ZN (n_216));
  AOI222_X1 g950__6783(.A1 (n_221), .A2 (ps2_host_tx_frame[7]), .B1
       (n_220), .B2 (tx_data[1]), .C1 (n_219), .C2
       (ps2_host_tx_frame[8]), .ZN (n_215));
  AOI222_X1 g951__3680(.A1 (n_221), .A2 (ps2_host_tx_frame[8]), .B1
       (n_220), .B2 (tx_data[0]), .C1 (n_219), .C2
       (ps2_host_tx_frame[9]), .ZN (n_214));
  AOI222_X1 g944__1617(.A1 (n_221), .A2 (ps2_host_tx_frame[1]), .B1
       (n_220), .B2 (tx_data[7]), .C1 (n_219), .C2
       (ps2_host_tx_frame[2]), .ZN (n_213));
  NAND2_X1 g902__2802(.A1 (n_211), .A2 (n_120), .ZN (n_212));
  NAND2_X1 g900__1705(.A1 (n_211), .A2 (n_122), .ZN (n_210));
  NAND2_X1 g901__5122(.A1 (n_211), .A2 (n_114), .ZN (n_209));
  DFF_X2 ps2_host_watchdog_watchdog_active_reg(.CK (sys_clk), .D
       (n_178), .Q (ps2_host_watchdog_watchdog_active), .QN
       (UNCONNECTED31));
  DFF_X2 \ps2_host_tx_frame_reg[0] (.CK (sys_clk), .D (n_177), .Q
       (ps2_host_tx_frame[0]), .QN (n_69));
  NOR3_X1 g932__8246(.A1 (n_205), .A2 (n_172), .A3 (ready), .ZN
       (n_208));
  INV_X1 g921(.A (n_191), .ZN (n_207));
  NOR3_X1 g922__7098(.A1 (n_205), .A2 (n_163), .A3 (ready), .ZN
       (n_206));
  NAND2_X1 g926__6131(.A1 (n_211), .A2 (n_111), .ZN (n_204));
  NOR3_X1 g929__1881(.A1 (n_205), .A2 (n_171), .A3 (ready), .ZN
       (n_203));
  NOR3_X1 g930__5115(.A1 (n_205), .A2 (n_170), .A3 (ready), .ZN
       (n_202));
  NOR3_X1 g931__7482(.A1 (n_205), .A2 (n_175), .A3 (ready), .ZN
       (n_201));
  INV_X1 g920(.A (n_192), .ZN (n_200));
  NOR3_X1 g933__4733(.A1 (n_205), .A2 (n_162), .A3 (ready), .ZN
       (n_199));
  NOR3_X1 g934__6161(.A1 (n_205), .A2 (n_167), .A3 (ready), .ZN
       (n_198));
  NOR3_X1 g935__9315(.A1 (n_205), .A2 (n_166), .A3 (ready), .ZN
       (n_197));
  NOR3_X1 g936__9945(.A1 (n_205), .A2 (n_165), .A3 (ready), .ZN
       (n_196));
  NOR3_X1 g937__2883(.A1 (n_205), .A2 (n_164), .A3 (ready), .ZN
       (n_195));
  NOR3_X1 g939__2346(.A1 (n_205), .A2 (n_168), .A3 (ready), .ZN
       (n_194));
  AOI222_X1 g943__1666(.A1 (n_220), .A2 (n_78), .B1 (n_221), .B2
       (ps2_host_tx_frame[0]), .C1 (n_219), .C2 (ps2_host_tx_frame[1]),
       .ZN (n_193));
  AOI22_X1 g952__7410(.A1 (n_221), .A2 (ps2_host_tx_frame[9]), .B1
       (n_219), .B2 (ps2_host_tx_frame[10]), .ZN (n_192));
  AOI22_X1 g953__6417(.A1 (n_221), .A2 (ps2_host_tx_frame[10]), .B1
       (n_219), .B2 (ps2_host_tx_frame[11]), .ZN (n_191));
  NOR2_X1 g894__5477(.A1 (n_188), .A2 (n_35), .ZN (n_190));
  NOR2_X1 g895__2398(.A1 (n_188), .A2 (n_88), .ZN (n_189));
  NAND2_X1 g896__5107(.A1 (n_176), .A2 (n_112), .ZN (n_187));
  NOR2_X1 g897__6260(.A1 (n_188), .A2 (n_118), .ZN (n_186));
  NOR2_X1 g908__4319(.A1 (n_188), .A2 (n_86), .ZN (n_185));
  NOR2_X1 g899__8428(.A1 (n_188), .A2 (n_66), .ZN (n_184));
  NOR2_X1 g903__5526(.A1 (n_188), .A2 (n_116), .ZN (n_183));
  NOR2_X1 g904__6783(.A1 (n_188), .A2 (n_119), .ZN (n_182));
  NOR2_X1 g905__3680(.A1 (n_188), .A2 (n_71), .ZN (n_181));
  NOR2_X1 g907__1617(.A1 (n_188), .A2 (n_84), .ZN (n_180));
  NOR2_X1 g893__2802(.A1 (n_188), .A2
       (ps2_host_watchdog_watchdog_timer[0]), .ZN (n_179));
  AOI21_X1 g892__1705(.A (n_113), .B1 (n_160), .B2 (n_169), .ZN
       (n_178));
  OAI22_X1 g942__5122(.A1 (n_161), .A2 (n_69), .B1 (n_159), .B2
       (n_135), .ZN (n_177));
  INV_X1 g954(.A (n_188), .ZN (n_211));
  AOI221_X1 g961__8246(.A (ready), .B1 (ps2_data), .B2 (n_174), .C1
       (n_173), .C2 (ps2_host_rx_frame[0]), .ZN (n_176));
  AOI22_X1 g990__7098(.A1 (n_174), .A2 (ps2_host_rx_frame[2]), .B1
       (n_173), .B2 (ps2_host_rx_frame[3]), .ZN (n_175));
  AOI22_X1 g985__6131(.A1 (n_174), .A2 (ps2_host_rx_frame[3]), .B1
       (n_173), .B2 (ps2_host_rx_frame[4]), .ZN (n_172));
  AOI22_X1 g986__1881(.A1 (n_174), .A2 (ps2_host_rx_frame[0]), .B1
       (n_173), .B2 (ps2_host_rx_frame[1]), .ZN (n_171));
  AOI22_X1 g987__5115(.A1 (n_174), .A2 (ps2_host_rx_frame[1]), .B1
       (n_173), .B2 (ps2_host_rx_frame[2]), .ZN (n_170));
  NAND4_X2 g968__7482(.A1 (n_121), .A2 (n_173), .A3 (n_169), .A4
       (ps2_host_watchdog_watchdog_active), .ZN (n_188));
  AOI22_X1 g1000__4733(.A1 (n_174), .A2 (ps2_host_rx_frame[10]), .B1
       (n_173), .B2 (ps2_host_rx_frame[11]), .ZN (n_168));
  AOI22_X1 g995__6161(.A1 (n_174), .A2 (ps2_host_rx_frame[5]), .B1
       (n_173), .B2 (ps2_host_rx_frame[6]), .ZN (n_167));
  AOI22_X1 g996__9315(.A1 (n_174), .A2 (ps2_host_rx_frame[6]), .B1
       (n_173), .B2 (ps2_host_rx_frame[7]), .ZN (n_166));
  AOI22_X1 g997__9945(.A1 (n_174), .A2 (ps2_host_rx_frame[7]), .B1
       (n_173), .B2 (ps2_host_rx_frame[8]), .ZN (n_165));
  AOI22_X1 g998__2883(.A1 (n_174), .A2 (ps2_host_rx_frame[8]), .B1
       (n_173), .B2 (ps2_host_rx_frame[9]), .ZN (n_164));
  AOI22_X1 g999__2346(.A1 (n_174), .A2 (ps2_host_rx_frame[9]), .B1
       (n_173), .B2 (ps2_host_rx_frame[10]), .ZN (n_163));
  AOI22_X1 g994__1666(.A1 (n_174), .A2 (ps2_host_rx_frame[4]), .B1
       (n_173), .B2 (ps2_host_rx_frame[5]), .ZN (n_162));
  INV_X1 g1004(.A (n_161), .ZN (n_219));
  NOR2_X1 g988__7410(.A1 (n_174), .A2
       (ps2_host_watchdog_watchdog_active), .ZN (n_160));
  NAND2_X1 g1011__6417(.A1 (n_159), .A2 (n_169), .ZN (n_161));
  NOR2_X2 g1010__5477(.A1 (n_143), .A2 (n_169), .ZN (n_221));
  INV_X2 g1021(.A (n_174), .ZN (n_173));
  NOR2_X2 g1026__2398(.A1 (ps2_host_clk_ctrl_ps2_clk_samples[1]), .A2
       (ps2_host_clk_ctrl_ps2_clk_samples[0]), .ZN (n_174));
  NAND2_X1 g1030__5107(.A1 (ps2_host_clk_ctrl_ps2_clk_samples[0]), .A2
       (ps2_host_clk_ctrl_ps2_clk_samples[1]), .ZN (n_169));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[13] (.CK (sys_clk), .D
       (n_158), .Q (ps2_host_clk_ctrl_inhibit_timer[13]), .QN
       (UNCONNECTED32));
  DFF_X2 \ps2_host_clk_ctrl_ps2_clk_samples_reg[1] (.CK (sys_clk), .D
       (n_157), .Q (UNCONNECTED33), .QN
       (ps2_host_clk_ctrl_ps2_clk_samples[1]));
  NAND2_X1 g891__6260(.A1 (n_155), .A2 (n_152), .ZN (n_158));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[9] (.CK (sys_clk), .D
       (n_154), .Q (ps2_host_clk_ctrl_inhibit_timer[9]), .QN
       (UNCONNECTED34));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[10] (.CK (sys_clk), .D
       (n_156), .Q (ps2_host_clk_ctrl_inhibit_timer[10]), .QN
       (UNCONNECTED35));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[4] (.CK (sys_clk), .D
       (n_150), .Q (ps2_host_clk_ctrl_inhibit_timer[4]), .QN
       (UNCONNECTED36));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[8] (.CK (sys_clk), .D
       (n_151), .Q (ps2_host_clk_ctrl_inhibit_timer[8]), .QN
       (UNCONNECTED37));
  DFF_X2 ps2_host_rx_error_reg(.CK (sys_clk), .D (n_149), .Q (error),
       .QN (UNCONNECTED38));
  OR2_X4 g1038__4319(.A1 (ps2_host_clk_ctrl_ps2_clk_samples[0]), .A2
       (sys_rst), .ZN (n_157));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[11] (.CK (sys_clk), .D
       (n_146), .Q (ps2_host_clk_ctrl_inhibit_timer[11]), .QN
       (UNCONNECTED39));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[1] (.CK (sys_clk), .D
       (n_148), .Q (ps2_host_clk_ctrl_inhibit_timer[1]), .QN
       (UNCONNECTED40));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[5] (.CK (sys_clk), .D
       (n_141), .Q (ps2_host_clk_ctrl_inhibit_timer[5]), .QN
       (UNCONNECTED41));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[12] (.CK (sys_clk), .D
       (n_145), .Q (ps2_host_clk_ctrl_inhibit_timer[12]), .QN
       (UNCONNECTED42));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[0] (.CK (sys_clk), .D
       (n_142), .Q (ps2_host_clk_ctrl_inhibit_timer[0]), .QN
       (UNCONNECTED43));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[2] (.CK (sys_clk), .D
       (n_147), .Q (ps2_host_clk_ctrl_inhibit_timer[2]), .QN
       (UNCONNECTED44));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[6] (.CK (sys_clk), .D
       (n_140), .Q (ps2_host_clk_ctrl_inhibit_timer[6]), .QN
       (UNCONNECTED45));
  OAI21_X1 g941__8428(.A (n_155), .B1 (n_107), .B2 (n_153), .ZN
       (n_156));
  OAI21_X1 g940__5526(.A (n_155), .B1 (n_102), .B2 (n_153), .ZN
       (n_154));
  OAI211_X1 g956__6783(.A (n_137), .B
       (ps2_host_clk_ctrl_inhibit_timer[13]), .C1 (n_98), .C2 (n_53),
       .ZN (n_152));
  OAI21_X1 g927__3680(.A (n_155), .B1 (n_153), .B2 (n_100), .ZN
       (n_151));
  OAI21_X1 g928__1617(.A (n_155), .B1 (n_153), .B2 (n_74), .ZN (n_150));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[7] (.CK (sys_clk), .D
       (n_139), .Q (ps2_host_clk_ctrl_inhibit_timer[7]), .QN
       (UNCONNECTED46));
  DFF_X2 \ps2_host_clk_ctrl_inhibit_timer_reg[3] (.CK (sys_clk), .D
       (n_144), .Q (ps2_host_clk_ctrl_inhibit_timer[3]), .QN
       (UNCONNECTED47));
  NOR2_X1 g886__2802(.A1 (n_138), .A2 (n_205), .ZN (n_149));
  DFF_X2 \ps2_host_clk_ctrl_ps2_clk_samples_reg[0] (.CK (sys_clk), .D
       (n_136), .Q (ps2_host_clk_ctrl_ps2_clk_samples[0]), .QN
       (UNCONNECTED48));
  NOR2_X1 g890__1705(.A1 (n_153), .A2 (n_37), .ZN (n_148));
  NOR2_X1 g898__5122(.A1 (n_153), .A2 (n_65), .ZN (n_147));
  DFF_X2 \ps2_host_rx_rx_data_reg[0] (.CK (sys_clk), .D (n_124), .Q
       (rx_data[0]), .QN (UNCONNECTED49));
  DFF_X2 \ps2_host_rx_rx_data_reg[3] (.CK (sys_clk), .D (n_132), .Q
       (rx_data[3]), .QN (UNCONNECTED50));
  DFF_X2 \ps2_host_rx_rx_data_reg[1] (.CK (sys_clk), .D (n_126), .Q
       (rx_data[1]), .QN (UNCONNECTED51));
  DFF_X2 \ps2_host_rx_rx_data_reg[2] (.CK (sys_clk), .D (n_133), .Q
       (rx_data[2]), .QN (UNCONNECTED52));
  DFF_X2 \ps2_host_rx_rx_data_reg[4] (.CK (sys_clk), .D (n_131), .Q
       (rx_data[4]), .QN (UNCONNECTED53));
  DFF_X2 \ps2_host_rx_rx_data_reg[5] (.CK (sys_clk), .D (n_130), .Q
       (rx_data[5]), .QN (UNCONNECTED54));
  DFF_X2 \ps2_host_rx_rx_data_reg[7] (.CK (sys_clk), .D (n_125), .Q
       (rx_data[7]), .QN (UNCONNECTED55));
  NAND2_X1 g967__8246(.A1 (n_153), .A2 (n_123), .ZN (n_155));
  NOR2_X1 g909__7098(.A1 (n_108), .A2 (n_153), .ZN (n_146));
  NOR2_X1 g910__6131(.A1 (n_109), .A2 (n_153), .ZN (n_145));
  NOR2_X1 g938__1881(.A1 (n_153), .A2 (n_72), .ZN (n_144));
  INV_X1 g1020(.A (n_159), .ZN (n_143));
  NOR2_X1 g880__5115(.A1 (n_153), .A2
       (ps2_host_clk_ctrl_inhibit_timer[0]), .ZN (n_142));
  NOR2_X1 g923__7482(.A1 (n_153), .A2 (n_82), .ZN (n_141));
  NOR2_X1 g924__4733(.A1 (n_153), .A2 (n_85), .ZN (n_140));
  NOR2_X1 g925__6161(.A1 (n_153), .A2 (n_83), .ZN (n_139));
  DFF_X2 \ps2_host_rx_rx_data_reg[6] (.CK (sys_clk), .D (n_129), .Q
       (rx_data[6]), .QN (UNCONNECTED56));
  DFF_X2 ps2_host_rx_ready_reg(.CK (sys_clk), .D (n_128), .Q (ready),
       .QN (UNCONNECTED57));
  AOI22_X1 g957__9315(.A1 (n_115), .A2 (ps2_host_rx_frame[11]), .B1
       (error), .B2 (n_127), .ZN (n_138));
  INV_X1 g984(.A (n_153), .ZN (n_137));
  OR2_X4 g1050__9945(.A1 (ps2_clk), .A2 (sys_rst), .ZN (n_136));
  NOR2_X1 g1025__2883(.A1 (n_135), .A2 (n_60), .ZN (n_159));
  NOR2_X2 g991__2346(.A1 (n_135), .A2 (busy), .ZN (n_220));
  NOR2_X1 g883__1666(.A1 (n_205), .A2 (n_33), .ZN (n_133));
  NOR2_X1 g884__7410(.A1 (n_205), .A2 (n_27), .ZN (n_132));
  NOR2_X1 g885__6417(.A1 (n_205), .A2 (n_32), .ZN (n_131));
  NOR2_X1 g887__5477(.A1 (n_205), .A2 (n_31), .ZN (n_130));
  NOR2_X1 g888__2398(.A1 (n_205), .A2 (n_30), .ZN (n_129));
  NOR2_X1 g1013__5107(.A1 (n_205), .A2 (n_127), .ZN (n_128));
  NOR2_X1 g882__6260(.A1 (n_205), .A2 (n_34), .ZN (n_126));
  NOR2_X1 g889__4319(.A1 (n_205), .A2 (n_29), .ZN (n_125));
  NOR2_X1 g881__8428(.A1 (n_205), .A2 (n_28), .ZN (n_124));
  NAND2_X2 g993__5526(.A1 (n_123), .A2 (n_103), .ZN (n_153));
  XNOR2_X1 g975__6783(.A (n_117), .B
       (ps2_host_watchdog_watchdog_timer[9]), .ZN (n_122));
  OAI21_X1 g1036__3680(.A (n_121), .B1 (busy), .B2 (send_req), .ZN
       (n_135));
  XOR2_X1 g970__1617(.A (n_95), .B
       (ps2_host_watchdog_watchdog_timer[11]), .Z (n_120));
  XNOR2_X1 g969__2802(.A (n_90), .B
       (ps2_host_watchdog_watchdog_timer[13]), .ZN (n_119));
  AOI21_X1 g1080__1705(.A (n_117), .B1 (n_106), .B2
       (ps2_host_watchdog_watchdog_timer[8]), .ZN (n_118));
  XOR2_X1 g971__5122(.A (n_93), .B
       (ps2_host_watchdog_watchdog_timer[12]), .Z (n_116));
  NAND3_X1 g1012__8246(.A1 (n_105), .A2 (ps2_host_rx_frame[0]), .A3
       (n_4), .ZN (n_115));
  XOR2_X1 g976__7098(.A (n_91), .B
       (ps2_host_watchdog_watchdog_timer[10]), .Z (n_114));
  INV_X1 g1037(.A (n_121), .ZN (n_113));
  NOR2_X1 g1014__6131(.A1 (n_104), .A2 (sys_rst), .ZN (n_123));
  INV_X2 g1027(.A (n_112), .ZN (n_205));
  TINV_X1 ps2_host_clk_ctrl_g11__1881(.EN (n_97), .I (1'b1), .ZN
       (ps2_clk));
  NAND2_X1 g966__5115(.A1 (n_96), .A2
       (ps2_host_watchdog_watchdog_timer[14]), .ZN (n_111));
  NOR3_X1 g1031__7482(.A1 (n_110), .A2 (busy), .A3 (sys_rst), .ZN
       (n_112));
  NOR2_X1 g1040__4733(.A1 (n_110), .A2 (sys_rst), .ZN (n_121));
  XNOR2_X1 g978__6161(.A (ps2_host_clk_ctrl_inhibit_timer[12]), .B
       (n_79), .ZN (n_109));
  XNOR2_X1 g977__9315(.A (ps2_host_clk_ctrl_inhibit_timer[11]), .B
       (n_80), .ZN (n_108));
  XOR2_X1 g1001__9945(.A (ps2_host_clk_ctrl_inhibit_timer[10]), .B
       (n_77), .Z (n_107));
  NOR2_X1 g1081__2883(.A1 (n_106), .A2
       (ps2_host_watchdog_watchdog_timer[8]), .ZN (n_117));
  XOR2_X1 g1034__2346(.A (n_75), .B (ps2_host_rx_frame[1]), .Z (n_105));
  NOR2_X1 g1022__1666(.A1 (n_103), .A2 (send_req), .ZN (n_104));
  XNOR2_X1 g1003__7410(.A (ps2_host_clk_ctrl_inhibit_timer[9]), .B
       (n_99), .ZN (n_102));
  XNOR2_X1 g983__6417(.A (n_87), .B
       (ps2_host_watchdog_watchdog_timer[5]), .ZN (n_101));
  AOI21_X1 g1079__5477(.A (n_99), .B1 (n_98), .B2
       (ps2_host_clk_ctrl_inhibit_timer[8]), .ZN (n_100));
  INV_X1 g1071(.A (n_103), .ZN (n_97));
  NAND3_X1 g989__2398(.A1 (n_94), .A2 (n_92), .A3 (n_7), .ZN (n_96));
  NAND2_X1 g1015__5107(.A1 (n_94), .A2 (n_89), .ZN (n_95));
  NAND2_X1 g1009__6260(.A1 (n_94), .A2 (n_92), .ZN (n_93));
  NAND2_X1 g1008__4319(.A1 (n_94), .A2 (n_17), .ZN (n_91));
  AND3_X4 g1016__8428(.A1 (n_94), .A2 (n_92), .A3 (n_2), .ZN (n_90));
  AND4_X2 g1047__5526(.A1 (n_68), .A2 (n_89), .A3 (n_40), .A4 (n_3),
       .ZN (n_110));
  TBUF_X1 ps2_host_tx_g9__6783(.A (ps2_host_tx_frame[11]), .EN (n_70),
       .Z (ps2_data));
  AOI21_X1 g1084__3680(.A (n_87), .B1 (n_81), .B2
       (ps2_host_watchdog_watchdog_timer[4]), .ZN (n_88));
  INV_X1 g1088(.A (n_94), .ZN (n_106));
  NAND4_X1 g1072__1617(.A1 (n_248), .A2 (n_36), .A3 (n_61), .A4 (n_25),
       .ZN (n_103));
  XOR2_X1 g972__2802(.A (n_58), .B
       (ps2_host_watchdog_watchdog_timer[7]), .Z (n_86));
  XOR2_X1 g973__1705(.A (n_62), .B
       (ps2_host_clk_ctrl_inhibit_timer[6]), .Z (n_85));
  XOR2_X1 g974__5122(.A (n_59), .B
       (ps2_host_watchdog_watchdog_timer[6]), .Z (n_84));
  XNOR2_X1 g979__8246(.A (ps2_host_clk_ctrl_inhibit_timer[7]), .B
       (n_50), .ZN (n_83));
  XNOR2_X1 g981__7098(.A (ps2_host_clk_ctrl_inhibit_timer[5]), .B
       (n_73), .ZN (n_82));
  NOR2_X1 g1082__6131(.A1 (n_98), .A2
       (ps2_host_clk_ctrl_inhibit_timer[8]), .ZN (n_99));
  NOR4_X2 g1091__1881(.A1 (n_81), .A2 (n_39), .A3
       (ps2_host_watchdog_watchdog_timer[7]), .A4
       (ps2_host_watchdog_watchdog_timer[6]), .ZN (n_94));
  NOR3_X1 g1018__5115(.A1 (n_98), .A2 (n_76), .A3
       (ps2_host_clk_ctrl_inhibit_timer[10]), .ZN (n_80));
  NOR2_X1 g1007__7482(.A1 (n_98), .A2 (n_52), .ZN (n_79));
  XOR2_X1 g1002__4733(.A (n_46), .B (n_51), .Z (n_78));
  OR2_X4 g1024__6161(.A1 (n_98), .A2 (n_76), .ZN (n_77));
  XOR2_X1 g1048__9315(.A (n_47), .B (n_45), .Z (n_75));
  AOI21_X1 g1083__9945(.A (n_73), .B1 (n_49), .B2
       (ps2_host_clk_ctrl_inhibit_timer[4]), .ZN (n_74));
  XNOR2_X1 g980__2883(.A (n_64), .B
       (ps2_host_clk_ctrl_inhibit_timer[3]), .ZN (n_72));
  NOR2_X1 g1085__2346(.A1 (n_81), .A2
       (ps2_host_watchdog_watchdog_timer[4]), .ZN (n_87));
  XNOR2_X1 g982__1666(.A (ps2_host_watchdog_watchdog_timer[3]), .B
       (n_67), .ZN (n_71));
  NAND2_X1 g1044__7410(.A1 (n_48), .A2 (n_69), .ZN (n_70));
  AND3_X4 g1051__6417(.A1 (n_67), .A2 (n_56), .A3 (n_0), .ZN (n_68));
  AOI21_X1 g1090__5477(.A (n_67), .B1 (n_41), .B2
       (ps2_host_watchdog_watchdog_timer[2]), .ZN (n_66));
  AOI21_X1 g1089__2398(.A (n_64), .B1 (n_42), .B2
       (ps2_host_clk_ctrl_inhibit_timer[2]), .ZN (n_65));
  NAND2_X1 g1005__6260(.A1 (n_55), .A2 (n_61), .ZN (n_62));
  INV_X1 g1046(.A (busy), .ZN (n_60));
  NAND2_X1 g1019__4319(.A1 (n_57), .A2 (n_5), .ZN (n_59));
  NAND2_X1 g1006__8428(.A1 (n_57), .A2 (n_56), .ZN (n_58));
  NAND3_X1 g1087__5526(.A1 (n_55), .A2 (n_61), .A3 (n_54), .ZN (n_98));
  OR2_X2 g1023__6783(.A1 (n_52), .A2
       (ps2_host_clk_ctrl_inhibit_timer[12]), .ZN (n_53));
  XOR2_X1 g1028__3680(.A (n_14), .B (n_13), .Z (n_51));
  NOR3_X1 g1017__1617(.A1 (n_49), .A2 (n_19), .A3
       (ps2_host_clk_ctrl_inhibit_timer[6]), .ZN (n_50));
  NOR2_X1 g1086__2802(.A1 (n_49), .A2
       (ps2_host_clk_ctrl_inhibit_timer[4]), .ZN (n_73));
  INV_X1 g1095(.A (n_57), .ZN (n_81));
  NAND3_X1 g1052__1705(.A1 (n_9), .A2 (n_22), .A3 (n_44), .ZN (n_48));
  XOR2_X1 g1058__5122(.A (n_24), .B (n_23), .Z (n_47));
  XOR2_X1 g1029__8246(.A (n_12), .B (n_6), .Z (n_46));
  XOR2_X1 g1057__7098(.A (n_15), .B (n_18), .Z (n_45));
  NAND4_X1 g1049__6131(.A1 (n_11), .A2 (n_10), .A3 (n_44), .A4 (n_1),
       .ZN (busy));
  NOR2_X1 g1092__5115(.A1 (n_42), .A2
       (ps2_host_clk_ctrl_inhibit_timer[2]), .ZN (n_64));
  INV_X1 g1094(.A (n_49), .ZN (n_55));
  NOR2_X1 g1093__7482(.A1 (n_41), .A2
       (ps2_host_watchdog_watchdog_timer[2]), .ZN (n_67));
  NOR3_X1 g1053__4733(.A1 (n_8), .A2
       (ps2_host_watchdog_watchdog_timer[11]), .A3
       (ps2_host_watchdog_watchdog_timer[14]), .ZN (n_40));
  NOR2_X1 g1060__6161(.A1 (n_38), .A2
       (ps2_host_watchdog_watchdog_timer[10]), .ZN (n_89));
  NOR2_X1 g1059__9315(.A1 (n_39), .A2
       (ps2_host_watchdog_watchdog_timer[6]), .ZN (n_56));
  NOR3_X1 g1035__9945(.A1 (n_38), .A2
       (ps2_host_watchdog_watchdog_timer[10]), .A3
       (ps2_host_watchdog_watchdog_timer[11]), .ZN (n_92));
  NOR3_X1 g1097__2883(.A1 (n_41), .A2
       (ps2_host_watchdog_watchdog_timer[2]), .A3
       (ps2_host_watchdog_watchdog_timer[3]), .ZN (n_57));
  AOI21_X1 g1105__2346(.A (n_36), .B1
       (ps2_host_clk_ctrl_inhibit_timer[0]), .B2
       (ps2_host_clk_ctrl_inhibit_timer[1]), .ZN (n_37));
  AOI21_X1 g1106__1666(.A (n_16), .B1
       (ps2_host_watchdog_watchdog_timer[0]), .B2
       (ps2_host_watchdog_watchdog_timer[1]), .ZN (n_35));
  AOI22_X1 g959__7410(.A1 (rx_data[1]), .A2 (n_127), .B1
       (ps2_host_rx_frame[8]), .B2 (ps2_host_rx_frame[11]), .ZN (n_34));
  AOI22_X1 g960__6417(.A1 (rx_data[2]), .A2 (n_127), .B1
       (ps2_host_rx_frame[7]), .B2 (ps2_host_rx_frame[11]), .ZN (n_33));
  AOI22_X1 g962__5477(.A1 (rx_data[4]), .A2 (n_127), .B1
       (ps2_host_rx_frame[5]), .B2 (ps2_host_rx_frame[11]), .ZN (n_32));
  AOI22_X1 g963__2398(.A1 (rx_data[5]), .A2 (n_127), .B1
       (ps2_host_rx_frame[4]), .B2 (ps2_host_rx_frame[11]), .ZN (n_31));
  AOI22_X1 g964__5107(.A1 (rx_data[6]), .A2 (n_127), .B1
       (ps2_host_rx_frame[3]), .B2 (ps2_host_rx_frame[11]), .ZN (n_30));
  AOI22_X1 g965__6260(.A1 (rx_data[7]), .A2 (n_127), .B1
       (ps2_host_rx_frame[2]), .B2 (ps2_host_rx_frame[11]), .ZN (n_29));
  AOI22_X1 g958__4319(.A1 (rx_data[0]), .A2 (n_127), .B1
       (ps2_host_rx_frame[9]), .B2 (ps2_host_rx_frame[11]), .ZN (n_28));
  AOI22_X1 g955__8428(.A1 (rx_data[3]), .A2 (n_127), .B1
       (ps2_host_rx_frame[6]), .B2 (ps2_host_rx_frame[11]), .ZN (n_27));
  NAND2_X1 g1033__5526(.A1 (n_26), .A2 (n_20), .ZN (n_52));
  NAND2_X1 g1096__6783(.A1 (n_36), .A2 (n_25), .ZN (n_49));
  XOR2_X1 g1068__3680(.A (ps2_host_rx_frame[8]), .B
       (ps2_host_rx_frame[3]), .Z (n_24));
  XNOR2_X1 g1069__1617(.A (ps2_host_rx_frame[5]), .B
       (ps2_host_rx_frame[7]), .ZN (n_23));
  NOR4_X1 g1061__2802(.A1 (ps2_host_tx_frame[8]), .A2
       (ps2_host_tx_frame[7]), .A3 (ps2_host_tx_frame[9]), .A4
       (ps2_host_tx_frame[10]), .ZN (n_22));
  INV_X1 g1100(.A (n_61), .ZN (n_19));
  XNOR2_X1 g1070__1705(.A (ps2_host_rx_frame[4]), .B
       (ps2_host_rx_frame[6]), .ZN (n_18));
  INV_X1 g1075(.A (n_26), .ZN (n_76));
  INV_X1 g1098(.A (n_36), .ZN (n_42));
  INV_X1 g1064(.A (n_17), .ZN (n_38));
  INV_X1 g1108(.A (n_16), .ZN (n_41));
  XOR2_X1 g1066__5122(.A (ps2_host_rx_frame[9]), .B
       (ps2_host_rx_frame[2]), .Z (n_15));
  XOR2_X1 g1042__8246(.A (tx_data[7]), .B (tx_data[0]), .Z (n_14));
  XOR2_X1 g1043__7098(.A (tx_data[4]), .B (tx_data[2]), .Z (n_13));
  XOR2_X1 g1039__6131(.A (tx_data[6]), .B (tx_data[1]), .Z (n_12));
  NOR4_X1 g1055__1881(.A1 (ps2_host_tx_frame[5]), .A2
       (ps2_host_tx_frame[4]), .A3 (ps2_host_tx_frame[6]), .A4
       (ps2_host_tx_frame[7]), .ZN (n_11));
  NOR4_X1 g1056__5115(.A1 (ps2_host_tx_frame[9]), .A2
       (ps2_host_tx_frame[8]), .A3 (ps2_host_tx_frame[10]), .A4
       (ps2_host_tx_frame[11]), .ZN (n_10));
  NOR4_X1 g1062__7482(.A1 (ps2_host_tx_frame[4]), .A2
       (ps2_host_tx_frame[3]), .A3 (ps2_host_tx_frame[5]), .A4
       (ps2_host_tx_frame[6]), .ZN (n_9));
  INV_X1 g1063(.A (n_7), .ZN (n_8));
  XNOR2_X1 g1041__4733(.A (tx_data[5]), .B (tx_data[3]), .ZN (n_6));
  NOR3_X1 g1054__6161(.A1 (ps2_host_tx_frame[0]), .A2
       (ps2_host_tx_frame[1]), .A3 (ps2_host_tx_frame[2]), .ZN (n_44));
  INV_X1 g1099(.A (n_5), .ZN (n_39));
  NOR2_X1 g1065__9315(.A1 (ps2_host_watchdog_watchdog_timer[12]), .A2
       (ps2_host_watchdog_watchdog_timer[13]), .ZN (n_7));
  NOR2_X1 g1101__9945(.A1 (ps2_host_watchdog_watchdog_timer[4]), .A2
       (ps2_host_watchdog_watchdog_timer[5]), .ZN (n_5));
  NOR2_X1 g1067__2883(.A1 (ps2_host_watchdog_watchdog_timer[8]), .A2
       (ps2_host_watchdog_watchdog_timer[9]), .ZN (n_17));
  NOR2_X1 g1078__2346(.A1 (ps2_host_clk_ctrl_inhibit_timer[10]), .A2
       (ps2_host_clk_ctrl_inhibit_timer[11]), .ZN (n_20));
  NOR2_X1 g1104__1666(.A1 (ps2_host_clk_ctrl_inhibit_timer[6]), .A2
       (ps2_host_clk_ctrl_inhibit_timer[7]), .ZN (n_54));
  NOR2_X1 g1109__7410(.A1 (ps2_host_watchdog_watchdog_timer[0]), .A2
       (ps2_host_watchdog_watchdog_timer[1]), .ZN (n_16));
  NOR2_X1 g1103__6417(.A1 (ps2_host_clk_ctrl_inhibit_timer[2]), .A2
       (ps2_host_clk_ctrl_inhibit_timer[3]), .ZN (n_25));
  NOR2_X1 g1076__5477(.A1 (ps2_host_clk_ctrl_inhibit_timer[8]), .A2
       (ps2_host_clk_ctrl_inhibit_timer[9]), .ZN (n_26));
  NOR2_X1 g1107__2398(.A1 (ps2_host_clk_ctrl_inhibit_timer[0]), .A2
       (ps2_host_clk_ctrl_inhibit_timer[1]), .ZN (n_36));
  NOR2_X1 g1102__5107(.A1 (ps2_host_clk_ctrl_inhibit_timer[4]), .A2
       (ps2_host_clk_ctrl_inhibit_timer[5]), .ZN (n_61));
  NOR3_X1 g2(.A1 (n_247), .A2 (ps2_host_clk_ctrl_inhibit_timer[12]),
       .A3 (ps2_host_clk_ctrl_inhibit_timer[13]), .ZN (n_248));
  NAND3_X1 g3(.A1 (n_26), .A2 (n_54), .A3 (n_20), .ZN (n_247));
endmodule

