
//input ports
add mapped point CLK_in CLK_in -type PI PI
add mapped point RST_top RST_top -type PI PI
add mapped point sys_ini sys_ini -type PI PI
add mapped point start_tx_but start_tx_but -type PI PI
add mapped point start_enc_but start_enc_but -type PI PI
add mapped point sw_in[7] sw_in[7] -type PI PI
add mapped point sw_in[6] sw_in[6] -type PI PI
add mapped point sw_in[5] sw_in[5] -type PI PI
add mapped point sw_in[4] sw_in[4] -type PI PI
add mapped point sw_in[3] sw_in[3] -type PI PI
add mapped point sw_in[2] sw_in[2] -type PI PI
add mapped point sw_in[1] sw_in[1] -type PI PI
add mapped point sw_in[0] sw_in[0] -type PI PI
add mapped point scan_in scan_in -type PI PI
add mapped point scan_enable scan_enable -type PI PI
add mapped point trg_1 trg_1 -type PI PI

//output ports
add mapped point Led[7] Led[7] -type PO PO
add mapped point Led[6] Led[6] -type PO PO
add mapped point Led[5] Led[5] -type PO PO
add mapped point Led[4] Led[4] -type PO PO
add mapped point Led[3] Led[3] -type PO PO
add mapped point Led[2] Led[2] -type PO PO
add mapped point Led[1] Led[1] -type PO PO
add mapped point Led[0] Led[0] -type PO PO
add mapped point rs232_trx rs232_trx -type PO PO
add mapped point an[3] an[3] -type PO PO
add mapped point an[2] an[2] -type PO PO
add mapped point an[1] an[1] -type PO PO
add mapped point an[0] an[0] -type PO PO
add mapped point seg[6] seg[6] -type PO PO
add mapped point seg[5] seg[5] -type PO PO
add mapped point seg[4] seg[4] -type PO PO
add mapped point seg[3] seg[3] -type PO PO
add mapped point seg[2] seg[2] -type PO PO
add mapped point seg[1] seg[1] -type PO PO
add mapped point seg[0] seg[0] -type PO PO
add mapped point dp dp -type PO PO
add mapped point scan_out scan_out -type PO PO

//inout ports
add mapped point PS2C_top PS2C_top
add mapped point PS2D_top PS2D_top
add mapped point HSYNC HSYNC
add mapped point VSYNC VSYNC
add mapped point vgaRed[2] vgaRed[2]
add mapped point vgaRed[1] vgaRed[1]
add mapped point vgaRed[0] vgaRed[0]
add mapped point vgaGreen[2] vgaGreen[2]
add mapped point vgaGreen[1] vgaGreen[1]
add mapped point vgaGreen[0] vgaGreen[0]
add mapped point vgaBlue[1] vgaBlue[1]
add mapped point vgaBlue[0] vgaBlue[0]




//Sequential Pins
add mapped point u2/kbass/ascii_ready/q u2/kbass_ascii_ready_reg/Q -type DFF DFF
add mapped point u2/kbass/ascii[0]/q u2/kbass_ascii_reg[0]/Q -type DFF DFF
add mapped point u2/kbass/ascii[1]/q u2/kbass_ascii_reg[1]/Q -type DFF DFF
add mapped point u2/kbass/ascii[2]/q u2/kbass_ascii_reg[2]/Q -type DFF DFF
add mapped point u2/kbass/ascii[3]/q u2/kbass_ascii_reg[3]/Q -type DFF DFF
add mapped point u2/kbass/ascii[4]/q u2/kbass_ascii_reg[4]/Q -type DFF DFF
add mapped point u2/kbass/ascii[5]/q u2/kbass_ascii_reg[5]/Q -type DFF DFF
add mapped point u2/kbass/ascii[6]/q u2/kbass_ascii_reg[6]/Q -type DFF DFF
add mapped point u2/kbass/ascii[7]/q u2/kbass_ascii_reg[7]/Q -type DFF DFF
add mapped point u2/kbass/ascii_valid/q u2/kbass_ascii_valid_reg/Q -type DFF DFF
add mapped point u2/kbass/key_up/q u2/kbass_key_up_reg/Q -type DFF DFF
add mapped point u2/kbass/shift_key/q u2/kbass_shift_key_reg/Q -type DFF DFF
add mapped point u11/ascii_input_reg[0]/q u11/ascii_input_reg_reg[0]/Q -type DFF DFF
add mapped point u11/ascii_input_reg[1]/q u11/ascii_input_reg_reg[1]/Q -type DFF DFF
add mapped point u11/ascii_input_reg[2]/q u11/ascii_input_reg_reg[2]/Q -type DFF DFF
add mapped point u11/ascii_input_reg[3]/q u11/ascii_input_reg_reg[3]/Q -type DFF DFF
add mapped point u11/ascii_input_reg[4]/q u11/ascii_input_reg_reg[4]/Q -type DFF DFF
add mapped point u11/ascii_input_reg[5]/q u11/ascii_input_reg_reg[5]/Q -type DFF DFF
add mapped point u11/ascii_input_reg[6]/q u11/ascii_input_reg_reg[6]/Q -type DFF DFF
add mapped point u11/ascii_input_reg[7]/q u11/ascii_input_reg_reg[7]/Q -type DFF DFF
add mapped point u11/ascii_read_in_reg/q u11/ascii_read_in_reg_reg/Q -type DFF DFF
add mapped point u11/clear_text_ram_reg/q u11/clear_text_ram_reg_reg/Q -type DFF DFF
add mapped point u11/cur_x[0]/q u11/cur_x_reg[0]/Q -type DFF DFF
add mapped point u11/cur_x[1]/q u11/cur_x_reg[1]/Q -type DFF DFF
add mapped point u11/cur_x[2]/q u11/cur_x_reg[2]/Q -type DFF DFF
add mapped point u11/cur_x[3]/q u11/cur_x_reg[3]/Q -type DFF DFF
add mapped point u11/cur_x[4]/q u11/cur_x_reg[4]/Q -type DFF DFF
add mapped point u11/cur_x[5]/q u11/cur_x_reg[5]/Q -type DFF DFF
add mapped point u11/cur_x[6]/q u11/cur_x_reg[6]/Q -type DFF DFF
add mapped point u11/cur_x[7]/q u11/cur_x_reg[7]/Q -type DFF DFF
add mapped point u11/cur_y[0]/q u11/cur_y_reg[0]/Q -type DFF DFF
add mapped point u11/cur_y[1]/q u11/cur_y_reg[1]/Q -type DFF DFF
add mapped point u11/cur_y[2]/q u11/cur_y_reg[2]/Q -type DFF DFF
add mapped point u11/cur_y[3]/q u11/cur_y_reg[3]/Q -type DFF DFF
add mapped point u11/cur_y[4]/q u11/cur_y_reg[4]/Q -type DFF DFF
add mapped point u11/cur_y[5]/q u11/cur_y_reg[5]/Q -type DFF DFF
add mapped point u11/cur_y[6]/q u11/cur_y_reg[6]/Q -type DFF DFF
add mapped point u11/cur_y[7]/q u11/cur_y_reg[7]/Q -type DFF DFF
add mapped point u11/text_ram_counter[0]/q u11/text_ram_counter_reg[0]/Q -type DFF DFF
add mapped point u11/text_ram_counter[1]/q u11/text_ram_counter_reg[1]/Q -type DFF DFF
add mapped point u11/text_ram_counter[2]/q u11/text_ram_counter_reg[2]/Q -type DFF DFF
add mapped point u11/text_ram_counter[3]/q u11/text_ram_counter_reg[3]/Q -type DFF DFF
add mapped point u11/text_ram_counter[4]/q u11/text_ram_counter_reg[4]/Q -type DFF DFF
add mapped point u11/text_ram_counter[5]/q u11/text_ram_counter_reg[5]/Q -type DFF DFF
add mapped point u11/text_ram_counter[6]/q u11/text_ram_counter_reg[6]/Q -type DFF DFF
add mapped point u11/text_ram_counter[7]/q u11/text_ram_counter_reg[7]/Q -type DFF DFF
add mapped point u11/text_ram_counter[8]/q u11/text_ram_counter_reg[8]/Q -type DFF DFF
add mapped point u11/text_ram_counter[9]/q u11/text_ram_counter_reg[9]/Q -type DFF DFF
add mapped point u11/text_ram_counter[10]/q u11/text_ram_counter_reg[10]/Q -type DFF DFF
add mapped point u11/text_ram_counter[11]/q u11/text_ram_counter_reg[11]/Q -type DFF DFF
add mapped point u4/dout_latch_0/q u4_dout_latch_0_reg/Q -type DFF DFF
add mapped point u4/enc_start_0/q u4_enc_start_0_reg/Q -type DFF DFF
add mapped point u4/in_buf_empty_1/q u4_in_buf_empty_1_reg/Q -type DFF DFF
add mapped point u7/enc_done_1/q u7_enc_done_1_reg/Q -type DFF DFF
add mapped point u9/out_buf_empty_1/q u9_out_buf_empty_1_reg/Q -type DFF DFF
add mapped point u9/rs232_busy_1/q u9_rs232_busy_1_reg/Q -type DFF DFF
add mapped point u9/start_tx_1/q u9_start_tx_1_reg/Q -type DFF DFF
add mapped point u9/start_tx_2/q u9_start_tx_2_reg/Q -type DFF DFF
add mapped point u10/TxD/q u10_TxD_reg/Q -type DFF DFF
add mapped point u13/out_buf_count[0]/q u13_out_buf_count_reg[0]/Q -type DFF DFF
add mapped point u13/out_buf_count[1]/q u13_out_buf_count_reg[1]/Q -type DFF DFF
add mapped point u13/out_buf_count[2]/q u13_out_buf_count_reg[2]/Q -type DFF DFF
add mapped point u13/out_buf_count[3]/q u13_out_buf_count_reg[3]/Q -type DFF DFF
add mapped point u13/out_buf_count[4]/q u13_out_buf_count_reg[4]/Q -type DFF DFF
add mapped point u13/out_buf_count[5]/q u13_out_buf_count_reg[5]/Q -type DFF DFF
add mapped point u13/out_buf_count[6]/q u13_out_buf_count_reg[6]/Q -type DFF DFF
add mapped point u13/out_buf_count[7]/q u13_out_buf_count_reg[7]/Q -type DFF DFF
add mapped point u13/out_buf_count[8]/q u13_out_buf_count_reg[8]/Q -type DFF DFF
add mapped point u13/out_buf_count[9]/q u13_out_buf_count_reg[9]/Q -type DFF DFF
add mapped point u13/state_decode[0]/q u13_state_decode_reg[0]/Q -type DFF DFF
add mapped point u13/state_decode[1]/q u13_state_decode_reg[1]/Q -type DFF DFF
add mapped point u13/state_decode[2]/q u13_state_decode_reg[2]/Q -type DFF DFF
add mapped point u13/state_decode[3]/q u13_state_decode_reg[3]/Q -type DFF DFF
add mapped point key_select_reg[0]/q key_select_reg_reg[0]/Q -type DFF DFF
add mapped point key_select_reg[1]/q key_select_reg_reg[1]/Q -type DFF DFF
add mapped point key_select_reg[2]/q key_select_reg_reg[2]/Q -type DFF DFF
add mapped point key_select_reg[3]/q key_select_reg_reg[3]/Q -type DFF DFF
add mapped point key_select_reg[4]/q key_select_reg_reg[4]/Q -type DFF DFF
add mapped point key_select_reg[5]/q key_select_reg_reg[5]/Q -type DFF DFF
add mapped point key_select_reg[6]/q key_select_reg_reg[6]/Q -type DFF DFF
add mapped point key_select_reg[7]/q key_select_reg_reg[7]/Q -type DFF DFF
add mapped point start_encryption_reg/q start_encryption_reg_reg/Q -type DFF DFF
add mapped point start_tx_out_reg/q start_tx_out_reg_reg/Q -type DFF DFF
add mapped point sys_ini_reg/q sys_ini_reg_reg/Q -type DFF DFF
add mapped point u4/dout[0]/q u4_dout_reg[0]/Q -type DFF DFF
add mapped point u4/dout[1]/q u4_dout_reg[1]/Q -type DFF DFF
add mapped point u4/dout[2]/q u4_dout_reg[2]/Q -type DFF DFF
add mapped point u4/dout[3]/q u4_dout_reg[3]/Q -type DFF DFF
add mapped point u4/dout[4]/q u4_dout_reg[4]/Q -type DFF DFF
add mapped point u4/dout[5]/q u4_dout_reg[5]/Q -type DFF DFF
add mapped point u4/dout[6]/q u4_dout_reg[6]/Q -type DFF DFF
add mapped point u4/dout[7]/q u4_dout_reg[7]/Q -type DFF DFF
add mapped point u4/dout[8]/q u4_dout_reg[8]/Q -type DFF DFF
add mapped point u4/dout[9]/q u4_dout_reg[9]/Q -type DFF DFF
add mapped point u4/dout[10]/q u4_dout_reg[10]/Q -type DFF DFF
add mapped point u4/dout[11]/q u4_dout_reg[11]/Q -type DFF DFF
add mapped point u4/dout[12]/q u4_dout_reg[12]/Q -type DFF DFF
add mapped point u4/dout[13]/q u4_dout_reg[13]/Q -type DFF DFF
add mapped point u4/dout[14]/q u4_dout_reg[14]/Q -type DFF DFF
add mapped point u4/dout[15]/q u4_dout_reg[15]/Q -type DFF DFF
add mapped point u4/dout[16]/q u4_dout_reg[16]/Q -type DFF DFF
add mapped point u4/dout[17]/q u4_dout_reg[17]/Q -type DFF DFF
add mapped point u4/dout[18]/q u4_dout_reg[18]/Q -type DFF DFF
add mapped point u4/dout[19]/q u4_dout_reg[19]/Q -type DFF DFF
add mapped point u4/dout[20]/q u4_dout_reg[20]/Q -type DFF DFF
add mapped point u4/dout[21]/q u4_dout_reg[21]/Q -type DFF DFF
add mapped point u4/dout[22]/q u4_dout_reg[22]/Q -type DFF DFF
add mapped point u4/dout[23]/q u4_dout_reg[23]/Q -type DFF DFF
add mapped point u4/dout[24]/q u4_dout_reg[24]/Q -type DFF DFF
add mapped point u4/dout[25]/q u4_dout_reg[25]/Q -type DFF DFF
add mapped point u4/dout[26]/q u4_dout_reg[26]/Q -type DFF DFF
add mapped point u4/dout[27]/q u4_dout_reg[27]/Q -type DFF DFF
add mapped point u4/dout[28]/q u4_dout_reg[28]/Q -type DFF DFF
add mapped point u4/dout[29]/q u4_dout_reg[29]/Q -type DFF DFF
add mapped point u4/dout[30]/q u4_dout_reg[30]/Q -type DFF DFF
add mapped point u4/dout[31]/q u4_dout_reg[31]/Q -type DFF DFF
add mapped point u4/dout[32]/q u4_dout_reg[32]/Q -type DFF DFF
add mapped point u4/dout[33]/q u4_dout_reg[33]/Q -type DFF DFF
add mapped point u4/dout[34]/q u4_dout_reg[34]/Q -type DFF DFF
add mapped point u4/dout[35]/q u4_dout_reg[35]/Q -type DFF DFF
add mapped point u4/dout[36]/q u4_dout_reg[36]/Q -type DFF DFF
add mapped point u4/dout[37]/q u4_dout_reg[37]/Q -type DFF DFF
add mapped point u4/dout[38]/q u4_dout_reg[38]/Q -type DFF DFF
add mapped point u4/dout[39]/q u4_dout_reg[39]/Q -type DFF DFF
add mapped point u4/dout[40]/q u4_dout_reg[40]/Q -type DFF DFF
add mapped point u4/dout[41]/q u4_dout_reg[41]/Q -type DFF DFF
add mapped point u4/dout[42]/q u4_dout_reg[42]/Q -type DFF DFF
add mapped point u4/dout[43]/q u4_dout_reg[43]/Q -type DFF DFF
add mapped point u4/dout[44]/q u4_dout_reg[44]/Q -type DFF DFF
add mapped point u4/dout[45]/q u4_dout_reg[45]/Q -type DFF DFF
add mapped point u4/dout[46]/q u4_dout_reg[46]/Q -type DFF DFF
add mapped point u4/dout[47]/q u4_dout_reg[47]/Q -type DFF DFF
add mapped point u4/dout[48]/q u4_dout_reg[48]/Q -type DFF DFF
add mapped point u4/dout[49]/q u4_dout_reg[49]/Q -type DFF DFF
add mapped point u4/dout[50]/q u4_dout_reg[50]/Q -type DFF DFF
add mapped point u4/dout[51]/q u4_dout_reg[51]/Q -type DFF DFF
add mapped point u4/dout[52]/q u4_dout_reg[52]/Q -type DFF DFF
add mapped point u4/dout[53]/q u4_dout_reg[53]/Q -type DFF DFF
add mapped point u4/dout[54]/q u4_dout_reg[54]/Q -type DFF DFF
add mapped point u4/dout[55]/q u4_dout_reg[55]/Q -type DFF DFF
add mapped point u4/dout[56]/q u4_dout_reg[56]/Q -type DFF DFF
add mapped point u4/dout[57]/q u4_dout_reg[57]/Q -type DFF DFF
add mapped point u4/dout[58]/q u4_dout_reg[58]/Q -type DFF DFF
add mapped point u4/dout[59]/q u4_dout_reg[59]/Q -type DFF DFF
add mapped point u4/dout[60]/q u4_dout_reg[60]/Q -type DFF DFF
add mapped point u4/dout[61]/q u4_dout_reg[61]/Q -type DFF DFF
add mapped point u4/dout[62]/q u4_dout_reg[62]/Q -type DFF DFF
add mapped point u4/dout[63]/q u4_dout_reg[63]/Q -type DFF DFF
add mapped point u4/dout[64]/q u4_dout_reg[64]/Q -type DFF DFF
add mapped point u4/dout[65]/q u4_dout_reg[65]/Q -type DFF DFF
add mapped point u4/dout[66]/q u4_dout_reg[66]/Q -type DFF DFF
add mapped point u4/dout[67]/q u4_dout_reg[67]/Q -type DFF DFF
add mapped point u4/dout[68]/q u4_dout_reg[68]/Q -type DFF DFF
add mapped point u4/dout[69]/q u4_dout_reg[69]/Q -type DFF DFF
add mapped point u4/dout[70]/q u4_dout_reg[70]/Q -type DFF DFF
add mapped point u4/dout[71]/q u4_dout_reg[71]/Q -type DFF DFF
add mapped point u4/dout[72]/q u4_dout_reg[72]/Q -type DFF DFF
add mapped point u4/dout[73]/q u4_dout_reg[73]/Q -type DFF DFF
add mapped point u4/dout[74]/q u4_dout_reg[74]/Q -type DFF DFF
add mapped point u4/dout[75]/q u4_dout_reg[75]/Q -type DFF DFF
add mapped point u4/dout[76]/q u4_dout_reg[76]/Q -type DFF DFF
add mapped point u4/dout[77]/q u4_dout_reg[77]/Q -type DFF DFF
add mapped point u4/dout[78]/q u4_dout_reg[78]/Q -type DFF DFF
add mapped point u4/dout[79]/q u4_dout_reg[79]/Q -type DFF DFF
add mapped point u4/dout[80]/q u4_dout_reg[80]/Q -type DFF DFF
add mapped point u4/dout[81]/q u4_dout_reg[81]/Q -type DFF DFF
add mapped point u4/dout[82]/q u4_dout_reg[82]/Q -type DFF DFF
add mapped point u4/dout[83]/q u4_dout_reg[83]/Q -type DFF DFF
add mapped point u4/dout[84]/q u4_dout_reg[84]/Q -type DFF DFF
add mapped point u4/dout[85]/q u4_dout_reg[85]/Q -type DFF DFF
add mapped point u4/dout[86]/q u4_dout_reg[86]/Q -type DFF DFF
add mapped point u4/dout[87]/q u4_dout_reg[87]/Q -type DFF DFF
add mapped point u4/dout[88]/q u4_dout_reg[88]/Q -type DFF DFF
add mapped point u4/dout[89]/q u4_dout_reg[89]/Q -type DFF DFF
add mapped point u4/dout[90]/q u4_dout_reg[90]/Q -type DFF DFF
add mapped point u4/dout[91]/q u4_dout_reg[91]/Q -type DFF DFF
add mapped point u4/dout[92]/q u4_dout_reg[92]/Q -type DFF DFF
add mapped point u4/dout[93]/q u4_dout_reg[93]/Q -type DFF DFF
add mapped point u4/dout[94]/q u4_dout_reg[94]/Q -type DFF DFF
add mapped point u4/dout[95]/q u4_dout_reg[95]/Q -type DFF DFF
add mapped point u4/dout[96]/q u4_dout_reg[96]/Q -type DFF DFF
add mapped point u4/dout[97]/q u4_dout_reg[97]/Q -type DFF DFF
add mapped point u4/dout[98]/q u4_dout_reg[98]/Q -type DFF DFF
add mapped point u4/dout[99]/q u4_dout_reg[99]/Q -type DFF DFF
add mapped point u4/dout[100]/q u4_dout_reg[100]/Q -type DFF DFF
add mapped point u4/dout[101]/q u4_dout_reg[101]/Q -type DFF DFF
add mapped point u4/dout[102]/q u4_dout_reg[102]/Q -type DFF DFF
add mapped point u4/dout[103]/q u4_dout_reg[103]/Q -type DFF DFF
add mapped point u4/dout[104]/q u4_dout_reg[104]/Q -type DFF DFF
add mapped point u4/dout[105]/q u4_dout_reg[105]/Q -type DFF DFF
add mapped point u4/dout[106]/q u4_dout_reg[106]/Q -type DFF DFF
add mapped point u4/dout[107]/q u4_dout_reg[107]/Q -type DFF DFF
add mapped point u4/dout[108]/q u4_dout_reg[108]/Q -type DFF DFF
add mapped point u4/dout[109]/q u4_dout_reg[109]/Q -type DFF DFF
add mapped point u4/dout[110]/q u4_dout_reg[110]/Q -type DFF DFF
add mapped point u4/dout[111]/q u4_dout_reg[111]/Q -type DFF DFF
add mapped point u4/dout[112]/q u4_dout_reg[112]/Q -type DFF DFF
add mapped point u4/dout[113]/q u4_dout_reg[113]/Q -type DFF DFF
add mapped point u4/dout[114]/q u4_dout_reg[114]/Q -type DFF DFF
add mapped point u4/dout[115]/q u4_dout_reg[115]/Q -type DFF DFF
add mapped point u4/dout[116]/q u4_dout_reg[116]/Q -type DFF DFF
add mapped point u4/dout[117]/q u4_dout_reg[117]/Q -type DFF DFF
add mapped point u4/dout[118]/q u4_dout_reg[118]/Q -type DFF DFF
add mapped point u4/dout[119]/q u4_dout_reg[119]/Q -type DFF DFF
add mapped point u4/dout[120]/q u4_dout_reg[120]/Q -type DFF DFF
add mapped point u4/dout[121]/q u4_dout_reg[121]/Q -type DFF DFF
add mapped point u4/dout[122]/q u4_dout_reg[122]/Q -type DFF DFF
add mapped point u4/dout[123]/q u4_dout_reg[123]/Q -type DFF DFF
add mapped point u4/dout[124]/q u4_dout_reg[124]/Q -type DFF DFF
add mapped point u4/dout[125]/q u4_dout_reg[125]/Q -type DFF DFF
add mapped point u4/dout[126]/q u4_dout_reg[126]/Q -type DFF DFF
add mapped point u4/dout[127]/q u4_dout_reg[127]/Q -type DFF DFF
add mapped point u4/enc_in_progress/q u4_enc_in_progress_reg/Q -type DFF DFF
add mapped point u4/enc_start/q u4_enc_start_reg/Q -type DFF DFF
add mapped point u4/pt_byte_0[0]/q u4_pt_byte_0_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_0[1]/q u4_pt_byte_0_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_0[2]/q u4_pt_byte_0_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_0[3]/q u4_pt_byte_0_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_0[4]/q u4_pt_byte_0_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_0[5]/q u4_pt_byte_0_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_0[6]/q u4_pt_byte_0_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_0[7]/q u4_pt_byte_0_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_1[0]/q u4_pt_byte_1_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_1[1]/q u4_pt_byte_1_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_1[2]/q u4_pt_byte_1_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_1[3]/q u4_pt_byte_1_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_1[4]/q u4_pt_byte_1_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_1[5]/q u4_pt_byte_1_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_1[6]/q u4_pt_byte_1_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_1[7]/q u4_pt_byte_1_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_2[0]/q u4_pt_byte_2_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_2[1]/q u4_pt_byte_2_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_2[2]/q u4_pt_byte_2_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_2[3]/q u4_pt_byte_2_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_2[4]/q u4_pt_byte_2_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_2[5]/q u4_pt_byte_2_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_2[6]/q u4_pt_byte_2_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_2[7]/q u4_pt_byte_2_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_3[0]/q u4_pt_byte_3_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_3[1]/q u4_pt_byte_3_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_3[2]/q u4_pt_byte_3_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_3[3]/q u4_pt_byte_3_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_3[4]/q u4_pt_byte_3_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_3[5]/q u4_pt_byte_3_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_3[6]/q u4_pt_byte_3_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_3[7]/q u4_pt_byte_3_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_4[0]/q u4_pt_byte_4_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_4[1]/q u4_pt_byte_4_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_4[2]/q u4_pt_byte_4_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_4[3]/q u4_pt_byte_4_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_4[4]/q u4_pt_byte_4_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_4[5]/q u4_pt_byte_4_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_4[6]/q u4_pt_byte_4_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_4[7]/q u4_pt_byte_4_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_5[0]/q u4_pt_byte_5_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_5[1]/q u4_pt_byte_5_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_5[2]/q u4_pt_byte_5_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_5[3]/q u4_pt_byte_5_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_5[4]/q u4_pt_byte_5_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_5[5]/q u4_pt_byte_5_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_5[6]/q u4_pt_byte_5_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_5[7]/q u4_pt_byte_5_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_6[0]/q u4_pt_byte_6_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_6[1]/q u4_pt_byte_6_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_6[2]/q u4_pt_byte_6_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_6[3]/q u4_pt_byte_6_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_6[4]/q u4_pt_byte_6_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_6[5]/q u4_pt_byte_6_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_6[6]/q u4_pt_byte_6_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_6[7]/q u4_pt_byte_6_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_7[0]/q u4_pt_byte_7_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_7[1]/q u4_pt_byte_7_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_7[2]/q u4_pt_byte_7_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_7[3]/q u4_pt_byte_7_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_7[4]/q u4_pt_byte_7_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_7[5]/q u4_pt_byte_7_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_7[6]/q u4_pt_byte_7_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_7[7]/q u4_pt_byte_7_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_8[0]/q u4_pt_byte_8_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_8[1]/q u4_pt_byte_8_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_8[2]/q u4_pt_byte_8_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_8[3]/q u4_pt_byte_8_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_8[4]/q u4_pt_byte_8_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_8[5]/q u4_pt_byte_8_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_8[6]/q u4_pt_byte_8_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_8[7]/q u4_pt_byte_8_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_9[0]/q u4_pt_byte_9_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_9[1]/q u4_pt_byte_9_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_9[2]/q u4_pt_byte_9_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_9[3]/q u4_pt_byte_9_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_9[4]/q u4_pt_byte_9_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_9[5]/q u4_pt_byte_9_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_9[6]/q u4_pt_byte_9_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_9[7]/q u4_pt_byte_9_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_A[0]/q u4_pt_byte_A_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_A[1]/q u4_pt_byte_A_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_A[2]/q u4_pt_byte_A_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_A[3]/q u4_pt_byte_A_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_A[4]/q u4_pt_byte_A_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_A[5]/q u4_pt_byte_A_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_A[6]/q u4_pt_byte_A_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_A[7]/q u4_pt_byte_A_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_B[0]/q u4_pt_byte_B_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_B[1]/q u4_pt_byte_B_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_B[2]/q u4_pt_byte_B_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_B[3]/q u4_pt_byte_B_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_B[4]/q u4_pt_byte_B_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_B[5]/q u4_pt_byte_B_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_B[6]/q u4_pt_byte_B_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_B[7]/q u4_pt_byte_B_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_C[0]/q u4_pt_byte_C_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_C[1]/q u4_pt_byte_C_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_C[2]/q u4_pt_byte_C_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_C[3]/q u4_pt_byte_C_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_C[4]/q u4_pt_byte_C_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_C[5]/q u4_pt_byte_C_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_C[6]/q u4_pt_byte_C_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_C[7]/q u4_pt_byte_C_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_D[0]/q u4_pt_byte_D_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_D[1]/q u4_pt_byte_D_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_D[2]/q u4_pt_byte_D_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_D[3]/q u4_pt_byte_D_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_D[4]/q u4_pt_byte_D_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_D[5]/q u4_pt_byte_D_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_D[6]/q u4_pt_byte_D_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_D[7]/q u4_pt_byte_D_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_E[0]/q u4_pt_byte_E_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_E[1]/q u4_pt_byte_E_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_E[2]/q u4_pt_byte_E_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_E[3]/q u4_pt_byte_E_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_E[4]/q u4_pt_byte_E_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_E[5]/q u4_pt_byte_E_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_E[6]/q u4_pt_byte_E_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_E[7]/q u4_pt_byte_E_reg[7]/Q -type DFF DFF
add mapped point u4/pt_byte_F[0]/q u4_pt_byte_F_reg[0]/Q -type DFF DFF
add mapped point u4/pt_byte_F[1]/q u4_pt_byte_F_reg[1]/Q -type DFF DFF
add mapped point u4/pt_byte_F[2]/q u4_pt_byte_F_reg[2]/Q -type DFF DFF
add mapped point u4/pt_byte_F[3]/q u4_pt_byte_F_reg[3]/Q -type DFF DFF
add mapped point u4/pt_byte_F[4]/q u4_pt_byte_F_reg[4]/Q -type DFF DFF
add mapped point u4/pt_byte_F[5]/q u4_pt_byte_F_reg[5]/Q -type DFF DFF
add mapped point u4/pt_byte_F[6]/q u4_pt_byte_F_reg[6]/Q -type DFF DFF
add mapped point u4/pt_byte_F[7]/q u4_pt_byte_F_reg[7]/Q -type DFF DFF
add mapped point u4/pt_sel_cntr[0]/q u4_pt_sel_cntr_reg[0]/Q -type DFF DFF
add mapped point u4/pt_sel_cntr[1]/q u4_pt_sel_cntr_reg[1]/Q -type DFF DFF
add mapped point u4/pt_sel_cntr[2]/q u4_pt_sel_cntr_reg[2]/Q -type DFF DFF
add mapped point u4/pt_sel_cntr[3]/q u4_pt_sel_cntr_reg[3]/Q -type DFF DFF
add mapped point u4/start_enc_1/q u4_start_enc_1_reg/Q -type DFF DFF
add mapped point u7/ct_byte_0[0]/q u7_ct_byte_0_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_0[1]/q u7_ct_byte_0_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_0[2]/q u7_ct_byte_0_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_0[3]/q u7_ct_byte_0_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_0[4]/q u7_ct_byte_0_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_0[5]/q u7_ct_byte_0_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_0[6]/q u7_ct_byte_0_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_0[7]/q u7_ct_byte_0_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_1[0]/q u7_ct_byte_1_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_1[1]/q u7_ct_byte_1_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_1[2]/q u7_ct_byte_1_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_1[3]/q u7_ct_byte_1_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_1[4]/q u7_ct_byte_1_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_1[5]/q u7_ct_byte_1_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_1[6]/q u7_ct_byte_1_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_1[7]/q u7_ct_byte_1_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_2[0]/q u7_ct_byte_2_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_2[1]/q u7_ct_byte_2_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_2[2]/q u7_ct_byte_2_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_2[3]/q u7_ct_byte_2_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_2[4]/q u7_ct_byte_2_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_2[5]/q u7_ct_byte_2_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_2[6]/q u7_ct_byte_2_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_2[7]/q u7_ct_byte_2_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_3[0]/q u7_ct_byte_3_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_3[1]/q u7_ct_byte_3_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_3[2]/q u7_ct_byte_3_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_3[3]/q u7_ct_byte_3_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_3[4]/q u7_ct_byte_3_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_3[5]/q u7_ct_byte_3_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_3[6]/q u7_ct_byte_3_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_3[7]/q u7_ct_byte_3_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_4[0]/q u7_ct_byte_4_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_4[1]/q u7_ct_byte_4_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_4[2]/q u7_ct_byte_4_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_4[3]/q u7_ct_byte_4_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_4[4]/q u7_ct_byte_4_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_4[5]/q u7_ct_byte_4_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_4[6]/q u7_ct_byte_4_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_4[7]/q u7_ct_byte_4_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_5[0]/q u7_ct_byte_5_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_5[1]/q u7_ct_byte_5_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_5[2]/q u7_ct_byte_5_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_5[3]/q u7_ct_byte_5_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_5[4]/q u7_ct_byte_5_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_5[5]/q u7_ct_byte_5_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_5[6]/q u7_ct_byte_5_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_5[7]/q u7_ct_byte_5_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_6[0]/q u7_ct_byte_6_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_6[1]/q u7_ct_byte_6_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_6[2]/q u7_ct_byte_6_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_6[3]/q u7_ct_byte_6_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_6[4]/q u7_ct_byte_6_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_6[5]/q u7_ct_byte_6_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_6[6]/q u7_ct_byte_6_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_6[7]/q u7_ct_byte_6_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_7[0]/q u7_ct_byte_7_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_7[1]/q u7_ct_byte_7_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_7[2]/q u7_ct_byte_7_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_7[3]/q u7_ct_byte_7_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_7[4]/q u7_ct_byte_7_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_7[5]/q u7_ct_byte_7_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_7[6]/q u7_ct_byte_7_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_7[7]/q u7_ct_byte_7_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_8[0]/q u7_ct_byte_8_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_8[1]/q u7_ct_byte_8_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_8[2]/q u7_ct_byte_8_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_8[3]/q u7_ct_byte_8_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_8[4]/q u7_ct_byte_8_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_8[5]/q u7_ct_byte_8_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_8[6]/q u7_ct_byte_8_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_8[7]/q u7_ct_byte_8_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_9[0]/q u7_ct_byte_9_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_9[1]/q u7_ct_byte_9_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_9[2]/q u7_ct_byte_9_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_9[3]/q u7_ct_byte_9_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_9[4]/q u7_ct_byte_9_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_9[5]/q u7_ct_byte_9_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_9[6]/q u7_ct_byte_9_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_9[7]/q u7_ct_byte_9_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_A[0]/q u7_ct_byte_A_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_A[1]/q u7_ct_byte_A_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_A[2]/q u7_ct_byte_A_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_A[3]/q u7_ct_byte_A_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_A[4]/q u7_ct_byte_A_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_A[5]/q u7_ct_byte_A_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_A[6]/q u7_ct_byte_A_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_A[7]/q u7_ct_byte_A_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_B[0]/q u7_ct_byte_B_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_B[1]/q u7_ct_byte_B_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_B[2]/q u7_ct_byte_B_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_B[3]/q u7_ct_byte_B_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_B[4]/q u7_ct_byte_B_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_B[5]/q u7_ct_byte_B_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_B[6]/q u7_ct_byte_B_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_B[7]/q u7_ct_byte_B_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_C[0]/q u7_ct_byte_C_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_C[1]/q u7_ct_byte_C_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_C[2]/q u7_ct_byte_C_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_C[3]/q u7_ct_byte_C_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_C[4]/q u7_ct_byte_C_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_C[5]/q u7_ct_byte_C_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_C[6]/q u7_ct_byte_C_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_C[7]/q u7_ct_byte_C_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_D[0]/q u7_ct_byte_D_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_D[1]/q u7_ct_byte_D_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_D[2]/q u7_ct_byte_D_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_D[3]/q u7_ct_byte_D_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_D[4]/q u7_ct_byte_D_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_D[5]/q u7_ct_byte_D_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_D[6]/q u7_ct_byte_D_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_D[7]/q u7_ct_byte_D_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_E[0]/q u7_ct_byte_E_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_E[1]/q u7_ct_byte_E_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_E[2]/q u7_ct_byte_E_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_E[3]/q u7_ct_byte_E_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_E[4]/q u7_ct_byte_E_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_E[5]/q u7_ct_byte_E_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_E[6]/q u7_ct_byte_E_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_E[7]/q u7_ct_byte_E_reg[7]/Q -type DFF DFF
add mapped point u7/ct_byte_F[0]/q u7_ct_byte_F_reg[0]/Q -type DFF DFF
add mapped point u7/ct_byte_F[1]/q u7_ct_byte_F_reg[1]/Q -type DFF DFF
add mapped point u7/ct_byte_F[2]/q u7_ct_byte_F_reg[2]/Q -type DFF DFF
add mapped point u7/ct_byte_F[3]/q u7_ct_byte_F_reg[3]/Q -type DFF DFF
add mapped point u7/ct_byte_F[4]/q u7_ct_byte_F_reg[4]/Q -type DFF DFF
add mapped point u7/ct_byte_F[5]/q u7_ct_byte_F_reg[5]/Q -type DFF DFF
add mapped point u7/ct_byte_F[6]/q u7_ct_byte_F_reg[6]/Q -type DFF DFF
add mapped point u7/ct_byte_F[7]/q u7_ct_byte_F_reg[7]/Q -type DFF DFF
add mapped point u7/ct_sel_cntr[0]/q u7_ct_sel_cntr_reg[0]/Q -type DFF DFF
add mapped point u7/ct_sel_cntr[1]/q u7_ct_sel_cntr_reg[1]/Q -type DFF DFF
add mapped point u7/ct_sel_cntr[2]/q u7_ct_sel_cntr_reg[2]/Q -type DFF DFF
add mapped point u7/ct_sel_cntr[3]/q u7_ct_sel_cntr_reg[3]/Q -type DFF DFF
add mapped point u9/cntr[0]/q u9_cntr_reg[0]/Q -type DFF DFF
add mapped point u9/cntr[1]/q u9_cntr_reg[1]/Q -type DFF DFF
add mapped point u9/cntr[2]/q u9_cntr_reg[2]/Q -type DFF DFF
add mapped point u9/cntr[3]/q u9_cntr_reg[3]/Q -type DFF DFF
add mapped point u9/cntr_stop/q u9_cntr_stop_reg/Q -type DFF DFF
add mapped point u9/end_seq/q u9_end_seq_reg/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[0]/q u10_BaudGeneratorAcc_reg[0]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[1]/q u10_BaudGeneratorAcc_reg[1]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[2]/q u10_BaudGeneratorAcc_reg[2]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[3]/q u10_BaudGeneratorAcc_reg[3]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[4]/q u10_BaudGeneratorAcc_reg[4]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[5]/q u10_BaudGeneratorAcc_reg[5]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[6]/q u10_BaudGeneratorAcc_reg[6]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[7]/q u10_BaudGeneratorAcc_reg[7]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[8]/q u10_BaudGeneratorAcc_reg[8]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[9]/q u10_BaudGeneratorAcc_reg[9]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[10]/q u10_BaudGeneratorAcc_reg[10]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[11]/q u10_BaudGeneratorAcc_reg[11]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[12]/q u10_BaudGeneratorAcc_reg[12]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[13]/q u10_BaudGeneratorAcc_reg[13]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[14]/q u10_BaudGeneratorAcc_reg[14]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[15]/q u10_BaudGeneratorAcc_reg[15]/Q -type DFF DFF
add mapped point u10/BaudGeneratorAcc[16]/q u10_BaudGeneratorAcc_reg[16]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[0]/q u10_TxD_dataReg_reg[0]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[1]/q u10_TxD_dataReg_reg[1]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[2]/q u10_TxD_dataReg_reg[2]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[3]/q u10_TxD_dataReg_reg[3]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[4]/q u10_TxD_dataReg_reg[4]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[5]/q u10_TxD_dataReg_reg[5]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[6]/q u10_TxD_dataReg_reg[6]/Q -type DFF DFF
add mapped point u10/TxD_dataReg[7]/q u10_TxD_dataReg_reg[7]/Q -type DFF DFF
add mapped point u10/state[0]/q u10_state_reg[0]/Q -type DFF DFF
add mapped point u10/state[1]/q u10_state_reg[1]/Q -type DFF DFF
add mapped point u10/state[2]/q u10_state_reg[2]/Q -type DFF DFF
add mapped point u10/state[3]/q u10_state_reg[3]/Q -type DFF DFF
add mapped point u13/cntr_1[0]/q u13_cntr_1_reg[0]/Q -type DFF DFF
add mapped point u13/cntr_1[1]/q u13_cntr_1_reg[1]/Q -type DFF DFF
add mapped point u13/cntr_1[2]/q u13_cntr_1_reg[2]/Q -type DFF DFF
add mapped point u13/cntr_1[3]/q u13_cntr_1_reg[3]/Q -type DFF DFF
add mapped point u13/cntr_1[4]/q u13_cntr_1_reg[4]/Q -type DFF DFF
add mapped point u13/cntr_1[5]/q u13_cntr_1_reg[5]/Q -type DFF DFF
add mapped point u13/cntr_1[6]/q u13_cntr_1_reg[6]/Q -type DFF DFF
add mapped point u13/cntr_1[7]/q u13_cntr_1_reg[7]/Q -type DFF DFF
add mapped point u13/cntr_1[8]/q u13_cntr_1_reg[8]/Q -type DFF DFF
add mapped point u13/cntr_1[9]/q u13_cntr_1_reg[9]/Q -type DFF DFF
add mapped point u13/cntr_1[10]/q u13_cntr_1_reg[10]/Q -type DFF DFF
add mapped point u13/cntr_1[11]/q u13_cntr_1_reg[11]/Q -type DFF DFF



//Black Boxes
add mapped point u2/ps2inface u2/ps2inface -type BBOX BBOX
add mapped point u3/inst u3/inst -type BBOX BBOX
add mapped point u6 u6 -type BBOX BBOX
add mapped point u8/inst u8/inst -type BBOX BBOX
add mapped point u11/u2/inst u11/u2/inst -type BBOX BBOX
add mapped point u11/u3/inst u11/u3/inst -type BBOX BBOX
add mapped point u11/u4/inst u11/u4/inst -type BBOX BBOX
add mapped point u11/u5 u11/u5 -type BBOX BBOX
add mapped point u_clk/inst/clkf_buf u_clk_inst/clkf_buf -type BBOX BBOX
add mapped point u_clk/inst/clkin1_ibufg u_clk_inst/clkin1_ibufg -type BBOX BBOX
add mapped point u_clk/inst/clkout1_buf u_clk_inst/clkout1_buf -type BBOX BBOX
add mapped point u_clk/inst/clkout2_buf u_clk_inst/clkout2_buf -type BBOX BBOX
add mapped point u_clk/inst/clkout3_buf u_clk_inst/clkout3_buf -type BBOX BBOX
add mapped point u_clk/inst/mmcm_adv_inst u_clk_inst/mmcm_adv_inst -type BBOX BBOX



//Empty Modules as Blackboxes
