/*
###############################################################
#  Generated by:      Cadence Tempus 20.20-p001_1
#  OS:                Linux x86_64(Host ID APL5.kletech.ac.in)
#  Generated on:      Wed Mar 12 15:50:59 2025
#  Design:            s298
###############################################################
*/
module s298 (
	GND, 
	VDD, 
	CK, 
	G0, 
	G1, 
	G117, 
	G118, 
	G132, 
	G133, 
	G2, 
	G66, 
	G67, 
	ts_si, 
	ts_so, 
	scan_en);
   input GND;
   input VDD;
   input CK;
   input G0;
   input G1;
   output G117;
   output G118;
   output G132;
   output G133;
   input G2;
   output G66;
   output G67;
   input [0:0] ts_si;
   output [0:0] ts_so;
   input scan_en;

   // Internal wires
   wire G10;
   wire G11;
   wire G12;
   wire G13;
   wire G14;
   wire G15;
   wire G22;
   wire G23;
   wire G29;
   wire G30;
   wire G34;
   wire G39;
   wire G44;
   wire G56;
   wire G86;
   wire G92;
   wire G98;
   wire G102;
   wire G107;
   wire G113;
   wire G119;
   wire G125;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;

   dff DFF_0 (.clk(CK),
	.q(G10),
	.d(G29),
	.ts_sea0(scan_en),
	.ts_extsi14(ts_si[0]));
   dff_26 DFF_1 (.clk(CK),
	.q(G11),
	.d(G30),
	.ts_sea0(scan_en),
	.ts_intno0(G10));
   dff_25 DFF_2 (.clk(CK),
	.q(G12),
	.d(G34),
	.ts_sea0(scan_en),
	.ts_intno13(G23));
   dff_24 DFF_3 (.clk(CK),
	.q(G13),
	.d(G39),
	.ts_sea0(scan_en),
	.ts_intno2(G12));
   dff_23 DFF_4 (.clk(CK),
	.q(G14),
	.d(G44),
	.ts_sea0(scan_en),
	.ts_intno3(G13));
   dff_22 DFF_5 (.clk(CK),
	.q(G15),
	.d(G56),
	.ts_sea0(scan_en),
	.ts_intno4(G14));
   dff_21 DFF_6 (.clk(CK),
	.q(G66),
	.d(G86),
	.ts_sea0(scan_en),
	.ts_intno5(G15));
   dff_20 DFF_7 (.clk(CK),
	.q(G67),
	.d(G92),
	.ts_sea0(scan_en),
	.ts_intno6(G66));
   dff_19 DFF_8 (.clk(CK),
	.q(G117),
	.d(G98),
	.ts_sea0(scan_en),
	.ts_intno7(G67));
   dff_18 DFF_9 (.clk(CK),
	.q(G118),
	.d(G102),
	.ts_sea0(scan_en),
	.ts_intno8(G117),
	.ts_no9(ts_so[0]));
   dff_17 DFF_10 (.clk(CK),
	.q(G132),
	.d(G107),
	.ts_sea0(scan_en),
	.ts_intno1(G11));
   dff_16 DFF_11 (.clk(CK),
	.q(G133),
	.d(G113),
	.ts_sea0(scan_en),
	.ts_intno10(G132));
   dff_15 DFF_12 (.clk(CK),
	.q(G22),
	.d(G119),
	.ts_sea0(scan_en),
	.ts_intno11(G133));
   dff_14 DFF_13 (.clk(CK),
	.q(G23),
	.d(G125),
	.ts_sea0(scan_en),
	.ts_intno12(G22));
   OAI211_X2 g1218__2398 (.A(n_77),
	.B(n_84),
	.C1(n_62),
	.C2(G10),
	.ZN(G102));
   OAI211_X2 g1219__5107 (.A(n_80),
	.B(n_69),
	.C1(n_83),
	.C2(G10),
	.ZN(G107));
   NOR2_X2 g1220__6260 (.A1(n_83),
	.A2(G0),
	.ZN(G56));
   NOR2_X2 g1221__4319 (.A1(n_82),
	.A2(G0),
	.ZN(G44));
   OAI211_X2 g1222__8428 (.A(n_79),
	.B(n_74),
	.C1(n_60),
	.C2(G11),
	.ZN(G92));
   NOR2_X2 g1223__5526 (.A1(n_75),
	.A2(G0),
	.ZN(G39));
   AOI21_X1 g1224__6783 (.A(n_70),
	.B1(n_68),
	.B2(G118),
	.ZN(n_84));
   NAND2_X2 g1225__3680 (.A1(n_77),
	.A2(n_78),
	.ZN(G86));
   NAND3_X2 g1226__1617 (.A1(n_81),
	.A2(n_74),
	.A3(n_60),
	.ZN(G98));
   XOR2_X1 g1227__2802 (.A(n_72),
	.B(G14),
	.Z(n_82));
   OAI21_X2 g1228__1705 (.A(n_76),
	.B1(n_60),
	.B2(n_49),
	.ZN(G113));
   AOI21_X2 g1229__5122 (.A(n_73),
	.B1(n_71),
	.B2(G15),
	.ZN(n_83));
   NAND2_X1 g1230__8246 (.A1(n_68),
	.A2(G117),
	.ZN(n_81));
   NAND2_X1 g1231__7098 (.A1(n_68),
	.A2(G132),
	.ZN(n_80));
   NAND2_X1 g1232__6131 (.A1(n_68),
	.A2(G67),
	.ZN(n_79));
   NAND2_X1 g1233__1881 (.A1(n_68),
	.A2(G66),
	.ZN(n_78));
   NOR2_X2 g1234__5115 (.A1(n_65),
	.A2(G0),
	.ZN(G30));
   NAND2_X1 g1235__7482 (.A1(n_68),
	.A2(G133),
	.ZN(n_76));
   AOI211_X2 g1236__4733 (.A(n_57),
	.B(n_64),
	.C1(n_61),
	.C2(G13),
	.ZN(n_75));
   NOR2_X2 g1237__6161 (.A1(n_66),
	.A2(G0),
	.ZN(G34));
   AND2_X2 g1238__9315 (.A1(n_71),
	.A2(n_67),
	.ZN(n_77));
   NOR2_X2 g1239__9945 (.A1(n_58),
	.A2(G0),
	.ZN(G125));
   NOR2_X2 g1240__2883 (.A1(n_59),
	.A2(G0),
	.ZN(G119));
   NOR3_X2 g1241__2346 (.A1(n_55),
	.A2(n_53),
	.A3(G14),
	.ZN(n_73));
   AOI21_X2 g1242__1666 (.A(G23),
	.B1(n_54),
	.B2(n_52),
	.ZN(n_72));
   NAND2_X2 g1243__7410 (.A1(n_63),
	.A2(G11),
	.ZN(n_74));
   INV_X4 g1244 (.A(n_69),
	.ZN(n_70));
   OAI211_X2 g1245__6417 (.A(n_56),
	.B(n_47),
	.C1(n_55),
	.C2(G12),
	.ZN(n_67));
   XOR2_X2 g1246__5477 (.A(n_50),
	.B(G12),
	.Z(n_66));
   AOI22_X2 g1247__2398 (.A1(n_54),
	.A2(n_53),
	.B1(G11),
	.B2(n_45),
	.ZN(n_65));
   NAND2_X2 g1248__5107 (.A1(n_64),
	.A2(n_48),
	.ZN(n_71));
   NAND3_X2 g1249__6260 (.A1(n_63),
	.A2(n_43),
	.A3(G14),
	.ZN(n_69));
   NOR3_X2 g1250__4319 (.A1(n_51),
	.A2(n_46),
	.A3(G15),
	.ZN(n_68));
   NOR2_X2 g1251__8428 (.A1(n_56),
	.A2(G15),
	.ZN(n_62));
   OAI21_X2 g1252__5526 (.A(G10),
	.B1(G11),
	.B2(n_44),
	.ZN(n_61));
   NOR2_X2 g1253__6783 (.A1(n_53),
	.A2(n_43),
	.ZN(n_64));
   AND2_X2 g1254__3680 (.A1(n_51),
	.A2(n_47),
	.ZN(n_63));
   XNOR2_X1 g1255__1617 (.A(G22),
	.B(G2),
	.ZN(n_59));
   XNOR2_X1 g1256__2802 (.A(G23),
	.B(G1),
	.ZN(n_58));
   NOR3_X2 g1257__1705 (.A1(n_50),
	.A2(n_44),
	.A3(G13),
	.ZN(n_57));
   OR3_X2 g1258__5122 (.A1(G14),
	.A2(G15),
	.A3(G13),
	.ZN(n_60));
   INV_X2 g1259 (.A(n_53),
	.ZN(n_52));
   AND2_X4 g1260__8246 (.A1(n_46),
	.A2(G13),
	.ZN(n_56));
   NAND2_X2 g1261__7098 (.A1(n_43),
	.A2(G22),
	.ZN(n_55));
   NOR2_X2 g1262__6131 (.A1(G11),
	.A2(n_45),
	.ZN(n_54));
   NAND2_X2 g1263__1881 (.A1(n_44),
	.A2(G13),
	.ZN(n_53));
   NAND2_X2 g1264__5115 (.A1(G11),
	.A2(G12),
	.ZN(n_49));
   NOR2_X2 g1265__7482 (.A1(G10),
	.A2(G0),
	.ZN(G29));
   NOR2_X2 g1266__4733 (.A1(G14),
	.A2(G22),
	.ZN(n_48));
   NOR2_X2 g1267__6161 (.A1(G12),
	.A2(G13),
	.ZN(n_51));
   NAND2_X2 g1268__9315 (.A1(G11),
	.A2(G10),
	.ZN(n_50));
   INV_X1 g1269 (.A(G15),
	.ZN(n_47));
   INV_X2 g1270 (.A(G14),
	.ZN(n_46));
   INV_X2 g1271 (.A(G10),
	.ZN(n_45));
   INV_X4 g1272 (.A(G12),
	.ZN(n_44));
   INV_X2 g1273 (.A(G11),
	.ZN(n_43));
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 12 2025 15:21:44 IST (Mar 12 2025 09:51:44 UTC)
// Verification Directory fv/s298 
module dff (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_extsi14);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_extsi14;

   // Internal wires
   wire UNCONNECTED;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_extsi14),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED));
endmodule

module dff_26 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno0);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno0;

   // Internal wires
   wire UNCONNECTED0;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno0),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED0));
endmodule

module dff_25 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno13);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno13;

   // Internal wires
   wire UNCONNECTED1;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno13),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED1));
endmodule

module dff_24 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno2);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno2;

   // Internal wires
   wire UNCONNECTED2;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno2),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED2));
endmodule

module dff_23 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno3);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno3;

   // Internal wires
   wire UNCONNECTED3;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno3),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED3));
endmodule

module dff_22 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno4);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno4;

   // Internal wires
   wire UNCONNECTED4;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno4),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED4));
endmodule

module dff_21 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno5);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno5;

   // Internal wires
   wire UNCONNECTED5;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno5),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED5));
endmodule

module dff_20 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno6);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno6;

   // Internal wires
   wire UNCONNECTED6;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno6),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED6));
endmodule

module dff_19 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno7);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno7;

   // Internal wires
   wire UNCONNECTED7;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno7),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED7));
endmodule

module active_high_latch (
	CLK, 
	D, 
	Q);
   input CLK;
   input D;
   output Q;

   DLH_X1 Q_reg (.D(D),
	.G(CLK),
	.Q(Q));
endmodule

module dff_18 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno8, 
	ts_no9);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno8;
   output ts_no9;

   // Internal wires
   wire UNCONNECTED8;

   active_high_latch ts_lockup_latchp_clkc1_intno9_i (.CLK(clk),
	.D(q),
	.Q(ts_no9));
   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno8),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED8));
endmodule

module dff_17 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno1);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno1;

   // Internal wires
   wire UNCONNECTED9;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno1),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED9));
endmodule

module dff_16 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno10);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno10;

   // Internal wires
   wire UNCONNECTED10;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno10),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED10));
endmodule

module dff_15 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno11);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno11;

   // Internal wires
   wire UNCONNECTED11;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno11),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED11));
endmodule

module dff_14 (
	clk, 
	q, 
	d, 
	ts_sea0, 
	ts_intno12);
   input clk;
   output q;
   input d;
   input ts_sea0;
   input ts_intno12;

   // Internal wires
   wire UNCONNECTED12;

   SDFF_X2 q_reg (.D(d),
	.SE(ts_sea0),
	.SI(ts_intno12),
	.CK(clk),
	.Q(q),
	.QN(UNCONNECTED12));
endmodule

