
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  1 2025 15:44:46 IST (May  1 2025 10:14:46 UTC)

// Verification Directory fv/rf_2p_512d_76w_2m_4b 

module rf_2p_512d_76w_2m_4b(CLKA, CENA, AA, CLKB, CENB, AB, DB, QA);
  input CLKA, CENA, CLKB, CENB;
  input [8:0] AA, AB;
  input [75:0] DB;
  output [75:0] QA;
  wire CLKA, CENA, CLKB, CENB;
  wire [8:0] AA, AB;
  wire [75:0] DB;
  wire [75:0] QA;
  wire u_sram16_0_n_75, u_sram16_0_n_76, u_sram16_0_n_77,
       u_sram16_0_n_78, u_sram16_0_n_79, u_sram16_0_n_80,
       u_sram16_0_n_81, u_sram16_0_n_82;
  wire u_sram16_0_n_83, u_sram16_0_n_84, u_sram16_0_n_85,
       u_sram16_0_n_86, u_sram16_0_n_87, u_sram16_0_n_88,
       u_sram16_0_n_89, u_sram16_0_n_90;
  wire u_sram16_1_n_71, u_sram16_1_n_72, u_sram16_1_n_73,
       u_sram16_1_n_74, u_sram16_1_n_75, u_sram16_1_n_76,
       u_sram16_1_n_77, u_sram16_1_n_78;
  wire u_sram16_1_n_79, u_sram16_1_n_80, u_sram16_1_n_81,
       u_sram16_1_n_82, u_sram16_1_n_83, u_sram16_1_n_84,
       u_sram16_1_n_85, u_sram16_1_n_86;
  wire u_sram16_1_n_87, u_sram16_1_n_88, u_sram16_1_n_89,
       u_sram16_1_n_90, u_sram24_0_n_99, u_sram24_0_n_100,
       u_sram24_0_n_101, u_sram24_0_n_102;
  wire u_sram24_0_n_103, u_sram24_0_n_104, u_sram24_0_n_105,
       u_sram24_0_n_106, u_sram24_0_n_107, u_sram24_0_n_108,
       u_sram24_0_n_109, u_sram24_0_n_110;
  wire u_sram24_0_n_111, u_sram24_0_n_112, u_sram24_0_n_113,
       u_sram24_0_n_114, u_sram24_0_n_115, u_sram24_0_n_116,
       u_sram24_0_n_117, u_sram24_0_n_118;
  wire u_sram24_0_n_119, u_sram24_0_n_120, u_sram24_0_n_121,
       u_sram24_0_n_122, u_sram24_1_n_99, u_sram24_1_n_100,
       u_sram24_1_n_101, u_sram24_1_n_102;
  wire u_sram24_1_n_103, u_sram24_1_n_104, u_sram24_1_n_105,
       u_sram24_1_n_106, u_sram24_1_n_107, u_sram24_1_n_108,
       u_sram24_1_n_109, u_sram24_1_n_110;
  wire u_sram24_1_n_111, u_sram24_1_n_112, u_sram24_1_n_113,
       u_sram24_1_n_114, u_sram24_1_n_115, u_sram24_1_n_116,
       u_sram24_1_n_117, u_sram24_1_n_118;
  wire u_sram24_1_n_119, u_sram24_1_n_120, u_sram24_1_n_121,
       u_sram24_1_n_122;
  rd3_512x16 u_sram16_0_u_dpram_512x16(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 (AA), .A2 (AB), .I1 (16'b0), .I2 (DB[63:48]),
       .O1 (QA[63:48]), .O2 ({u_sram16_0_n_90, u_sram16_0_n_89,
       u_sram16_0_n_88, u_sram16_0_n_87, u_sram16_0_n_86,
       u_sram16_0_n_85, u_sram16_0_n_84, u_sram16_0_n_83,
       u_sram16_0_n_82, u_sram16_0_n_81, u_sram16_0_n_80,
       u_sram16_0_n_79, u_sram16_0_n_78, u_sram16_0_n_77,
       u_sram16_0_n_76, u_sram16_0_n_75}));
  rd3_512x16 u_sram16_1_u_dpram_512x16(.CE1 (CLKA), .CE2 (CLKB), .CSB1
       (CENA), .CSB2 (CENB), .OEB1 (1'b0), .OEB2 (1'b1), .WEB1 (1'b1),
       .WEB2 (1'b0), .A1 (AA), .A2 (AB), .I1 (16'b0), .I2 ({4'b0,
       DB[75:64]}), .O1 ({u_sram16_1_n_74, u_sram16_1_n_73,
       u_sram16_1_n_72, u_sram16_1_n_71, QA[75:64]}), .O2
       ({u_sram16_1_n_90, u_sram16_1_n_89, u_sram16_1_n_88,
       u_sram16_1_n_87, u_sram16_1_n_86, u_sram16_1_n_85,
       u_sram16_1_n_84, u_sram16_1_n_83, u_sram16_1_n_82,
       u_sram16_1_n_81, u_sram16_1_n_80, u_sram16_1_n_79,
       u_sram16_1_n_78, u_sram16_1_n_77, u_sram16_1_n_76,
       u_sram16_1_n_75}));
  DPRAM_512x24 u_sram24_0_u_dpram_512x24(.CE1 (CLKA), .CE2 (CLKB),
       .OEB1 (1'b0), .CSB1 (CENA), .WEB1 (1'b1), .A1 (AA), .I1 (24'b0),
       .OEB2 (1'b1), .CSB2 (CENB), .WEB2 (1'b0), .A2 (AB), .I2
       (DB[23:0]), .O1 (QA[23:0]), .O2 ({u_sram24_0_n_122,
       u_sram24_0_n_121, u_sram24_0_n_120, u_sram24_0_n_119,
       u_sram24_0_n_118, u_sram24_0_n_117, u_sram24_0_n_116,
       u_sram24_0_n_115, u_sram24_0_n_114, u_sram24_0_n_113,
       u_sram24_0_n_112, u_sram24_0_n_111, u_sram24_0_n_110,
       u_sram24_0_n_109, u_sram24_0_n_108, u_sram24_0_n_107,
       u_sram24_0_n_106, u_sram24_0_n_105, u_sram24_0_n_104,
       u_sram24_0_n_103, u_sram24_0_n_102, u_sram24_0_n_101,
       u_sram24_0_n_100, u_sram24_0_n_99}));
  DPRAM_512x24 u_sram24_1_u_dpram_512x24(.CE1 (CLKA), .CE2 (CLKB),
       .OEB1 (1'b0), .CSB1 (CENA), .WEB1 (1'b1), .A1 (AA), .I1 (24'b0),
       .OEB2 (1'b1), .CSB2 (CENB), .WEB2 (1'b0), .A2 (AB), .I2
       (DB[47:24]), .O1 (QA[47:24]), .O2 ({u_sram24_1_n_122,
       u_sram24_1_n_121, u_sram24_1_n_120, u_sram24_1_n_119,
       u_sram24_1_n_118, u_sram24_1_n_117, u_sram24_1_n_116,
       u_sram24_1_n_115, u_sram24_1_n_114, u_sram24_1_n_113,
       u_sram24_1_n_112, u_sram24_1_n_111, u_sram24_1_n_110,
       u_sram24_1_n_109, u_sram24_1_n_108, u_sram24_1_n_107,
       u_sram24_1_n_106, u_sram24_1_n_105, u_sram24_1_n_104,
       u_sram24_1_n_103, u_sram24_1_n_102, u_sram24_1_n_101,
       u_sram24_1_n_100, u_sram24_1_n_99}));
endmodule

