
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 16:53:39 IST (Jun 13 2025 11:23:39 UTC)

// Verification Directory fv/spi2ram 

module spi2ram(spi_sck, spi_cs, spi_mosi, scan_in, scan_enable,
     spi_miso, scan_out, sAddress, sCSn, sOEn, sWRn, sDqDir, sDqOut,
     sDqIn);
  input spi_sck, spi_cs, spi_mosi, scan_in, scan_enable;
  input [7:0] sDqIn;
  output spi_miso, scan_out, sCSn, sOEn, sWRn, sDqDir;
  output [15:0] sAddress;
  output [7:0] sDqOut;
  wire spi_sck, spi_cs, spi_mosi, scan_in, scan_enable;
  wire [7:0] sDqIn;
  wire spi_miso, scan_out, sCSn, sOEn, sWRn, sDqDir;
  wire [15:0] sAddress;
  wire [7:0] sDqOut;
  wire [7:0] rINBUF;
  wire [7:0] rOUTBUF;
  wire [7:0] rState;
  wire [15:0] rAddress;
  wire [5:0] rCnt;
  wire [7:0] rCmd;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, rCmdGotFlag, rReadFlag1, rReadFlag2,
       rWriteFlag1;
  assign scan_out = 1'b0;
  DFFR_X2 \rAddress_reg[15] (.RN (n_229), .CK (n_228), .D (n_226), .Q
       (sAddress[15]), .QN (UNCONNECTED));
  DFFR_X2 \rAddress_reg[14] (.RN (n_229), .CK (n_228), .D (n_227), .Q
       (sAddress[14]), .QN (n_8));
  INV_X1 g6909(.A (n_225), .ZN (n_227));
  OAI221_X1 g6906__2398(.A (n_224), .B1 (n_221), .B2 (n_206), .C1
       (n_103), .C2 (rINBUF[7]), .ZN (n_226));
  AOI221_X1 g6910__5107(.A (n_207), .B1 (n_223), .B2 (sAddress[14]),
       .C1 (n_219), .C2 (sDqOut[6]), .ZN (n_225));
  DFFR_X2 \rAddress_reg[13] (.RN (n_229), .CK (n_228), .D (n_222), .Q
       (sAddress[13]), .QN (n_3));
  NAND2_X1 g6911__6260(.A1 (n_223), .A2 (sAddress[15]), .ZN (n_224));
  DFFR_X2 \rAddress_reg[12] (.RN (n_229), .CK (n_228), .D (n_218), .Q
       (sAddress[12]), .QN (n_197));
  DFFR_X2 \rAddress_reg[11] (.RN (n_229), .CK (n_228), .D (n_217), .Q
       (sAddress[11]), .QN (n_2));
  INV_X1 g6912(.A (n_220), .ZN (n_222));
  MUX2_X2 g6914__4319(.A (n_209), .B (sAddress[14]), .S (sAddress[15]),
       .Z (n_221));
  AOI222_X1 g6913__8428(.A1 (n_219), .A2 (sDqOut[5]), .B1 (n_205), .B2
       (n_215), .C1 (n_210), .C2 (sAddress[13]), .ZN (n_220));
  INV_X1 g6921(.A (n_216), .ZN (n_218));
  INV_X1 g6924(.A (n_214), .ZN (n_217));
  INV_X1 g6916(.A (n_211), .ZN (n_223));
  AOI222_X1 g6922__5526(.A1 (n_213), .A2 (sAddress[12]), .B1 (n_200),
       .B2 (n_215), .C1 (n_219), .C2 (sDqOut[4]), .ZN (n_216));
  DFFR_X2 \rAddress_reg[10] (.RN (n_229), .CK (n_228), .D (n_204), .Q
       (sAddress[10]), .QN (UNCONNECTED0));
  AOI222_X1 g6925__6783(.A1 (n_213), .A2 (sAddress[11]), .B1 (n_196),
       .B2 (n_215), .C1 (n_219), .C2 (sDqOut[3]), .ZN (n_214));
  AOI21_X1 g6917__3680(.A (n_210), .B1 (n_208), .B2 (n_215), .ZN
       (n_211));
  OR2_X4 g6919__1617(.A1 (n_208), .A2 (n_8), .ZN (n_209));
  NOR3_X1 g6915__2802(.A1 (n_208), .A2 (n_206), .A3 (sAddress[14]), .ZN
       (n_207));
  XNOR2_X1 g6926__1705(.A (sAddress[13]), .B (n_203), .ZN (n_205));
  INV_X1 g6928(.A (n_202), .ZN (n_204));
  DFF_X2 \rOUTBUF_reg[5] (.CK (n_228), .D (n_195), .Q (rOUTBUF[5]), .QN
       (UNCONNECTED1));
  OR2_X4 g6927__5122(.A1 (n_203), .A2 (n_3), .ZN (n_208));
  AOI222_X1 g6929__8246(.A1 (n_192), .A2 (n_215), .B1 (n_219), .B2
       (sDqOut[2]), .C1 (n_210), .C2 (sAddress[10]), .ZN (n_202));
  OAI21_X1 g6931__7098(.A (n_199), .B1 (n_197), .B2 (sAddress[11]), .ZN
       (n_200));
  DFFR_X2 \rAddress_reg[9] (.RN (n_229), .CK (n_228), .D (n_193), .Q
       (sAddress[9]), .QN (UNCONNECTED2));
  DFF_X2 \rOUTBUF_reg[0] (.CK (n_228), .D (n_194), .Q (rOUTBUF[0]), .QN
       (UNCONNECTED3));
  OAI21_X1 g6932__6131(.A (n_83), .B1 (n_198), .B2 (n_206), .ZN
       (n_213));
  NAND3_X1 g6935__1881(.A1 (n_198), .A2 (n_197), .A3 (sAddress[11]),
       .ZN (n_199));
  AND2_X4 g6934__5115(.A1 (n_198), .A2 (n_2), .ZN (n_196));
  DFF_X2 \rOUTBUF_reg[1] (.CK (n_228), .D (n_184), .Q (rOUTBUF[1]), .QN
       (UNCONNECTED4));
  DFF_X2 \rOUTBUF_reg[6] (.CK (n_228), .D (n_191), .Q (rOUTBUF[6]), .QN
       (UNCONNECTED5));
  DFF_X2 \rOUTBUF_reg[3] (.CK (n_228), .D (n_190), .Q (rOUTBUF[3]), .QN
       (UNCONNECTED6));
  NAND4_X1 g6952__7482(.A1 (n_181), .A2 (n_183), .A3 (n_158), .A4
       (n_45), .ZN (n_195));
  DFF_X2 \rOUTBUF_reg[7] (.CK (n_228), .D (n_185), .Q (spi_miso), .QN
       (UNCONNECTED7));
  DFF_X2 \rOUTBUF_reg[4] (.CK (n_228), .D (n_188), .Q (rOUTBUF[4]), .QN
       (UNCONNECTED8));
  DFF_X2 \rOUTBUF_reg[2] (.CK (n_228), .D (n_189), .Q (rOUTBUF[2]), .QN
       (UNCONNECTED9));
  NAND3_X1 g6930__4733(.A1 (n_198), .A2 (sAddress[11]), .A3
       (sAddress[12]), .ZN (n_203));
  NAND2_X1 g6962__6161(.A1 (n_182), .A2 (n_187), .ZN (n_194));
  INV_X1 g6937(.A (n_186), .ZN (n_193));
  HA_X1 g6936__9315(.A (n_166), .B (sAddress[10]), .CO (n_198), .S
       (n_192));
  NAND2_X1 g6965__9945(.A1 (n_172), .A2 (n_162), .ZN (n_191));
  NAND2_X1 g6966__2883(.A1 (n_173), .A2 (n_161), .ZN (n_190));
  NAND2_X1 g6967__2346(.A1 (n_176), .A2 (n_160), .ZN (n_189));
  NAND3_X1 g6958__1666(.A1 (n_175), .A2 (n_168), .A3 (n_187), .ZN
       (n_188));
  AOI222_X1 g6938__7410(.A1 (n_167), .A2 (n_215), .B1 (n_219), .B2
       (sDqOut[1]), .C1 (n_210), .C2 (sAddress[9]), .ZN (n_186));
  NAND2_X1 g6968__6417(.A1 (n_171), .A2 (n_159), .ZN (n_185));
  NAND3_X1 g6959__5477(.A1 (n_177), .A2 (n_169), .A3 (n_183), .ZN
       (n_184));
  DFFR_X2 \rAddress_reg[8] (.RN (n_229), .CK (n_228), .D (n_170), .Q
       (sAddress[8]), .QN (UNCONNECTED10));
  AOI222_X1 g6972__2398(.A1 (n_180), .A2 (rState[0]), .B1 (n_179), .B2
       (sDqIn[0]), .C1 (n_178), .C2 (rOUTBUF[0]), .ZN (n_182));
  AOI222_X1 g6975__5107(.A1 (n_180), .A2 (rState[5]), .B1 (n_179), .B2
       (sDqIn[5]), .C1 (n_178), .C2 (rOUTBUF[5]), .ZN (n_181));
  AOI22_X1 g6971__6260(.A1 (n_180), .A2 (rState[1]), .B1 (n_174), .B2
       (rOUTBUF[0]), .ZN (n_177));
  AOI22_X1 g6974__4319(.A1 (n_180), .A2 (rState[2]), .B1 (n_179), .B2
       (sDqIn[2]), .ZN (n_176));
  AOI22_X1 g6976__8428(.A1 (n_180), .A2 (rState[4]), .B1 (n_174), .B2
       (rOUTBUF[3]), .ZN (n_175));
  AOI22_X1 g6977__5526(.A1 (n_180), .A2 (rState[3]), .B1 (n_179), .B2
       (sDqIn[3]), .ZN (n_173));
  AOI22_X1 g6978__6783(.A1 (n_180), .A2 (rState[6]), .B1 (n_179), .B2
       (sDqIn[6]), .ZN (n_172));
  AOI22_X1 g6979__3680(.A1 (n_180), .A2 (rState[7]), .B1 (n_179), .B2
       (sDqIn[7]), .ZN (n_171));
  INV_X1 g6941(.A (n_165), .ZN (n_170));
  AOI22_X1 g6980__1617(.A1 (n_179), .A2 (sDqIn[1]), .B1 (n_178), .B2
       (rOUTBUF[1]), .ZN (n_169));
  AOI22_X1 g6981__2802(.A1 (n_179), .A2 (sDqIn[4]), .B1 (n_178), .B2
       (rOUTBUF[4]), .ZN (n_168));
  HA_X1 g6940__1705(.A (n_156), .B (sAddress[9]), .CO (n_166), .S
       (n_167));
  AOI222_X1 g6942__5122(.A1 (n_157), .A2 (n_215), .B1 (n_219), .B2
       (sDqOut[0]), .C1 (n_210), .C2 (sAddress[8]), .ZN (n_165));
  NAND2_X1 g6985__8246(.A1 (n_164), .A2 (n_52), .ZN (n_187));
  NAND2_X1 g6986__7098(.A1 (n_164), .A2 (n_35), .ZN (n_183));
  OAI22_X2 g6987__6131(.A1 (n_178), .A2 (n_133), .B1 (n_163), .B2
       (n_62), .ZN (n_180));
  DFFR_X2 \rAddress_reg[7] (.RN (n_229), .CK (n_228), .D (n_155), .Q
       (rAddress[7]), .QN (UNCONNECTED11));
  NOR2_X1 g6991__1881(.A1 (n_163), .A2 (n_61), .ZN (n_164));
  NOR2_X2 g6992__5115(.A1 (n_163), .A2 (n_74), .ZN (n_179));
  AOI22_X1 g6993__7482(.A1 (n_178), .A2 (rOUTBUF[6]), .B1 (n_174), .B2
       (rOUTBUF[5]), .ZN (n_162));
  AOI22_X1 g6994__4733(.A1 (n_178), .A2 (rOUTBUF[3]), .B1 (n_174), .B2
       (rOUTBUF[2]), .ZN (n_161));
  DFF_X2 \rState_reg[1] (.CK (n_228), .D (n_151), .Q (rState[1]), .QN
       (UNCONNECTED12));
  AOI22_X1 g6995__6161(.A1 (n_178), .A2 (rOUTBUF[2]), .B1 (n_174), .B2
       (rOUTBUF[1]), .ZN (n_160));
  AOI22_X1 g6996__9315(.A1 (n_178), .A2 (spi_miso), .B1 (n_174), .B2
       (rOUTBUF[6]), .ZN (n_159));
  NAND3_X1 g6999__9945(.A1 (n_152), .A2 (n_134), .A3 (n_65), .ZN
       (n_158));
  HA_X1 g6944__2883(.A (n_148), .B (sAddress[8]), .CO (n_156), .S
       (n_157));
  INV_X1 g6945(.A (n_154), .ZN (n_155));
  OR2_X4 g6998__2346(.A1 (n_178), .A2 (n_73), .ZN (n_163));
  AOI222_X1 g6946__1666(.A1 (n_145), .A2 (rAddress[7]), .B1 (n_149),
       .B2 (n_215), .C1 (n_144), .C2 (sDqOut[7]), .ZN (n_154));
  DFFR_X2 \rAddress_reg[6] (.RN (n_229), .CK (n_228), .D (n_150), .Q
       (rAddress[6]), .QN (UNCONNECTED13));
  INV_X1 g7003(.A (n_178), .ZN (n_152));
  MUX2_X2 g7004__7410(.A (sDqOut[1]), .B (rState[1]), .S (n_143), .Z
       (n_151));
  NOR3_X2 g7005__6417(.A1 (n_142), .A2 (n_137), .A3 (n_174), .ZN
       (n_178));
  INV_X1 g6951(.A (n_146), .ZN (n_150));
  XNOR2_X1 g6960__5477(.A (n_147), .B (n_138), .ZN (n_149));
  NOR2_X1 g6963__2398(.A1 (n_139), .A2 (n_147), .ZN (n_148));
  DFFR_X2 \rAddress_reg[5] (.RN (n_229), .CK (n_228), .D (n_140), .Q
       (rAddress[5]), .QN (UNCONNECTED14));
  AOI222_X1 g6953__5107(.A1 (n_145), .A2 (rAddress[6]), .B1 (n_131),
       .B2 (n_215), .C1 (n_144), .C2 (sDqOut[6]), .ZN (n_146));
  NOR2_X1 g7009__6260(.A1 (n_116), .A2 (n_141), .ZN (n_143));
  AOI211_X1 g7010__4319(.A (spi_cs), .B (n_135), .C1 (n_76), .C2
       (rCmdGotFlag), .ZN (n_142));
  NOR3_X1 g7015__8428(.A1 (n_136), .A2 (n_39), .A3 (sDqOut[0]), .ZN
       (n_141));
  INV_X1 g6970(.A (n_132), .ZN (n_140));
  INV_X1 g6969(.A (n_138), .ZN (n_139));
  NOR3_X1 g7014__5526(.A1 (n_136), .A2 (n_129), .A3 (sDqOut[1]), .ZN
       (n_137));
  NOR2_X1 g7017__6783(.A1 (n_134), .A2 (rCmdGotFlag), .ZN (n_135));
  OR2_X4 g7019__3680(.A1 (n_134), .A2 (n_70), .ZN (n_133));
  AOI222_X1 g6973__1617(.A1 (n_145), .A2 (rAddress[5]), .B1 (n_123),
       .B2 (n_215), .C1 (n_144), .C2 (sDqOut[5]), .ZN (n_132));
  XNOR2_X1 g6982__2802(.A (n_130), .B (n_126), .ZN (n_131));
  NOR2_X1 g6984__1705(.A1 (n_127), .A2 (n_130), .ZN (n_138));
  DFFR_X2 \rAddress_reg[4] (.RN (n_229), .CK (n_228), .D (n_128), .Q
       (rAddress[4]), .QN (UNCONNECTED15));
  NAND3_X1 g7024__5122(.A1 (n_125), .A2 (rINBUF[3]), .A3 (n_229), .ZN
       (n_136));
  DFFR_X2 \rAddress_reg[1] (.RN (n_229), .CK (n_228), .D (n_121), .Q
       (rAddress[1]), .QN (UNCONNECTED16));
  DFFR_X2 \rAddress_reg[3] (.RN (n_229), .CK (n_228), .D (n_115), .Q
       (rAddress[3]), .QN (UNCONNECTED17));
  NOR3_X1 g7025__8246(.A1 (n_118), .A2 (rINBUF[3]), .A3 (n_129), .ZN
       (n_134));
  DFFR_X2 \rAddress_reg[0] (.RN (n_229), .CK (n_228), .D (n_120), .Q
       (rAddress[0]), .QN (UNCONNECTED18));
  INV_X1 g6989(.A (n_124), .ZN (n_128));
  INV_X1 g6988(.A (n_126), .ZN (n_127));
  DFF_X2 \rState_reg[7] (.CK (n_228), .D (n_117), .Q (rState[7]), .QN
       (UNCONNECTED19));
  DFFR_X2 \rAddress_reg[2] (.RN (n_229), .CK (n_228), .D (n_119), .Q
       (rAddress[2]), .QN (UNCONNECTED20));
  NOR4_X1 g7033__7098(.A1 (n_107), .A2 (sDqOut[4]), .A3 (sDqOut[7]),
       .A4 (rCmdGotFlag), .ZN (n_125));
  AOI222_X1 g6990__6131(.A1 (n_145), .A2 (rAddress[4]), .B1 (n_105),
       .B2 (n_215), .C1 (n_144), .C2 (sDqOut[4]), .ZN (n_124));
  XNOR2_X1 g7000__1881(.A (n_122), .B (n_109), .ZN (n_123));
  NOR2_X1 g7002__5115(.A1 (n_110), .A2 (n_122), .ZN (n_126));
  INV_X1 g7029(.A (n_111), .ZN (n_121));
  INV_X1 g7028(.A (n_112), .ZN (n_120));
  INV_X1 g7018(.A (n_113), .ZN (n_119));
  NAND4_X1 g7034__7482(.A1 (n_106), .A2 (sDqOut[4]), .A3 (sDqOut[1]),
       .A4 (sDqOut[7]), .ZN (n_118));
  MUX2_X2 g7060__4733(.A (rState[7]), .B (sDqOut[7]), .S (n_116), .Z
       (n_117));
  INV_X1 g7007(.A (n_108), .ZN (n_115));
  MUX2_X1 g7056__6161(.A (rAddress[7]), .B (sDqOut[7]), .S
       (rReadFlag1), .Z (sAddress[7]));
  AOI22_X1 g7053__9315(.A1 (n_100), .A2 (sDqOut[7]), .B1 (n_99), .B2
       (rAddress[7]), .ZN (n_147));
  AOI222_X1 g7020__9945(.A1 (n_215), .A2 (n_80), .B1 (n_145), .B2
       (rAddress[2]), .C1 (n_144), .C2 (sDqOut[2]), .ZN (n_113));
  AOI222_X1 g7030__2883(.A1 (n_215), .A2 (n_54), .B1 (n_144), .B2
       (sDqOut[0]), .C1 (n_145), .C2 (rAddress[0]), .ZN (n_112));
  DFF_X2 \rState_reg[6] (.CK (n_228), .D (n_101), .Q (rState[6]), .QN
       (UNCONNECTED21));
  AOI222_X1 g7031__2346(.A1 (n_215), .A2 (n_55), .B1 (n_145), .B2
       (rAddress[1]), .C1 (n_144), .C2 (sDqOut[1]), .ZN (n_111));
  INV_X1 g7006(.A (n_109), .ZN (n_110));
  AOI222_X1 g7008__1666(.A1 (n_215), .A2 (n_96), .B1 (n_145), .B2
       (rAddress[3]), .C1 (n_144), .C2 (sDqOut[3]), .ZN (n_108));
  INV_X1 g7070(.A (n_106), .ZN (n_107));
  XNOR2_X1 g7011__7410(.A (n_104), .B (n_97), .ZN (n_105));
  NOR2_X1 g7013__6417(.A1 (n_98), .A2 (n_104), .ZN (n_109));
  INV_X1 g7041(.A (n_219), .ZN (n_103));
  MUX2_X1 g7073__5477(.A (rAddress[6]), .B (sDqOut[6]), .S
       (rReadFlag1), .Z (sAddress[6]));
  MUX2_X2 g7059__2398(.A (rState[6]), .B (sDqOut[6]), .S (n_116), .Z
       (n_101));
  DFFR_X2 \rCnt_reg[5] (.RN (n_229), .CK (spi_sck), .D (n_92), .Q
       (rCnt[5]), .QN (n_1));
  AOI22_X1 g7075__5107(.A1 (n_100), .A2 (sDqOut[6]), .B1 (n_99), .B2
       (rAddress[6]), .ZN (n_130));
  NOR3_X1 g7074__6260(.A1 (rINBUF[2]), .A2 (sDqOut[5]), .A3
       (sDqOut[6]), .ZN (n_106));
  DFF_X2 \rState_reg[5] (.CK (n_228), .D (n_93), .Q (rState[5]), .QN
       (UNCONNECTED22));
  INV_X1 g7016(.A (n_97), .ZN (n_98));
  DFF_X2 \rState_reg[3] (.CK (n_228), .D (n_90), .Q (rState[3]), .QN
       (UNCONNECTED23));
  INV_X1 g7048(.A (n_215), .ZN (n_206));
  OAI21_X2 g7047__4319(.A (n_78), .B1 (n_210), .B2 (n_22), .ZN (n_219));
  DFFR_X2 \rINBUF_reg[7] (.RN (n_229), .CK (spi_sck), .D (sDqOut[6]),
       .Q (sDqOut[7]), .QN (rINBUF[7]));
  DFF_X2 \rState_reg[2] (.CK (n_228), .D (n_88), .Q (rState[2]), .QN
       (UNCONNECTED24));
  DFF_X2 \rState_reg[4] (.CK (n_228), .D (n_89), .Q (rState[4]), .QN
       (UNCONNECTED25));
  DFF_X2 \rState_reg[0] (.CK (n_228), .D (n_91), .Q (rState[0]), .QN
       (UNCONNECTED26));
  XNOR2_X1 g7023__8428(.A (n_94), .B (n_85), .ZN (n_96));
  MUX2_X1 g7092__5526(.A (rAddress[5]), .B (sDqOut[5]), .S
       (rReadFlag1), .Z (sAddress[5]));
  NOR2_X1 g7026__6783(.A1 (n_86), .A2 (n_94), .ZN (n_97));
  DFFR_X2 rWriteFlag1_reg(.RN (n_229), .CK (n_228), .D (n_84), .Q
       (rWriteFlag1), .QN (n_38));
  MUX2_X2 g7061__3680(.A (rState[5]), .B (sDqOut[5]), .S (n_116), .Z
       (n_93));
  XOR2_X1 g7035__1617(.A (rCnt[5]), .B (n_81), .Z (n_92));
  AOI22_X1 g7093__2802(.A1 (n_100), .A2 (sDqOut[5]), .B1 (n_99), .B2
       (rAddress[5]), .ZN (n_122));
  AOI21_X4 g7055__1705(.A (n_145), .B1 (n_26), .B2 (n_38), .ZN (n_215));
  MUX2_X2 g7051__5122(.A (rState[0]), .B (sDqOut[0]), .S (n_116), .Z
       (n_91));
  MUX2_X2 g7057__8246(.A (rState[3]), .B (sDqOut[3]), .S (n_116), .Z
       (n_90));
  DFFR_X2 rReadFlag1_reg(.RN (n_229), .CK (n_228), .D (n_79), .Q
       (rReadFlag1), .QN (n_9));
  MUX2_X2 g7062__7098(.A (rState[4]), .B (sDqOut[4]), .S (n_116), .Z
       (n_89));
  MUX2_X2 g7058__6131(.A (rState[2]), .B (sDqOut[2]), .S (n_116), .Z
       (n_88));
  DFFR_X2 \rCnt_reg[4] (.RN (n_229), .CK (spi_sck), .D (n_82), .Q
       (rCnt[4]), .QN (n_6));
  DFFR_X2 \rINBUF_reg[6] (.RN (n_229), .CK (spi_sck), .D (sDqOut[5]),
       .Q (sDqOut[6]), .QN (UNCONNECTED27));
  MUX2_X1 g7104__1881(.A (rAddress[4]), .B (sDqOut[4]), .S
       (rReadFlag1), .Z (sAddress[4]));
  DFFR_X2 \rCmd_reg[0] (.RN (n_229), .CK (n_228), .D (n_68), .Q
       (rCmd[0]), .QN (n_10));
  DFFR_X2 \rCmd_reg[2] (.RN (n_229), .CK (n_228), .D (n_67), .Q
       (rCmd[2]), .QN (UNCONNECTED28));
  DFFR_X2 \rCmd_reg[3] (.RN (n_229), .CK (n_228), .D (n_66), .Q
       (rCmd[3]), .QN (n_0));
  DFFR_X2 \rCmd_reg[1] (.RN (n_229), .CK (n_228), .D (n_71), .Q
       (rCmd[1]), .QN (n_5));
  INV_X1 g7032(.A (n_85), .ZN (n_86));
  OR2_X4 g7050__5115(.A1 (n_144), .A2 (rWriteFlag1), .ZN (n_84));
  AOI22_X1 g7106__7482(.A1 (n_100), .A2 (sDqOut[4]), .B1 (n_99), .B2
       (rAddress[4]), .ZN (n_104));
  INV_X1 g7071(.A (n_83), .ZN (n_210));
  INV_X1 g7072(.A (n_75), .ZN (n_145));
  HA_X1 g7049__4733(.A (n_46), .B (rCnt[4]), .CO (n_81), .S (n_82));
  XNOR2_X1 g7042__6161(.A (n_77), .B (n_56), .ZN (n_80));
  OAI21_X1 g7064__9315(.A (n_78), .B1 (n_53), .B2 (n_9), .ZN (n_79));
  NOR2_X1 g7052__9945(.A1 (n_57), .A2 (n_77), .ZN (n_85));
  INV_X1 g7100(.A (n_64), .ZN (n_76));
  OAI22_X1 g7078__2883(.A1 (n_74), .A2 (n_73), .B1 (n_72), .B2 (n_27),
       .ZN (n_75));
  OAI22_X1 g7076__2346(.A1 (n_63), .A2 (n_73), .B1 (n_72), .B2 (n_21),
       .ZN (n_83));
  DFFR_X2 \rINBUF_reg[5] (.RN (n_229), .CK (spi_sck), .D (sDqOut[4]),
       .Q (sDqOut[5]), .QN (UNCONNECTED29));
  MUX2_X2 g7089__1666(.A (sDqOut[1]), .B (rCmd[1]), .S (n_70), .Z
       (n_71));
  MUX2_X1 g7116__7410(.A (rAddress[3]), .B (sDqOut[3]), .S
       (rReadFlag1), .Z (sAddress[3]));
  DFFR_X2 rCmdGotFlag_reg(.RN (n_229), .CK (n_228), .D (n_50), .Q
       (rCmdGotFlag), .QN (UNCONNECTED30));
  AND2_X4 g7086__6417(.A1 (n_49), .A2 (n_229), .ZN (n_116));
  NOR3_X2 g7077__5477(.A1 (n_72), .A2 (n_29), .A3 (rWriteFlag1), .ZN
       (n_144));
  MUX2_X2 g7088__2398(.A (sDqOut[0]), .B (rCmd[0]), .S (n_70), .Z
       (n_68));
  MUX2_X2 g7090__5107(.A (sDqOut[2]), .B (rCmd[2]), .S (n_70), .Z
       (n_67));
  OAI22_X1 g7091__6260(.A1 (n_70), .A2 (rINBUF[3]), .B1 (n_65), .B2
       (n_0), .ZN (n_66));
  OAI211_X1 g7103__4319(.A (n_63), .B (n_62), .C1 (n_34), .C2 (n_61),
       .ZN (n_64));
  AOI22_X1 g7119__8428(.A1 (n_100), .A2 (sDqOut[3]), .B1 (n_99), .B2
       (rAddress[3]), .ZN (n_94));
  DFFR_X2 rReadFlag2_reg(.RN (n_229), .CK (n_228), .D (n_51), .Q
       (rReadFlag2), .QN (n_25));
  AND2_X2 g7081__5526(.A1 (sWRn), .A2 (sOEn), .ZN (sCSn));
  INV_X1 g7063(.A (n_56), .ZN (n_57));
  DFFR_X2 \rCnt_reg[3] (.RN (n_229), .CK (spi_sck), .D (n_47), .Q
       (rCnt[3]), .QN (UNCONNECTED31));
  XOR2_X1 g7087__6783(.A (n_54), .B (n_48), .Z (n_55));
  NAND2_X1 g7082__3680(.A1 (n_53), .A2 (n_52), .ZN (n_78));
  DFFR_X2 \rINBUF_reg[4] (.RN (n_229), .CK (spi_sck), .D (sDqOut[3]),
       .Q (sDqOut[4]), .QN (UNCONNECTED32));
  OAI21_X1 g7080__1617(.A (n_25), .B1 (n_73), .B2 (n_41), .ZN (n_51));
  OR2_X4 g7095__2802(.A1 (n_65), .A2 (rCmdGotFlag), .ZN (n_50));
  NOR4_X1 g7105__1705(.A1 (n_73), .A2 (n_28), .A3 (n_15), .A4
       (rCmd[1]), .ZN (n_49));
  NOR2_X1 g7098__5122(.A1 (n_54), .A2 (n_48), .ZN (n_56));
  NAND2_X1 g7097__8246(.A1 (n_37), .A2 (n_23), .ZN (n_72));
  HA_X1 g7094__7098(.A (n_30), .B (rCnt[3]), .CO (n_46), .S (n_47));
  NAND2_X1 g7102__6131(.A1 (n_174), .A2 (rOUTBUF[4]), .ZN (n_45));
  MUX2_X1 g7126__1881(.A (rAddress[2]), .B (sDqOut[2]), .S
       (rReadFlag1), .Z (sAddress[2]));
  INV_X1 g7101(.A (sDqDir), .ZN (sWRn));
  NOR2_X1 g7096__5115(.A1 (n_73), .A2 (n_42), .ZN (n_53));
  AND2_X4 g7111__7482(.A1 (n_42), .A2 (n_40), .ZN (n_63));
  AOI22_X1 g7120__4733(.A1 (n_100), .A2 (sDqOut[2]), .B1 (n_99), .B2
       (rAddress[2]), .ZN (n_77));
  AND2_X4 g7110__6161(.A1 (n_41), .A2 (n_40), .ZN (n_74));
  INV_X1 g7109(.A (n_65), .ZN (n_70));
  AOI22_X1 g7118__9315(.A1 (n_100), .A2 (sDqOut[1]), .B1 (n_99), .B2
       (rAddress[1]), .ZN (n_48));
  NOR3_X1 g7107__9945(.A1 (n_39), .A2 (n_38), .A3 (n_228), .ZN
       (sDqDir));
  NOR2_X1 g7115__2883(.A1 (n_39), .A2 (rCmdGotFlag), .ZN (n_65));
  INV_X1 g7108(.A (n_73), .ZN (n_37));
  AOI22_X1 g7121__2346(.A1 (n_100), .A2 (sDqOut[0]), .B1 (n_99), .B2
       (rAddress[0]), .ZN (n_54));
  DFFR_X2 \rINBUF_reg[3] (.RN (n_229), .CK (spi_sck), .D (sDqOut[2]),
       .Q (sDqOut[3]), .QN (rINBUF[3]));
  OAI21_X1 g7117__1666(.A (n_36), .B1 (rReadFlag1), .B2 (rReadFlag2),
       .ZN (sOEn));
  DFFR_X2 \rCnt_reg[2] (.RN (n_229), .CK (spi_sck), .D (n_31), .Q
       (rCnt[2]), .QN (UNCONNECTED33));
  NAND2_X1 g7112__7410(.A1 (n_36), .A2 (rCmdGotFlag), .ZN (n_73));
  NAND2_X1 g7122__6417(.A1 (n_100), .A2 (n_33), .ZN (n_42));
  NAND2_X1 g7127__5477(.A1 (n_100), .A2 (n_35), .ZN (n_41));
  NOR2_X2 g7114__2398(.A1 (n_36), .A2 (spi_cs), .ZN (n_174));
  INV_X1 g7137(.A (n_33), .ZN (n_34));
  MUX2_X1 g7134__5107(.A (rAddress[1]), .B (sDqOut[1]), .S
       (rReadFlag1), .Z (sAddress[1]));
  INV_X1 g7125(.A (n_36), .ZN (n_39));
  HA_X1 g7130__6260(.A (n_19), .B (rCnt[2]), .CO (n_30), .S (n_31));
  DFFR_X2 \rCnt_reg[1] (.RN (n_229), .CK (spi_sck), .D (n_20), .Q
       (rCnt[1]), .QN (n_7));
  NAND2_X1 g7142__4319(.A1 (n_29), .A2 (n_28), .ZN (n_33));
  NOR3_X1 g7128__8428(.A1 (n_16), .A2 (n_18), .A3 (rCnt[2]), .ZN
       (n_36));
  NOR2_X1 g7139__5526(.A1 (n_35), .A2 (rWriteFlag1), .ZN (n_27));
  OR2_X4 g7132__6783(.A1 (n_26), .A2 (n_25), .ZN (n_40));
  DFFR_X2 \rINBUF_reg[2] (.RN (n_229), .CK (spi_sck), .D (sDqOut[1]),
       .Q (sDqOut[2]), .QN (rINBUF[2]));
  NOR2_X2 g7136__3680(.A1 (n_26), .A2 (rReadFlag2), .ZN (n_100));
  MUX2_X1 g7145__1617(.A (rAddress[0]), .B (sDqOut[0]), .S
       (rReadFlag1), .Z (sAddress[0]));
  OR2_X4 g7135__2802(.A1 (n_23), .A2 (rReadFlag2), .ZN (n_99));
  NAND2_X1 g7131__1705(.A1 (n_23), .A2 (n_38), .ZN (n_22));
  NOR2_X1 g7140__5122(.A1 (n_52), .A2 (rWriteFlag1), .ZN (n_21));
  NOR2_X1 g7150__8246(.A1 (n_19), .A2 (n_17), .ZN (n_20));
  INV_X1 g7153(.A (n_29), .ZN (n_35));
  DFFR_X2 \rINBUF_reg[1] (.RN (n_229), .CK (spi_sck), .D (sDqOut[0]),
       .Q (sDqOut[1]), .QN (UNCONNECTED34));
  INV_X1 g7154(.A (n_52), .ZN (n_28));
  NAND3_X1 g7146__7098(.A1 (n_12), .A2 (rCmd[1]), .A3 (rCmd[3]), .ZN
       (n_61));
  NAND2_X1 g7148__6131(.A1 (n_14), .A2 (rCmd[1]), .ZN (n_26));
  INV_X1 g7162(.A (n_17), .ZN (n_18));
  OR3_X4 g7147__1881(.A1 (n_11), .A2 (rCmd[1]), .A3 (rCmd[3]), .ZN
       (n_62));
  NAND3_X1 g7156__5115(.A1 (rCnt[4]), .A2 (n_1), .A3 (rCnt[3]), .ZN
       (n_29));
  NOR3_X1 g7144__7482(.A1 (n_13), .A2 (rCnt[4]), .A3 (rCmdGotFlag), .ZN
       (n_16));
  INV_X1 g7152(.A (n_14), .ZN (n_15));
  NOR4_X1 g7149__4733(.A1 (n_5), .A2 (rCmd[3]), .A3 (rCmd[0]), .A4
       (rCmd[2]), .ZN (n_23));
  NOR2_X1 g7157__6161(.A1 (n_13), .A2 (n_6), .ZN (n_52));
  NOR2_X1 g7164__9315(.A1 (n_4), .A2 (rCnt[1]), .ZN (n_17));
  NOR2_X1 g7166__9945(.A1 (rCnt[0]), .A2 (n_7), .ZN (n_19));
  DFFR_X2 \rINBUF_reg[0] (.RN (n_229), .CK (spi_sck), .D (spi_mosi), .Q
       (sDqOut[0]), .QN (n_129));
  INV_X1 g7163(.A (n_11), .ZN (n_12));
  NOR3_X1 g7155__2883(.A1 (n_10), .A2 (rCmd[3]), .A3 (rCmd[2]), .ZN
       (n_14));
  DFFR_X2 \rCnt_reg[0] (.RN (n_229), .CK (spi_sck), .D (rCnt[0]), .Q
       (n_4), .QN (rCnt[0]));
  NAND2_X1 g7165__2346(.A1 (rCmd[2]), .A2 (rCmd[0]), .ZN (n_11));
  OR2_X4 g7159__1666(.A1 (rCnt[5]), .A2 (rCnt[3]), .ZN (n_13));
  INV_X4 g7182(.A (spi_sck), .ZN (n_228));
  INV_X1 g7181(.A (spi_cs), .ZN (n_229));
endmodule

