
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point ce ce -type PI PI
add mapped point we we -type PI PI
add mapped point oe oe -type PI PI
add mapped point addr[5] addr[5] -type PI PI
add mapped point addr[4] addr[4] -type PI PI
add mapped point addr[3] addr[3] -type PI PI
add mapped point addr[2] addr[2] -type PI PI
add mapped point addr[1] addr[1] -type PI PI
add mapped point addr[0] addr[0] -type PI PI
add mapped point di[7] di[7] -type PI PI
add mapped point di[6] di[6] -type PI PI
add mapped point di[5] di[5] -type PI PI
add mapped point di[4] di[4] -type PI PI
add mapped point di[3] di[3] -type PI PI
add mapped point di[2] di[2] -type PI PI
add mapped point di[1] di[1] -type PI PI
add mapped point di[0] di[0] -type PI PI

//output ports
add mapped point do[7] do[7] -type PO PO
add mapped point do[6] do[6] -type PO PO
add mapped point do[5] do[5] -type PO PO
add mapped point do[4] do[4] -type PO PO
add mapped point do[3] do[3] -type PO PO
add mapped point do[2] do[2] -type PO PO
add mapped point do[1] do[1] -type PO PO
add mapped point do[0] do[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point mem[37][7]/q mem_reg[37][7]/Q -type DFF DFF
add mapped point mem[37][1]/q mem_reg[37][1]/Q -type DFF DFF
add mapped point mem[37][2]/q mem_reg[37][2]/Q -type DFF DFF
add mapped point mem[37][3]/q mem_reg[37][3]/Q -type DFF DFF
add mapped point mem[37][4]/q mem_reg[37][4]/Q -type DFF DFF
add mapped point mem[37][5]/q mem_reg[37][5]/Q -type DFF DFF
add mapped point mem[37][0]/q mem_reg[37][0]/Q -type DFF DFF
add mapped point mem[39][0]/q mem_reg[39][0]/Q -type DFF DFF
add mapped point mem[39][1]/q mem_reg[39][1]/Q -type DFF DFF
add mapped point mem[39][2]/q mem_reg[39][2]/Q -type DFF DFF
add mapped point mem[39][3]/q mem_reg[39][3]/Q -type DFF DFF
add mapped point mem[37][6]/q mem_reg[37][6]/Q -type DFF DFF
add mapped point mem[39][4]/q mem_reg[39][4]/Q -type DFF DFF
add mapped point mem[39][5]/q mem_reg[39][5]/Q -type DFF DFF
add mapped point mem[39][6]/q mem_reg[39][6]/Q -type DFF DFF
add mapped point mem[39][7]/q mem_reg[39][7]/Q -type DFF DFF
add mapped point mem[53][0]/q mem_reg[53][0]/Q -type DFF DFF
add mapped point mem[53][1]/q mem_reg[53][1]/Q -type DFF DFF
add mapped point mem[53][2]/q mem_reg[53][2]/Q -type DFF DFF
add mapped point mem[53][3]/q mem_reg[53][3]/Q -type DFF DFF
add mapped point mem[53][4]/q mem_reg[53][4]/Q -type DFF DFF
add mapped point mem[53][5]/q mem_reg[53][5]/Q -type DFF DFF
add mapped point mem[53][6]/q mem_reg[53][6]/Q -type DFF DFF
add mapped point mem[53][7]/q mem_reg[53][7]/Q -type DFF DFF
add mapped point mem[55][0]/q mem_reg[55][0]/Q -type DFF DFF
add mapped point mem[55][1]/q mem_reg[55][1]/Q -type DFF DFF
add mapped point mem[55][2]/q mem_reg[55][2]/Q -type DFF DFF
add mapped point mem[55][3]/q mem_reg[55][3]/Q -type DFF DFF
add mapped point mem[55][4]/q mem_reg[55][4]/Q -type DFF DFF
add mapped point mem[55][7]/q mem_reg[55][7]/Q -type DFF DFF
add mapped point mem[55][6]/q mem_reg[55][6]/Q -type DFF DFF
add mapped point mem[55][5]/q mem_reg[55][5]/Q -type DFF DFF
add mapped point mem[47][6]/q mem_reg[47][6]/Q -type DFF DFF
add mapped point mem[38][0]/q mem_reg[38][0]/Q -type DFF DFF
add mapped point mem[20][1]/q mem_reg[20][1]/Q -type DFF DFF
add mapped point mem[20][2]/q mem_reg[20][2]/Q -type DFF DFF
add mapped point mem[20][3]/q mem_reg[20][3]/Q -type DFF DFF
add mapped point mem[20][4]/q mem_reg[20][4]/Q -type DFF DFF
add mapped point mem[20][5]/q mem_reg[20][5]/Q -type DFF DFF
add mapped point mem[20][6]/q mem_reg[20][6]/Q -type DFF DFF
add mapped point mem[20][7]/q mem_reg[20][7]/Q -type DFF DFF
add mapped point mem[21][0]/q mem_reg[21][0]/Q -type DFF DFF
add mapped point mem[21][1]/q mem_reg[21][1]/Q -type DFF DFF
add mapped point mem[21][2]/q mem_reg[21][2]/Q -type DFF DFF
add mapped point mem[21][3]/q mem_reg[21][3]/Q -type DFF DFF
add mapped point mem[21][4]/q mem_reg[21][4]/Q -type DFF DFF
add mapped point mem[21][5]/q mem_reg[21][5]/Q -type DFF DFF
add mapped point mem[21][6]/q mem_reg[21][6]/Q -type DFF DFF
add mapped point mem[40][6]/q mem_reg[40][6]/Q -type DFF DFF
add mapped point mem[21][7]/q mem_reg[21][7]/Q -type DFF DFF
add mapped point mem[22][0]/q mem_reg[22][0]/Q -type DFF DFF
add mapped point mem[22][1]/q mem_reg[22][1]/Q -type DFF DFF
add mapped point mem[22][2]/q mem_reg[22][2]/Q -type DFF DFF
add mapped point mem[22][3]/q mem_reg[22][3]/Q -type DFF DFF
add mapped point mem[22][4]/q mem_reg[22][4]/Q -type DFF DFF
add mapped point mem[22][5]/q mem_reg[22][5]/Q -type DFF DFF
add mapped point mem[22][6]/q mem_reg[22][6]/Q -type DFF DFF
add mapped point mem[22][7]/q mem_reg[22][7]/Q -type DFF DFF
add mapped point mem[23][0]/q mem_reg[23][0]/Q -type DFF DFF
add mapped point mem[23][1]/q mem_reg[23][1]/Q -type DFF DFF
add mapped point mem[23][2]/q mem_reg[23][2]/Q -type DFF DFF
add mapped point mem[23][3]/q mem_reg[23][3]/Q -type DFF DFF
add mapped point mem[23][4]/q mem_reg[23][4]/Q -type DFF DFF
add mapped point mem[23][7]/q mem_reg[23][7]/Q -type DFF DFF
add mapped point mem[36][0]/q mem_reg[36][0]/Q -type DFF DFF
add mapped point mem[36][1]/q mem_reg[36][1]/Q -type DFF DFF
add mapped point mem[36][2]/q mem_reg[36][2]/Q -type DFF DFF
add mapped point mem[36][3]/q mem_reg[36][3]/Q -type DFF DFF
add mapped point mem[36][4]/q mem_reg[36][4]/Q -type DFF DFF
add mapped point mem[36][5]/q mem_reg[36][5]/Q -type DFF DFF
add mapped point mem[36][6]/q mem_reg[36][6]/Q -type DFF DFF
add mapped point mem[36][7]/q mem_reg[36][7]/Q -type DFF DFF
add mapped point mem[23][6]/q mem_reg[23][6]/Q -type DFF DFF
add mapped point mem[23][5]/q mem_reg[23][5]/Q -type DFF DFF
add mapped point mem[20][0]/q mem_reg[20][0]/Q -type DFF DFF
add mapped point mem[63][1]/q mem_reg[63][1]/Q -type DFF DFF
add mapped point mem[38][3]/q mem_reg[38][3]/Q -type DFF DFF
add mapped point mem[38][4]/q mem_reg[38][4]/Q -type DFF DFF
add mapped point mem[38][5]/q mem_reg[38][5]/Q -type DFF DFF
add mapped point mem[38][6]/q mem_reg[38][6]/Q -type DFF DFF
add mapped point mem[38][7]/q mem_reg[38][7]/Q -type DFF DFF
add mapped point mem[52][0]/q mem_reg[52][0]/Q -type DFF DFF
add mapped point mem[52][1]/q mem_reg[52][1]/Q -type DFF DFF
add mapped point mem[52][2]/q mem_reg[52][2]/Q -type DFF DFF
add mapped point mem[52][3]/q mem_reg[52][3]/Q -type DFF DFF
add mapped point mem[52][4]/q mem_reg[52][4]/Q -type DFF DFF
add mapped point mem[52][5]/q mem_reg[52][5]/Q -type DFF DFF
add mapped point mem[52][6]/q mem_reg[52][6]/Q -type DFF DFF
add mapped point mem[52][7]/q mem_reg[52][7]/Q -type DFF DFF
add mapped point mem[54][0]/q mem_reg[54][0]/Q -type DFF DFF
add mapped point mem[54][1]/q mem_reg[54][1]/Q -type DFF DFF
add mapped point mem[54][2]/q mem_reg[54][2]/Q -type DFF DFF
add mapped point mem[54][3]/q mem_reg[54][3]/Q -type DFF DFF
add mapped point mem[54][4]/q mem_reg[54][4]/Q -type DFF DFF
add mapped point mem[54][5]/q mem_reg[54][5]/Q -type DFF DFF
add mapped point mem[54][6]/q mem_reg[54][6]/Q -type DFF DFF
add mapped point mem[54][7]/q mem_reg[54][7]/Q -type DFF DFF
add mapped point mem[5][6]/q mem_reg[5][6]/Q -type DFF DFF
add mapped point mem[7][6]/q mem_reg[7][6]/Q -type DFF DFF
add mapped point mem[7][5]/q mem_reg[7][5]/Q -type DFF DFF
add mapped point mem[7][4]/q mem_reg[7][4]/Q -type DFF DFF
add mapped point mem[7][3]/q mem_reg[7][3]/Q -type DFF DFF
add mapped point mem[7][2]/q mem_reg[7][2]/Q -type DFF DFF
add mapped point mem[7][1]/q mem_reg[7][1]/Q -type DFF DFF
add mapped point mem[7][0]/q mem_reg[7][0]/Q -type DFF DFF
add mapped point mem[6][7]/q mem_reg[6][7]/Q -type DFF DFF
add mapped point mem[6][6]/q mem_reg[6][6]/Q -type DFF DFF
add mapped point mem[6][5]/q mem_reg[6][5]/Q -type DFF DFF
add mapped point mem[6][4]/q mem_reg[6][4]/Q -type DFF DFF
add mapped point mem[6][3]/q mem_reg[6][3]/Q -type DFF DFF
add mapped point mem[6][2]/q mem_reg[6][2]/Q -type DFF DFF
add mapped point mem[6][1]/q mem_reg[6][1]/Q -type DFF DFF
add mapped point mem[6][0]/q mem_reg[6][0]/Q -type DFF DFF
add mapped point mem[7][7]/q mem_reg[7][7]/Q -type DFF DFF
add mapped point mem[5][7]/q mem_reg[5][7]/Q -type DFF DFF
add mapped point mem[5][5]/q mem_reg[5][5]/Q -type DFF DFF
add mapped point mem[5][4]/q mem_reg[5][4]/Q -type DFF DFF
add mapped point mem[5][3]/q mem_reg[5][3]/Q -type DFF DFF
add mapped point mem[5][2]/q mem_reg[5][2]/Q -type DFF DFF
add mapped point mem[5][1]/q mem_reg[5][1]/Q -type DFF DFF
add mapped point mem[5][0]/q mem_reg[5][0]/Q -type DFF DFF
add mapped point mem[4][7]/q mem_reg[4][7]/Q -type DFF DFF
add mapped point mem[4][6]/q mem_reg[4][6]/Q -type DFF DFF
add mapped point mem[4][5]/q mem_reg[4][5]/Q -type DFF DFF
add mapped point mem[4][4]/q mem_reg[4][4]/Q -type DFF DFF
add mapped point mem[4][3]/q mem_reg[4][3]/Q -type DFF DFF
add mapped point mem[4][2]/q mem_reg[4][2]/Q -type DFF DFF
add mapped point mem[4][1]/q mem_reg[4][1]/Q -type DFF DFF
add mapped point mem[4][0]/q mem_reg[4][0]/Q -type DFF DFF
add mapped point mem[61][5]/q mem_reg[61][5]/Q -type DFF DFF
add mapped point mem[38][1]/q mem_reg[38][1]/Q -type DFF DFF
add mapped point mem[40][0]/q mem_reg[40][0]/Q -type DFF DFF
add mapped point mem[40][1]/q mem_reg[40][1]/Q -type DFF DFF
add mapped point mem[40][2]/q mem_reg[40][2]/Q -type DFF DFF
add mapped point mem[40][3]/q mem_reg[40][3]/Q -type DFF DFF
add mapped point mem[40][4]/q mem_reg[40][4]/Q -type DFF DFF
add mapped point mem[40][5]/q mem_reg[40][5]/Q -type DFF DFF
add mapped point mem[40][7]/q mem_reg[40][7]/Q -type DFF DFF
add mapped point mem[38][2]/q mem_reg[38][2]/Q -type DFF DFF
add mapped point mem[45][0]/q mem_reg[45][0]/Q -type DFF DFF
add mapped point mem[45][1]/q mem_reg[45][1]/Q -type DFF DFF
add mapped point mem[45][2]/q mem_reg[45][2]/Q -type DFF DFF
add mapped point mem[45][3]/q mem_reg[45][3]/Q -type DFF DFF
add mapped point mem[45][4]/q mem_reg[45][4]/Q -type DFF DFF
add mapped point mem[45][5]/q mem_reg[45][5]/Q -type DFF DFF
add mapped point mem[45][6]/q mem_reg[45][6]/Q -type DFF DFF
add mapped point mem[45][7]/q mem_reg[45][7]/Q -type DFF DFF
add mapped point mem[47][0]/q mem_reg[47][0]/Q -type DFF DFF
add mapped point mem[47][1]/q mem_reg[47][1]/Q -type DFF DFF
add mapped point mem[47][2]/q mem_reg[47][2]/Q -type DFF DFF
add mapped point mem[47][3]/q mem_reg[47][3]/Q -type DFF DFF
add mapped point mem[47][4]/q mem_reg[47][4]/Q -type DFF DFF
add mapped point mem[47][5]/q mem_reg[47][5]/Q -type DFF DFF
add mapped point mem[47][7]/q mem_reg[47][7]/Q -type DFF DFF
add mapped point mem[61][0]/q mem_reg[61][0]/Q -type DFF DFF
add mapped point mem[61][1]/q mem_reg[61][1]/Q -type DFF DFF
add mapped point mem[61][2]/q mem_reg[61][2]/Q -type DFF DFF
add mapped point mem[61][3]/q mem_reg[61][3]/Q -type DFF DFF
add mapped point mem[61][4]/q mem_reg[61][4]/Q -type DFF DFF
add mapped point mem[61][7]/q mem_reg[61][7]/Q -type DFF DFF
add mapped point mem[63][7]/q mem_reg[63][7]/Q -type DFF DFF
add mapped point mem[63][6]/q mem_reg[63][6]/Q -type DFF DFF
add mapped point mem[63][5]/q mem_reg[63][5]/Q -type DFF DFF
add mapped point mem[63][4]/q mem_reg[63][4]/Q -type DFF DFF
add mapped point mem[63][3]/q mem_reg[63][3]/Q -type DFF DFF
add mapped point mem[63][2]/q mem_reg[63][2]/Q -type DFF DFF
add mapped point mem[63][0]/q mem_reg[63][0]/Q -type DFF DFF
add mapped point mem[61][6]/q mem_reg[61][6]/Q -type DFF DFF
add mapped point mem[8][1]/q mem_reg[8][1]/Q -type DFF DFF
add mapped point mem[10][1]/q mem_reg[10][1]/Q -type DFF DFF
add mapped point mem[58][6]/q mem_reg[58][6]/Q -type DFF DFF
add mapped point mem[43][6]/q mem_reg[43][6]/Q -type DFF DFF
add mapped point mem[58][2]/q mem_reg[58][2]/Q -type DFF DFF
add mapped point mem[57][6]/q mem_reg[57][6]/Q -type DFF DFF
add mapped point mem[56][6]/q mem_reg[56][6]/Q -type DFF DFF
add mapped point mem[42][6]/q mem_reg[42][6]/Q -type DFF DFF
add mapped point mem[59][6]/q mem_reg[59][6]/Q -type DFF DFF
add mapped point mem[42][2]/q mem_reg[42][2]/Q -type DFF DFF
add mapped point mem[41][6]/q mem_reg[41][6]/Q -type DFF DFF
add mapped point mem[56][2]/q mem_reg[56][2]/Q -type DFF DFF
add mapped point mem[26][6]/q mem_reg[26][6]/Q -type DFF DFF
add mapped point mem[24][6]/q mem_reg[24][6]/Q -type DFF DFF
add mapped point mem[24][0]/q mem_reg[24][0]/Q -type DFF DFF
add mapped point mem[24][1]/q mem_reg[24][1]/Q -type DFF DFF
add mapped point mem[24][2]/q mem_reg[24][2]/Q -type DFF DFF
add mapped point mem[24][3]/q mem_reg[24][3]/Q -type DFF DFF
add mapped point mem[24][4]/q mem_reg[24][4]/Q -type DFF DFF
add mapped point mem[24][5]/q mem_reg[24][5]/Q -type DFF DFF
add mapped point mem[24][7]/q mem_reg[24][7]/Q -type DFF DFF
add mapped point mem[26][0]/q mem_reg[26][0]/Q -type DFF DFF
add mapped point mem[26][1]/q mem_reg[26][1]/Q -type DFF DFF
add mapped point mem[26][2]/q mem_reg[26][2]/Q -type DFF DFF
add mapped point mem[26][3]/q mem_reg[26][3]/Q -type DFF DFF
add mapped point mem[26][4]/q mem_reg[26][4]/Q -type DFF DFF
add mapped point mem[26][5]/q mem_reg[26][5]/Q -type DFF DFF
add mapped point mem[26][7]/q mem_reg[26][7]/Q -type DFF DFF
add mapped point mem[41][0]/q mem_reg[41][0]/Q -type DFF DFF
add mapped point mem[41][1]/q mem_reg[41][1]/Q -type DFF DFF
add mapped point mem[41][2]/q mem_reg[41][2]/Q -type DFF DFF
add mapped point mem[41][3]/q mem_reg[41][3]/Q -type DFF DFF
add mapped point mem[41][4]/q mem_reg[41][4]/Q -type DFF DFF
add mapped point mem[41][5]/q mem_reg[41][5]/Q -type DFF DFF
add mapped point mem[41][7]/q mem_reg[41][7]/Q -type DFF DFF
add mapped point mem[42][0]/q mem_reg[42][0]/Q -type DFF DFF
add mapped point mem[42][1]/q mem_reg[42][1]/Q -type DFF DFF
add mapped point mem[42][3]/q mem_reg[42][3]/Q -type DFF DFF
add mapped point mem[42][4]/q mem_reg[42][4]/Q -type DFF DFF
add mapped point mem[42][5]/q mem_reg[42][5]/Q -type DFF DFF
add mapped point mem[43][1]/q mem_reg[43][1]/Q -type DFF DFF
add mapped point mem[43][3]/q mem_reg[43][3]/Q -type DFF DFF
add mapped point mem[43][4]/q mem_reg[43][4]/Q -type DFF DFF
add mapped point mem[43][5]/q mem_reg[43][5]/Q -type DFF DFF
add mapped point mem[43][7]/q mem_reg[43][7]/Q -type DFF DFF
add mapped point mem[43][0]/q mem_reg[43][0]/Q -type DFF DFF
add mapped point mem[42][7]/q mem_reg[42][7]/Q -type DFF DFF
add mapped point mem[56][0]/q mem_reg[56][0]/Q -type DFF DFF
add mapped point mem[56][1]/q mem_reg[56][1]/Q -type DFF DFF
add mapped point mem[56][3]/q mem_reg[56][3]/Q -type DFF DFF
add mapped point mem[56][4]/q mem_reg[56][4]/Q -type DFF DFF
add mapped point mem[56][5]/q mem_reg[56][5]/Q -type DFF DFF
add mapped point mem[56][7]/q mem_reg[56][7]/Q -type DFF DFF
add mapped point mem[57][0]/q mem_reg[57][0]/Q -type DFF DFF
add mapped point mem[57][1]/q mem_reg[57][1]/Q -type DFF DFF
add mapped point mem[57][2]/q mem_reg[57][2]/Q -type DFF DFF
add mapped point mem[57][3]/q mem_reg[57][3]/Q -type DFF DFF
add mapped point mem[57][4]/q mem_reg[57][4]/Q -type DFF DFF
add mapped point mem[57][5]/q mem_reg[57][5]/Q -type DFF DFF
add mapped point mem[57][7]/q mem_reg[57][7]/Q -type DFF DFF
add mapped point mem[58][0]/q mem_reg[58][0]/Q -type DFF DFF
add mapped point mem[58][1]/q mem_reg[58][1]/Q -type DFF DFF
add mapped point mem[58][3]/q mem_reg[58][3]/Q -type DFF DFF
add mapped point mem[58][4]/q mem_reg[58][4]/Q -type DFF DFF
add mapped point mem[58][5]/q mem_reg[58][5]/Q -type DFF DFF
add mapped point mem[59][1]/q mem_reg[59][1]/Q -type DFF DFF
add mapped point mem[59][2]/q mem_reg[59][2]/Q -type DFF DFF
add mapped point mem[59][3]/q mem_reg[59][3]/Q -type DFF DFF
add mapped point mem[59][4]/q mem_reg[59][4]/Q -type DFF DFF
add mapped point mem[59][5]/q mem_reg[59][5]/Q -type DFF DFF
add mapped point mem[59][7]/q mem_reg[59][7]/Q -type DFF DFF
add mapped point mem[59][0]/q mem_reg[59][0]/Q -type DFF DFF
add mapped point mem[58][7]/q mem_reg[58][7]/Q -type DFF DFF
add mapped point mem[10][7]/q mem_reg[10][7]/Q -type DFF DFF
add mapped point mem[10][6]/q mem_reg[10][6]/Q -type DFF DFF
add mapped point mem[10][5]/q mem_reg[10][5]/Q -type DFF DFF
add mapped point mem[10][4]/q mem_reg[10][4]/Q -type DFF DFF
add mapped point mem[10][3]/q mem_reg[10][3]/Q -type DFF DFF
add mapped point mem[10][2]/q mem_reg[10][2]/Q -type DFF DFF
add mapped point mem[8][7]/q mem_reg[8][7]/Q -type DFF DFF
add mapped point mem[8][6]/q mem_reg[8][6]/Q -type DFF DFF
add mapped point mem[8][5]/q mem_reg[8][5]/Q -type DFF DFF
add mapped point mem[8][4]/q mem_reg[8][4]/Q -type DFF DFF
add mapped point mem[8][3]/q mem_reg[8][3]/Q -type DFF DFF
add mapped point mem[8][2]/q mem_reg[8][2]/Q -type DFF DFF
add mapped point mem[10][0]/q mem_reg[10][0]/Q -type DFF DFF
add mapped point mem[8][0]/q mem_reg[8][0]/Q -type DFF DFF
add mapped point mem[43][2]/q mem_reg[43][2]/Q -type DFF DFF
add mapped point mem[62][5]/q mem_reg[62][5]/Q -type DFF DFF
add mapped point mem[44][2]/q mem_reg[44][2]/Q -type DFF DFF
add mapped point mem[44][7]/q mem_reg[44][7]/Q -type DFF DFF
add mapped point mem[60][7]/q mem_reg[60][7]/Q -type DFF DFF
add mapped point mem[46][2]/q mem_reg[46][2]/Q -type DFF DFF
add mapped point mem[46][6]/q mem_reg[46][6]/Q -type DFF DFF
add mapped point mem[46][7]/q mem_reg[46][7]/Q -type DFF DFF
add mapped point mem[62][1]/q mem_reg[62][1]/Q -type DFF DFF
add mapped point mem[44][6]/q mem_reg[44][6]/Q -type DFF DFF
add mapped point mem[13][6]/q mem_reg[13][6]/Q -type DFF DFF
add mapped point mem[31][6]/q mem_reg[31][6]/Q -type DFF DFF
add mapped point mem[15][0]/q mem_reg[15][0]/Q -type DFF DFF
add mapped point mem[12][0]/q mem_reg[12][0]/Q -type DFF DFF
add mapped point mem[12][1]/q mem_reg[12][1]/Q -type DFF DFF
add mapped point mem[12][3]/q mem_reg[12][3]/Q -type DFF DFF
add mapped point mem[12][4]/q mem_reg[12][4]/Q -type DFF DFF
add mapped point mem[12][5]/q mem_reg[12][5]/Q -type DFF DFF
add mapped point mem[28][6]/q mem_reg[28][6]/Q -type DFF DFF
add mapped point mem[12][7]/q mem_reg[12][7]/Q -type DFF DFF
add mapped point mem[13][0]/q mem_reg[13][0]/Q -type DFF DFF
add mapped point mem[13][1]/q mem_reg[13][1]/Q -type DFF DFF
add mapped point mem[13][3]/q mem_reg[13][3]/Q -type DFF DFF
add mapped point mem[13][4]/q mem_reg[13][4]/Q -type DFF DFF
add mapped point mem[13][5]/q mem_reg[13][5]/Q -type DFF DFF
add mapped point mem[13][7]/q mem_reg[13][7]/Q -type DFF DFF
add mapped point mem[14][0]/q mem_reg[14][0]/Q -type DFF DFF
add mapped point mem[14][1]/q mem_reg[14][1]/Q -type DFF DFF
add mapped point mem[14][3]/q mem_reg[14][3]/Q -type DFF DFF
add mapped point mem[14][4]/q mem_reg[14][4]/Q -type DFF DFF
add mapped point mem[14][5]/q mem_reg[14][5]/Q -type DFF DFF
add mapped point mem[29][2]/q mem_reg[29][2]/Q -type DFF DFF
add mapped point mem[14][7]/q mem_reg[14][7]/Q -type DFF DFF
add mapped point mem[31][2]/q mem_reg[31][2]/Q -type DFF DFF
add mapped point mem[15][1]/q mem_reg[15][1]/Q -type DFF DFF
add mapped point mem[15][3]/q mem_reg[15][3]/Q -type DFF DFF
add mapped point mem[15][4]/q mem_reg[15][4]/Q -type DFF DFF
add mapped point mem[15][5]/q mem_reg[15][5]/Q -type DFF DFF
add mapped point mem[15][7]/q mem_reg[15][7]/Q -type DFF DFF
add mapped point mem[60][2]/q mem_reg[60][2]/Q -type DFF DFF
add mapped point mem[15][2]/q mem_reg[15][2]/Q -type DFF DFF
add mapped point mem[28][0]/q mem_reg[28][0]/Q -type DFF DFF
add mapped point mem[28][1]/q mem_reg[28][1]/Q -type DFF DFF
add mapped point mem[28][2]/q mem_reg[28][2]/Q -type DFF DFF
add mapped point mem[28][3]/q mem_reg[28][3]/Q -type DFF DFF
add mapped point mem[28][4]/q mem_reg[28][4]/Q -type DFF DFF
add mapped point mem[28][5]/q mem_reg[28][5]/Q -type DFF DFF
add mapped point mem[28][7]/q mem_reg[28][7]/Q -type DFF DFF
add mapped point mem[29][0]/q mem_reg[29][0]/Q -type DFF DFF
add mapped point mem[29][1]/q mem_reg[29][1]/Q -type DFF DFF
add mapped point mem[29][3]/q mem_reg[29][3]/Q -type DFF DFF
add mapped point mem[29][4]/q mem_reg[29][4]/Q -type DFF DFF
add mapped point mem[29][5]/q mem_reg[29][5]/Q -type DFF DFF
add mapped point mem[29][7]/q mem_reg[29][7]/Q -type DFF DFF
add mapped point mem[30][0]/q mem_reg[30][0]/Q -type DFF DFF
add mapped point mem[30][1]/q mem_reg[30][1]/Q -type DFF DFF
add mapped point mem[30][3]/q mem_reg[30][3]/Q -type DFF DFF
add mapped point mem[30][4]/q mem_reg[30][4]/Q -type DFF DFF
add mapped point mem[30][5]/q mem_reg[30][5]/Q -type DFF DFF
add mapped point mem[14][2]/q mem_reg[14][2]/Q -type DFF DFF
add mapped point mem[30][7]/q mem_reg[30][7]/Q -type DFF DFF
add mapped point mem[31][0]/q mem_reg[31][0]/Q -type DFF DFF
add mapped point mem[31][1]/q mem_reg[31][1]/Q -type DFF DFF
add mapped point mem[31][3]/q mem_reg[31][3]/Q -type DFF DFF
add mapped point mem[31][4]/q mem_reg[31][4]/Q -type DFF DFF
add mapped point mem[31][5]/q mem_reg[31][5]/Q -type DFF DFF
add mapped point mem[31][7]/q mem_reg[31][7]/Q -type DFF DFF
add mapped point mem[30][6]/q mem_reg[30][6]/Q -type DFF DFF
add mapped point mem[14][6]/q mem_reg[14][6]/Q -type DFF DFF
add mapped point mem[44][0]/q mem_reg[44][0]/Q -type DFF DFF
add mapped point mem[44][1]/q mem_reg[44][1]/Q -type DFF DFF
add mapped point mem[44][3]/q mem_reg[44][3]/Q -type DFF DFF
add mapped point mem[44][4]/q mem_reg[44][4]/Q -type DFF DFF
add mapped point mem[44][5]/q mem_reg[44][5]/Q -type DFF DFF
add mapped point mem[13][2]/q mem_reg[13][2]/Q -type DFF DFF
add mapped point mem[46][0]/q mem_reg[46][0]/Q -type DFF DFF
add mapped point mem[46][1]/q mem_reg[46][1]/Q -type DFF DFF
add mapped point mem[46][3]/q mem_reg[46][3]/Q -type DFF DFF
add mapped point mem[46][4]/q mem_reg[46][4]/Q -type DFF DFF
add mapped point mem[46][5]/q mem_reg[46][5]/Q -type DFF DFF
add mapped point mem[60][6]/q mem_reg[60][6]/Q -type DFF DFF
add mapped point mem[12][6]/q mem_reg[12][6]/Q -type DFF DFF
add mapped point mem[12][2]/q mem_reg[12][2]/Q -type DFF DFF
add mapped point mem[60][0]/q mem_reg[60][0]/Q -type DFF DFF
add mapped point mem[60][1]/q mem_reg[60][1]/Q -type DFF DFF
add mapped point mem[60][3]/q mem_reg[60][3]/Q -type DFF DFF
add mapped point mem[60][4]/q mem_reg[60][4]/Q -type DFF DFF
add mapped point mem[60][5]/q mem_reg[60][5]/Q -type DFF DFF
add mapped point mem[62][7]/q mem_reg[62][7]/Q -type DFF DFF
add mapped point mem[62][6]/q mem_reg[62][6]/Q -type DFF DFF
add mapped point mem[62][4]/q mem_reg[62][4]/Q -type DFF DFF
add mapped point mem[62][3]/q mem_reg[62][3]/Q -type DFF DFF
add mapped point mem[62][2]/q mem_reg[62][2]/Q -type DFF DFF
add mapped point mem[30][2]/q mem_reg[30][2]/Q -type DFF DFF
add mapped point mem[62][0]/q mem_reg[62][0]/Q -type DFF DFF
add mapped point mem[29][6]/q mem_reg[29][6]/Q -type DFF DFF
add mapped point mem[15][6]/q mem_reg[15][6]/Q -type DFF DFF
add mapped point mem[11][2]/q mem_reg[11][2]/Q -type DFF DFF
add mapped point mem[34][5]/q mem_reg[34][5]/Q -type DFF DFF
add mapped point mem[49][4]/q mem_reg[49][4]/Q -type DFF DFF
add mapped point mem[33][1]/q mem_reg[33][1]/Q -type DFF DFF
add mapped point mem[9][1]/q mem_reg[9][1]/Q -type DFF DFF
add mapped point mem[32][7]/q mem_reg[32][7]/Q -type DFF DFF
add mapped point mem[49][1]/q mem_reg[49][1]/Q -type DFF DFF
add mapped point mem[33][7]/q mem_reg[33][7]/Q -type DFF DFF
add mapped point mem[34][3]/q mem_reg[34][3]/Q -type DFF DFF
add mapped point mem[0][7]/q mem_reg[0][7]/Q -type DFF DFF
add mapped point mem[16][2]/q mem_reg[16][2]/Q -type DFF DFF
add mapped point mem[48][1]/q mem_reg[48][1]/Q -type DFF DFF
add mapped point mem[35][7]/q mem_reg[35][7]/Q -type DFF DFF
add mapped point mem[33][3]/q mem_reg[33][3]/Q -type DFF DFF
add mapped point mem[18][3]/q mem_reg[18][3]/Q -type DFF DFF
add mapped point mem[48][5]/q mem_reg[48][5]/Q -type DFF DFF
add mapped point mem[16][1]/q mem_reg[16][1]/Q -type DFF DFF
add mapped point mem[9][5]/q mem_reg[9][5]/Q -type DFF DFF
add mapped point mem[16][3]/q mem_reg[16][3]/Q -type DFF DFF
add mapped point mem[16][0]/q mem_reg[16][0]/Q -type DFF DFF
add mapped point mem[34][7]/q mem_reg[34][7]/Q -type DFF DFF
add mapped point mem[35][3]/q mem_reg[35][3]/Q -type DFF DFF
add mapped point mem[32][5]/q mem_reg[32][5]/Q -type DFF DFF
add mapped point mem[11][0]/q mem_reg[11][0]/Q -type DFF DFF
add mapped point mem[32][3]/q mem_reg[32][3]/Q -type DFF DFF
add mapped point mem[2][5]/q mem_reg[2][5]/Q -type DFF DFF
add mapped point mem[0][1]/q mem_reg[0][1]/Q -type DFF DFF
add mapped point mem[50][2]/q mem_reg[50][2]/Q -type DFF DFF
add mapped point mem[11][3]/q mem_reg[11][3]/Q -type DFF DFF
add mapped point mem[11][4]/q mem_reg[11][4]/Q -type DFF DFF
add mapped point mem[11][5]/q mem_reg[11][5]/Q -type DFF DFF
add mapped point mem[25][0]/q mem_reg[25][0]/Q -type DFF DFF
add mapped point mem[25][1]/q mem_reg[25][1]/Q -type DFF DFF
add mapped point mem[25][3]/q mem_reg[25][3]/Q -type DFF DFF
add mapped point mem[25][5]/q mem_reg[25][5]/Q -type DFF DFF
add mapped point mem[27][0]/q mem_reg[27][0]/Q -type DFF DFF
add mapped point mem[27][1]/q mem_reg[27][1]/Q -type DFF DFF
add mapped point mem[27][3]/q mem_reg[27][3]/Q -type DFF DFF
add mapped point mem[27][5]/q mem_reg[27][5]/Q -type DFF DFF
add mapped point mem[27][7]/q mem_reg[27][7]/Q -type DFF DFF
add mapped point mem[27][2]/q mem_reg[27][2]/Q -type DFF DFF
add mapped point mem[50][0]/q mem_reg[50][0]/Q -type DFF DFF
add mapped point mem[27][6]/q mem_reg[27][6]/Q -type DFF DFF
add mapped point mem[11][7]/q mem_reg[11][7]/Q -type DFF DFF
add mapped point mem[27][4]/q mem_reg[27][4]/Q -type DFF DFF
add mapped point mem[0][5]/q mem_reg[0][5]/Q -type DFF DFF
add mapped point mem[11][6]/q mem_reg[11][6]/Q -type DFF DFF
add mapped point mem[25][4]/q mem_reg[25][4]/Q -type DFF DFF
add mapped point mem[9][7]/q mem_reg[9][7]/Q -type DFF DFF
add mapped point mem[9][6]/q mem_reg[9][6]/Q -type DFF DFF
add mapped point mem[9][4]/q mem_reg[9][4]/Q -type DFF DFF
add mapped point mem[9][3]/q mem_reg[9][3]/Q -type DFF DFF
add mapped point mem[9][2]/q mem_reg[9][2]/Q -type DFF DFF
add mapped point mem[9][0]/q mem_reg[9][0]/Q -type DFF DFF
add mapped point mem[51][2]/q mem_reg[51][2]/Q -type DFF DFF
add mapped point mem[50][4]/q mem_reg[50][4]/Q -type DFF DFF
add mapped point mem[11][1]/q mem_reg[11][1]/Q -type DFF DFF
add mapped point mem[48][6]/q mem_reg[48][6]/Q -type DFF DFF
add mapped point mem[48][7]/q mem_reg[48][7]/Q -type DFF DFF
add mapped point mem[49][0]/q mem_reg[49][0]/Q -type DFF DFF
add mapped point mem[49][2]/q mem_reg[49][2]/Q -type DFF DFF
add mapped point mem[49][3]/q mem_reg[49][3]/Q -type DFF DFF
add mapped point mem[0][0]/q mem_reg[0][0]/Q -type DFF DFF
add mapped point mem[49][5]/q mem_reg[49][5]/Q -type DFF DFF
add mapped point mem[49][6]/q mem_reg[49][6]/Q -type DFF DFF
add mapped point mem[49][7]/q mem_reg[49][7]/Q -type DFF DFF
add mapped point mem[25][7]/q mem_reg[25][7]/Q -type DFF DFF
add mapped point mem[50][1]/q mem_reg[50][1]/Q -type DFF DFF
add mapped point mem[0][2]/q mem_reg[0][2]/Q -type DFF DFF
add mapped point mem[50][3]/q mem_reg[50][3]/Q -type DFF DFF
add mapped point mem[0][3]/q mem_reg[0][3]/Q -type DFF DFF
add mapped point mem[0][4]/q mem_reg[0][4]/Q -type DFF DFF
add mapped point mem[50][5]/q mem_reg[50][5]/Q -type DFF DFF
add mapped point mem[50][6]/q mem_reg[50][6]/Q -type DFF DFF
add mapped point mem[50][7]/q mem_reg[50][7]/Q -type DFF DFF
add mapped point mem[51][0]/q mem_reg[51][0]/Q -type DFF DFF
add mapped point mem[51][1]/q mem_reg[51][1]/Q -type DFF DFF
add mapped point mem[0][6]/q mem_reg[0][6]/Q -type DFF DFF
add mapped point mem[25][6]/q mem_reg[25][6]/Q -type DFF DFF
add mapped point mem[51][3]/q mem_reg[51][3]/Q -type DFF DFF
add mapped point mem[51][4]/q mem_reg[51][4]/Q -type DFF DFF
add mapped point mem[51][5]/q mem_reg[51][5]/Q -type DFF DFF
add mapped point mem[51][6]/q mem_reg[51][6]/Q -type DFF DFF
add mapped point mem[51][7]/q mem_reg[51][7]/Q -type DFF DFF
add mapped point mem[2][0]/q mem_reg[2][0]/Q -type DFF DFF
add mapped point mem[2][1]/q mem_reg[2][1]/Q -type DFF DFF
add mapped point mem[2][2]/q mem_reg[2][2]/Q -type DFF DFF
add mapped point mem[2][3]/q mem_reg[2][3]/Q -type DFF DFF
add mapped point mem[2][4]/q mem_reg[2][4]/Q -type DFF DFF
add mapped point mem[2][6]/q mem_reg[2][6]/Q -type DFF DFF
add mapped point mem[2][7]/q mem_reg[2][7]/Q -type DFF DFF
add mapped point mem[48][4]/q mem_reg[48][4]/Q -type DFF DFF
add mapped point mem[48][3]/q mem_reg[48][3]/Q -type DFF DFF
add mapped point mem[48][2]/q mem_reg[48][2]/Q -type DFF DFF
add mapped point mem[48][0]/q mem_reg[48][0]/Q -type DFF DFF
add mapped point mem[35][6]/q mem_reg[35][6]/Q -type DFF DFF
add mapped point mem[35][5]/q mem_reg[35][5]/Q -type DFF DFF
add mapped point mem[35][4]/q mem_reg[35][4]/Q -type DFF DFF
add mapped point mem[35][2]/q mem_reg[35][2]/Q -type DFF DFF
add mapped point mem[35][1]/q mem_reg[35][1]/Q -type DFF DFF
add mapped point mem[35][0]/q mem_reg[35][0]/Q -type DFF DFF
add mapped point mem[34][6]/q mem_reg[34][6]/Q -type DFF DFF
add mapped point mem[34][4]/q mem_reg[34][4]/Q -type DFF DFF
add mapped point mem[34][2]/q mem_reg[34][2]/Q -type DFF DFF
add mapped point mem[34][1]/q mem_reg[34][1]/Q -type DFF DFF
add mapped point mem[34][0]/q mem_reg[34][0]/Q -type DFF DFF
add mapped point mem[33][6]/q mem_reg[33][6]/Q -type DFF DFF
add mapped point mem[33][5]/q mem_reg[33][5]/Q -type DFF DFF
add mapped point mem[33][4]/q mem_reg[33][4]/Q -type DFF DFF
add mapped point mem[33][2]/q mem_reg[33][2]/Q -type DFF DFF
add mapped point mem[33][0]/q mem_reg[33][0]/Q -type DFF DFF
add mapped point mem[32][6]/q mem_reg[32][6]/Q -type DFF DFF
add mapped point mem[32][4]/q mem_reg[32][4]/Q -type DFF DFF
add mapped point mem[25][2]/q mem_reg[25][2]/Q -type DFF DFF
add mapped point mem[32][2]/q mem_reg[32][2]/Q -type DFF DFF
add mapped point mem[32][1]/q mem_reg[32][1]/Q -type DFF DFF
add mapped point mem[32][0]/q mem_reg[32][0]/Q -type DFF DFF
add mapped point mem[18][7]/q mem_reg[18][7]/Q -type DFF DFF
add mapped point mem[18][6]/q mem_reg[18][6]/Q -type DFF DFF
add mapped point mem[18][5]/q mem_reg[18][5]/Q -type DFF DFF
add mapped point mem[18][4]/q mem_reg[18][4]/Q -type DFF DFF
add mapped point mem[18][2]/q mem_reg[18][2]/Q -type DFF DFF
add mapped point mem[18][1]/q mem_reg[18][1]/Q -type DFF DFF
add mapped point mem[18][0]/q mem_reg[18][0]/Q -type DFF DFF
add mapped point mem[16][7]/q mem_reg[16][7]/Q -type DFF DFF
add mapped point mem[16][6]/q mem_reg[16][6]/Q -type DFF DFF
add mapped point mem[16][5]/q mem_reg[16][5]/Q -type DFF DFF
add mapped point mem[16][4]/q mem_reg[16][4]/Q -type DFF DFF
add mapped point mem[3][1]/q mem_reg[3][1]/Q -type DFF DFF
add mapped point mem[3][0]/q mem_reg[3][0]/Q -type DFF DFF
add mapped point mem[19][4]/q mem_reg[19][4]/Q -type DFF DFF
add mapped point mem[1][5]/q mem_reg[1][5]/Q -type DFF DFF
add mapped point mem[3][7]/q mem_reg[3][7]/Q -type DFF DFF
add mapped point mem[1][6]/q mem_reg[1][6]/Q -type DFF DFF
add mapped point mem[19][3]/q mem_reg[19][3]/Q -type DFF DFF
add mapped point mem[1][7]/q mem_reg[1][7]/Q -type DFF DFF
add mapped point mem[17][7]/q mem_reg[17][7]/Q -type DFF DFF
add mapped point mem[17][3]/q mem_reg[17][3]/Q -type DFF DFF
add mapped point mem[17][0]/q mem_reg[17][0]/Q -type DFF DFF
add mapped point mem[19][5]/q mem_reg[19][5]/Q -type DFF DFF
add mapped point mem[19][7]/q mem_reg[19][7]/Q -type DFF DFF
add mapped point mem[3][5]/q mem_reg[3][5]/Q -type DFF DFF
add mapped point mem[3][3]/q mem_reg[3][3]/Q -type DFF DFF
add mapped point mem[17][2]/q mem_reg[17][2]/Q -type DFF DFF
add mapped point mem[17][1]/q mem_reg[17][1]/Q -type DFF DFF
add mapped point mem[17][4]/q mem_reg[17][4]/Q -type DFF DFF
add mapped point mem[17][5]/q mem_reg[17][5]/Q -type DFF DFF
add mapped point mem[17][6]/q mem_reg[17][6]/Q -type DFF DFF
add mapped point mem[19][2]/q mem_reg[19][2]/Q -type DFF DFF
add mapped point mem[19][0]/q mem_reg[19][0]/Q -type DFF DFF
add mapped point mem[19][1]/q mem_reg[19][1]/Q -type DFF DFF
add mapped point mem[1][0]/q mem_reg[1][0]/Q -type DFF DFF
add mapped point mem[1][1]/q mem_reg[1][1]/Q -type DFF DFF
add mapped point mem[1][3]/q mem_reg[1][3]/Q -type DFF DFF
add mapped point mem[1][4]/q mem_reg[1][4]/Q -type DFF DFF
add mapped point mem[1][2]/q mem_reg[1][2]/Q -type DFF DFF
add mapped point mem[3][2]/q mem_reg[3][2]/Q -type DFF DFF
add mapped point mem[3][4]/q mem_reg[3][4]/Q -type DFF DFF
add mapped point mem[3][6]/q mem_reg[3][6]/Q -type DFF DFF
add mapped point mem[19][6]/q mem_reg[19][6]/Q -type DFF DFF
add mapped point raddr[0]/q raddr_reg[0]/Q -type DFF DFF
add mapped point raddr[5]/q raddr_reg[5]/Q -type DFF DFF
add mapped point raddr[4]/q raddr_reg[4]/Q -type DFF DFF
add mapped point raddr[2]/q raddr_reg[2]/Q -type DFF DFF
add mapped point raddr[1]/q raddr_reg[1]/Q -type DFF DFF
add mapped point raddr[3]/q raddr_reg[3]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
