
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  2 2025 09:51:20 IST (May  2 2025 04:21:20 UTC)

// Verification Directory fv/sram_sp_16384d_36w_16m_8b 

module sram_sp_16384d_36w_16m_8b(CLK, CEN, GWEN, A, D, WEN, Q, ijtag_tck, 
                                 ijtag_reset, ijtag_ce, ijtag_se, ijtag_ue, 
                                 ijtag_sel, ijtag_si, ijtag_so);
  input CLK, CEN, GWEN;
  input [13:0] A;
  input [35:0] D, WEN;
  output [35:0] Q;
  wire CLK, CEN, GWEN;
  wire [13:0] A;
  wire [35:0] D, WEN;
  wire [35:0] Q;
  input ijtag_tck, ijtag_reset, ijtag_ce, ijtag_se, ijtag_ue, ijtag_sel, 
        ijtag_si;
  wire ijtag_tck, ijtag_reset, ijtag_ce, ijtag_se, ijtag_ue, ijtag_sel, 
       ijtag_si;
  output ijtag_so;
  wire ijtag_so;

  wire [35:0] q0;
  wire [35:0] q1;
  wire csb0, csb1, web0, web1;
  wire [2:1] BIST_SETUP_ts1;
  wire [0:0] toBist, bistEn;
  wire [12:0] u_bank0_my_sram_interface_inst_A, 
              u_bank1_my_sram_interface_inst_A;
  wire sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_mbist_inst_so, 
       sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst_so, 
       sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst_to_select, 
       ijtag_to_tck, ijtag_to_ue, ijtag_to_reset, ijtag_to_se, ijtag_to_ce, 
       ijtag_to_sel, ltest_to_en, ltest_to_mem_bypass_en, ltest_to_scan_en, 
       ltest_to_mcp_bounding_en, BIST_HOLD, BIST_SETUP, BIST_SELECT_TEST_DATA, 
       to_controllers_tck, mcp_bounding_to_en, scan_to_en, memory_bypass_to_en, 
       ltest_to_en_ts1, BIST_ALGO_MODE0, BIST_ALGO_MODE1, ENABLE_MEM_RESET, 
       REDUCED_ADDRESS_COUNT, BIST_ASYNC_RESET, MEM0_BIST_COLLAR_SI, 
       MEM1_BIST_COLLAR_SI, MBISTPG_SO, BIST_SO, BIST_SO_ts1, MBISTPG_DONE, 
       MBISTPG_GO, BIST_GO, BIST_GO_ts1, BIST_DIAG_EN, BIST_COLLAR_DIAG_EN, 
       FL_CNT_MODE0, FL_CNT_MODE1, BIST_WRITEENABLE, BIST_OUTPUTENABLE, 
       BIST_SELECT, BIST_CMP, INCLUDE_MEM_RESULTS_REG, BIST_COL_ADD, 
       BIST_COL_ADD_ts1, BIST_COL_ADD_ts2, BIST_COL_ADD_ts3, BIST_COL_ADD_ts4, 
       BIST_COL_ADD_ts5, BIST_ROW_ADD, BIST_ROW_ADD_ts1, BIST_ROW_ADD_ts2, 
       BIST_ROW_ADD_ts3, BIST_ROW_ADD_ts4, BIST_ROW_ADD_ts5, BIST_ROW_ADD_ts6, 
       BIST_COLLAR_EN0, BIST_COLLAR_EN1, BIST_RUN_TO_COLLAR0, 
       BIST_RUN_TO_COLLAR1, to_interfaces_tck, BIST_TESTDATA_SELECT_TO_COLLAR, 
       BIST_ON_TO_COLLAR, BIST_WRITE_DATA, BIST_WRITE_DATA_ts1, 
       BIST_EXPECT_DATA, BIST_EXPECT_DATA_ts1, BIST_SHIFT_COLLAR, 
       BIST_COLLAR_SETUP, BIST_CLEAR_DEFAULT, BIST_CLEAR, BIST_COLLAR_HOLD, 
       FREEZE_STOP_ERROR, ERROR_CNT_ZERO, MBISTPG_RESET_REG_SETUP2, WEB, 
       WEB_ts1, CSB, CSB_ts1, 
       sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_bap_inst_so;
  wire [35:0] u_bank0_my_sram_interface_inst_I, 
              u_bank1_my_sram_interface_inst_I;
  
  SPRAM_8192x36 u_bank0_my_sram(.CE (CLK), .OEB (1'b0), .CSB (CSB),
       .WEB (WEB), .A (u_bank0_my_sram_interface_inst_A), .I (u_bank0_my_sram_interface_inst_I), .O (q0));
  SPRAM_8192x36 u_bank1_my_sram(.CE (CLK), .OEB (1'b0), .CSB (CSB_ts1),
       .WEB (WEB_ts1), .A (u_bank1_my_sram_interface_inst_A), .I (u_bank1_my_sram_interface_inst_I), .O (q1));
  CLKMX2X6 g1049__2398(.A (q0[6]), .B (q1[6]), .S0 (A[13]), .Y (Q[6]));
  NAND2BX4 g1050__5107(.AN (csb1), .B (GWEN), .Y (web1));
  CLKMX2X6 g1051__6260(.A (q0[29]), .B (q1[29]), .S0 (A[13]), .Y
       (Q[29]));
  CLKMX2X6 g1052__4319(.A (q0[22]), .B (q1[22]), .S0 (A[13]), .Y
       (Q[22]));
  CLKMX2X6 g1053__8428(.A (q0[9]), .B (q1[9]), .S0 (A[13]), .Y (Q[9]));
  CLKMX2X6 g1054__5526(.A (q0[8]), .B (q1[8]), .S0 (A[13]), .Y (Q[8]));
  CLKMX2X6 g1055__6783(.A (q0[7]), .B (q1[7]), .S0 (A[13]), .Y (Q[7]));
  CLKMX2X6 g1056__3680(.A (q0[28]), .B (q1[28]), .S0 (A[13]), .Y
       (Q[28]));
  CLKMX2X6 g1057__1617(.A (q0[21]), .B (q1[21]), .S0 (A[13]), .Y
       (Q[21]));
  NAND2BX4 g1058__2802(.AN (csb0), .B (GWEN), .Y (web0));
  CLKMX2X6 g1059__1705(.A (q0[20]), .B (q1[20]), .S0 (A[13]), .Y
       (Q[20]));
  CLKMX2X6 g1060__5122(.A (q0[5]), .B (q1[5]), .S0 (A[13]), .Y (Q[5]));
  CLKMX2X6 g1061__8246(.A (q0[4]), .B (q1[4]), .S0 (A[13]), .Y (Q[4]));
  CLKMX2X6 g1062__7098(.A (q0[35]), .B (q1[35]), .S0 (A[13]), .Y
       (Q[35]));
  CLKMX2X6 g1063__6131(.A (q0[27]), .B (q1[27]), .S0 (A[13]), .Y
       (Q[27]));
  CLKMX2X6 g1064__1881(.A (q0[19]), .B (q1[19]), .S0 (A[13]), .Y
       (Q[19]));
  CLKMX2X6 g1065__5115(.A (q0[3]), .B (q1[3]), .S0 (A[13]), .Y (Q[3]));
  CLKMX2X6 g1066__7482(.A (q0[2]), .B (q1[2]), .S0 (A[13]), .Y (Q[2]));
  CLKMX2X6 g1067__4733(.A (q0[18]), .B (q1[18]), .S0 (A[13]), .Y
       (Q[18]));
  CLKMX2X6 g1068__6161(.A (q0[15]), .B (q1[15]), .S0 (A[13]), .Y
       (Q[15]));
  CLKMX2X6 g1069__9315(.A (q0[32]), .B (q1[32]), .S0 (A[13]), .Y
       (Q[32]));
  CLKMX2X6 g1070__9945(.A (q0[0]), .B (q1[0]), .S0 (A[13]), .Y (Q[0]));
  CLKMX2X6 g1071__2883(.A (q0[31]), .B (q1[31]), .S0 (A[13]), .Y
       (Q[31]));
  CLKMX2X6 g1072__2346(.A (q0[26]), .B (q1[26]), .S0 (A[13]), .Y
       (Q[26]));
  CLKMX2X6 g1073__1666(.A (q0[17]), .B (q1[17]), .S0 (A[13]), .Y
       (Q[17]));
  CLKMX2X6 g1074__7410(.A (q0[34]), .B (q1[34]), .S0 (A[13]), .Y
       (Q[34]));
  CLKMX2X6 g1075__6417(.A (q0[33]), .B (q1[33]), .S0 (A[13]), .Y
       (Q[33]));
  CLKMX2X6 g1076__5477(.A (q0[16]), .B (q1[16]), .S0 (A[13]), .Y
       (Q[16]));
  CLKMX2X6 g1077__2398(.A (q0[1]), .B (q1[1]), .S0 (A[13]), .Y (Q[1]));
  CLKMX2X6 g1078__5107(.A (q0[30]), .B (q1[30]), .S0 (A[13]), .Y
       (Q[30]));
  CLKMX2X6 g1079__6260(.A (q0[25]), .B (q1[25]), .S0 (A[13]), .Y
       (Q[25]));
  CLKMX2X6 g1080__4319(.A (q0[14]), .B (q1[14]), .S0 (A[13]), .Y
       (Q[14]));
  CLKMX2X6 g1081__8428(.A (q0[24]), .B (q1[24]), .S0 (A[13]), .Y
       (Q[24]));
  CLKMX2X6 g1082__5526(.A (q0[13]), .B (q1[13]), .S0 (A[13]), .Y
       (Q[13]));
  CLKMX2X6 g1083__6783(.A (q0[12]), .B (q1[12]), .S0 (A[13]), .Y
       (Q[12]));
  CLKMX2X6 g1084__3680(.A (q0[23]), .B (q1[23]), .S0 (A[13]), .Y
       (Q[23]));
  CLKMX2X6 g1085__1617(.A (q0[11]), .B (q1[11]), .S0 (A[13]), .Y
       (Q[11]));
  CLKMX2X6 g1086__2802(.A (q0[10]), .B (q1[10]), .S0 (A[13]), .Y
       (Q[10]));
  NAND2BX4 g1087__1705(.AN (CEN), .B (A[13]), .Y (csb1));
  OR2X2 g1088__5122(.A (A[13]), .B (CEN), .Y (csb0));

  sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_1 sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst(
      .ijtag_reset(ijtag_reset), .ijtag_sel(ijtag_sel), .ijtag_si(ijtag_si), .ijtag_ce(ijtag_ce), 
      .ijtag_se(ijtag_se), .ijtag_ue(ijtag_ue), .ijtag_tck(ijtag_tck), .ijtag_so(ijtag_so), 
      .ijtag_from_so(sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_mbist_inst_so), 
      .ltest_si(1'b0), .ltest_scan_en(1'b0), .ltest_en(1'b0), .ltest_clk(1'b0), 
      .ltest_mem_bypass_en(1'b1), .ltest_mcp_bounding_en(1'b0), .ltest_occ_en(1'b0), 
      .ltest_async_set_reset_static_disable(1'b0), .ltest_static_clock_control_mode(1'b0), 
      .ltest_clock_sequence({1'b0, 1'b0}), .ijtag_to_tck(ijtag_to_tck), .ijtag_to_reset(ijtag_to_reset), 
      .ijtag_to_si(sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst_so), .ijtag_to_ce(ijtag_to_ce), 
      .ijtag_to_se(ijtag_to_se), .ijtag_to_ue(ijtag_to_ue), .ltest_so(), .ltest_to_en(ltest_to_en), 
      .ltest_to_mem_bypass_en(ltest_to_mem_bypass_en), .ltest_to_mcp_bounding_en(ltest_to_mcp_bounding_en), 
      .ltest_to_scan_en(ltest_to_scan_en), .ijtag_to_sel(sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst_to_select)
  );

  sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_2 sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_mbist_inst(
      .ijtag_reset(ijtag_to_reset), .ijtag_sel(sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst_to_select), 
      .ijtag_si(sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst_so), .ijtag_ce(ijtag_to_ce), 
      .ijtag_se(ijtag_to_se), .ijtag_ue(ijtag_to_ue), .ijtag_tck(ijtag_to_tck), 
      .ijtag_so(sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_mbist_inst_so), .ijtag_from_so(sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_bap_inst_so), 
      .ijtag_to_sel(ijtag_to_sel)
  );

  sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_bap sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_bap_inst(
      .reset(ijtag_to_reset), .ijtag_select(ijtag_to_sel), .si(sram_sp_16384d_36w_16m_8b_rtl_tessent_sib_sti_inst_so), 
      .capture_en(ijtag_to_ce), .shift_en(ijtag_to_se), .shift_en_R(), .update_en(ijtag_to_ue), 
      .tck(ijtag_to_tck), .to_interfaces_tck(to_interfaces_tck), .to_controllers_tck(to_controllers_tck), 
      .mcp_bounding_en(ltest_to_mcp_bounding_en), .mcp_bounding_to_en(mcp_bounding_to_en), 
      .scan_en(ltest_to_scan_en), .scan_to_en(scan_to_en), .memory_bypass_en(ltest_to_mem_bypass_en), 
      .memory_bypass_to_en(memory_bypass_to_en), .ltest_en(ltest_to_en), .ltest_to_en(ltest_to_en_ts1), 
      .BIST_HOLD(BIST_HOLD), .ENABLE_MEM_RESET(ENABLE_MEM_RESET), .REDUCED_ADDRESS_COUNT(REDUCED_ADDRESS_COUNT), 
      .BIST_SELECT_TEST_DATA(BIST_SELECT_TEST_DATA), .BIST_ALGO_MODE0(BIST_ALGO_MODE0), 
      .BIST_ALGO_MODE1(BIST_ALGO_MODE1), .BIST_DIAG_EN(BIST_DIAG_EN), .BIST_ASYNC_RESET(BIST_ASYNC_RESET), 
      .FL_CNT_MODE0(FL_CNT_MODE0), .FL_CNT_MODE1(FL_CNT_MODE1), .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
      .CHAIN_BYPASS_EN(), .TCK_MODE(), .BIST_SETUP({BIST_SETUP_ts1[2:1], 
      BIST_SETUP}), .MBISTPG_GO(MBISTPG_GO), .MBISTPG_DONE(MBISTPG_DONE), .bistEn(bistEn), 
      .toBist(toBist), .fromBist(MBISTPG_SO), .so(sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_bap_inst_so)
  );

  sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_c1_controller sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_c1_controller_inst(
      .MBISTPG_ALGO_MODE({BIST_ALGO_MODE1, BIST_ALGO_MODE0}), .MBISTPG_MEM_RST(ENABLE_MEM_RESET), 
      .MBISTPG_REDUCED_ADDR_CNT_EN(REDUCED_ADDRESS_COUNT), .MEM_BYPASS_EN(memory_bypass_to_en), 
      .MCP_BOUNDING_EN(mcp_bounding_to_en), .MEM0_BIST_COLLAR_SO(BIST_SO), .MEM1_BIST_COLLAR_SO(BIST_SO_ts1), 
      .FL_CNT_MODE({FL_CNT_MODE1, FL_CNT_MODE0}), .BIST_COLLAR_GO({
      BIST_GO_ts1, BIST_GO}), .MBISTPG_DIAG_EN(BIST_DIAG_EN), .BIST_CLK(CLK), .BIST_SI(toBist), 
      .BIST_HOLD(BIST_HOLD), .BIST_SETUP2(BIST_SETUP_ts1[2]), .BIST_SETUP({
      BIST_SETUP_ts1[1], BIST_SETUP}), .MBISTPG_TESTDATA_SELECT(BIST_SELECT_TEST_DATA), 
      .TCK(to_controllers_tck), .MBISTPG_EN(bistEn), .MBISTPG_ASYNC_RESETN(BIST_ASYNC_RESET), 
      .LV_TM(ltest_to_en_ts1), .MBISTPG_RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), 
      .BIST_COL_ADD({BIST_COL_ADD_ts5, BIST_COL_ADD_ts4, BIST_COL_ADD_ts3, 
      BIST_COL_ADD_ts2, BIST_COL_ADD_ts1, BIST_COL_ADD}), .BIST_ROW_ADD({
      BIST_ROW_ADD_ts6, BIST_ROW_ADD_ts5, BIST_ROW_ADD_ts4, BIST_ROW_ADD_ts3, 
      BIST_ROW_ADD_ts2, BIST_ROW_ADD_ts1, BIST_ROW_ADD}), .BIST_WRITE_DATA({
      BIST_WRITE_DATA_ts1, BIST_WRITE_DATA}), .BIST_EXPECT_DATA({
      BIST_EXPECT_DATA_ts1, BIST_EXPECT_DATA}), .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), 
      .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), .MEM0_BIST_COLLAR_SI(MEM0_BIST_COLLAR_SI), 
      .MEM1_BIST_COLLAR_SI(MEM1_BIST_COLLAR_SI), .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), 
      .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), 
      .ERROR_CNT_ZERO(ERROR_CNT_ZERO), .BIST_COLLAR_DIAG_EN(BIST_COLLAR_DIAG_EN), 
      .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), .MBISTPG_SO(MBISTPG_SO), 
      .BIST_WRITEENABLE(BIST_WRITEENABLE), .BIST_OUTPUTENABLE(BIST_OUTPUTENABLE), 
      .BIST_SELECT(BIST_SELECT), .BIST_CMP(BIST_CMP), .BIST_COLLAR_EN0(BIST_COLLAR_EN0), 
      .BIST_RUN_TO_COLLAR0(BIST_RUN_TO_COLLAR0), .BIST_COLLAR_EN1(BIST_COLLAR_EN1), 
      .BIST_RUN_TO_COLLAR1(BIST_RUN_TO_COLLAR1), .MBISTPG_GO(MBISTPG_GO), .MBISTPG_DONE(MBISTPG_DONE), 
      .BIST_ON_TO_COLLAR(BIST_ON_TO_COLLAR)
  );

  sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_c1_interface_m1 u_bank0_my_sram_interface_inst(
      .WEB_IN(web0), .CSB_IN(csb0), .A_IN(A[12:0]), .I_IN(D[35:0]), .O(q0), .TCK(to_interfaces_tck), 
      .BIST_CMP(BIST_CMP), .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), .BIST_WRITEENABLE(BIST_WRITEENABLE), 
      .BIST_OUTPUTENABLE(BIST_OUTPUTENABLE), .BIST_SELECT(BIST_SELECT), .BIST_COL_ADD({
      BIST_COL_ADD_ts5, BIST_COL_ADD_ts4, BIST_COL_ADD_ts3, BIST_COL_ADD_ts2, 
      BIST_COL_ADD_ts1, BIST_COL_ADD}), .BIST_ROW_ADD({BIST_ROW_ADD_ts6, 
      BIST_ROW_ADD_ts5, BIST_ROW_ADD_ts4, BIST_ROW_ADD_ts3, BIST_ROW_ADD_ts2, 
      BIST_ROW_ADD_ts1, BIST_ROW_ADD}), .BIST_WRITE_DATA({BIST_WRITE_DATA_ts1, 
      BIST_WRITE_DATA}), .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), 
      .MEM_BYPASS_EN(memory_bypass_to_en), .SCAN_SHIFT_EN(scan_to_en), .MCP_BOUNDING_EN(mcp_bounding_to_en), 
      .BIST_ON(BIST_ON_TO_COLLAR), .BIST_RUN(BIST_RUN_TO_COLLAR0), .BIST_ASYNC_RESETN(BIST_ASYNC_RESET), 
      .BIST_CLK(CLK), .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), .BIST_EXPECT_DATA({
      BIST_EXPECT_DATA_ts1, BIST_EXPECT_DATA}), .BIST_SI(MEM0_BIST_COLLAR_SI), .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), 
      .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), .BIST_DIAG_EN(BIST_COLLAR_DIAG_EN), 
      .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), .BIST_SETUP0(BIST_SETUP), 
      .LV_TM(ltest_to_en_ts1), .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), .BIST_COLLAR_EN(BIST_COLLAR_EN0), 
      .RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), .ERROR_CNT_ZERO(ERROR_CNT_ZERO), 
      .WEB(WEB), .CSB(CSB), .A(u_bank0_my_sram_interface_inst_A), .I(u_bank0_my_sram_interface_inst_I), 
      .SCAN_OBS_FLOPS(), .BIST_SO(BIST_SO), .BIST_GO(BIST_GO)
  );

  sram_sp_16384d_36w_16m_8b_rtl_tessent_mbist_c1_interface_m2 u_bank1_my_sram_interface_inst(
      .WEB_IN(web1), .CSB_IN(csb1), .A_IN(A[12:0]), .I_IN(D[35:0]), .O(q1), .TCK(to_interfaces_tck), 
      .BIST_CMP(BIST_CMP), .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), .BIST_WRITEENABLE(BIST_WRITEENABLE), 
      .BIST_OUTPUTENABLE(BIST_OUTPUTENABLE), .BIST_SELECT(BIST_SELECT), .BIST_COL_ADD({
      BIST_COL_ADD_ts5, BIST_COL_ADD_ts4, BIST_COL_ADD_ts3, BIST_COL_ADD_ts2, 
      BIST_COL_ADD_ts1, BIST_COL_ADD}), .BIST_ROW_ADD({BIST_ROW_ADD_ts6, 
      BIST_ROW_ADD_ts5, BIST_ROW_ADD_ts4, BIST_ROW_ADD_ts3, BIST_ROW_ADD_ts2, 
      BIST_ROW_ADD_ts1, BIST_ROW_ADD}), .BIST_WRITE_DATA({BIST_WRITE_DATA_ts1, 
      BIST_WRITE_DATA}), .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), 
      .MEM_BYPASS_EN(memory_bypass_to_en), .SCAN_SHIFT_EN(scan_to_en), .MCP_BOUNDING_EN(mcp_bounding_to_en), 
      .BIST_ON(BIST_ON_TO_COLLAR), .BIST_RUN(BIST_RUN_TO_COLLAR1), .BIST_ASYNC_RESETN(BIST_ASYNC_RESET), 
      .BIST_CLK(CLK), .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), .BIST_EXPECT_DATA({
      BIST_EXPECT_DATA_ts1, BIST_EXPECT_DATA}), .BIST_SI(MEM1_BIST_COLLAR_SI), .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), 
      .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), .BIST_DIAG_EN(BIST_COLLAR_DIAG_EN), 
      .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), .BIST_SETUP0(BIST_SETUP), 
      .LV_TM(ltest_to_en_ts1), .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), .BIST_COLLAR_EN(BIST_COLLAR_EN1), 
      .RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), .ERROR_CNT_ZERO(ERROR_CNT_ZERO), 
      .WEB(WEB_ts1), .CSB(CSB_ts1), .A(u_bank1_my_sram_interface_inst_A), .I(u_bank1_my_sram_interface_inst_I), 
      .SCAN_OBS_FLOPS(), .BIST_SO(BIST_SO_ts1), .BIST_GO(BIST_GO_ts1)
  );
endmodule

