
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 18:03:15 IST (Jun 13 2025 12:33:15 UTC)

// Verification Directory  

module clk_wiz_clk_wiz(clk_out1, clk_out2, clk_out3, reset, locked,
     clk_in1);
  input reset, clk_in1;
  output clk_out1, clk_out2, clk_out3, locked;
  wire reset, clk_in1;
  wire clk_out1, clk_out2, clk_out3, locked;
  wire [15:0] do_unused;
  wire clk_in1_clk_wiz, clk_out1_clk_wiz, clk_out2_clk_wiz,
       clk_out3_clk_wiz, clkfbout_buf_clk_wiz, clkfbout_clk_wiz,
       clkfboutb_unused, clkfbstopped_unused;
  wire clkinstopped_unused, clkout0b_unused, clkout1b_unused,
       clkout2b_unused, clkout3_unused, clkout3b_unused,
       clkout4_unused, clkout5_unused;
  wire clkout6_unused, drdy_unused, locked_int, psdone_unused;
  BUFG clkf_buf(.O (clkfbout_buf_clk_wiz), .I (clkfbout_clk_wiz));
  IBUF clkin1_ibufg(.O (clk_in1_clk_wiz), .I (clk_in1));
  BUFG clkout1_buf(.O (clk_out1), .I (clk_out1_clk_wiz));
  BUFG clkout2_buf(.O (clk_out2), .I (clk_out2_clk_wiz));
  BUFG clkout3_buf(.O (clk_out3), .I (clk_out3_clk_wiz));
  MMCME2_ADV_BANDWIDTHx4f5054494d495a4544_CLKOUT4_CASCADEx46414c5345_COMPENSATIONx5a484f4c44_STARTUP_WAITx46414c5345_DIVCLK_DIVIDE1_CLKFBOUT_MULT_Fx10p000000_CLKFBOUT_PHASEx0p000000_CLKFBOUT_USE_FINE_PSx46414c5345_CLKOUT0_DIVIDE_Fx20p000000_CLKOUT0_PHASEx0p000000_CLKOUT0_DUTY_CYCLEx0p500000_CLKOUT0_USE_FINE_PSx46414c5345_CLKOUT1_DIVIDE40_CLKOUT1_PHASEx0p000000_CLKOUT1_DUTY_CYCLEx0p500000_CLKOUT1_USE_FINE_PSx46414c5345_CLKOUT2_DIVIDE100_CLKOUT2_PHASEx0p000000_CLKOUT2_DUTY_CYCLEx0p500000_CLKOUT2_USE_FINE_PSx46414c5345_CLKIN1_PERIODx10p000000
       mmcm_adv_inst(.CLKFBOUT (clkfbout_clk_wiz), .CLKFBOUTB
       (clkfboutb_unused), .CLKOUT0 (clk_out1_clk_wiz), .CLKOUT0B
       (clkout0b_unused), .CLKOUT1 (clk_out2_clk_wiz), .CLKOUT1B
       (clkout1b_unused), .CLKOUT2 (clk_out3_clk_wiz), .CLKOUT2B
       (clkout2b_unused), .CLKOUT3 (clkout3_unused), .CLKOUT3B
       (clkout3b_unused), .CLKOUT4 (clkout4_unused), .CLKOUT5
       (clkout5_unused), .CLKOUT6 (clkout6_unused), .CLKFBIN
       (clkfbout_buf_clk_wiz), .CLKIN1 (clk_in1_clk_wiz), .CLKIN2
       (1'b0), .CLKINSEL (1'b1), .DADDR (7'b0), .DCLK (1'b0), .DEN
       (1'b0), .DI (16'b0), .DO (do_unused), .DRDY (drdy_unused), .DWE
       (1'b0), .PSCLK (1'b0), .PSEN (1'b0), .PSINCDEC (1'b0), .PSDONE
       (psdone_unused), .LOCKED (locked_int), .CLKINSTOPPED
       (clkinstopped_unused), .CLKFBSTOPPED (clkfbstopped_unused),
       .PWRDWN (1'b0), .RST (reset));
endmodule

