
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 18:03:15 IST (Jun 13 2025 12:33:15 UTC)

// Verification Directory  

module kbtop(PS2C, PS2D, CLK1, RST, kb_ascii_out, kb_data_valid);
  input CLK1, RST;
  output [7:0] kb_ascii_out;
  output kb_data_valid;
  inout PS2C, PS2D;
  wire CLK1, RST;
  wire [7:0] kb_ascii_out;
  wire kb_data_valid;
  wire PS2C, PS2D;
  wire [7:0] rx_data;
  wire [7:0] tx_data;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, kbass_ascii_ready,
       kbass_key_up, kbass_shift_key, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, ps2_busy, ps2_err, ps2_read;
  wire ps2_write;
  assign ps2_write = 1'b0;
  ps2interface ps2inface(.ps2_clk (PS2C), .ps2_data (PS2D), .clk
       (CLK1), .rst (RST), .rx_data (rx_data), .tx_data (tx_data),
       .write (ps2_write), .read (ps2_read), .err (ps2_err), .busy
       (ps2_busy));
  INV_X1 g6093(.A (RST), .ZN (n_222));
  DFFR_X2 kbass_ascii_ready_reg(.RN (n_222), .CK (CLK1), .D (n_34), .Q
       (kbass_ascii_ready), .QN (UNCONNECTED));
  DFFR_X2 \kbass_ascii_reg[0] (.RN (n_222), .CK (CLK1), .D (n_215), .Q
       (kb_ascii_out[0]), .QN (UNCONNECTED0));
  DFFR_X2 \kbass_ascii_reg[1] (.RN (n_222), .CK (CLK1), .D (n_218), .Q
       (kb_ascii_out[1]), .QN (UNCONNECTED1));
  DFFR_X2 \kbass_ascii_reg[2] (.RN (n_222), .CK (CLK1), .D (n_219), .Q
       (kb_ascii_out[2]), .QN (UNCONNECTED2));
  DFFR_X2 \kbass_ascii_reg[3] (.RN (n_222), .CK (CLK1), .D (n_209), .Q
       (kb_ascii_out[3]), .QN (UNCONNECTED3));
  DFFR_X2 \kbass_ascii_reg[4] (.RN (n_222), .CK (CLK1), .D (n_217), .Q
       (kb_ascii_out[4]), .QN (UNCONNECTED4));
  DFFR_X2 \kbass_ascii_reg[5] (.RN (n_222), .CK (CLK1), .D (n_213), .Q
       (kb_ascii_out[5]), .QN (UNCONNECTED5));
  DFFR_X2 \kbass_ascii_reg[6] (.RN (n_222), .CK (CLK1), .D (n_221), .Q
       (kb_ascii_out[6]), .QN (UNCONNECTED6));
  DFFR_X2 \kbass_ascii_reg[7] (.RN (n_222), .CK (CLK1), .D (n_212), .Q
       (kb_ascii_out[7]), .QN (UNCONNECTED7));
  DFFR_X2 kbass_ascii_valid_reg(.RN (n_222), .CK (CLK1), .D (n_152), .Q
       (kb_data_valid), .QN (UNCONNECTED8));
  DFFR_X2 kbass_key_up_reg(.RN (n_222), .CK (CLK1), .D (n_191), .Q
       (kbass_key_up), .QN (UNCONNECTED9));
  DFFR_X2 kbass_shift_key_reg(.RN (n_222), .CK (CLK1), .D (n_201), .Q
       (kbass_shift_key), .QN (n_0));
  MUX2_X2 g10339__2398(.A (kb_ascii_out[6]), .B (n_220), .S (ps2_read),
       .Z (n_221));
  NAND3_X1 g10343__5107(.A1 (n_216), .A2 (n_97), .A3 (n_9), .ZN
       (n_220));
  MUX2_X2 g10344__6260(.A (kb_ascii_out[2]), .B (n_214), .S (ps2_read),
       .Z (n_219));
  MUX2_X2 g10347__4319(.A (kb_ascii_out[1]), .B (n_211), .S (ps2_read),
       .Z (n_218));
  MUX2_X2 g10348__8428(.A (kb_ascii_out[4]), .B (n_210), .S (ps2_read),
       .Z (n_217));
  NOR4_X1 g10350__5526(.A1 (n_202), .A2 (n_131), .A3 (n_165), .A4
       (n_76), .ZN (n_216));
  MUX2_X2 g10351__6783(.A (kb_ascii_out[0]), .B (n_208), .S (ps2_read),
       .Z (n_215));
  OR3_X2 g10353__3680(.A1 (n_205), .A2 (n_139), .A3 (n_127), .ZN
       (n_214));
  MUX2_X2 g10354__1617(.A (kb_ascii_out[5]), .B (n_207), .S (ps2_read),
       .Z (n_213));
  MUX2_X2 g10355__2802(.A (kb_ascii_out[7]), .B (n_204), .S (ps2_read),
       .Z (n_212));
  NAND2_X1 g10356__1705(.A1 (n_206), .A2 (n_9), .ZN (n_211));
  OR4_X1 g10357__5122(.A1 (n_200), .A2 (n_148), .A3 (n_127), .A4
       (n_47), .ZN (n_210));
  MUX2_X2 g10358__8246(.A (kb_ascii_out[3]), .B (n_203), .S (ps2_read),
       .Z (n_209));
  OR3_X2 g10359__7098(.A1 (n_199), .A2 (n_148), .A3 (n_127), .ZN
       (n_208));
  OR4_X1 g10360__6131(.A1 (n_198), .A2 (n_164), .A3 (n_54), .A4 (n_47),
       .ZN (n_207));
  NOR4_X1 g10361__1881(.A1 (n_197), .A2 (n_149), .A3 (n_139), .A4
       (n_69), .ZN (n_206));
  NAND4_X1 g10362__5115(.A1 (n_193), .A2 (n_140), .A3 (n_151), .A4
       (n_150), .ZN (n_205));
  OR4_X1 g10363__7482(.A1 (n_196), .A2 (n_148), .A3 (n_160), .A4
       (n_165), .ZN (n_204));
  OR3_X2 g10365__4733(.A1 (n_195), .A2 (n_148), .A3 (n_149), .ZN
       (n_203));
  OAI211_X1 g10366__6161(.A (n_194), .B (n_159), .C1 (n_26), .C2 (n_8),
       .ZN (n_202));
  OAI221_X1 g10367__9315(.A (n_95), .B1 (n_185), .B2 (kbass_key_up),
       .C1 (n_181), .C2 (n_0), .ZN (n_201));
  OR4_X1 g10368__9945(.A1 (n_189), .A2 (n_114), .A3 (n_131), .A4
       (n_163), .ZN (n_200));
  NAND3_X1 g10369__2883(.A1 (n_192), .A2 (n_99), .A3 (n_130), .ZN
       (n_199));
  NAND4_X1 g10370__2346(.A1 (n_182), .A2 (n_104), .A3 (n_151), .A4
       (n_103), .ZN (n_198));
  NAND4_X1 g10371__1666(.A1 (n_184), .A2 (n_113), .A3 (n_129), .A4
       (n_150), .ZN (n_197));
  OR4_X1 g10372__7410(.A1 (n_178), .A2 (n_164), .A3 (n_128), .A4
       (n_136), .ZN (n_196));
  NAND4_X1 g10373__6417(.A1 (n_173), .A2 (n_183), .A3 (n_101), .A4
       (n_78), .ZN (n_195));
  AOI221_X1 g10374__5477(.A (n_188), .B1 (n_48), .B2 (n_4), .C1
       (n_100), .C2 (rx_data[0]), .ZN (n_194));
  AOI211_X1 g10375__2398(.A (n_177), .B (n_186), .C1 (n_67), .C2
       (n_29), .ZN (n_193));
  AOI221_X1 g10377__5107(.A (n_187), .B1 (n_63), .B2 (rx_data[0]), .C1
       (n_25), .C2 (n_12), .ZN (n_192));
  INV_X4 g10378(.A (n_190), .ZN (n_191));
  AOI22_X1 g10379__6260(.A1 (n_174), .A2 (rx_data[5]), .B1
       (kbass_key_up), .B2 (n_5), .ZN (n_190));
  NAND4_X1 g10380__4319(.A1 (n_134), .A2 (n_138), .A3 (n_156), .A4
       (n_166), .ZN (n_189));
  OAI221_X1 g10381__8428(.A (n_179), .B1 (n_66), .B2 (rx_data[4]), .C1
       (n_86), .C2 (rx_data[2]), .ZN (n_188));
  NAND4_X1 g10382__5526(.A1 (n_153), .A2 (n_180), .A3 (n_175), .A4
       (n_137), .ZN (n_187));
  OAI211_X1 g10383__6783(.A (n_117), .B (n_170), .C1 (n_66), .C2
       (n_15), .ZN (n_186));
  AOI22_X1 g10384__3680(.A1 (n_171), .A2 (n_4), .B1 (n_157), .B2 (n_7),
       .ZN (n_185));
  AOI211_X1 g10385__1617(.A (n_119), .B (n_172), .C1 (n_88), .C2
       (n_45), .ZN (n_184));
  AOI211_X1 g10386__2802(.A (n_132), .B (n_176), .C1 (n_12), .C2
       (n_36), .ZN (n_183));
  AOI211_X1 g10387__1705(.A (n_161), .B (n_168), .C1 (kbass_shift_key),
       .C2 (n_58), .ZN (n_182));
  AND4_X2 g10388__5122(.A1 (n_141), .A2 (n_90), .A3 (n_41), .A4 (n_26),
       .ZN (n_181));
  AOI222_X1 g10389__8246(.A1 (n_144), .A2 (rx_data[4]), .B1 (n_40), .B2
       (n_48), .C1 (n_120), .C2 (rx_data[6]), .ZN (n_180));
  AOI221_X1 g10390__7098(.A (n_169), .B1 (n_40), .B2 (n_29), .C1
       (n_50), .C2 (n_36), .ZN (n_179));
  OAI221_X1 g10391__6131(.A (n_167), .B1 (n_71), .B2 (n_49), .C1
       (n_77), .C2 (rx_data[2]), .ZN (n_178));
  OAI222_X1 g10392__1881(.A1 (n_135), .A2 (rx_data[6]), .B1 (n_102),
       .B2 (n_41), .C1 (n_126), .C2 (n_8), .ZN (n_177));
  OAI221_X1 g10393__5115(.A (n_162), .B1 (n_56), .B2 (rx_data[0]), .C1
       (n_71), .C2 (n_19), .ZN (n_176));
  AOI221_X1 g10394__7482(.A (n_142), .B1 (n_125), .B2 (n_12), .C1
       (n_45), .C2 (n_38), .ZN (n_175));
  NOR3_X1 g10395__4733(.A1 (n_146), .A2 (n_5), .A3 (rx_data[2]), .ZN
       (n_174));
  AOI221_X1 g10396__6161(.A (n_154), .B1 (n_51), .B2 (n_68), .C1
       (n_70), .C2 (n_7), .ZN (n_173));
  OAI221_X1 g10397__9315(.A (n_155), .B1 (n_112), .B2 (n_41), .C1
       (n_90), .C2 (n_37), .ZN (n_172));
  AND3_X4 g10398__9945(.A1 (n_141), .A2 (n_19), .A3 (n_6), .ZN (n_171));
  AOI222_X1 g10399__2883(.A1 (n_115), .A2 (n_38), .B1 (n_82), .B2
       (rx_data[0]), .C1 (n_89), .C2 (n_3), .ZN (n_170));
  OAI221_X1 g10400__2346(.A (n_147), .B1 (n_0), .B2 (n_116), .C1
       (n_43), .C2 (n_31), .ZN (n_169));
  OAI221_X1 g10401__1666(.A (n_158), .B1 (n_68), .B2 (n_17), .C1
       (n_86), .C2 (n_6), .ZN (n_168));
  AOI221_X1 g10402__7410(.A (n_133), .B1 (n_118), .B2 (n_15), .C1
       (n_70), .C2 (n_80), .ZN (n_167));
  AOI22_X1 g10403__6417(.A1 (n_0), .A2 (n_143), .B1 (n_45), .B2 (n_52),
       .ZN (n_166));
  OAI22_X1 g10405__5477(.A1 (n_107), .A2 (rx_data[3]), .B1 (n_105), .B2
       (n_3), .ZN (n_163));
  AOI21_X1 g10406__2398(.A (n_109), .B1 (n_124), .B2 (n_3), .ZN
       (n_162));
  OAI21_X1 g10407__5107(.A (n_111), .B1 (kbass_shift_key), .B2 (n_121),
       .ZN (n_161));
  OAI21_X1 g10408__6260(.A (n_81), .B1 (n_123), .B2 (rx_data[0]), .ZN
       (n_165));
  NAND2_X1 g10409__4319(.A1 (n_140), .A2 (n_75), .ZN (n_164));
  INV_X2 g10410(.A (n_159), .ZN (n_160));
  AOI22_X1 g10411__8428(.A1 (n_122), .A2 (n_3), .B1 (kbass_shift_key),
       .B2 (n_74), .ZN (n_158));
  NOR4_X1 g10412__5526(.A1 (n_68), .A2 (n_93), .A3 (n_5), .A4
       (rx_data[7]), .ZN (n_157));
  AOI222_X1 g10413__6783(.A1 (n_70), .A2 (rx_data[5]), .B1 (n_91), .B2
       (n_8), .C1 (kbass_shift_key), .C2 (n_69), .ZN (n_156));
  AOI22_X1 g10414__3680(.A1 (n_108), .A2 (n_4), .B1 (n_106), .B2
       (rx_data[3]), .ZN (n_155));
  OAI222_X1 g10415__1617(.A1 (n_86), .A2 (n_17), .B1 (n_66), .B2
       (rx_data[5]), .C1 (n_43), .C2 (n_46), .ZN (n_154));
  AOI222_X1 g10416__2802(.A1 (n_57), .A2 (rx_data[5]), .B1 (n_36), .B2
       (rx_data[3]), .C1 (n_96), .C2 (n_39), .ZN (n_153));
  AOI21_X1 g10417__1705(.A (n_139), .B1 (n_36), .B2 (n_38), .ZN
       (n_159));
  INV_X4 g10418(.A (n_145), .ZN (n_152));
  AOI22_X1 g10419__5122(.A1 (n_62), .A2 (n_12), .B1 (n_59), .B2
       (rx_data[3]), .ZN (n_147));
  OR3_X2 g10420__8246(.A1 (n_66), .A2 (n_37), .A3 (n_9), .ZN (n_146));
  OAI21_X1 g10421__7098(.A (kbass_ascii_ready), .B1 (n_60), .B2 (n_61),
       .ZN (n_145));
  OAI22_X1 g10422__6131(.A1 (n_83), .A2 (n_7), .B1 (n_14), .B2
       (rx_data[5]), .ZN (n_144));
  OAI221_X1 g10423__1881(.A (n_43), .B1 (n_13), .B2 (n_44), .C1 (n_10),
       .C2 (rx_data[5]), .ZN (n_143));
  OAI33_X1 g10424__5115(.A1 (n_53), .A2 (n_30), .A3 (n_7), .B1 (n_0),
       .B2 (n_21), .B3 (rx_data[1]), .ZN (n_142));
  AOI21_X1 g10425__7482(.A (rx_data[7]), .B1 (n_70), .B2 (rx_data[6]),
       .ZN (n_151));
  AOI21_X1 g10426__4733(.A (n_94), .B1 (n_85), .B2 (rx_data[2]), .ZN
       (n_150));
  OR2_X4 g10427__6161(.A1 (n_110), .A2 (n_127), .ZN (n_149));
  OAI21_X1 g10428__9315(.A (n_9), .B1 (n_98), .B2 (rx_data[2]), .ZN
       (n_148));
  AOI22_X1 g10429__9945(.A1 (n_25), .A2 (n_67), .B1 (n_88), .B2 (n_18),
       .ZN (n_138));
  AOI22_X1 g10430__2883(.A1 (n_0), .A2 (n_55), .B1 (n_65), .B2 (n_37),
       .ZN (n_137));
  OAI22_X1 g10431__2346(.A1 (n_64), .A2 (rx_data[5]), .B1 (n_93), .B2
       (rx_data[1]), .ZN (n_136));
  AOI22_X1 g10432__1666(.A1 (n_79), .A2 (rx_data[5]), .B1 (n_12), .B2
       (n_18), .ZN (n_135));
  AOI22_X1 g10433__7410(.A1 (n_92), .A2 (n_31), .B1 (n_12), .B2
       (rx_data[6]), .ZN (n_134));
  OAI22_X1 g10434__6417(.A1 (n_92), .A2 (n_73), .B1 (n_84), .B2 (n_43),
       .ZN (n_133));
  OAI33_X1 g10435__5477(.A1 (n_20), .A2 (n_26), .A3 (n_3), .B1 (n_17),
       .B2 (n_49), .B3 (rx_data[6]), .ZN (n_132));
  AND3_X4 g10436__2398(.A1 (n_69), .A2 (n_9), .A3 (ps2_read), .ZN
       (n_141));
  AOI22_X1 g10437__5107(.A1 (n_69), .A2 (n_2), .B1 (kbass_shift_key),
       .B2 (n_36), .ZN (n_140));
  OAI21_X1 g10438__6260(.A (n_130), .B1 (n_11), .B2 (n_23), .ZN
       (n_139));
  INV_X2 g10439(.A (n_128), .ZN (n_129));
  AOI21_X1 g10440__4319(.A (n_72), .B1 (n_45), .B2 (rx_data[0]), .ZN
       (n_126));
  OR2_X2 g10441__8428(.A1 (n_91), .A2 (n_47), .ZN (n_125));
  AND2_X4 g10442__5526(.A1 (n_91), .A2 (n_2), .ZN (n_124));
  NAND2_X1 g10443__6783(.A1 (n_85), .A2 (rx_data[1]), .ZN (n_123));
  OAI21_X1 g10444__3680(.A (n_87), .B1 (n_43), .B2 (rx_data[3]), .ZN
       (n_122));
  NOR3_X1 g10445__1617(.A1 (n_48), .A2 (n_28), .A3 (rx_data[0]), .ZN
       (n_121));
  OR2_X2 g10446__2802(.A1 (n_92), .A2 (n_14), .ZN (n_120));
  NOR3_X1 g10447__1705(.A1 (n_24), .A2 (n_49), .A3 (rx_data[5]), .ZN
       (n_119));
  OAI21_X1 g10448__5122(.A (n_86), .B1 (n_13), .B2 (rx_data[4]), .ZN
       (n_118));
  OAI211_X1 g10449__8246(.A (n_48), .B (rx_data[3]), .C1
       (kbass_shift_key), .C2 (n_1), .ZN (n_117));
  NOR2_X1 g10450__7098(.A1 (n_98), .A2 (rx_data[4]), .ZN (n_131));
  NAND2_X1 g10451__6131(.A1 (n_85), .A2 (n_2), .ZN (n_130));
  OAI21_X1 g10452__1881(.A (n_99), .B1 (n_35), .B2 (rx_data[5]), .ZN
       (n_128));
  NAND2_X1 g10453__5115(.A1 (n_73), .A2 (n_75), .ZN (n_127));
  INV_X4 g10454(.A (n_115), .ZN (n_116));
  INV_X4 g10455(.A (n_113), .ZN (n_114));
  MUX2_X2 g10456__7482(.A (n_15), .B (rx_data[2]), .S (n_21), .Z
       (n_112));
  NAND3_X1 g10457__4733(.A1 (n_38), .A2 (rx_data[3]), .A3 (rx_data[5]),
       .ZN (n_111));
  NOR3_X1 g10458__6161(.A1 (n_0), .A2 (n_39), .A3 (n_17), .ZN (n_110));
  AOI21_X1 g10459__9315(.A (n_97), .B1 (n_13), .B2 (rx_data[1]), .ZN
       (n_109));
  OAI22_X1 g10460__9945(.A1 (n_17), .A2 (n_20), .B1 (n_38), .B2 (n_27),
       .ZN (n_108));
  AOI21_X1 g10461__2883(.A (n_36), .B1 (n_42), .B2 (rx_data[4]), .ZN
       (n_107));
  OAI22_X1 g10462__2346(.A1 (n_54), .A2 (n_26), .B1 (n_43), .B2
       (rx_data[6]), .ZN (n_106));
  OAI21_X1 g10463__1666(.A (n_1), .B1 (n_40), .B2 (rx_data[0]), .ZN
       (n_105));
  AOI22_X1 g10464__7410(.A1 (n_22), .A2 (n_50), .B1 (n_25), .B2 (n_16),
       .ZN (n_104));
  AOI22_X1 g10465__6417(.A1 (n_52), .A2 (n_8), .B1 (n_12), .B2 (n_7),
       .ZN (n_103));
  AOI22_X1 g10466__5477(.A1 (n_45), .A2 (rx_data[2]), .B1 (n_15), .B2
       (n_3), .ZN (n_102));
  AOI22_X1 g10467__2398(.A1 (n_50), .A2 (n_7), .B1 (n_38), .B2
       (rx_data[6]), .ZN (n_101));
  OAI22_X1 g10468__5107(.A1 (n_20), .A2 (rx_data[4]), .B1 (n_49), .B2
       (n_3), .ZN (n_100));
  OAI22_X1 g10469__6260(.A1 (n_17), .A2 (rx_data[3]), .B1 (n_2), .B2
       (n_6), .ZN (n_115));
  OAI21_X1 g10470__4319(.A (n_14), .B1 (n_51), .B2 (n_48), .ZN (n_113));
  INV_X2 g10471(.A (n_95), .ZN (n_96));
  INV_X2 g10472(.A (n_93), .ZN (n_94));
  INV_X2 g10473(.A (n_89), .ZN (n_90));
  INV_X2 g10474(.A (n_87), .ZN (n_88));
  INV_X2 g10475(.A (n_84), .ZN (n_85));
  NAND2_X1 g10476__8428(.A1 (kbass_shift_key), .A2 (n_40), .ZN (n_83));
  NOR2_X1 g10477__5526(.A1 (n_23), .A2 (rx_data[1]), .ZN (n_82));
  NAND2_X1 g10478__6783(.A1 (n_45), .A2 (n_50), .ZN (n_81));
  NAND2_X1 g10479__3680(.A1 (n_37), .A2 (n_33), .ZN (n_80));
  NOR2_X1 g10480__1617(.A1 (n_13), .A2 (rx_data[2]), .ZN (n_79));
  NAND2_X1 g10481__2802(.A1 (n_43), .A2 (n_32), .ZN (n_78));
  NAND2_X1 g10483__1705(.A1 (kbass_shift_key), .A2 (n_47), .ZN (n_99));
  NAND2_X1 g10484__5122(.A1 (kbass_shift_key), .A2 (n_12), .ZN (n_98));
  OR2_X4 g10485__8246(.A1 (n_23), .A2 (rx_data[6]), .ZN (n_97));
  NAND2_X1 g10486__7098(.A1 (n_51), .A2 (n_2), .ZN (n_95));
  NAND2_X1 g10487__6131(.A1 (n_36), .A2 (n_1), .ZN (n_93));
  NOR2_X1 g10488__1881(.A1 (kbass_shift_key), .A2 (n_39), .ZN (n_92));
  OR2_X4 g10489__5115(.A1 (n_15), .A2 (n_52), .ZN (n_91));
  NAND2_X1 g10490__7482(.A1 (n_13), .A2 (n_49), .ZN (n_89));
  NAND2_X1 g10491__4733(.A1 (n_38), .A2 (n_2), .ZN (n_87));
  NAND2_X1 g10492__6161(.A1 (n_40), .A2 (rx_data[0]), .ZN (n_86));
  NAND2_X1 g10493__9315(.A1 (n_47), .A2 (n_3), .ZN (n_84));
  INV_X2 g10494(.A (n_76), .ZN (n_77));
  INV_X4 g10495(.A (n_73), .ZN (n_74));
  INV_X2 g10496(.A (n_71), .ZN (n_72));
  INV_X2 g10497(.A (n_68), .ZN (n_67));
  INV_X4 g10498(.A (n_66), .ZN (n_65));
  NAND2_X1 g10499__9945(.A1 (n_40), .A2 (n_22), .ZN (n_64));
  NOR2_X1 g10500__2883(.A1 (n_16), .A2 (rx_data[3]), .ZN (n_63));
  NAND2_X1 g10501__2346(.A1 (n_21), .A2 (rx_data[5]), .ZN (n_62));
  NAND4_X1 g10502__1666(.A1 (kb_ascii_out[4]), .A2 (kb_ascii_out[7]),
       .A3 (kb_ascii_out[6]), .A4 (kb_ascii_out[5]), .ZN (n_61));
  NAND4_X1 g10503__7410(.A1 (kb_ascii_out[0]), .A2 (kb_ascii_out[3]),
       .A3 (kb_ascii_out[2]), .A4 (kb_ascii_out[1]), .ZN (n_60));
  AOI21_X1 g10504__6417(.A (rx_data[5]), .B1 (n_0), .B2 (n_4), .ZN
       (n_59));
  NOR2_X1 g10505__5477(.A1 (n_13), .A2 (n_16), .ZN (n_58));
  NOR2_X1 g10506__2398(.A1 (n_13), .A2 (n_23), .ZN (n_57));
  NAND2_X1 g10507__5107(.A1 (n_11), .A2 (n_28), .ZN (n_56));
  NOR2_X1 g10508__6260(.A1 (n_20), .A2 (n_27), .ZN (n_55));
  NOR3_X1 g10509__4319(.A1 (rx_data[0]), .A2 (rx_data[6]), .A3
       (rx_data[1]), .ZN (n_76));
  NAND2_X1 g10510__8428(.A1 (n_38), .A2 (rx_data[0]), .ZN (n_75));
  NAND2_X1 g10511__5526(.A1 (n_45), .A2 (n_1), .ZN (n_73));
  NAND2_X1 g10512__6783(.A1 (n_36), .A2 (rx_data[0]), .ZN (n_71));
  NOR2_X1 g10513__3680(.A1 (n_11), .A2 (rx_data[0]), .ZN (n_70));
  NOR2_X1 g10514__1617(.A1 (n_23), .A2 (rx_data[5]), .ZN (n_69));
  NAND2_X1 g10515__2802(.A1 (n_12), .A2 (rx_data[0]), .ZN (n_68));
  NAND2_X1 g10516__1705(.A1 (n_40), .A2 (n_4), .ZN (n_66));
  INV_X2 g10517(.A (n_53), .ZN (n_54));
  INV_X4 g10518(.A (n_46), .ZN (n_47));
  INV_X4 g10519(.A (n_44), .ZN (n_45));
  INV_X4 g10520(.A (n_42), .ZN (n_43));
  INV_X4 g10521(.A (n_41), .ZN (n_40));
  INV_X4 g10522(.A (n_39), .ZN (n_38));
  INV_X4 g10523(.A (n_37), .ZN (n_36));
  NAND2_X1 g10524__5122(.A1 (n_7), .A2 (n_8), .ZN (n_35));
  AND2_X4 g10525__8246(.A1 (kbass_key_up), .A2 (ps2_read), .ZN (n_34));
  NAND2_X1 g10526__7098(.A1 (n_0), .A2 (n_8), .ZN (n_53));
  NOR2_X1 g10527__6131(.A1 (rx_data[2]), .A2 (rx_data[0]), .ZN (n_52));
  NOR2_X1 g10528__1881(.A1 (n_0), .A2 (n_6), .ZN (n_51));
  NOR2_X1 g10529__5115(.A1 (rx_data[5]), .A2 (rx_data[3]), .ZN (n_50));
  NAND2_X1 g10530__7482(.A1 (rx_data[3]), .A2 (rx_data[1]), .ZN (n_49));
  NOR2_X1 g10531__4733(.A1 (rx_data[4]), .A2 (rx_data[2]), .ZN (n_48));
  NAND2_X1 g10532__6161(.A1 (rx_data[6]), .A2 (rx_data[5]), .ZN (n_46));
  NAND2_X1 g10533__9315(.A1 (n_3), .A2 (n_6), .ZN (n_44));
  NOR2_X1 g10534__9945(.A1 (n_4), .A2 (n_7), .ZN (n_42));
  NAND2_X1 g10535__2883(.A1 (n_2), .A2 (n_8), .ZN (n_41));
  NAND2_X1 g10536__2346(.A1 (rx_data[2]), .A2 (rx_data[1]), .ZN (n_39));
  NAND2_X1 g10537__1666(.A1 (rx_data[6]), .A2 (rx_data[4]), .ZN (n_37));
  INV_X2 g10538(.A (n_32), .ZN (n_33));
  INV_X2 g10539(.A (n_29), .ZN (n_30));
  INV_X4 g10540(.A (n_27), .ZN (n_28));
  INV_X2 g10541(.A (n_24), .ZN (n_25));
  INV_X4 g10542(.A (n_21), .ZN (n_22));
  INV_X2 g10543(.A (n_20), .ZN (n_19));
  INV_X4 g10544(.A (n_18), .ZN (n_17));
  INV_X4 g10545(.A (n_16), .ZN (n_15));
  INV_X4 g10546(.A (n_14), .ZN (n_13));
  INV_X4 g10547(.A (n_12), .ZN (n_11));
  NAND2_X1 g10548__7410(.A1 (n_6), .A2 (rx_data[1]), .ZN (n_10));
  NOR2_X1 g10549__6417(.A1 (rx_data[5]), .A2 (rx_data[4]), .ZN (n_32));
  NAND2_X1 g10550__5477(.A1 (n_3), .A2 (rx_data[3]), .ZN (n_31));
  NOR2_X1 g10551__2398(.A1 (n_3), .A2 (rx_data[6]), .ZN (n_29));
  NAND2_X1 g10552__5107(.A1 (n_3), .A2 (rx_data[6]), .ZN (n_27));
  NAND2_X1 g10553__6260(.A1 (n_6), .A2 (rx_data[0]), .ZN (n_26));
  NAND2_X1 g10554__4319(.A1 (n_0), .A2 (rx_data[4]), .ZN (n_24));
  NAND2_X1 g10555__8428(.A1 (n_7), .A2 (rx_data[4]), .ZN (n_23));
  NAND2_X1 g10556__5526(.A1 (n_4), .A2 (rx_data[4]), .ZN (n_21));
  NAND2_X1 g10557__6783(.A1 (n_2), .A2 (rx_data[1]), .ZN (n_20));
  NOR2_X1 g10558__3680(.A1 (n_3), .A2 (n_1), .ZN (n_18));
  NAND2_X1 g10559__1617(.A1 (n_7), .A2 (rx_data[6]), .ZN (n_16));
  NOR2_X1 g10560__2802(.A1 (n_2), .A2 (rx_data[0]), .ZN (n_14));
  NOR2_X2 g10561__1705(.A1 (n_2), .A2 (rx_data[1]), .ZN (n_12));
  INV_X4 g10562(.A (rx_data[7]), .ZN (n_9));
  INV_X4 g10563(.A (rx_data[1]), .ZN (n_8));
  INV_X2 g10564(.A (rx_data[2]), .ZN (n_7));
  INV_X4 g10565(.A (rx_data[6]), .ZN (n_6));
  INV_X4 g10566(.A (ps2_read), .ZN (n_5));
  INV_X4 g10567(.A (rx_data[0]), .ZN (n_4));
  INV_X4 g10568(.A (rx_data[4]), .ZN (n_3));
  INV_X4 g10570(.A (rx_data[3]), .ZN (n_2));
  INV_X4 g10571(.A (rx_data[5]), .ZN (n_1));
endmodule

