
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 18:03:15 IST (Jun 13 2025 12:33:15 UTC)

// Verification Directory  

module fontrom(clka, wea, addra, dina, douta);
  input clka;
  input [0:0] wea;
  input [11:0] addra;
  input [7:0] dina;
  output [7:0] douta;
  wire clka;
  wire [0:0] wea;
  wire [11:0] addra;
  wire [7:0] dina;
  wire [7:0] douta;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  blk_mem_gen_v8_4_5_C_FAMILYx617274697837_C_XDEVICEFAMILYx617274697837_C_ELABORATION_DIR11823_C_INTERFACE_TYPE0_C_AXI_TYPE1_C_AXI_SLAVE_TYPE0_C_USE_BRAM_BLOCK0_C_ENABLE_32BIT_ADDRESS0_C_CTRL_ECC_ALGO1313820229_C_HAS_AXI_ID0_C_AXI_ID_WIDTH4_C_MEM_TYPE0_C_BYTE_SIZE9_C_ALGORITHM1_C_PRIM_TYPE1_C_LOAD_INIT_FILE1_C_INIT_FILE_NAMEx666f6e74726f6d2e6d6966_C_INIT_FILEx666f6e74726f6d2e6d656d_C_USE_DEFAULT_DATA0_C_DEFAULT_DATA48_C_HAS_RSTA0_C_RST_PRIORITY_A17221_C_RSTRAM_A0_C_INITA_VAL48_C_HAS_ENA0_C_HAS_REGCEA0_C_USE_BYTE_WEA0_C_WEA_WIDTH1_C_WRITE_MODE_Ax57524954455f4649525354_C_WRITE_WIDTH_A8_C_READ_WIDTH_A8_C_WRITE_DEPTH_A4096_C_READ_DEPTH_A4096_C_ADDRA_WIDTH12_C_HAS_RSTB0_C_RST_PRIORITY_B17221_C_RSTRAM_B0_C_INITB_VAL48_C_HAS_ENB0_C_HAS_REGCEB0_C_USE_BYTE_WEB0_C_WEB_WIDTH1_C_WRITE_MODE_Bx57524954455f4649525354_C_WRITE_WIDTH_B8_C_READ_WIDTH_B8_C_WRITE_DEPTH_B4096_C_READ_DEPTH_B4096_C_ADDRB_WIDTH12_C_HAS_MEM_OUTPUT_REGS_A0_C_HAS_MEM_OUTPUT_REGS_B0_C_HAS_MUX_OUTPUT_REGS_A0_C_HAS_MUX_OUTPUT_REGS_B0_C_MUX_PIPELINE_STAGES0_C_HAS_SOFTECC_INPUT_REGS_A0_C_HAS_SOFTECC_OUTPUT_REGS_B0_C_USE_SOFTECC0_C_USE_ECC0_C_EN_ECC_PIPE0_C_READ_LATENCY_A1_C_READ_LATENCY_B1_C_HAS_INJECTERR0_C_SIM_COLLISION_CHECK4279372_C_COMMON_CLK0_C_DISABLE_WARN_BHV_COLL0_C_EN_SLEEP_PIN0_C_USE_URAM0_C_EN_RDADDRA_CHG0_C_EN_RDADDRB_CHG0_C_EN_DEEPSLEEP_PIN0_C_EN_SHUTDOWN_PIN0_C_EN_SAFETY_CKT0_C_DISABLE_WARN_BHV_RANGE0_C_COUNT_36K_BRAM49_C_COUNT_18K_BRAM48_C_EST_POWER_SUMMARYx457374696d6174656420506f77657220666f7220495020202020203a2020202020322e353335363939206d57
       inst(.clka (clka), .rsta (1'b0), .ena (1'b0), .regcea (1'b0),
       .wea (wea), .addra (addra), .dina (dina), .douta (douta), .clkb
       (1'b0), .rstb (1'b0), .enb (1'b0), .regceb (1'b0), .web (1'b0),
       .addrb (12'b0), .dinb (8'b0), .doutb (UNCONNECTED),
       .injectsbiterr (1'b0), .injectdbiterr (1'b0), .eccpipece (1'b0),
       .sbiterr (UNCONNECTED0), .dbiterr (UNCONNECTED1), .rdaddrecc
       (UNCONNECTED2), .sleep (1'b0), .deepsleep (1'b0), .shutdown
       (1'b0), .rsta_busy (UNCONNECTED3), .rstb_busy (UNCONNECTED4),
       .s_aclk (1'b0), .s_aresetn (1'b0), .s_axi_awid (4'b0),
       .s_axi_awaddr (32'b0), .s_axi_awlen (8'b0), .s_axi_awsize
       (3'b0), .s_axi_awburst (2'b0), .s_axi_awvalid (1'b0),
       .s_axi_awready (UNCONNECTED5), .s_axi_wdata (8'b0), .s_axi_wstrb
       (1'b0), .s_axi_wlast (1'b0), .s_axi_wvalid (1'b0), .s_axi_wready
       (UNCONNECTED6), .s_axi_bid (UNCONNECTED7), .s_axi_bresp
       (UNCONNECTED8), .s_axi_bvalid (UNCONNECTED9), .s_axi_bready
       (1'b0), .s_axi_arid (4'b0), .s_axi_araddr (32'b0), .s_axi_arlen
       (8'b0), .s_axi_arsize (3'b0), .s_axi_arburst (2'b0),
       .s_axi_arvalid (1'b0), .s_axi_arready (UNCONNECTED10),
       .s_axi_rid (UNCONNECTED11), .s_axi_rdata (UNCONNECTED12),
       .s_axi_rresp (UNCONNECTED13), .s_axi_rlast (UNCONNECTED14),
       .s_axi_rvalid (UNCONNECTED15), .s_axi_rready (1'b0),
       .s_axi_injectsbiterr (1'b0), .s_axi_injectdbiterr (1'b0),
       .s_axi_sbiterr (UNCONNECTED16), .s_axi_dbiterr (UNCONNECTED17),
       .s_axi_rdaddrecc (UNCONNECTED18));
endmodule

module logorom(clka, ena, wea, addra, dina, douta);
  input clka, ena;
  input [0:0] wea;
  input [11:0] addra;
  input [7:0] dina;
  output [7:0] douta;
  wire clka, ena;
  wire [0:0] wea;
  wire [11:0] addra;
  wire [7:0] dina;
  wire [7:0] douta;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, UNCONNECTED69, UNCONNECTED70;
  wire UNCONNECTED71, UNCONNECTED72, UNCONNECTED73, UNCONNECTED74,
       UNCONNECTED75, UNCONNECTED76, UNCONNECTED77, UNCONNECTED78;
  blk_mem_gen_v8_4_5_C_FAMILYx617274697837_C_XDEVICEFAMILYx617274697837_C_ELABORATION_DIR11823_C_INTERFACE_TYPE0_C_AXI_TYPE1_C_AXI_SLAVE_TYPE0_C_USE_BRAM_BLOCK0_C_ENABLE_32BIT_ADDRESS0_C_CTRL_ECC_ALGO1313820229_C_HAS_AXI_ID0_C_AXI_ID_WIDTH4_C_MEM_TYPE0_C_BYTE_SIZE9_C_ALGORITHM1_C_PRIM_TYPE1_C_LOAD_INIT_FILE1_C_INIT_FILE_NAMEx6c6f676f726f6d2e6d6966_C_INIT_FILEx6c6f676f726f6d2e6d656d_C_USE_DEFAULT_DATA1_C_DEFAULT_DATA48_C_HAS_RSTA0_C_RST_PRIORITY_A17221_C_RSTRAM_A0_C_INITA_VAL48_C_HAS_ENA1_C_HAS_REGCEA0_C_USE_BYTE_WEA0_C_WEA_WIDTH1_C_WRITE_MODE_Ax57524954455f4649525354_C_WRITE_WIDTH_A8_C_READ_WIDTH_A8_C_WRITE_DEPTH_A4096_C_READ_DEPTH_A4096_C_ADDRA_WIDTH12_C_HAS_RSTB0_C_RST_PRIORITY_B17221_C_RSTRAM_B0_C_INITB_VAL48_C_HAS_ENB0_C_HAS_REGCEB0_C_USE_BYTE_WEB0_C_WEB_WIDTH1_C_WRITE_MODE_Bx57524954455f4649525354_C_WRITE_WIDTH_B8_C_READ_WIDTH_B8_C_WRITE_DEPTH_B4096_C_READ_DEPTH_B4096_C_ADDRB_WIDTH12_C_HAS_MEM_OUTPUT_REGS_A0_C_HAS_MEM_OUTPUT_REGS_B0_C_HAS_MUX_OUTPUT_REGS_A0_C_HAS_MUX_OUTPUT_REGS_B0_C_MUX_PIPELINE_STAGES0_C_HAS_SOFTECC_INPUT_REGS_A0_C_HAS_SOFTECC_OUTPUT_REGS_B0_C_USE_SOFTECC0_C_USE_ECC0_C_EN_ECC_PIPE0_C_READ_LATENCY_A1_C_READ_LATENCY_B1_C_HAS_INJECTERR0_C_SIM_COLLISION_CHECK4279372_C_COMMON_CLK0_C_DISABLE_WARN_BHV_COLL0_C_EN_SLEEP_PIN0_C_USE_URAM0_C_EN_RDADDRA_CHG0_C_EN_RDADDRB_CHG0_C_EN_DEEPSLEEP_PIN0_C_EN_SHUTDOWN_PIN0_C_EN_SAFETY_CKT0_C_DISABLE_WARN_BHV_RANGE0_C_COUNT_36K_BRAM49_C_COUNT_18K_BRAM48_C_EST_POWER_SUMMARYx457374696d6174656420506f77657220666f7220495020202020203a2020202020322e353335363939206d57
       inst(.clka (clka), .rsta (1'b0), .ena (ena), .regcea (1'b0),
       .wea (wea), .addra (addra), .dina (dina), .douta (douta), .clkb
       (1'b0), .rstb (1'b0), .enb (1'b0), .regceb (1'b0), .web (1'b0),
       .addrb (12'b0), .dinb (8'b0), .doutb (UNCONNECTED39),
       .injectsbiterr (1'b0), .injectdbiterr (1'b0), .eccpipece (1'b0),
       .sbiterr (UNCONNECTED40), .dbiterr (UNCONNECTED41), .rdaddrecc
       (UNCONNECTED42), .sleep (1'b0), .deepsleep (1'b0), .shutdown
       (1'b0), .rsta_busy (UNCONNECTED43), .rstb_busy (UNCONNECTED44),
       .s_aclk (1'b0), .s_aresetn (1'b0), .s_axi_awid (4'b0),
       .s_axi_awaddr (32'b0), .s_axi_awlen (8'b0), .s_axi_awsize
       (3'b0), .s_axi_awburst (2'b0), .s_axi_awvalid (1'b0),
       .s_axi_awready (UNCONNECTED45), .s_axi_wdata (8'b0),
       .s_axi_wstrb (1'b0), .s_axi_wlast (1'b0), .s_axi_wvalid (1'b0),
       .s_axi_wready (UNCONNECTED46), .s_axi_bid (UNCONNECTED47),
       .s_axi_bresp (UNCONNECTED48), .s_axi_bvalid (UNCONNECTED49),
       .s_axi_bready (1'b0), .s_axi_arid (4'b0), .s_axi_araddr (32'b0),
       .s_axi_arlen (8'b0), .s_axi_arsize (3'b0), .s_axi_arburst
       (2'b0), .s_axi_arvalid (1'b0), .s_axi_arready (UNCONNECTED50),
       .s_axi_rid (UNCONNECTED51), .s_axi_rdata (UNCONNECTED52),
       .s_axi_rresp (UNCONNECTED53), .s_axi_rlast (UNCONNECTED54),
       .s_axi_rvalid (UNCONNECTED55), .s_axi_rready (1'b0),
       .s_axi_injectsbiterr (1'b0), .s_axi_injectdbiterr (1'b0),
       .s_axi_sbiterr (UNCONNECTED56), .s_axi_dbiterr (UNCONNECTED57),
       .s_axi_rdaddrecc (UNCONNECTED58));
endmodule

module textram(clka, ena, wea, addra, dina, clkb, addrb, doutb);
  input clka, ena, clkb;
  input [0:0] wea;
  input [11:0] addra, addrb;
  input [7:0] dina;
  output [7:0] doutb;
  wire clka, ena, clkb;
  wire [0:0] wea;
  wire [11:0] addra, addrb;
  wire [7:0] dina;
  wire [7:0] doutb;
  wire UNCONNECTED79, UNCONNECTED80, UNCONNECTED81, UNCONNECTED82,
       UNCONNECTED83, UNCONNECTED84, UNCONNECTED85, UNCONNECTED86;
  wire UNCONNECTED87, UNCONNECTED88, UNCONNECTED89, UNCONNECTED90,
       UNCONNECTED91, UNCONNECTED92, UNCONNECTED93, UNCONNECTED94;
  wire UNCONNECTED95, UNCONNECTED96, UNCONNECTED97, UNCONNECTED98,
       UNCONNECTED99, UNCONNECTED100, UNCONNECTED101, UNCONNECTED102;
  wire UNCONNECTED103, UNCONNECTED104, UNCONNECTED105, UNCONNECTED106,
       UNCONNECTED107, UNCONNECTED108, UNCONNECTED109, UNCONNECTED110;
  wire UNCONNECTED111, UNCONNECTED112, UNCONNECTED113, UNCONNECTED114,
       UNCONNECTED115, UNCONNECTED116, UNCONNECTED117, UNCONNECTED118;
  blk_mem_gen_v8_4_5_C_FAMILYx617274697837_C_XDEVICEFAMILYx617274697837_C_ELABORATION_DIR11823_C_INTERFACE_TYPE0_C_AXI_TYPE1_C_AXI_SLAVE_TYPE0_C_USE_BRAM_BLOCK0_C_ENABLE_32BIT_ADDRESS0_C_CTRL_ECC_ALGO1313820229_C_HAS_AXI_ID0_C_AXI_ID_WIDTH4_C_MEM_TYPE1_C_BYTE_SIZE9_C_ALGORITHM1_C_PRIM_TYPE1_C_LOAD_INIT_FILE0_C_INIT_FILE_NAMEx6e6f5f636f655f66696c655f6c6f61646564_C_INIT_FILEx7465787472616d2e6d656d_C_USE_DEFAULT_DATA0_C_DEFAULT_DATA48_C_HAS_RSTA0_C_RST_PRIORITY_A17221_C_RSTRAM_A0_C_INITA_VAL48_C_HAS_ENA1_C_HAS_REGCEA0_C_USE_BYTE_WEA0_C_WEA_WIDTH1_C_WRITE_MODE_Ax4e4f5f4348414e4745_C_WRITE_WIDTH_A8_C_READ_WIDTH_A8_C_WRITE_DEPTH_A4096_C_READ_DEPTH_A4096_C_ADDRA_WIDTH12_C_HAS_RSTB0_C_RST_PRIORITY_B17221_C_RSTRAM_B0_C_INITB_VAL48_C_HAS_ENB0_C_HAS_REGCEB0_C_USE_BYTE_WEB0_C_WEB_WIDTH1_C_WRITE_MODE_Bx57524954455f4649525354_C_WRITE_WIDTH_B8_C_READ_WIDTH_B8_C_WRITE_DEPTH_B4096_C_READ_DEPTH_B4096_C_ADDRB_WIDTH12_C_HAS_MEM_OUTPUT_REGS_A0_C_HAS_MEM_OUTPUT_REGS_B0_C_HAS_MUX_OUTPUT_REGS_A0_C_HAS_MUX_OUTPUT_REGS_B0_C_MUX_PIPELINE_STAGES0_C_HAS_SOFTECC_INPUT_REGS_A0_C_HAS_SOFTECC_OUTPUT_REGS_B0_C_USE_SOFTECC0_C_USE_ECC0_C_EN_ECC_PIPE0_C_READ_LATENCY_A1_C_READ_LATENCY_B1_C_HAS_INJECTERR0_C_SIM_COLLISION_CHECK4279372_C_COMMON_CLK0_C_DISABLE_WARN_BHV_COLL0_C_EN_SLEEP_PIN0_C_USE_URAM0_C_EN_RDADDRA_CHG0_C_EN_RDADDRB_CHG0_C_EN_DEEPSLEEP_PIN0_C_EN_SHUTDOWN_PIN0_C_EN_SAFETY_CKT0_C_DISABLE_WARN_BHV_RANGE0_C_COUNT_36K_BRAM49_C_COUNT_18K_BRAM48_C_EST_POWER_SUMMARYx457374696d6174656420506f77657220666f7220495020202020203a2020202020342e3533343735206d57
       inst(.clka (clka), .rsta (1'b0), .ena (ena), .regcea (1'b0),
       .wea (wea), .addra (addra), .dina (dina), .douta
       (UNCONNECTED79), .clkb (clkb), .rstb (1'b0), .enb (1'b0),
       .regceb (1'b0), .web (1'b0), .addrb (addrb), .dinb (8'b0),
       .doutb (doutb), .injectsbiterr (1'b0), .injectdbiterr (1'b0),
       .eccpipece (1'b0), .sbiterr (UNCONNECTED80), .dbiterr
       (UNCONNECTED81), .rdaddrecc (UNCONNECTED82), .sleep (1'b0),
       .deepsleep (1'b0), .shutdown (1'b0), .rsta_busy (UNCONNECTED83),
       .rstb_busy (UNCONNECTED84), .s_aclk (1'b0), .s_aresetn (1'b0),
       .s_axi_awid (4'b0), .s_axi_awaddr (32'b0), .s_axi_awlen (8'b0),
       .s_axi_awsize (3'b0), .s_axi_awburst (2'b0), .s_axi_awvalid
       (1'b0), .s_axi_awready (UNCONNECTED85), .s_axi_wdata (8'b0),
       .s_axi_wstrb (1'b0), .s_axi_wlast (1'b0), .s_axi_wvalid (1'b0),
       .s_axi_wready (UNCONNECTED86), .s_axi_bid (UNCONNECTED87),
       .s_axi_bresp (UNCONNECTED88), .s_axi_bvalid (UNCONNECTED89),
       .s_axi_bready (1'b0), .s_axi_arid (4'b0), .s_axi_araddr (32'b0),
       .s_axi_arlen (8'b0), .s_axi_arsize (3'b0), .s_axi_arburst
       (2'b0), .s_axi_arvalid (1'b0), .s_axi_arready (UNCONNECTED90),
       .s_axi_rid (UNCONNECTED91), .s_axi_rdata (UNCONNECTED92),
       .s_axi_rresp (UNCONNECTED93), .s_axi_rlast (UNCONNECTED94),
       .s_axi_rvalid (UNCONNECTED95), .s_axi_rready (1'b0),
       .s_axi_injectsbiterr (1'b0), .s_axi_injectdbiterr (1'b0),
       .s_axi_sbiterr (UNCONNECTED96), .s_axi_dbiterr (UNCONNECTED97),
       .s_axi_rdaddrecc (UNCONNECTED98));
endmodule

module video_ctrl(clk50mhz, clk25mhz, rst, ascii_input, ascii_read_in,
     clear_text_ram, cursor_on, show_logo, vsync, hsync, red_bit,
     green_bit, blue_bit);
  input clk50mhz, clk25mhz, rst, ascii_read_in, clear_text_ram,
       cursor_on, show_logo;
  input [7:0] ascii_input;
  inout vsync, hsync, red_bit, green_bit, blue_bit;
  wire clk50mhz, clk25mhz, rst, ascii_read_in, clear_text_ram,
       cursor_on, show_logo;
  wire [7:0] ascii_input;
  wire vsync, hsync, red_bit, green_bit, blue_bit;
  wire [11:0] vga_font_addr;
  wire [7:0] vga_font_data;
  wire [11:0] vga_ram_addr;
  wire [7:0] logo_ram_data;
  wire [11:0] text_ram_counter;
  wire [7:0] text_ram_input_data;
  wire [7:0] text_ram_vga_data;
  wire [7:0] cur_y;
  wire [7:0] cur_x;
  wire [7:0] vga_ram_data;
  wire [7:0] ascii_input_reg;
  wire UNCONNECTED119, UNCONNECTED120, UNCONNECTED121, UNCONNECTED122,
       UNCONNECTED123, UNCONNECTED124, UNCONNECTED125, UNCONNECTED126;
  wire UNCONNECTED127, UNCONNECTED128, UNCONNECTED129, UNCONNECTED130,
       UNCONNECTED131, UNCONNECTED132, UNCONNECTED133, UNCONNECTED134;
  wire UNCONNECTED135, UNCONNECTED136, UNCONNECTED137, UNCONNECTED138,
       UNCONNECTED139, UNCONNECTED140, UNCONNECTED141, UNCONNECTED142;
  wire UNCONNECTED143, UNCONNECTED144, UNCONNECTED145, UNCONNECTED146,
       UNCONNECTED147, UNCONNECTED148, UNCONNECTED149,
       ascii_read_in_reg;
  wire clear_text_ram_reg, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_98, n_102, n_130, n_142;
  fontrom u2(.clka (clk25mhz), .wea (1'b0), .addra (vga_font_addr),
       .dina (8'b0), .douta (vga_font_data));
  logorom u3(.clka (clk25mhz), .ena (show_logo), .wea (1'b0), .addra
       (vga_ram_addr), .dina (8'b0), .douta (logo_ram_data));
  textram u4(.clka (clk50mhz), .ena (n_102), .wea (n_130), .addra
       (text_ram_counter), .dina (text_ram_input_data), .clkb
       (clk25mhz), .addrb (vga_ram_addr), .doutb (text_ram_vga_data));
  vga80x40 u5(.reset (rst), .clk25MHz (clk25mhz), .R (red_bit), .G
       (green_bit), .B (blue_bit), .hsync (hsync), .vsync (vsync),
       .TEXT_A (vga_ram_addr), .TEXT_D (vga_ram_data), .FONT_A
       (vga_font_addr), .FONT_D (vga_font_data), .ocrx (cur_y), .ocry
       (cur_x), .octl ({1'b1, cursor_on, 6'b110010}));
  INV_X1 g960(.A (rst), .ZN (n_98));
  MUX2_X1 g1150__5122(.A (text_ram_vga_data[2]), .B (logo_ram_data[2]),
       .S (show_logo), .Z (vga_ram_data[2]));
  MUX2_X1 g1151__8246(.A (text_ram_vga_data[1]), .B (logo_ram_data[1]),
       .S (show_logo), .Z (vga_ram_data[1]));
  MUX2_X1 g1152__7098(.A (text_ram_vga_data[0]), .B (logo_ram_data[0]),
       .S (show_logo), .Z (vga_ram_data[0]));
  MUX2_X1 g1153__6131(.A (text_ram_vga_data[4]), .B (logo_ram_data[4]),
       .S (show_logo), .Z (vga_ram_data[4]));
  MUX2_X1 g1154__1881(.A (text_ram_vga_data[5]), .B (logo_ram_data[5]),
       .S (show_logo), .Z (vga_ram_data[5]));
  MUX2_X1 g1155__5115(.A (text_ram_vga_data[7]), .B (logo_ram_data[7]),
       .S (show_logo), .Z (vga_ram_data[7]));
  MUX2_X1 g1156__7482(.A (text_ram_vga_data[6]), .B (logo_ram_data[6]),
       .S (show_logo), .Z (vga_ram_data[6]));
  MUX2_X1 g1157__4733(.A (text_ram_vga_data[3]), .B (logo_ram_data[3]),
       .S (show_logo), .Z (vga_ram_data[3]));
  AND2_X2 g1158__6161(.A1 (ascii_input_reg[3]), .A2 (n_6), .ZN
       (text_ram_input_data[3]));
  AND2_X2 g1159__9315(.A1 (ascii_input_reg[2]), .A2 (n_6), .ZN
       (text_ram_input_data[2]));
  AND2_X2 g1160__9945(.A1 (ascii_input_reg[1]), .A2 (n_6), .ZN
       (text_ram_input_data[1]));
  AND2_X2 g1161__2883(.A1 (ascii_input_reg[4]), .A2 (n_6), .ZN
       (text_ram_input_data[4]));
  AND2_X2 g1162__2346(.A1 (ascii_input_reg[6]), .A2 (n_6), .ZN
       (text_ram_input_data[6]));
  OR2_X2 g1163__1666(.A1 (clear_text_ram_reg), .A2
       (ascii_input_reg[5]), .ZN (text_ram_input_data[5]));
  AND2_X2 g1164__7410(.A1 (ascii_input_reg[0]), .A2 (n_6), .ZN
       (text_ram_input_data[0]));
  AND2_X2 g1165__6417(.A1 (ascii_input_reg[7]), .A2 (n_6), .ZN
       (text_ram_input_data[7]));
  OR2_X4 g1166__5477(.A1 (clear_text_ram_reg), .A2 (ascii_read_in_reg),
       .ZN (n_142));
  NAND2_X1 g1167__2398(.A1 (show_logo), .A2 (n_6), .ZN (n_102));
  DFFR_X2 \ascii_input_reg_reg[0] (.RN (n_98), .CK (clk50mhz), .D
       (n_17), .Q (ascii_input_reg[0]), .QN (UNCONNECTED119));
  DFFR_X2 \ascii_input_reg_reg[1] (.RN (n_98), .CK (clk50mhz), .D
       (n_19), .Q (ascii_input_reg[1]), .QN (UNCONNECTED120));
  DFFR_X2 \ascii_input_reg_reg[2] (.RN (n_98), .CK (clk50mhz), .D
       (n_16), .Q (ascii_input_reg[2]), .QN (UNCONNECTED121));
  DFFR_X2 \ascii_input_reg_reg[3] (.RN (n_98), .CK (clk50mhz), .D
       (n_13), .Q (ascii_input_reg[3]), .QN (UNCONNECTED122));
  DFFR_X2 \ascii_input_reg_reg[4] (.RN (n_98), .CK (clk50mhz), .D
       (n_14), .Q (ascii_input_reg[4]), .QN (UNCONNECTED123));
  DFFR_X2 \ascii_input_reg_reg[5] (.RN (n_98), .CK (clk50mhz), .D
       (n_15), .Q (ascii_input_reg[5]), .QN (UNCONNECTED124));
  DFFR_X2 \ascii_input_reg_reg[6] (.RN (n_98), .CK (clk50mhz), .D
       (n_12), .Q (ascii_input_reg[6]), .QN (UNCONNECTED125));
  DFFR_X2 \ascii_input_reg_reg[7] (.RN (n_98), .CK (clk50mhz), .D
       (n_11), .Q (ascii_input_reg[7]), .QN (UNCONNECTED126));
  DFFR_X2 ascii_read_in_reg_reg(.RN (n_98), .CK (clk50mhz), .D
       (ascii_read_in), .Q (ascii_read_in_reg), .QN (UNCONNECTED127));
  DFFS_X2 clear_text_ram_reg_reg(.SN (n_98), .CK (clk50mhz), .D (n_95),
       .Q (clear_text_ram_reg), .QN (n_6));
  DFFR_X2 \cur_x_reg[0] (.RN (n_98), .CK (clk50mhz), .D (n_49), .Q
       (cur_x[0]), .QN (n_0));
  DFFR_X2 \cur_x_reg[1] (.RN (n_98), .CK (clk50mhz), .D (n_56), .Q
       (cur_x[1]), .QN (UNCONNECTED128));
  DFFR_X2 \cur_x_reg[2] (.RN (n_98), .CK (clk50mhz), .D (n_64), .Q
       (cur_x[2]), .QN (UNCONNECTED129));
  DFFR_X2 \cur_x_reg[3] (.RN (n_98), .CK (clk50mhz), .D (n_53), .Q
       (cur_x[3]), .QN (n_3));
  DFFR_X2 \cur_x_reg[4] (.RN (n_98), .CK (clk50mhz), .D (n_48), .Q
       (cur_x[4]), .QN (n_2));
  DFFR_X2 \cur_x_reg[5] (.RN (n_98), .CK (clk50mhz), .D (n_52), .Q
       (cur_x[5]), .QN (n_1));
  DFFR_X2 \cur_x_reg[6] (.RN (n_98), .CK (clk50mhz), .D (n_58), .Q
       (cur_x[6]), .QN (UNCONNECTED130));
  DFFR_X2 \cur_x_reg[7] (.RN (n_98), .CK (clk50mhz), .D (n_63), .Q
       (cur_x[7]), .QN (UNCONNECTED131));
  DFFR_X2 \cur_y_reg[0] (.RN (n_98), .CK (clk50mhz), .D (n_38), .Q
       (cur_y[0]), .QN (UNCONNECTED132));
  DFFR_X2 \cur_y_reg[1] (.RN (n_98), .CK (clk50mhz), .D (n_32), .Q
       (cur_y[1]), .QN (UNCONNECTED133));
  DFFR_X2 \cur_y_reg[2] (.RN (n_98), .CK (clk50mhz), .D (n_45), .Q
       (cur_y[2]), .QN (UNCONNECTED134));
  DFFR_X2 \cur_y_reg[3] (.RN (n_98), .CK (clk50mhz), .D (n_61), .Q
       (cur_y[3]), .QN (UNCONNECTED135));
  DFFR_X2 \cur_y_reg[4] (.RN (n_98), .CK (clk50mhz), .D (n_70), .Q
       (cur_y[4]), .QN (UNCONNECTED136));
  DFFR_X2 \cur_y_reg[5] (.RN (n_98), .CK (clk50mhz), .D (n_74), .Q
       (cur_y[5]), .QN (n_4));
  DFFR_X2 \cur_y_reg[6] (.RN (n_98), .CK (clk50mhz), .D (n_81), .Q
       (cur_y[6]), .QN (UNCONNECTED137));
  DFFR_X2 \cur_y_reg[7] (.RN (n_98), .CK (clk50mhz), .D (n_82), .Q
       (cur_y[7]), .QN (UNCONNECTED138));
  DFFR_X2 \text_ram_counter_reg[0] (.RN (n_98), .CK (clk50mhz), .D
       (n_18), .Q (text_ram_counter[0]), .QN (n_5));
  DFFR_X2 \text_ram_counter_reg[1] (.RN (n_98), .CK (clk50mhz), .D
       (n_27), .Q (text_ram_counter[1]), .QN (UNCONNECTED139));
  DFFR_X2 \text_ram_counter_reg[2] (.RN (n_98), .CK (clk50mhz), .D
       (n_37), .Q (text_ram_counter[2]), .QN (UNCONNECTED140));
  DFFR_X2 \text_ram_counter_reg[3] (.RN (n_98), .CK (clk50mhz), .D
       (n_54), .Q (text_ram_counter[3]), .QN (UNCONNECTED141));
  DFFR_X2 \text_ram_counter_reg[4] (.RN (n_98), .CK (clk50mhz), .D
       (n_67), .Q (text_ram_counter[4]), .QN (UNCONNECTED142));
  DFFR_X2 \text_ram_counter_reg[5] (.RN (n_98), .CK (clk50mhz), .D
       (n_71), .Q (text_ram_counter[5]), .QN (UNCONNECTED143));
  DFFR_X2 \text_ram_counter_reg[6] (.RN (n_98), .CK (clk50mhz), .D
       (n_78), .Q (text_ram_counter[6]), .QN (UNCONNECTED144));
  DFFR_X2 \text_ram_counter_reg[7] (.RN (n_98), .CK (clk50mhz), .D
       (n_83), .Q (text_ram_counter[7]), .QN (UNCONNECTED145));
  DFFR_X2 \text_ram_counter_reg[8] (.RN (n_98), .CK (clk50mhz), .D
       (n_86), .Q (text_ram_counter[8]), .QN (UNCONNECTED146));
  DFFR_X2 \text_ram_counter_reg[9] (.RN (n_98), .CK (clk50mhz), .D
       (n_89), .Q (text_ram_counter[9]), .QN (UNCONNECTED147));
  DFFR_X2 \text_ram_counter_reg[10] (.RN (n_98), .CK (clk50mhz), .D
       (n_92), .Q (text_ram_counter[10]), .QN (UNCONNECTED148));
  DFFR_X2 \text_ram_counter_reg[11] (.RN (n_98), .CK (clk50mhz), .D
       (n_96), .Q (text_ram_counter[11]), .QN (UNCONNECTED149));
  MUX2_X2 g1750__5107(.A (text_ram_counter[11]), .B (n_94), .S (n_142),
       .Z (n_96));
  NOR2_X1 g1751__6260(.A1 (n_93), .A2 (n_6), .ZN (n_95));
  HA_X1 g1752__4319(.A (n_90), .B (text_ram_counter[11]), .CO (n_93),
       .S (n_94));
  MUX2_X2 g1754__8428(.A (text_ram_counter[10]), .B (n_91), .S (n_142),
       .Z (n_92));
  HA_X1 g1755__5526(.A (n_87), .B (text_ram_counter[10]), .CO (n_90),
       .S (n_91));
  MUX2_X2 g1757__6783(.A (text_ram_counter[9]), .B (n_88), .S (n_142),
       .Z (n_89));
  HA_X1 g1758__3680(.A (n_84), .B (text_ram_counter[9]), .CO (n_87), .S
       (n_88));
  MUX2_X2 g1760__1617(.A (text_ram_counter[8]), .B (n_85), .S (n_142),
       .Z (n_86));
  HA_X1 g1761__2802(.A (n_79), .B (text_ram_counter[8]), .CO (n_84), .S
       (n_85));
  MUX2_X2 g1765__1705(.A (text_ram_counter[7]), .B (n_80), .S (n_142),
       .Z (n_83));
  XOR2_X1 g1766__5122(.A (n_77), .B (cur_y[7]), .Z (n_82));
  NOR3_X1 g1767__8246(.A1 (n_77), .A2 (n_76), .A3 (n_33), .ZN (n_81));
  HA_X1 g1768__7098(.A (n_72), .B (text_ram_counter[7]), .CO (n_79), .S
       (n_80));
  MUX2_X2 g1770__6131(.A (text_ram_counter[6]), .B (n_73), .S (n_142),
       .Z (n_78));
  NOR2_X1 g1772__1881(.A1 (n_75), .A2 (cur_y[6]), .ZN (n_76));
  AND2_X4 g1773__5115(.A1 (n_75), .A2 (cur_y[6]), .ZN (n_77));
  HA_X1 g1774__7482(.A (n_65), .B (cur_y[5]), .CO (n_75), .S (n_74));
  HA_X1 g1775__4733(.A (n_68), .B (text_ram_counter[6]), .CO (n_72), .S
       (n_73));
  MUX2_X2 g1778__6161(.A (text_ram_counter[5]), .B (n_69), .S (n_142),
       .Z (n_71));
  NOR3_X1 g1779__9315(.A1 (n_65), .A2 (n_66), .A3 (n_33), .ZN (n_70));
  HA_X1 g1780__9945(.A (n_59), .B (text_ram_counter[5]), .CO (n_68), .S
       (n_69));
  MUX2_X2 g1783__2883(.A (text_ram_counter[4]), .B (n_60), .S (n_142),
       .Z (n_67));
  NOR2_X1 g1785__2346(.A1 (n_62), .A2 (cur_y[4]), .ZN (n_66));
  XOR2_X1 g1787__1666(.A (n_55), .B (cur_x[2]), .Z (n_64));
  XOR2_X1 g1788__7410(.A (n_57), .B (cur_x[7]), .Z (n_63));
  AND2_X4 g1789__6417(.A1 (n_62), .A2 (cur_y[4]), .ZN (n_65));
  HA_X1 g1790__5477(.A (n_44), .B (cur_y[3]), .CO (n_62), .S (n_61));
  HA_X1 g1791__2398(.A (n_46), .B (text_ram_counter[4]), .CO (n_59), .S
       (n_60));
  HA_X1 g1797__5107(.A (n_36), .B (cur_x[6]), .CO (n_57), .S (n_58));
  HA_X1 g1798__6260(.A (n_40), .B (cur_x[1]), .CO (n_55), .S (n_56));
  MUX2_X2 g1801__4319(.A (text_ram_counter[3]), .B (n_47), .S (n_142),
       .Z (n_54));
  OAI21_X1 g1802__8428(.A (n_51), .B1 (n_43), .B2 (n_3), .ZN (n_53));
  OAI21_X1 g1803__5526(.A (n_50), .B1 (n_42), .B2 (n_1), .ZN (n_52));
  OR3_X2 g1804__6783(.A1 (n_41), .A2 (n_20), .A3 (cur_x[3]), .ZN
       (n_51));
  OR3_X2 g1806__3680(.A1 (n_41), .A2 (n_25), .A3 (cur_x[5]), .ZN
       (n_50));
  OAI22_X1 g1807__1617(.A1 (n_41), .A2 (cur_x[0]), .B1 (n_33), .B2
       (n_0), .ZN (n_49));
  XOR2_X1 g1808__2802(.A (n_39), .B (cur_x[4]), .Z (n_48));
  HA_X1 g1809__1705(.A (n_29), .B (text_ram_counter[3]), .CO (n_46), .S
       (n_47));
  HA_X1 g1810__5122(.A (n_31), .B (cur_y[2]), .CO (n_44), .S (n_45));
  AOI21_X1 g1813__8246(.A (n_34), .B1 (n_35), .B2 (n_20), .ZN (n_43));
  AOI21_X1 g1814__7098(.A (n_34), .B1 (n_35), .B2 (n_25), .ZN (n_42));
  NOR2_X1 g1815__6131(.A1 (n_34), .A2 (n_0), .ZN (n_40));
  NOR2_X1 g1816__1881(.A1 (n_34), .A2 (n_22), .ZN (n_39));
  NAND2_X1 g1817__5115(.A1 (n_33), .A2 (n_35), .ZN (n_41));
  NOR3_X1 g1818__7482(.A1 (n_33), .A2 (n_9), .A3 (n_10), .ZN (n_38));
  MUX2_X2 g1819__4733(.A (text_ram_counter[2]), .B (n_30), .S (n_142),
       .Z (n_37));
  NOR3_X1 g1820__6161(.A1 (n_34), .A2 (n_25), .A3 (n_1), .ZN (n_36));
  INV_X4 g1822(.A (n_34), .ZN (n_33));
  NAND2_X1 g1823__9315(.A1 (n_28), .A2 (cur_x[3]), .ZN (n_35));
  NAND4_X1 g1824__9945(.A1 (n_26), .A2 (n_4), .A3 (cur_y[4]), .A4
       (cur_y[6]), .ZN (n_34));
  HA_X1 g1825__2883(.A (n_9), .B (cur_y[1]), .CO (n_31), .S (n_32));
  HA_X1 g1826__2346(.A (n_23), .B (text_ram_counter[2]), .CO (n_29), .S
       (n_30));
  NOR4_X1 g1828__1666(.A1 (n_21), .A2 (cur_x[0]), .A3 (cur_x[1]), .A4
       (cur_x[6]), .ZN (n_28));
  MUX2_X2 g1829__7410(.A (text_ram_counter[1]), .B (n_24), .S (n_142),
       .Z (n_27));
  NOR4_X1 g1830__6417(.A1 (n_8), .A2 (cur_y[2]), .A3 (cur_y[3]), .A4
       (cur_y[1]), .ZN (n_26));
  OR2_X4 g1831__5477(.A1 (n_22), .A2 (n_2), .ZN (n_25));
  HA_X1 g1832__2398(.A (text_ram_counter[0]), .B (text_ram_counter[1]),
       .CO (n_23), .S (n_24));
  OR4_X1 g1838__5107(.A1 (n_1), .A2 (cur_x[2]), .A3 (cur_x[4]), .A4
       (cur_x[7]), .ZN (n_21));
  OR2_X4 g1842__6260(.A1 (n_20), .A2 (n_3), .ZN (n_22));
  MUX2_X2 g1844__4319(.A (ascii_input_reg[1]), .B (ascii_input[1]), .S
       (ascii_read_in), .Z (n_19));
  OAI22_X1 g1845__8428(.A1 (n_142), .A2 (n_5), .B1 (n_7), .B2
       (text_ram_counter[0]), .ZN (n_18));
  MUX2_X2 g1846__5526(.A (ascii_input_reg[0]), .B (ascii_input[0]), .S
       (ascii_read_in), .Z (n_17));
  MUX2_X2 g1847__6783(.A (ascii_input_reg[2]), .B (ascii_input[2]), .S
       (ascii_read_in), .Z (n_16));
  NAND3_X1 g1848__3680(.A1 (cur_x[1]), .A2 (cur_x[0]), .A3 (cur_x[2]),
       .ZN (n_20));
  MUX2_X2 g1849__1617(.A (ascii_input_reg[5]), .B (ascii_input[5]), .S
       (ascii_read_in), .Z (n_15));
  MUX2_X2 g1850__2802(.A (ascii_input_reg[4]), .B (ascii_input[4]), .S
       (ascii_read_in), .Z (n_14));
  MUX2_X2 g1851__1705(.A (ascii_input_reg[3]), .B (ascii_input[3]), .S
       (ascii_read_in), .Z (n_13));
  MUX2_X2 g1852__5122(.A (ascii_input_reg[6]), .B (ascii_input[6]), .S
       (ascii_read_in), .Z (n_12));
  MUX2_X2 g1853__8246(.A (ascii_input_reg[7]), .B (ascii_input[7]), .S
       (ascii_read_in), .Z (n_11));
  NOR2_X1 g1854__7098(.A1 (ascii_read_in_reg), .A2 (cur_y[0]), .ZN
       (n_10));
  OR2_X4 g1856__6131(.A1 (cur_y[7]), .A2 (cur_y[0]), .ZN (n_8));
  AND2_X4 g1857__1881(.A1 (cur_y[0]), .A2 (ascii_read_in_reg), .ZN
       (n_9));
  INV_X4 g1859(.A (n_142), .ZN (n_7));
  BUF_X4 g1866(.A (n_142), .Z (n_130));
endmodule

