
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 14 2025 15:21:56 IST (Apr 14 2025 09:51:56 UTC)

// Verification Directory fv/random_counter_lfsr 

module D_FF(q, d, rst_n, clk, init_value);
  input d, rst_n, clk, init_value;
  output q;
  wire d, rst_n, clk, init_value;
  wire q;
  wire UNCONNECTED, n_0, n_1, n_2;
  DFFRS_X2 q_reg(.RN (n_1), .SN (n_2), .CK (clk), .D (d), .Q (q), .QN
       (UNCONNECTED));
  NAND2_X1 g37__2398(.A1 (n_0), .A2 (init_value), .ZN (n_2));
  OR2_X1 g38__5107(.A1 (rst_n), .A2 (init_value), .ZN (n_1));
  INV_X4 g39(.A (rst_n), .ZN (n_0));
endmodule

module D_FF_12(q, d, rst_n, clk, init_value);
  input d, rst_n, clk, init_value;
  output q;
  wire d, rst_n, clk, init_value;
  wire q;
  wire UNCONNECTED0, n_0, n_1, n_2;
  DFFRS_X2 q_reg(.RN (n_1), .SN (n_2), .CK (clk), .D (d), .Q (q), .QN
       (UNCONNECTED0));
  NAND2_X1 g37__6260(.A1 (n_0), .A2 (init_value), .ZN (n_2));
  OR2_X1 g38__4319(.A1 (rst_n), .A2 (init_value), .ZN (n_1));
  INV_X4 g39(.A (rst_n), .ZN (n_0));
endmodule

module D_FF_11(q, d, rst_n, clk, init_value);
  input d, rst_n, clk, init_value;
  output q;
  wire d, rst_n, clk, init_value;
  wire q;
  wire UNCONNECTED1, n_0, n_1, n_2;
  DFFRS_X1 q_reg(.RN (n_1), .SN (n_2), .CK (clk), .D (d), .Q (q), .QN
       (UNCONNECTED1));
  NAND2_X1 g37__8428(.A1 (n_0), .A2 (init_value), .ZN (n_2));
  OR2_X1 g38__5526(.A1 (rst_n), .A2 (init_value), .ZN (n_1));
  INV_X4 g39(.A (rst_n), .ZN (n_0));
endmodule

module D_FF_10(q, d, rst_n, clk, init_value);
  input d, rst_n, clk, init_value;
  output q;
  wire d, rst_n, clk, init_value;
  wire q;
  wire UNCONNECTED2, n_0, n_1, n_2;
  DFFRS_X2 q_reg(.RN (n_1), .SN (n_2), .CK (clk), .D (d), .Q (q), .QN
       (UNCONNECTED2));
  NAND2_X1 g37__6783(.A1 (n_0), .A2 (init_value), .ZN (n_2));
  OR2_X1 g38__3680(.A1 (rst_n), .A2 (init_value), .ZN (n_1));
  INV_X4 g39(.A (rst_n), .ZN (n_0));
endmodule

module D_FF_9(q, d, rst_n, clk, init_value);
  input d, rst_n, clk, init_value;
  output q;
  wire d, rst_n, clk, init_value;
  wire q;
  wire UNCONNECTED3, n_0, n_1, n_2;
  DFFRS_X2 q_reg(.RN (n_1), .SN (n_2), .CK (clk), .D (d), .Q (q), .QN
       (UNCONNECTED3));
  NAND2_X1 g37__1617(.A1 (n_0), .A2 (init_value), .ZN (n_2));
  OR2_X1 g38__2802(.A1 (rst_n), .A2 (init_value), .ZN (n_1));
  INV_X4 g39(.A (rst_n), .ZN (n_0));
endmodule

module random_counter_lfsr(clk, rst_n, initialized_value,
     counter_random);
  input clk, rst_n;
  input [4:0] initialized_value;
  output [4:0] counter_random;
  wire clk, rst_n;
  wire [4:0] initialized_value;
  wire [4:0] counter_random;
  wire d_xor;
  D_FF u0(.q (counter_random[0]), .d (counter_random[4]), .rst_n
       (rst_n), .clk (clk), .init_value (initialized_value[0]));
  D_FF_12 u1(.q (counter_random[1]), .d (counter_random[0]), .rst_n
       (rst_n), .clk (clk), .init_value (initialized_value[1]));
  D_FF_11 u2(.q (counter_random[2]), .d (d_xor), .rst_n (rst_n), .clk
       (clk), .init_value (initialized_value[2]));
  D_FF_10 u3(.q (counter_random[3]), .d (counter_random[2]), .rst_n
       (rst_n), .clk (clk), .init_value (initialized_value[3]));
  D_FF_9 u4(.q (counter_random[4]), .d (counter_random[3]), .rst_n
       (rst_n), .clk (clk), .init_value (initialized_value[4]));
  XOR2_X1 g13__1705(.A (counter_random[4]), .B (counter_random[1]), .Z
       (d_xor));
endmodule

