
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 17:03:58 IST (Jun 13 2025 11:33:58 UTC)

// Verification Directory fv/double_sync_high 

module double_sync_high(in_data, out_clk, out_rst_n, out_data);
  input [0:0] in_data;
  input out_clk, out_rst_n;
  output [0:0] out_data;
  wire [0:0] in_data;
  wire out_clk, out_rst_n;
  wire [0:0] out_data;
  wire [0:0] in_data_2s;
  wire [0:0] in_data_s;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1;
  DFFR_X1 \in_data_3s_reg[0] (.RN (out_rst_n), .CK (out_clk), .D
       (in_data_2s), .Q (out_data), .QN (UNCONNECTED));
  DFFR_X2 \in_data_2s_reg[0] (.RN (out_rst_n), .CK (out_clk), .D
       (in_data_s), .Q (in_data_2s), .QN (UNCONNECTED0));
  DFFR_X2 \in_data_s_reg[0] (.RN (out_rst_n), .CK (out_clk), .D
       (in_data), .Q (in_data_s), .QN (UNCONNECTED1));
endmodule

