
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 17:03:58 IST (Jun 13 2025 11:33:58 UTC)

// Verification Directory fv/generic_intr_stat_reg 

module generic_intr_stat_reg(clk, reset_n, reg_we, reg_din, hware_req,
     data_out);
  input clk, reset_n;
  input [0:0] reg_we, reg_din, hware_req;
  output [0:0] data_out;
  wire clk, reset_n;
  wire [0:0] reg_we, reg_din, hware_req;
  wire [0:0] data_out;
  wire UNCONNECTED, n_0, n_1;
  DFFR_X2 \gen_bit_reg[0].u_bit_reg_data_out_reg (.RN (reset_n), .CK
       (clk), .D (n_1), .Q (data_out), .QN (UNCONNECTED));
  MUX2_X2 g63__2398(.A (hware_req), .B (data_out), .S (n_0), .Z (n_1));
  AOI21_X1 g64__5107(.A (hware_req), .B1 (reg_we), .B2 (reg_din), .ZN
       (n_0));
endmodule

