
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 13 2025 17:03:58 IST (Jun 13 2025 11:33:58 UTC)

// Verification Directory fv/req_register 

module req_register(clk, reset_n, cpu_we, cpu_req, hware_ack, data_out);
  input clk, reset_n, cpu_we, cpu_req, hware_ack;
  output data_out;
  wire clk, reset_n, cpu_we, cpu_req, hware_ack;
  wire data_out;
  wire UNCONNECTED, n_0, n_1, n_2;
  DFFR_X2 data_out_reg(.RN (reset_n), .CK (clk), .D (n_2), .Q
       (data_out), .QN (UNCONNECTED));
  MUX2_X2 g63__2398(.A (n_0), .B (data_out), .S (n_1), .Z (n_2));
  NOR2_X1 g64__5107(.A1 (n_0), .A2 (hware_ack), .ZN (n_1));
  AND2_X4 g65__6260(.A1 (cpu_we), .A2 (cpu_req), .ZN (n_0));
endmodule

