
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 14 2025 12:55:03 IST (Apr 14 2025 07:25:03 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, en, q);
  input clk, rst, en;
  output [31:0] q;
  wire clk, rst, en;
  wire [31:0] q;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire inc_add_16_8_n_0, inc_add_16_8_n_1, inc_add_16_8_n_3,
       inc_add_16_8_n_5, inc_add_16_8_n_6, inc_add_16_8_n_7,
       inc_add_16_8_n_8, inc_add_16_8_n_9;
  wire inc_add_16_8_n_10, inc_add_16_8_n_12, inc_add_16_8_n_13,
       inc_add_16_8_n_16, inc_add_16_8_n_17, inc_add_16_8_n_18,
       inc_add_16_8_n_19, inc_add_16_8_n_22;
  wire inc_add_16_8_n_23, inc_add_16_8_n_26, inc_add_16_8_n_27,
       inc_add_16_8_n_28, inc_add_16_8_n_30, inc_add_16_8_n_31,
       inc_add_16_8_n_33, inc_add_16_8_n_36;
  wire inc_add_16_8_n_37, inc_add_16_8_n_39, inc_add_16_8_n_42,
       inc_add_16_8_n_43, inc_add_16_8_n_45, inc_add_16_8_n_48,
       inc_add_16_8_n_50, inc_add_16_8_n_54;
  wire inc_add_16_8_n_56, inc_add_16_8_n_59, inc_add_16_8_n_63, n_0,
       n_1, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_99;
  INV_X1 g772(.A (rst), .ZN (n_45));
  DFF_X2 \q_reg[27] (.CK (clk), .D (n_30), .Q (q[27]), .QN
       (UNCONNECTED));
  DFF_X2 \q_reg[13] (.CK (clk), .D (n_28), .Q (q[13]), .QN
       (UNCONNECTED0));
  DFF_X2 \q_reg[14] (.CK (clk), .D (n_42), .Q (q[14]), .QN
       (UNCONNECTED1));
  DFF_X2 \q_reg[15] (.CK (clk), .D (n_40), .Q (q[15]), .QN
       (UNCONNECTED2));
  DFF_X2 \q_reg[16] (.CK (clk), .D (n_41), .Q (q[16]), .QN
       (UNCONNECTED3));
  DFF_X2 \q_reg[17] (.CK (clk), .D (n_39), .Q (q[17]), .QN
       (UNCONNECTED4));
  DFF_X2 \q_reg[18] (.CK (clk), .D (n_38), .Q (q[18]), .QN
       (UNCONNECTED5));
  DFF_X2 \q_reg[19] (.CK (clk), .D (n_37), .Q (q[19]), .QN
       (UNCONNECTED6));
  DFF_X2 \q_reg[20] (.CK (clk), .D (n_36), .Q (q[20]), .QN
       (UNCONNECTED7));
  DFF_X2 \q_reg[21] (.CK (clk), .D (n_35), .Q (q[21]), .QN
       (UNCONNECTED8));
  DFF_X2 \q_reg[22] (.CK (clk), .D (n_34), .Q (q[22]), .QN
       (UNCONNECTED9));
  DFF_X2 \q_reg[23] (.CK (clk), .D (n_33), .Q (q[23]), .QN
       (UNCONNECTED10));
  DFF_X2 \q_reg[24] (.CK (clk), .D (n_32), .Q (q[24]), .QN
       (UNCONNECTED11));
  DFF_X2 \q_reg[25] (.CK (clk), .D (n_31), .Q (q[25]), .QN
       (UNCONNECTED12));
  DFF_X2 \q_reg[26] (.CK (clk), .D (n_44), .Q (q[26]), .QN
       (UNCONNECTED13));
  DFF_X2 \q_reg[1] (.CK (clk), .D (n_25), .Q (q[1]), .QN
       (UNCONNECTED14));
  DFF_X2 \q_reg[6] (.CK (clk), .D (n_20), .Q (q[6]), .QN
       (UNCONNECTED15));
  DFF_X2 \q_reg[30] (.CK (clk), .D (n_26), .Q (q[30]), .QN
       (UNCONNECTED16));
  DFF_X2 \q_reg[31] (.CK (clk), .D (n_27), .Q (q[31]), .QN
       (UNCONNECTED17));
  DFF_X2 \q_reg[2] (.CK (clk), .D (n_24), .Q (q[2]), .QN
       (UNCONNECTED18));
  DFF_X2 \q_reg[3] (.CK (clk), .D (n_23), .Q (q[3]), .QN
       (UNCONNECTED19));
  DFF_X2 \q_reg[4] (.CK (clk), .D (n_22), .Q (q[4]), .QN
       (UNCONNECTED20));
  DFF_X2 \q_reg[5] (.CK (clk), .D (n_21), .Q (q[5]), .QN
       (UNCONNECTED21));
  DFF_X2 \q_reg[29] (.CK (clk), .D (n_43), .Q (q[29]), .QN
       (UNCONNECTED22));
  DFF_X2 \q_reg[7] (.CK (clk), .D (n_19), .Q (q[7]), .QN
       (UNCONNECTED23));
  DFF_X2 \q_reg[8] (.CK (clk), .D (n_18), .Q (q[8]), .QN
       (UNCONNECTED24));
  DFF_X2 \q_reg[9] (.CK (clk), .D (n_17), .Q (q[9]), .QN
       (UNCONNECTED25));
  DFF_X2 \q_reg[10] (.CK (clk), .D (n_16), .Q (q[10]), .QN
       (UNCONNECTED26));
  DFF_X2 \q_reg[11] (.CK (clk), .D (n_15), .Q (q[11]), .QN
       (UNCONNECTED27));
  DFF_X2 \q_reg[12] (.CK (clk), .D (n_14), .Q (q[12]), .QN
       (UNCONNECTED28));
  DFF_X2 \q_reg[28] (.CK (clk), .D (n_13), .Q (q[28]), .QN
       (UNCONNECTED29));
  DFF_X2 \q_reg[0] (.CK (clk), .D (n_29), .Q (q[0]), .QN
       (UNCONNECTED30));
  AND2_X2 g1230__2398(.A1 (n_71), .A2 (n_12), .ZN (n_44));
  AND2_X2 g1231__5107(.A1 (n_74), .A2 (n_12), .ZN (n_43));
  AND2_X2 g1232__6260(.A1 (n_59), .A2 (n_12), .ZN (n_42));
  AND2_X2 g1233__4319(.A1 (n_61), .A2 (n_12), .ZN (n_41));
  AND2_X2 g1234__8428(.A1 (n_60), .A2 (n_12), .ZN (n_40));
  AND2_X2 g1235__5526(.A1 (n_62), .A2 (n_12), .ZN (n_39));
  AND2_X2 g1236__6783(.A1 (n_63), .A2 (n_12), .ZN (n_38));
  AND2_X2 g1237__3680(.A1 (n_64), .A2 (n_12), .ZN (n_37));
  AND2_X2 g1238__1617(.A1 (n_65), .A2 (n_12), .ZN (n_36));
  AND2_X2 g1239__2802(.A1 (n_66), .A2 (n_12), .ZN (n_35));
  AND2_X2 g1240__1705(.A1 (n_67), .A2 (n_12), .ZN (n_34));
  AND2_X2 g1241__5122(.A1 (n_68), .A2 (n_12), .ZN (n_33));
  AND2_X2 g1242__8246(.A1 (n_69), .A2 (n_12), .ZN (n_32));
  AND2_X2 g1243__7098(.A1 (n_70), .A2 (n_12), .ZN (n_31));
  AND2_X2 g1244__6131(.A1 (n_72), .A2 (n_12), .ZN (n_30));
  NOR2_X2 g1245__1881(.A1 (n_11), .A2 (q[0]), .ZN (n_29));
  AND2_X2 g1246__5115(.A1 (n_58), .A2 (n_12), .ZN (n_28));
  AND2_X2 g1247__7482(.A1 (n_76), .A2 (n_12), .ZN (n_27));
  AND2_X2 g1248__4733(.A1 (n_75), .A2 (n_12), .ZN (n_26));
  AND2_X2 g1249__6161(.A1 (n_12), .A2 (n_46), .ZN (n_25));
  AND2_X2 g1250__9315(.A1 (n_12), .A2 (n_47), .ZN (n_24));
  AND2_X2 g1251__9945(.A1 (n_12), .A2 (n_48), .ZN (n_23));
  AND2_X2 g1252__2883(.A1 (n_12), .A2 (n_49), .ZN (n_22));
  AND2_X2 g1253__2346(.A1 (n_12), .A2 (n_50), .ZN (n_21));
  AND2_X2 g1254__1666(.A1 (n_51), .A2 (n_12), .ZN (n_20));
  AND2_X2 g1255__7410(.A1 (n_52), .A2 (n_12), .ZN (n_19));
  AND2_X2 g1256__6417(.A1 (n_12), .A2 (n_53), .ZN (n_18));
  AND2_X2 g1257__5477(.A1 (n_54), .A2 (n_12), .ZN (n_17));
  AND2_X2 g1258__2398(.A1 (n_55), .A2 (n_12), .ZN (n_16));
  AND2_X2 g1259__5107(.A1 (n_56), .A2 (n_12), .ZN (n_15));
  AND2_X2 g1260__6260(.A1 (n_57), .A2 (n_12), .ZN (n_14));
  AND2_X2 g1261__4319(.A1 (n_73), .A2 (n_12), .ZN (n_13));
  INV_X4 g1262(.A (n_12), .ZN (n_11));
  AND3_X4 g1263__8428(.A1 (n_10), .A2 (n_45), .A3 (en), .ZN (n_12));
  NAND2_X2 g1264__5526(.A1 (n_8), .A2 (n_9), .ZN (n_10));
  NOR4_X2 g1265__6783(.A1 (n_4), .A2 (n_6), .A3 (n_7), .A4 (n_5), .ZN
       (n_9));
  NOR4_X2 g1266__3680(.A1 (n_0), .A2 (n_3), .A3 (n_1), .A4 (n_99), .ZN
       (n_8));
  NAND4_X2 g1267__1617(.A1 (q[8]), .A2 (q[11]), .A3 (q[10]), .A4
       (q[9]), .ZN (n_7));
  NAND4_X2 g1268__2802(.A1 (q[12]), .A2 (q[3]), .A3 (q[2]), .A4 (q[1]),
       .ZN (n_6));
  NAND4_X2 g1269__1705(.A1 (q[4]), .A2 (q[7]), .A3 (q[6]), .A4 (q[5]),
       .ZN (n_5));
  NAND4_X2 g1270__5122(.A1 (q[13]), .A2 (q[15]), .A3 (q[14]), .A4
       (q[0]), .ZN (n_4));
  NAND4_X2 g1271__8246(.A1 (q[27]), .A2 (q[26]), .A3 (q[24]), .A4
       (q[25]), .ZN (n_3));
  NAND4_X2 g1273__6131(.A1 (q[23]), .A2 (q[22]), .A3 (q[20]), .A4
       (q[21]), .ZN (n_1));
  NAND4_X2 g1274__1881(.A1 (q[28]), .A2 (q[31]), .A3 (q[30]), .A4
       (q[29]), .ZN (n_0));
  XOR2_X2 inc_add_16_8_g482__5115(.A (inc_add_16_8_n_63), .B (q[19]),
       .Z (n_64));
  XOR2_X2 inc_add_16_8_g483__7482(.A (inc_add_16_8_n_59), .B (q[31]),
       .Z (n_76));
  HA_X1 inc_add_16_8_g484__4733(.A (inc_add_16_8_n_50), .B (q[18]), .CO
       (inc_add_16_8_n_63), .S (n_63));
  XOR2_X2 inc_add_16_8_g485__6161(.A (inc_add_16_8_n_56), .B (q[29]),
       .Z (n_74));
  XOR2_X2 inc_add_16_8_g486__9315(.A (inc_add_16_8_n_54), .B (q[11]),
       .Z (n_56));
  HA_X1 inc_add_16_8_g487__9945(.A (inc_add_16_8_n_42), .B (q[30]), .CO
       (inc_add_16_8_n_59), .S (n_75));
  XOR2_X2 inc_add_16_8_g488__2883(.A (inc_add_16_8_n_48), .B (q[27]),
       .Z (n_72));
  HA_X1 inc_add_16_8_g489__2346(.A (inc_add_16_8_n_36), .B (q[28]), .CO
       (inc_add_16_8_n_56), .S (n_73));
  HA_X1 inc_add_16_8_g490__1666(.A (inc_add_16_8_n_37), .B (q[10]), .CO
       (inc_add_16_8_n_54), .S (n_55));
  XOR2_X2 inc_add_16_8_g491__7410(.A (inc_add_16_8_n_45), .B (q[25]),
       .Z (n_70));
  XOR2_X2 inc_add_16_8_g492__6417(.A (inc_add_16_8_n_43), .B (q[23]),
       .Z (n_68));
  HA_X1 inc_add_16_8_g493__5477(.A (inc_add_16_8_n_33), .B (q[17]), .CO
       (inc_add_16_8_n_50), .S (n_62));
  HA_X1 inc_add_16_8_g494__2398(.A (inc_add_16_8_n_30), .B (q[26]), .CO
       (inc_add_16_8_n_48), .S (n_71));
  XOR2_X2 inc_add_16_8_g495__5107(.A (inc_add_16_8_n_39), .B (q[21]),
       .Z (n_66));
  HA_X1 inc_add_16_8_g496__6260(.A (inc_add_16_8_n_26), .B (q[24]), .CO
       (inc_add_16_8_n_45), .S (n_69));
  HA_X1 inc_add_16_8_g497__4319(.A (inc_add_16_8_n_27), .B (q[22]), .CO
       (inc_add_16_8_n_43), .S (n_67));
  AND3_X4 inc_add_16_8_g498__8428(.A1 (inc_add_16_8_n_36), .A2 (q[28]),
       .A3 (q[29]), .ZN (inc_add_16_8_n_42));
  XOR2_X2 inc_add_16_8_g499__5526(.A (inc_add_16_8_n_31), .B (q[15]),
       .Z (n_60));
  HA_X1 inc_add_16_8_g500__6783(.A (inc_add_16_8_n_22), .B (q[20]), .CO
       (inc_add_16_8_n_39), .S (n_65));
  HA_X1 inc_add_16_8_g501__3680(.A (inc_add_16_8_n_23), .B (q[9]), .CO
       (inc_add_16_8_n_37), .S (n_54));
  AND3_X2 inc_add_16_8_g502__1617(.A1 (inc_add_16_8_n_30), .A2 (q[26]),
       .A3 (q[27]), .ZN (inc_add_16_8_n_36));
  XOR2_X2 inc_add_16_8_g503__2802(.A (inc_add_16_8_n_28), .B (q[13]),
       .Z (n_58));
  HA_X1 inc_add_16_8_g504__1705(.A (inc_add_16_8_n_17), .B (q[16]), .CO
       (inc_add_16_8_n_33), .S (n_61));
  HA_X1 inc_add_16_8_g505__5122(.A (inc_add_16_8_n_18), .B (q[14]), .CO
       (inc_add_16_8_n_31), .S (n_59));
  AND3_X2 inc_add_16_8_g506__8246(.A1 (inc_add_16_8_n_26), .A2 (q[24]),
       .A3 (q[25]), .ZN (inc_add_16_8_n_30));
  HA_X1 inc_add_16_8_g507__7098(.A (inc_add_16_8_n_12), .B (q[12]), .CO
       (inc_add_16_8_n_28), .S (n_57));
  AND2_X2 inc_add_16_8_g508__6131(.A1 (inc_add_16_8_n_22), .A2
       (inc_add_16_8_n_1), .ZN (inc_add_16_8_n_27));
  AND4_X2 inc_add_16_8_g509__1881(.A1 (inc_add_16_8_n_22), .A2
       (inc_add_16_8_n_1), .A3 (q[23]), .A4 (q[22]), .ZN
       (inc_add_16_8_n_26));
  XOR2_X2 inc_add_16_8_g510__5115(.A (inc_add_16_8_n_19), .B (q[7]), .Z
       (n_52));
  HA_X1 inc_add_16_8_g511__7482(.A (inc_add_16_8_n_9), .B (q[8]), .CO
       (inc_add_16_8_n_23), .S (n_53));
  NOR2_X2 inc_add_16_8_g512__4733(.A1 (inc_add_16_8_n_16), .A2 (n_99),
       .ZN (inc_add_16_8_n_22));
  XOR2_X1 inc_add_16_8_g513__6161(.A (inc_add_16_8_n_13), .B (q[5]), .Z
       (n_50));
  HA_X1 inc_add_16_8_g514__9315(.A (inc_add_16_8_n_7), .B (q[6]), .CO
       (inc_add_16_8_n_19), .S (n_51));
  AND2_X2 inc_add_16_8_g515__9945(.A1 (inc_add_16_8_n_12), .A2
       (inc_add_16_8_n_0), .ZN (inc_add_16_8_n_18));
  INV_X1 inc_add_16_8_g516(.A (inc_add_16_8_n_16), .ZN
       (inc_add_16_8_n_17));
  NAND4_X2 inc_add_16_8_g517__2883(.A1 (inc_add_16_8_n_12), .A2
       (inc_add_16_8_n_0), .A3 (q[14]), .A4 (q[15]), .ZN
       (inc_add_16_8_n_16));
  XOR2_X1 inc_add_16_8_g518__2346(.A (inc_add_16_8_n_10), .B (q[3]), .Z
       (n_48));
  HA_X1 inc_add_16_8_g519__1666(.A (inc_add_16_8_n_6), .B (q[4]), .CO
       (inc_add_16_8_n_13), .S (n_49));
  NOR2_X2 inc_add_16_8_g520__7410(.A1 (inc_add_16_8_n_8), .A2
       (inc_add_16_8_n_3), .ZN (inc_add_16_8_n_12));
  HA_X1 inc_add_16_8_g521__6417(.A (inc_add_16_8_n_5), .B (q[2]), .CO
       (inc_add_16_8_n_10), .S (n_47));
  INV_X1 inc_add_16_8_g522(.A (inc_add_16_8_n_8), .ZN
       (inc_add_16_8_n_9));
  NAND3_X1 inc_add_16_8_g523__5477(.A1 (inc_add_16_8_n_7), .A2 (q[7]),
       .A3 (q[6]), .ZN (inc_add_16_8_n_8));
  AND3_X2 inc_add_16_8_g524__2398(.A1 (inc_add_16_8_n_6), .A2 (q[4]),
       .A3 (q[5]), .ZN (inc_add_16_8_n_7));
  AND3_X2 inc_add_16_8_g525__5107(.A1 (inc_add_16_8_n_5), .A2 (q[2]),
       .A3 (q[3]), .ZN (inc_add_16_8_n_6));
  HA_X1 inc_add_16_8_g526__6260(.A (q[0]), .B (q[1]), .CO
       (inc_add_16_8_n_5), .S (n_46));
  NAND4_X2 inc_add_16_8_g527__4319(.A1 (q[11]), .A2 (q[8]), .A3 (q[9]),
       .A4 (q[10]), .ZN (inc_add_16_8_n_3));
  AND2_X2 inc_add_16_8_g529__5526(.A1 (q[20]), .A2 (q[21]), .ZN
       (inc_add_16_8_n_1));
  AND2_X2 inc_add_16_8_g530__6783(.A1 (q[12]), .A2 (q[13]), .ZN
       (inc_add_16_8_n_0));
  NAND4_X2 g1272__1308(.A1 (q[19]), .A2 (q[18]), .A3 (q[16]), .A4
       (q[17]), .ZN (n_99));
endmodule

