
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 16 2025 09:30:58 IST (May 16 2025 04:00:58 UTC)

// Verification Directory fv/counter_16bit 

module counter_16bit(clk, rst, Q);
  input clk, rst;
  output [15:0] Q;
  wire clk, rst;
  wire [15:0] Q;
  wire \Q[0]_85 , UNCONNECTED, UNCONNECTED0, UNCONNECTED1,
       UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5;
  wire UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9,
       UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29;
  DFFR_X1 \Q_reg[15] (.RN (rst), .CK (clk), .D (n_29), .Q (Q[15]), .QN
       (UNCONNECTED));
  XOR2_X2 g783__2398(.A (Q[15]), .B (n_27), .Z (n_29));
  DFFR_X1 \Q_reg[14] (.RN (rst), .CK (clk), .D (n_28), .Q (Q[14]), .QN
       (UNCONNECTED0));
  HA_X1 g785__5107(.A (n_25), .B (Q[14]), .CO (n_27), .S (n_28));
  DFFR_X1 \Q_reg[11] (.RN (rst), .CK (clk), .D (n_24), .Q (Q[11]), .QN
       (UNCONNECTED1));
  DFFR_X1 \Q_reg[13] (.RN (rst), .CK (clk), .D (n_26), .Q (Q[13]), .QN
       (UNCONNECTED2));
  HA_X1 g789__6260(.A (n_20), .B (Q[13]), .CO (n_25), .S (n_26));
  XOR2_X2 g788__4319(.A (Q[11]), .B (n_22), .Z (n_24));
  DFFR_X1 \Q_reg[10] (.RN (rst), .CK (clk), .D (n_23), .Q (Q[10]), .QN
       (UNCONNECTED3));
  DFFR_X1 \Q_reg[12] (.RN (rst), .CK (clk), .D (n_21), .Q (Q[12]), .QN
       (UNCONNECTED4));
  HA_X1 g791__8428(.A (n_18), .B (Q[10]), .CO (n_22), .S (n_23));
  HA_X1 g793__5526(.A (n_17), .B (Q[12]), .CO (n_20), .S (n_21));
  DFFR_X1 \Q_reg[9] (.RN (rst), .CK (clk), .D (n_19), .Q (Q[9]), .QN
       (UNCONNECTED5));
  HA_X1 g795__6783(.A (n_16), .B (Q[9]), .CO (n_18), .S (n_19));
  AND4_X4 g797__3680(.A1 (n_16), .A2 (Q[11]), .A3 (Q[10]), .A4 (Q[9]),
       .ZN (n_17));
  DFFR_X1 \Q_reg[8] (.RN (rst), .CK (clk), .D (n_15), .Q (Q[8]), .QN
       (UNCONNECTED6));
  HA_X1 g798__1617(.A (n_13), .B (Q[8]), .CO (n_16), .S (n_15));
  DFFR_X1 \Q_reg[7] (.RN (rst), .CK (clk), .D (n_14), .Q (Q[7]), .QN
       (UNCONNECTED7));
  HA_X1 g800__2802(.A (n_11), .B (Q[7]), .CO (n_13), .S (n_14));
  DFFR_X1 \Q_reg[6] (.RN (rst), .CK (clk), .D (n_12), .Q (Q[6]), .QN
       (UNCONNECTED8));
  HA_X1 g802__1705(.A (n_9), .B (Q[6]), .CO (n_11), .S (n_12));
  DFFR_X1 \Q_reg[5] (.RN (rst), .CK (clk), .D (n_10), .Q (Q[5]), .QN
       (UNCONNECTED9));
  HA_X1 g804__5122(.A (n_7), .B (Q[5]), .CO (n_9), .S (n_10));
  DFFR_X2 \Q_reg[4] (.RN (rst), .CK (clk), .D (n_8), .Q (Q[4]), .QN
       (UNCONNECTED10));
  HA_X1 g806__8246(.A (n_5), .B (Q[4]), .CO (n_7), .S (n_8));
  DFFR_X2 \Q_reg[3] (.RN (rst), .CK (clk), .D (n_6), .Q (Q[3]), .QN
       (UNCONNECTED11));
  HA_X1 g808__7098(.A (n_3), .B (Q[3]), .CO (n_5), .S (n_6));
  DFFR_X2 \Q_reg[2] (.RN (rst), .CK (clk), .D (n_4), .Q (Q[2]), .QN
       (UNCONNECTED12));
  HA_X1 g810__6131(.A (n_1), .B (Q[2]), .CO (n_3), .S (n_4));
  DFFR_X2 \Q_reg[1] (.RN (rst), .CK (clk), .D (n_2), .Q (Q[1]), .QN
       (UNCONNECTED13));
  HA_X1 g812__1881(.A (Q[1]), .B (Q[0]), .CO (n_1), .S (n_2));
  DFFR_X2 \Q_reg[0] (.RN (rst), .CK (clk), .D (\Q[0]_85 ), .Q (Q[0]),
       .QN (\Q[0]_85 ));
endmodule

