
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  2 2025 09:50:16 IST (May  2 2025 04:20:16 UTC)

// Verification Directory fv/sram_sp_32768d_33w_16m_8b 

module sram_sp_32768d_33w_16m_8b(CLK, CEN, GWEN, A, D, WEN, Q);
  input CLK, CEN, GWEN;
  input [14:0] A;
  input [32:0] D, WEN;
  output [32:0] Q;
  wire CLK, CEN, GWEN;
  wire [14:0] A;
  wire [32:0] D, WEN;
  wire [32:0] Q;
  wire [4:0] \q_5bit[0] ;
  wire [6:0] \q_7bit[0] ;
  wire [6:0] \q_7bit[1] ;
  wire [6:0] \q_7bit[2] ;
  wire [6:0] \q_7bit[3] ;
  wire [4:0] \q_5bit[1] ;
  wire [6:0] \q_7bit[4] ;
  wire [6:0] \q_7bit[5] ;
  wire [6:0] \q_7bit[6] ;
  wire [6:0] \q_7bit[7] ;
  wire [4:0] \q_5bit[2] ;
  wire [6:0] \q_7bit[8] ;
  wire [6:0] \q_7bit[9] ;
  wire [6:0] \q_7bit[10] ;
  wire [6:0] \q_7bit[11] ;
  wire [4:0] \q_5bit[3] ;
  wire [6:0] \q_7bit[12] ;
  wire [6:0] \q_7bit[13] ;
  wire [6:0] \q_7bit[14] ;
  wire [6:0] \q_7bit[15] ;
  wire \cen_internal[0] , \cen_internal[1] , \cen_internal[2] ,
       \cen_internal[3] , n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71;
  spram_8192_5 \gen_banks[0].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[0] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[32:28]), .O (\q_5bit[0] ));
  spram_8192_7 \gen_banks[0].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[6:0]), .O (\q_7bit[0] ));
  spram_8192_7 \gen_banks[0].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[13:7]), .O (\q_7bit[1] ));
  spram_8192_7 \gen_banks[0].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[20:14]), .O (\q_7bit[2] ));
  spram_8192_7 \gen_banks[0].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[27:21]), .O (\q_7bit[3] ));
  spram_8192_5 \gen_banks[1].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[1] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[32:28]), .O (\q_5bit[1] ));
  spram_8192_7 \gen_banks[1].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[6:0]), .O (\q_7bit[4] ));
  spram_8192_7 \gen_banks[1].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[13:7]), .O (\q_7bit[5] ));
  spram_8192_7 \gen_banks[1].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[20:14]), .O (\q_7bit[6] ));
  spram_8192_7 \gen_banks[1].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[27:21]), .O (\q_7bit[7] ));
  spram_8192_5 \gen_banks[2].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[2] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[32:28]), .O (\q_5bit[2] ));
  spram_8192_7 \gen_banks[2].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[6:0]), .O (\q_7bit[8] ));
  spram_8192_7 \gen_banks[2].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[13:7]), .O (\q_7bit[9] ));
  spram_8192_7 \gen_banks[2].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[20:14]), .O (\q_7bit[10] ));
  spram_8192_7 \gen_banks[2].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[27:21]), .O (\q_7bit[11] ));
  spram_8192_5 \gen_banks[3].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[3] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[32:28]), .O (\q_5bit[3] ));
  spram_8192_7 \gen_banks[3].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[6:0]), .O (\q_7bit[12] ));
  spram_8192_7 \gen_banks[3].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[13:7]), .O (\q_7bit[13] ));
  spram_8192_7 \gen_banks[3].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[20:14]), .O (\q_7bit[14] ));
  spram_8192_7 \gen_banks[3].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (GWEN), .A (A[12:0]), .I
       (D[27:21]), .O (\q_7bit[15] ));
  OR2X2 g2701__2398(.A (n_45), .B (n_43), .Y (Q[3]));
  OR2X2 g2702__5107(.A (n_57), .B (n_10), .Y (Q[31]));
  OR2X2 g2703__6260(.A (n_71), .B (n_53), .Y (Q[26]));
  OR2X2 g2704__4319(.A (n_70), .B (n_67), .Y (Q[21]));
  OR2X2 g2705__8428(.A (n_69), .B (n_68), .Y (Q[9]));
  OR2X2 g2706__5526(.A (n_65), .B (n_64), .Y (Q[8]));
  OR2X2 g2707__6783(.A (n_63), .B (n_59), .Y (Q[20]));
  OR2X2 g2708__3680(.A (n_62), .B (n_60), .Y (Q[7]));
  OR2X2 g2709__1617(.A (n_54), .B (n_50), .Y (Q[19]));
  OR2X2 g2710__2802(.A (n_58), .B (n_56), .Y (Q[6]));
  OR2X2 g2711__1705(.A (n_52), .B (n_51), .Y (Q[5]));
  OR2X2 g2712__5122(.A (n_49), .B (n_48), .Y (Q[4]));
  OR2X2 g2713__8246(.A (n_47), .B (n_31), .Y (Q[29]));
  OR2X2 g2714__7098(.A (n_42), .B (n_34), .Y (Q[25]));
  OR2X2 g2715__6131(.A (n_46), .B (n_44), .Y (Q[18]));
  OR2X2 g2716__1881(.A (n_61), .B (n_22), .Y (Q[32]));
  OR2X2 g2717__5115(.A (n_39), .B (n_35), .Y (Q[17]));
  OR2X2 g2718__7482(.A (n_41), .B (n_40), .Y (Q[2]));
  OR2X2 g2719__4733(.A (n_37), .B (n_36), .Y (Q[1]));
  OR2X2 g2720__6161(.A (n_28), .B (n_25), .Y (Q[24]));
  OR2X2 g2721__9315(.A (n_30), .B (n_29), .Y (Q[16]));
  OR2X2 g2722__9945(.A (n_33), .B (n_32), .Y (Q[0]));
  OR2X2 g2723__2883(.A (n_9), .B (n_55), .Y (Q[30]));
  OR2X2 g2724__2346(.A (n_23), .B (n_15), .Y (Q[28]));
  OR2X2 g2725__1666(.A (n_27), .B (n_26), .Y (Q[15]));
  OR2X2 g2726__7410(.A (n_24), .B (n_38), .Y (Q[14]));
  OR2X2 g2727__6417(.A (n_21), .B (n_18), .Y (Q[23]));
  OR2X2 g2728__5477(.A (n_20), .B (n_19), .Y (Q[13]));
  OR2X2 g2729__2398(.A (n_7), .B (n_66), .Y (Q[27]));
  OR2X2 g2730__5107(.A (n_14), .B (n_12), .Y (Q[22]));
  OR2X2 g2731__6260(.A (n_17), .B (n_16), .Y (Q[12]));
  OR2X2 g2732__4319(.A (n_13), .B (n_11), .Y (Q[11]));
  OR2X2 g2733__8428(.A (n_8), .B (n_6), .Y (Q[10]));
  AO22X2 g2734__5526(.A0 (n_5), .A1 (\q_7bit[11] [5]), .B0 (n_3), .B1
       (\q_7bit[15] [5]), .Y (n_71));
  AO22X2 g2735__6783(.A0 (n_5), .A1 (\q_7bit[11] [0]), .B0 (n_3), .B1
       (\q_7bit[15] [0]), .Y (n_70));
  AO22X2 g2736__3680(.A0 (n_5), .A1 (\q_7bit[9] [2]), .B0 (n_3), .B1
       (\q_7bit[13] [2]), .Y (n_69));
  AO22X2 g2737__1617(.A0 (n_4), .A1 (\q_7bit[1] [2]), .B0 (n_2), .B1
       (\q_7bit[5] [2]), .Y (n_68));
  AO22X2 g2738__2802(.A0 (n_4), .A1 (\q_7bit[3] [0]), .B0 (n_2), .B1
       (\q_7bit[7] [0]), .Y (n_67));
  AO22X2 g2739__1705(.A0 (n_4), .A1 (\q_7bit[3] [6]), .B0 (n_2), .B1
       (\q_7bit[7] [6]), .Y (n_66));
  AO22X2 g2740__5122(.A0 (n_5), .A1 (\q_7bit[9] [1]), .B0 (n_3), .B1
       (\q_7bit[13] [1]), .Y (n_65));
  AO22X2 g2741__8246(.A0 (n_4), .A1 (\q_7bit[1] [1]), .B0 (n_2), .B1
       (\q_7bit[5] [1]), .Y (n_64));
  AO22X2 g2742__7098(.A0 (n_5), .A1 (\q_7bit[10] [6]), .B0 (n_3), .B1
       (\q_7bit[14] [6]), .Y (n_63));
  AO22X2 g2743__6131(.A0 (n_5), .A1 (\q_7bit[9] [0]), .B0 (n_3), .B1
       (\q_7bit[13] [0]), .Y (n_62));
  AO22X2 g2744__1881(.A0 (n_5), .A1 (\q_5bit[2] [4]), .B0 (n_3), .B1
       (\q_5bit[3] [4]), .Y (n_61));
  AO22X2 g2745__5115(.A0 (n_4), .A1 (\q_7bit[1] [0]), .B0 (n_2), .B1
       (\q_7bit[5] [0]), .Y (n_60));
  AO22X2 g2746__7482(.A0 (n_4), .A1 (\q_7bit[2] [6]), .B0 (n_2), .B1
       (\q_7bit[6] [6]), .Y (n_59));
  AO22X2 g2747__4733(.A0 (n_5), .A1 (\q_7bit[8] [6]), .B0 (n_3), .B1
       (\q_7bit[12] [6]), .Y (n_58));
  AO22X2 g2748__6161(.A0 (n_5), .A1 (\q_5bit[2] [3]), .B0 (n_3), .B1
       (\q_5bit[3] [3]), .Y (n_57));
  AO22X2 g2749__9315(.A0 (n_4), .A1 (\q_7bit[0] [6]), .B0 (n_2), .B1
       (\q_7bit[4] [6]), .Y (n_56));
  AO22X2 g2750__9945(.A0 (n_4), .A1 (\q_5bit[0] [2]), .B0 (n_2), .B1
       (\q_5bit[1] [2]), .Y (n_55));
  AO22X2 g2751__2883(.A0 (n_5), .A1 (\q_7bit[10] [5]), .B0 (n_3), .B1
       (\q_7bit[14] [5]), .Y (n_54));
  AO22X2 g2752__2346(.A0 (n_4), .A1 (\q_7bit[3] [5]), .B0 (n_2), .B1
       (\q_7bit[7] [5]), .Y (n_53));
  AO22X2 g2753__1666(.A0 (n_5), .A1 (\q_7bit[8] [5]), .B0 (n_3), .B1
       (\q_7bit[12] [5]), .Y (n_52));
  AO22X2 g2754__7410(.A0 (n_4), .A1 (\q_7bit[0] [5]), .B0 (n_2), .B1
       (\q_7bit[4] [5]), .Y (n_51));
  AO22X2 g2755__6417(.A0 (n_4), .A1 (\q_7bit[2] [5]), .B0 (n_2), .B1
       (\q_7bit[6] [5]), .Y (n_50));
  AO22X2 g2756__5477(.A0 (n_5), .A1 (\q_7bit[8] [4]), .B0 (n_3), .B1
       (\q_7bit[12] [4]), .Y (n_49));
  AO22X2 g2757__2398(.A0 (n_4), .A1 (\q_7bit[0] [4]), .B0 (n_2), .B1
       (\q_7bit[4] [4]), .Y (n_48));
  AO22X2 g2758__5107(.A0 (n_5), .A1 (\q_5bit[2] [1]), .B0 (n_3), .B1
       (\q_5bit[3] [1]), .Y (n_47));
  AO22X2 g2759__6260(.A0 (n_5), .A1 (\q_7bit[10] [4]), .B0 (n_3), .B1
       (\q_7bit[14] [4]), .Y (n_46));
  AO22X2 g2760__4319(.A0 (n_5), .A1 (\q_7bit[8] [3]), .B0 (n_3), .B1
       (\q_7bit[12] [3]), .Y (n_45));
  AO22X2 g2761__8428(.A0 (n_4), .A1 (\q_7bit[2] [4]), .B0 (n_2), .B1
       (\q_7bit[6] [4]), .Y (n_44));
  AO22X2 g2762__5526(.A0 (n_4), .A1 (\q_7bit[0] [3]), .B0 (n_2), .B1
       (\q_7bit[4] [3]), .Y (n_43));
  AO22X2 g2763__6783(.A0 (n_5), .A1 (\q_7bit[11] [4]), .B0 (n_3), .B1
       (\q_7bit[15] [4]), .Y (n_42));
  AO22X2 g2764__3680(.A0 (n_5), .A1 (\q_7bit[8] [2]), .B0 (n_3), .B1
       (\q_7bit[12] [2]), .Y (n_41));
  AO22X2 g2765__1617(.A0 (n_4), .A1 (\q_7bit[0] [2]), .B0 (n_2), .B1
       (\q_7bit[4] [2]), .Y (n_40));
  AO22X2 g2766__2802(.A0 (n_5), .A1 (\q_7bit[10] [3]), .B0 (n_3), .B1
       (\q_7bit[14] [3]), .Y (n_39));
  AO22X2 g2767__1705(.A0 (n_4), .A1 (\q_7bit[2] [0]), .B0 (n_2), .B1
       (\q_7bit[6] [0]), .Y (n_38));
  AO22X2 g2768__5122(.A0 (n_5), .A1 (\q_7bit[8] [1]), .B0 (n_3), .B1
       (\q_7bit[12] [1]), .Y (n_37));
  AO22X2 g2769__8246(.A0 (n_4), .A1 (\q_7bit[0] [1]), .B0 (n_2), .B1
       (\q_7bit[4] [1]), .Y (n_36));
  AO22X2 g2770__7098(.A0 (n_4), .A1 (\q_7bit[2] [3]), .B0 (n_2), .B1
       (\q_7bit[6] [3]), .Y (n_35));
  AO22X2 g2771__6131(.A0 (n_4), .A1 (\q_7bit[3] [4]), .B0 (n_2), .B1
       (\q_7bit[7] [4]), .Y (n_34));
  AO22X2 g2772__1881(.A0 (n_5), .A1 (\q_7bit[8] [0]), .B0 (n_3), .B1
       (\q_7bit[12] [0]), .Y (n_33));
  AO22X2 g2773__5115(.A0 (n_4), .A1 (\q_7bit[0] [0]), .B0 (n_2), .B1
       (\q_7bit[4] [0]), .Y (n_32));
  AO22X2 g2774__7482(.A0 (n_4), .A1 (\q_5bit[0] [1]), .B0 (n_2), .B1
       (\q_5bit[1] [1]), .Y (n_31));
  AO22X2 g2775__4733(.A0 (n_5), .A1 (\q_7bit[10] [2]), .B0 (n_3), .B1
       (\q_7bit[14] [2]), .Y (n_30));
  AO22X2 g2776__6161(.A0 (n_4), .A1 (\q_7bit[2] [2]), .B0 (n_2), .B1
       (\q_7bit[6] [2]), .Y (n_29));
  AO22X2 g2777__9315(.A0 (n_5), .A1 (\q_7bit[11] [3]), .B0 (n_3), .B1
       (\q_7bit[15] [3]), .Y (n_28));
  AO22X2 g2778__9945(.A0 (n_5), .A1 (\q_7bit[10] [1]), .B0 (n_3), .B1
       (\q_7bit[14] [1]), .Y (n_27));
  AO22X2 g2779__2883(.A0 (n_4), .A1 (\q_7bit[2] [1]), .B0 (n_2), .B1
       (\q_7bit[6] [1]), .Y (n_26));
  AO22X2 g2780__2346(.A0 (n_4), .A1 (\q_7bit[3] [3]), .B0 (n_2), .B1
       (\q_7bit[7] [3]), .Y (n_25));
  AO22X2 g2781__1666(.A0 (n_5), .A1 (\q_7bit[10] [0]), .B0 (n_3), .B1
       (\q_7bit[14] [0]), .Y (n_24));
  AO22X2 g2782__7410(.A0 (n_5), .A1 (\q_5bit[2] [0]), .B0 (n_3), .B1
       (\q_5bit[3] [0]), .Y (n_23));
  AO22X2 g2783__6417(.A0 (n_4), .A1 (\q_5bit[0] [4]), .B0 (n_2), .B1
       (\q_5bit[1] [4]), .Y (n_22));
  AO22X2 g2784__5477(.A0 (n_5), .A1 (\q_7bit[11] [2]), .B0 (n_3), .B1
       (\q_7bit[15] [2]), .Y (n_21));
  AO22X2 g2785__2398(.A0 (n_5), .A1 (\q_7bit[9] [6]), .B0 (n_3), .B1
       (\q_7bit[13] [6]), .Y (n_20));
  AO22X2 g2786__5107(.A0 (n_4), .A1 (\q_7bit[1] [6]), .B0 (n_2), .B1
       (\q_7bit[5] [6]), .Y (n_19));
  AO22X2 g2787__6260(.A0 (n_4), .A1 (\q_7bit[3] [2]), .B0 (n_2), .B1
       (\q_7bit[7] [2]), .Y (n_18));
  AO22X2 g2788__4319(.A0 (n_5), .A1 (\q_7bit[9] [5]), .B0 (n_3), .B1
       (\q_7bit[13] [5]), .Y (n_17));
  AO22X2 g2789__8428(.A0 (n_4), .A1 (\q_7bit[1] [5]), .B0 (n_2), .B1
       (\q_7bit[5] [5]), .Y (n_16));
  AO22X2 g2790__5526(.A0 (n_4), .A1 (\q_5bit[0] [0]), .B0 (n_2), .B1
       (\q_5bit[1] [0]), .Y (n_15));
  AO22X2 g2791__6783(.A0 (n_5), .A1 (\q_7bit[11] [1]), .B0 (n_3), .B1
       (\q_7bit[15] [1]), .Y (n_14));
  AO22X2 g2792__3680(.A0 (n_5), .A1 (\q_7bit[9] [4]), .B0 (n_3), .B1
       (\q_7bit[13] [4]), .Y (n_13));
  AO22X2 g2793__1617(.A0 (n_4), .A1 (\q_7bit[3] [1]), .B0 (n_2), .B1
       (\q_7bit[7] [1]), .Y (n_12));
  AO22X2 g2794__2802(.A0 (n_4), .A1 (\q_7bit[1] [4]), .B0 (n_2), .B1
       (\q_7bit[5] [4]), .Y (n_11));
  AO22X2 g2795__1705(.A0 (n_4), .A1 (\q_5bit[0] [3]), .B0 (n_2), .B1
       (\q_5bit[1] [3]), .Y (n_10));
  AO22X2 g2796__5122(.A0 (n_5), .A1 (\q_5bit[2] [2]), .B0 (n_3), .B1
       (\q_5bit[3] [2]), .Y (n_9));
  AO22X2 g2797__8246(.A0 (n_5), .A1 (\q_7bit[9] [3]), .B0 (n_3), .B1
       (\q_7bit[13] [3]), .Y (n_8));
  AO22X2 g2798__7098(.A0 (n_5), .A1 (\q_7bit[11] [6]), .B0 (n_3), .B1
       (\q_7bit[15] [6]), .Y (n_7));
  AO22X2 g2799__6131(.A0 (n_4), .A1 (\q_7bit[1] [3]), .B0 (n_2), .B1
       (\q_7bit[5] [3]), .Y (n_6));
  NAND2BX4 g2800__1881(.AN (CEN), .B (n_2), .Y (\cen_internal[1] ));
  NAND2BX4 g2801__5115(.AN (CEN), .B (n_4), .Y (\cen_internal[0] ));
  NAND2BX4 g2802__7482(.AN (CEN), .B (n_3), .Y (\cen_internal[3] ));
  NAND2BX4 g2803__4733(.AN (CEN), .B (n_5), .Y (\cen_internal[2] ));
  AND2X8 g2804__6161(.A (A[14]), .B (n_0), .Y (n_5));
  NOR2X8 g2805__9315(.A (A[13]), .B (A[14]), .Y (n_4));
  AND2X8 g2806__9945(.A (A[13]), .B (A[14]), .Y (n_3));
  AND2X8 g2807__2883(.A (A[13]), .B (n_1), .Y (n_2));
  CLKINVX20 g2808(.A (A[14]), .Y (n_1));
  CLKINVX20 g2809(.A (A[13]), .Y (n_0));
endmodule

