/* Generated by Tessent Shell 2022.4 at Mon Apr 14 13:47:54 IST 2025 */
module counter(clk, rst, en, q, ts_si, ts_so, scan_en, int_ltest_en);
  input  [0:0] ts_si;
  input  clk, rst, en, scan_en, int_ltest_en;
  output [31:0] q;
  output [0:0] ts_so;

  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, 
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, 
       UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, 
       UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, UNCONNECTED16, 
       UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, 
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, 
       UNCONNECTED25, UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, 
       UNCONNECTED29, UNCONNECTED30, inc_add_16_8_n_0, inc_add_16_8_n_1, 
       inc_add_16_8_n_3, inc_add_16_8_n_5, inc_add_16_8_n_6, inc_add_16_8_n_7, 
       inc_add_16_8_n_8, inc_add_16_8_n_9, inc_add_16_8_n_10, 
       inc_add_16_8_n_12, inc_add_16_8_n_13, inc_add_16_8_n_16, 
       inc_add_16_8_n_17, inc_add_16_8_n_18, inc_add_16_8_n_19, 
       inc_add_16_8_n_22, inc_add_16_8_n_23, inc_add_16_8_n_26, 
       inc_add_16_8_n_27, inc_add_16_8_n_28, inc_add_16_8_n_30, 
       inc_add_16_8_n_31, inc_add_16_8_n_33, inc_add_16_8_n_36, 
       inc_add_16_8_n_37, inc_add_16_8_n_39, inc_add_16_8_n_42, 
       inc_add_16_8_n_43, inc_add_16_8_n_45, inc_add_16_8_n_48, 
       inc_add_16_8_n_50, inc_add_16_8_n_54, inc_add_16_8_n_56, 
       inc_add_16_8_n_59, inc_add_16_8_n_63, n_0, n_1, n_3, n_4, n_5, n_6, n_7, 
       n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19, 
       n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31, 
       n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43, 
       n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55, 
       n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67, 
       n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_99, 
       ts_lockup_latchp_clkc2_intno31_, 
       ts_pipeline_fsffn_clkc1_lo0l1_extsi32_sea0_, 
       ts_sihw_mux_sea0_not_so0__si0_, ts_sihw_not_so0_, ts_or_sea0_intstes0_, 
       ts_sihw_mux_sea0_not_so1__si1_, ts_sihw_not_so1_, 
       ts_sihw_mux_sea0_not_so2__si2_, ts_sihw_not_so2_, 
       ts_sihw_mux_sea0_not_so3__si3_, ts_sihw_not_so3_, 
       ts_sihw_mux_sea0_not_so4__si4_, ts_sihw_not_so4_, 
       ts_sihw_mux_sea0_not_so5__si5_, ts_sihw_not_so5_, 
       ts_sihw_mux_sea0_not_so6__si6_, ts_sihw_not_so6_, 
       ts_sihw_mux_sea0_not_so7__si7_, ts_sihw_not_so7_, 
       ts_sihw_mux_sea0_not_so8__si8_, ts_sihw_not_so8_, 
       ts_sihw_mux_sea0_not_so9__si9_, ts_sihw_not_so9_, 
       ts_sihw_mux_sea0_not_so10__si10_, ts_sihw_not_so10_, 
       ts_sihw_mux_sea0_not_so11__si11_, ts_sihw_not_so11_, 
       ts_sihw_mux_sea0_not_so12__si12_, ts_sihw_not_so12_, 
       ts_sihw_mux_sea0_not_so13__si13_, ts_sihw_not_so13_, 
       ts_sihw_mux_sea0_not_so14__si14_, ts_sihw_not_so14_, 
       ts_sihw_mux_sea0_not_so15__si15_, ts_sihw_not_so15_, 
       ts_sihw_mux_sea0_not_so16__si16_, ts_sihw_not_so16_, 
       ts_sihw_mux_sea0_not_so17__si17_, ts_sihw_not_so17_, 
       ts_sihw_mux_sea0_not_so18__si18_, ts_sihw_not_so18_, 
       ts_sihw_mux_sea0_not_so19__si19_, ts_sihw_not_so19_, 
       ts_sihw_mux_sea0_not_so20__si20_, ts_sihw_not_so20_, 
       ts_sihw_mux_sea0_not_so21__si21_, ts_sihw_not_so21_, 
       ts_sihw_mux_sea0_not_so22__si22_, ts_sihw_not_so22_, 
       ts_sihw_mux_sea0_not_so23__si23_, ts_sihw_not_so23_, 
       ts_sihw_mux_sea0_not_so24__si24_, ts_sihw_not_so24_, 
       ts_sihw_mux_sea0_not_so25__si25_, ts_sihw_not_so25_, 
       ts_sihw_mux_sea0_not_so26__si26_, ts_sihw_not_so26_, 
       ts_sihw_mux_sea0_not_so27__si27_, ts_sihw_not_so27_, 
       ts_sihw_mux_sea0_not_so28__si28_, ts_sihw_not_so28_, 
       ts_sihw_mux_sea0_not_so29__si29_, ts_sihw_not_so29_, 
       ts_sihw_mux_sea0_not_so30__si30_, ts_sihw_not_so30_, 
       ts_sihw_mux_sea0_not_so31__si31_, ts_sihw_not_so31_;

  assign ts_so = ts_lockup_latchp_clkc2_intno31_;
  INV_X1 g772(
      .A(rst), .ZN(n_45)
  );
  SDFF_X2 \q_reg[27] (
      .CK(clk), .D(n_30), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so0__si0_), 
      .Q(q[27]), .QN(UNCONNECTED)
  );
  SDFF_X2 \q_reg[13] (
      .CK(clk), .D(n_28), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so1__si1_), 
      .Q(q[13]), .QN(UNCONNECTED0)
  );
  SDFF_X2 \q_reg[14] (
      .CK(clk), .D(n_42), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so2__si2_), 
      .Q(q[14]), .QN(UNCONNECTED1)
  );
  SDFF_X2 \q_reg[15] (
      .CK(clk), .D(n_40), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so3__si3_), 
      .Q(q[15]), .QN(UNCONNECTED2)
  );
  SDFF_X2 \q_reg[16] (
      .CK(clk), .D(n_41), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so4__si4_), 
      .Q(q[16]), .QN(UNCONNECTED3)
  );
  SDFF_X2 \q_reg[17] (
      .CK(clk), .D(n_39), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so5__si5_), 
      .Q(q[17]), .QN(UNCONNECTED4)
  );
  SDFF_X2 \q_reg[18] (
      .CK(clk), .D(n_38), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so6__si6_), 
      .Q(q[18]), .QN(UNCONNECTED5)
  );
  SDFF_X2 \q_reg[19] (
      .CK(clk), .D(n_37), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so7__si7_), 
      .Q(q[19]), .QN(UNCONNECTED6)
  );
  SDFF_X2 \q_reg[20] (
      .CK(clk), .D(n_36), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so8__si8_), 
      .Q(q[20]), .QN(UNCONNECTED7)
  );
  SDFF_X2 \q_reg[21] (
      .CK(clk), .D(n_35), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so9__si9_), 
      .Q(q[21]), .QN(UNCONNECTED8)
  );
  SDFF_X2 \q_reg[22] (
      .CK(clk), .D(n_34), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so10__si10_), 
      .Q(q[22]), .QN(UNCONNECTED9)
  );
  SDFF_X2 \q_reg[23] (
      .CK(clk), .D(n_33), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so11__si11_), 
      .Q(q[23]), .QN(UNCONNECTED10)
  );
  SDFF_X2 \q_reg[24] (
      .CK(clk), .D(n_32), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so12__si12_), 
      .Q(q[24]), .QN(UNCONNECTED11)
  );
  SDFF_X2 \q_reg[25] (
      .CK(clk), .D(n_31), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so13__si13_), 
      .Q(q[25]), .QN(UNCONNECTED12)
  );
  SDFF_X2 \q_reg[26] (
      .CK(clk), .D(n_44), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so14__si14_), 
      .Q(q[26]), .QN(UNCONNECTED13)
  );
  SDFF_X2 \q_reg[1] (
      .CK(clk), .D(n_25), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so15__si15_), 
      .Q(q[1]), .QN(UNCONNECTED14)
  );
  SDFF_X2 \q_reg[6] (
      .CK(clk), .D(n_20), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so16__si16_), 
      .Q(q[6]), .QN(UNCONNECTED15)
  );
  SDFF_X2 \q_reg[30] (
      .CK(clk), .D(n_26), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so17__si17_), 
      .Q(q[30]), .QN(UNCONNECTED16)
  );
  SDFF_X2 \q_reg[31] (
      .CK(clk), .D(n_27), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so18__si18_), 
      .Q(q[31]), .QN(UNCONNECTED17)
  );
  SDFF_X2 \q_reg[2] (
      .CK(clk), .D(n_24), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so19__si19_), 
      .Q(q[2]), .QN(UNCONNECTED18)
  );
  SDFF_X2 \q_reg[3] (
      .CK(clk), .D(n_23), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so20__si20_), 
      .Q(q[3]), .QN(UNCONNECTED19)
  );
  SDFF_X2 \q_reg[4] (
      .CK(clk), .D(n_22), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so21__si21_), 
      .Q(q[4]), .QN(UNCONNECTED20)
  );
  SDFF_X2 \q_reg[5] (
      .CK(clk), .D(n_21), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so22__si22_), 
      .Q(q[5]), .QN(UNCONNECTED21)
  );
  SDFF_X2 \q_reg[29] (
      .CK(clk), .D(n_43), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so23__si23_), 
      .Q(q[29]), .QN(UNCONNECTED22)
  );
  SDFF_X2 \q_reg[7] (
      .CK(clk), .D(n_19), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so24__si24_), 
      .Q(q[7]), .QN(UNCONNECTED23)
  );
  SDFF_X2 \q_reg[8] (
      .CK(clk), .D(n_18), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so25__si25_), 
      .Q(q[8]), .QN(UNCONNECTED24)
  );
  SDFF_X2 \q_reg[9] (
      .CK(clk), .D(n_17), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so26__si26_), 
      .Q(q[9]), .QN(UNCONNECTED25)
  );
  SDFF_X2 \q_reg[10] (
      .CK(clk), .D(n_16), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so27__si27_), 
      .Q(q[10]), .QN(UNCONNECTED26)
  );
  SDFF_X2 \q_reg[11] (
      .CK(clk), .D(n_15), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so28__si28_), 
      .Q(q[11]), .QN(UNCONNECTED27)
  );
  SDFF_X2 \q_reg[12] (
      .CK(clk), .D(n_14), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so29__si29_), 
      .Q(q[12]), .QN(UNCONNECTED28)
  );
  SDFF_X2 \q_reg[28] (
      .CK(clk), .D(n_13), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so30__si30_), 
      .Q(q[28]), .QN(UNCONNECTED29)
  );
  SDFF_X2 \q_reg[0] (
      .CK(clk), .D(n_29), .SE(ts_or_sea0_intstes0_), .SI(ts_sihw_mux_sea0_not_so31__si31_), 
      .Q(q[0]), .QN(UNCONNECTED30)
  );
  AND2_X2 g1230__2398(
      .A1(n_71), .A2(n_12), .ZN(n_44)
  );
  AND2_X2 g1231__5107(
      .A1(n_74), .A2(n_12), .ZN(n_43)
  );
  AND2_X2 g1232__6260(
      .A1(n_59), .A2(n_12), .ZN(n_42)
  );
  AND2_X2 g1233__4319(
      .A1(n_61), .A2(n_12), .ZN(n_41)
  );
  AND2_X2 g1234__8428(
      .A1(n_60), .A2(n_12), .ZN(n_40)
  );
  AND2_X2 g1235__5526(
      .A1(n_62), .A2(n_12), .ZN(n_39)
  );
  AND2_X2 g1236__6783(
      .A1(n_63), .A2(n_12), .ZN(n_38)
  );
  AND2_X2 g1237__3680(
      .A1(n_64), .A2(n_12), .ZN(n_37)
  );
  AND2_X2 g1238__1617(
      .A1(n_65), .A2(n_12), .ZN(n_36)
  );
  AND2_X2 g1239__2802(
      .A1(n_66), .A2(n_12), .ZN(n_35)
  );
  AND2_X2 g1240__1705(
      .A1(n_67), .A2(n_12), .ZN(n_34)
  );
  AND2_X2 g1241__5122(
      .A1(n_68), .A2(n_12), .ZN(n_33)
  );
  AND2_X2 g1242__8246(
      .A1(n_69), .A2(n_12), .ZN(n_32)
  );
  AND2_X2 g1243__7098(
      .A1(n_70), .A2(n_12), .ZN(n_31)
  );
  AND2_X2 g1244__6131(
      .A1(n_72), .A2(n_12), .ZN(n_30)
  );
  NOR2_X2 g1245__1881(
      .A1(n_11), .A2(q[0]), .ZN(n_29)
  );
  AND2_X2 g1246__5115(
      .A1(n_58), .A2(n_12), .ZN(n_28)
  );
  AND2_X2 g1247__7482(
      .A1(n_76), .A2(n_12), .ZN(n_27)
  );
  AND2_X2 g1248__4733(
      .A1(n_75), .A2(n_12), .ZN(n_26)
  );
  AND2_X2 g1249__6161(
      .A1(n_12), .A2(n_46), .ZN(n_25)
  );
  AND2_X2 g1250__9315(
      .A1(n_12), .A2(n_47), .ZN(n_24)
  );
  AND2_X2 g1251__9945(
      .A1(n_12), .A2(n_48), .ZN(n_23)
  );
  AND2_X2 g1252__2883(
      .A1(n_12), .A2(n_49), .ZN(n_22)
  );
  AND2_X2 g1253__2346(
      .A1(n_12), .A2(n_50), .ZN(n_21)
  );
  AND2_X2 g1254__1666(
      .A1(n_51), .A2(n_12), .ZN(n_20)
  );
  AND2_X2 g1255__7410(
      .A1(n_52), .A2(n_12), .ZN(n_19)
  );
  AND2_X2 g1256__6417(
      .A1(n_12), .A2(n_53), .ZN(n_18)
  );
  AND2_X2 g1257__5477(
      .A1(n_54), .A2(n_12), .ZN(n_17)
  );
  AND2_X2 g1258__2398(
      .A1(n_55), .A2(n_12), .ZN(n_16)
  );
  AND2_X2 g1259__5107(
      .A1(n_56), .A2(n_12), .ZN(n_15)
  );
  AND2_X2 g1260__6260(
      .A1(n_57), .A2(n_12), .ZN(n_14)
  );
  AND2_X2 g1261__4319(
      .A1(n_73), .A2(n_12), .ZN(n_13)
  );
  INV_X4 g1262(
      .A(n_12), .ZN(n_11)
  );
  AND3_X4 g1263__8428(
      .A1(n_10), .A2(n_45), .A3(en), .ZN(n_12)
  );
  NAND2_X2 g1264__5526(
      .A1(n_8), .A2(n_9), .ZN(n_10)
  );
  NOR4_X2 g1265__6783(
      .A1(n_4), .A2(n_6), .A3(n_7), .A4(n_5), .ZN(n_9)
  );
  NOR4_X2 g1266__3680(
      .A1(n_0), .A2(n_3), .A3(n_1), .A4(n_99), .ZN(n_8)
  );
  NAND4_X2 g1267__1617(
      .A1(q[8]), .A2(q[11]), .A3(q[10]), .A4(q[9]), .ZN(n_7)
  );
  NAND4_X2 g1268__2802(
      .A1(q[12]), .A2(q[3]), .A3(q[2]), .A4(q[1]), .ZN(n_6)
  );
  NAND4_X2 g1269__1705(
      .A1(q[4]), .A2(q[7]), .A3(q[6]), .A4(q[5]), .ZN(n_5)
  );
  NAND4_X2 g1270__5122(
      .A1(q[13]), .A2(q[15]), .A3(q[14]), .A4(q[0]), .ZN(n_4)
  );
  NAND4_X2 g1271__8246(
      .A1(q[27]), .A2(q[26]), .A3(q[24]), .A4(q[25]), .ZN(n_3)
  );
  NAND4_X2 g1273__6131(
      .A1(q[23]), .A2(q[22]), .A3(q[20]), .A4(q[21]), .ZN(n_1)
  );
  NAND4_X2 g1274__1881(
      .A1(q[28]), .A2(q[31]), .A3(q[30]), .A4(q[29]), .ZN(n_0)
  );
  XOR2_X2 inc_add_16_8_g482__5115(
      .A(inc_add_16_8_n_63), .B(q[19]), .Z(n_64)
  );
  XOR2_X2 inc_add_16_8_g483__7482(
      .A(inc_add_16_8_n_59), .B(q[31]), .Z(n_76)
  );
  HA_X1 inc_add_16_8_g484__4733(
      .A(inc_add_16_8_n_50), .B(q[18]), .CO(inc_add_16_8_n_63), .S(n_63)
  );
  XOR2_X2 inc_add_16_8_g485__6161(
      .A(inc_add_16_8_n_56), .B(q[29]), .Z(n_74)
  );
  XOR2_X2 inc_add_16_8_g486__9315(
      .A(inc_add_16_8_n_54), .B(q[11]), .Z(n_56)
  );
  HA_X1 inc_add_16_8_g487__9945(
      .A(inc_add_16_8_n_42), .B(q[30]), .CO(inc_add_16_8_n_59), .S(n_75)
  );
  XOR2_X2 inc_add_16_8_g488__2883(
      .A(inc_add_16_8_n_48), .B(q[27]), .Z(n_72)
  );
  HA_X1 inc_add_16_8_g489__2346(
      .A(inc_add_16_8_n_36), .B(q[28]), .CO(inc_add_16_8_n_56), .S(n_73)
  );
  HA_X1 inc_add_16_8_g490__1666(
      .A(inc_add_16_8_n_37), .B(q[10]), .CO(inc_add_16_8_n_54), .S(n_55)
  );
  XOR2_X2 inc_add_16_8_g491__7410(
      .A(inc_add_16_8_n_45), .B(q[25]), .Z(n_70)
  );
  XOR2_X2 inc_add_16_8_g492__6417(
      .A(inc_add_16_8_n_43), .B(q[23]), .Z(n_68)
  );
  HA_X1 inc_add_16_8_g493__5477(
      .A(inc_add_16_8_n_33), .B(q[17]), .CO(inc_add_16_8_n_50), .S(n_62)
  );
  HA_X1 inc_add_16_8_g494__2398(
      .A(inc_add_16_8_n_30), .B(q[26]), .CO(inc_add_16_8_n_48), .S(n_71)
  );
  XOR2_X2 inc_add_16_8_g495__5107(
      .A(inc_add_16_8_n_39), .B(q[21]), .Z(n_66)
  );
  HA_X1 inc_add_16_8_g496__6260(
      .A(inc_add_16_8_n_26), .B(q[24]), .CO(inc_add_16_8_n_45), .S(n_69)
  );
  HA_X1 inc_add_16_8_g497__4319(
      .A(inc_add_16_8_n_27), .B(q[22]), .CO(inc_add_16_8_n_43), .S(n_67)
  );
  AND3_X4 inc_add_16_8_g498__8428(
      .A1(inc_add_16_8_n_36), .A2(q[28]), .A3(q[29]), .ZN(inc_add_16_8_n_42)
  );
  XOR2_X2 inc_add_16_8_g499__5526(
      .A(inc_add_16_8_n_31), .B(q[15]), .Z(n_60)
  );
  HA_X1 inc_add_16_8_g500__6783(
      .A(inc_add_16_8_n_22), .B(q[20]), .CO(inc_add_16_8_n_39), .S(n_65)
  );
  HA_X1 inc_add_16_8_g501__3680(
      .A(inc_add_16_8_n_23), .B(q[9]), .CO(inc_add_16_8_n_37), .S(n_54)
  );
  AND3_X2 inc_add_16_8_g502__1617(
      .A1(inc_add_16_8_n_30), .A2(q[26]), .A3(q[27]), .ZN(inc_add_16_8_n_36)
  );
  XOR2_X2 inc_add_16_8_g503__2802(
      .A(inc_add_16_8_n_28), .B(q[13]), .Z(n_58)
  );
  HA_X1 inc_add_16_8_g504__1705(
      .A(inc_add_16_8_n_17), .B(q[16]), .CO(inc_add_16_8_n_33), .S(n_61)
  );
  HA_X1 inc_add_16_8_g505__5122(
      .A(inc_add_16_8_n_18), .B(q[14]), .CO(inc_add_16_8_n_31), .S(n_59)
  );
  AND3_X2 inc_add_16_8_g506__8246(
      .A1(inc_add_16_8_n_26), .A2(q[24]), .A3(q[25]), .ZN(inc_add_16_8_n_30)
  );
  HA_X1 inc_add_16_8_g507__7098(
      .A(inc_add_16_8_n_12), .B(q[12]), .CO(inc_add_16_8_n_28), .S(n_57)
  );
  AND2_X2 inc_add_16_8_g508__6131(
      .A1(inc_add_16_8_n_22), .A2(inc_add_16_8_n_1), .ZN(inc_add_16_8_n_27)
  );
  AND4_X2 inc_add_16_8_g509__1881(
      .A1(inc_add_16_8_n_22), .A2(inc_add_16_8_n_1), .A3(q[23]), .A4(q[22]), .ZN(inc_add_16_8_n_26)
  );
  XOR2_X2 inc_add_16_8_g510__5115(
      .A(inc_add_16_8_n_19), .B(q[7]), .Z(n_52)
  );
  HA_X1 inc_add_16_8_g511__7482(
      .A(inc_add_16_8_n_9), .B(q[8]), .CO(inc_add_16_8_n_23), .S(n_53)
  );
  NOR2_X2 inc_add_16_8_g512__4733(
      .A1(inc_add_16_8_n_16), .A2(n_99), .ZN(inc_add_16_8_n_22)
  );
  XOR2_X1 inc_add_16_8_g513__6161(
      .A(inc_add_16_8_n_13), .B(q[5]), .Z(n_50)
  );
  HA_X1 inc_add_16_8_g514__9315(
      .A(inc_add_16_8_n_7), .B(q[6]), .CO(inc_add_16_8_n_19), .S(n_51)
  );
  AND2_X2 inc_add_16_8_g515__9945(
      .A1(inc_add_16_8_n_12), .A2(inc_add_16_8_n_0), .ZN(inc_add_16_8_n_18)
  );
  INV_X1 inc_add_16_8_g516(
      .A(inc_add_16_8_n_16), .ZN(inc_add_16_8_n_17)
  );
  NAND4_X2 inc_add_16_8_g517__2883(
      .A1(inc_add_16_8_n_12), .A2(inc_add_16_8_n_0), .A3(q[14]), .A4(q[15]), .ZN(inc_add_16_8_n_16)
  );
  XOR2_X1 inc_add_16_8_g518__2346(
      .A(inc_add_16_8_n_10), .B(q[3]), .Z(n_48)
  );
  HA_X1 inc_add_16_8_g519__1666(
      .A(inc_add_16_8_n_6), .B(q[4]), .CO(inc_add_16_8_n_13), .S(n_49)
  );
  NOR2_X2 inc_add_16_8_g520__7410(
      .A1(inc_add_16_8_n_8), .A2(inc_add_16_8_n_3), .ZN(inc_add_16_8_n_12)
  );
  HA_X1 inc_add_16_8_g521__6417(
      .A(inc_add_16_8_n_5), .B(q[2]), .CO(inc_add_16_8_n_10), .S(n_47)
  );
  INV_X1 inc_add_16_8_g522(
      .A(inc_add_16_8_n_8), .ZN(inc_add_16_8_n_9)
  );
  NAND3_X1 inc_add_16_8_g523__5477(
      .A1(inc_add_16_8_n_7), .A2(q[7]), .A3(q[6]), .ZN(inc_add_16_8_n_8)
  );
  AND3_X2 inc_add_16_8_g524__2398(
      .A1(inc_add_16_8_n_6), .A2(q[4]), .A3(q[5]), .ZN(inc_add_16_8_n_7)
  );
  AND3_X2 inc_add_16_8_g525__5107(
      .A1(inc_add_16_8_n_5), .A2(q[2]), .A3(q[3]), .ZN(inc_add_16_8_n_6)
  );
  HA_X1 inc_add_16_8_g526__6260(
      .A(q[0]), .B(q[1]), .CO(inc_add_16_8_n_5), .S(n_46)
  );
  NAND4_X2 inc_add_16_8_g527__4319(
      .A1(q[11]), .A2(q[8]), .A3(q[9]), .A4(q[10]), .ZN(inc_add_16_8_n_3)
  );
  AND2_X2 inc_add_16_8_g529__5526(
      .A1(q[20]), .A2(q[21]), .ZN(inc_add_16_8_n_1)
  );
  AND2_X2 inc_add_16_8_g530__6783(
      .A1(q[12]), .A2(q[13]), .ZN(inc_add_16_8_n_0)
  );
  NAND4_X2 g1272__1308(
      .A1(q[19]), .A2(q[18]), .A3(q[16]), .A4(q[17]), .ZN(n_99)
  );
  active_high_latch ts_lockup_latchp_clkc2_intno31_i(
      .CLK(clk), .D(q[0]), .Q(ts_lockup_latchp_clkc2_intno31_)
  );
  SDFF_X2 ts_pipeline_fsffn_clkc1_lo0l1_extsi32_sea0_i(
      .CK(clk), .D(ts_pipeline_fsffn_clkc1_lo0l1_extsi32_sea0_), .SE(scan_en), 
      .SI(ts_si), .Q(ts_pipeline_fsffn_clkc1_lo0l1_extsi32_sea0_), .QN()
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so0__si0_i(
      .A(ts_sihw_not_so0_), .B(ts_pipeline_fsffn_clkc1_lo0l1_extsi32_sea0_), .S(scan_en), 
      .Z(ts_sihw_mux_sea0_not_so0__si0_)
  );
  INV_X4 ts_sihw_not_so0_i(
      .A(q[27]), .ZN(ts_sihw_not_so0_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so1__si1_i(
      .A(ts_sihw_not_so1_), .B(q[27]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so1__si1_)
  );
  INV_X4 ts_sihw_not_so1_i(
      .A(q[13]), .ZN(ts_sihw_not_so1_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so2__si2_i(
      .A(ts_sihw_not_so2_), .B(q[13]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so2__si2_)
  );
  INV_X4 ts_sihw_not_so2_i(
      .A(q[14]), .ZN(ts_sihw_not_so2_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so3__si3_i(
      .A(ts_sihw_not_so3_), .B(q[14]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so3__si3_)
  );
  INV_X4 ts_sihw_not_so3_i(
      .A(q[15]), .ZN(ts_sihw_not_so3_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so4__si4_i(
      .A(ts_sihw_not_so4_), .B(q[15]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so4__si4_)
  );
  INV_X4 ts_sihw_not_so4_i(
      .A(q[16]), .ZN(ts_sihw_not_so4_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so5__si5_i(
      .A(ts_sihw_not_so5_), .B(q[16]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so5__si5_)
  );
  INV_X4 ts_sihw_not_so5_i(
      .A(q[17]), .ZN(ts_sihw_not_so5_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so6__si6_i(
      .A(ts_sihw_not_so6_), .B(q[17]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so6__si6_)
  );
  INV_X4 ts_sihw_not_so6_i(
      .A(q[18]), .ZN(ts_sihw_not_so6_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so7__si7_i(
      .A(ts_sihw_not_so7_), .B(q[18]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so7__si7_)
  );
  INV_X4 ts_sihw_not_so7_i(
      .A(q[19]), .ZN(ts_sihw_not_so7_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so8__si8_i(
      .A(ts_sihw_not_so8_), .B(q[19]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so8__si8_)
  );
  INV_X4 ts_sihw_not_so8_i(
      .A(q[20]), .ZN(ts_sihw_not_so8_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so9__si9_i(
      .A(ts_sihw_not_so9_), .B(q[20]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so9__si9_)
  );
  INV_X4 ts_sihw_not_so9_i(
      .A(q[21]), .ZN(ts_sihw_not_so9_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so10__si10_i(
      .A(ts_sihw_not_so10_), .B(q[21]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so10__si10_)
  );
  INV_X4 ts_sihw_not_so10_i(
      .A(q[22]), .ZN(ts_sihw_not_so10_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so11__si11_i(
      .A(ts_sihw_not_so11_), .B(q[22]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so11__si11_)
  );
  INV_X4 ts_sihw_not_so11_i(
      .A(q[23]), .ZN(ts_sihw_not_so11_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so12__si12_i(
      .A(ts_sihw_not_so12_), .B(q[23]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so12__si12_)
  );
  INV_X4 ts_sihw_not_so12_i(
      .A(q[24]), .ZN(ts_sihw_not_so12_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so13__si13_i(
      .A(ts_sihw_not_so13_), .B(q[24]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so13__si13_)
  );
  INV_X4 ts_sihw_not_so13_i(
      .A(q[25]), .ZN(ts_sihw_not_so13_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so14__si14_i(
      .A(ts_sihw_not_so14_), .B(q[25]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so14__si14_)
  );
  INV_X4 ts_sihw_not_so14_i(
      .A(q[26]), .ZN(ts_sihw_not_so14_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so15__si15_i(
      .A(ts_sihw_not_so15_), .B(q[26]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so15__si15_)
  );
  INV_X4 ts_sihw_not_so15_i(
      .A(q[1]), .ZN(ts_sihw_not_so15_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so16__si16_i(
      .A(ts_sihw_not_so16_), .B(q[1]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so16__si16_)
  );
  INV_X4 ts_sihw_not_so16_i(
      .A(q[6]), .ZN(ts_sihw_not_so16_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so17__si17_i(
      .A(ts_sihw_not_so17_), .B(q[6]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so17__si17_)
  );
  INV_X4 ts_sihw_not_so17_i(
      .A(q[30]), .ZN(ts_sihw_not_so17_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so18__si18_i(
      .A(ts_sihw_not_so18_), .B(q[30]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so18__si18_)
  );
  INV_X4 ts_sihw_not_so18_i(
      .A(q[31]), .ZN(ts_sihw_not_so18_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so19__si19_i(
      .A(ts_sihw_not_so19_), .B(q[31]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so19__si19_)
  );
  INV_X4 ts_sihw_not_so19_i(
      .A(q[2]), .ZN(ts_sihw_not_so19_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so20__si20_i(
      .A(ts_sihw_not_so20_), .B(q[2]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so20__si20_)
  );
  INV_X4 ts_sihw_not_so20_i(
      .A(q[3]), .ZN(ts_sihw_not_so20_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so21__si21_i(
      .A(ts_sihw_not_so21_), .B(q[3]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so21__si21_)
  );
  INV_X4 ts_sihw_not_so21_i(
      .A(q[4]), .ZN(ts_sihw_not_so21_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so22__si22_i(
      .A(ts_sihw_not_so22_), .B(q[4]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so22__si22_)
  );
  INV_X4 ts_sihw_not_so22_i(
      .A(q[5]), .ZN(ts_sihw_not_so22_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so23__si23_i(
      .A(ts_sihw_not_so23_), .B(q[5]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so23__si23_)
  );
  INV_X4 ts_sihw_not_so23_i(
      .A(q[29]), .ZN(ts_sihw_not_so23_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so24__si24_i(
      .A(ts_sihw_not_so24_), .B(q[29]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so24__si24_)
  );
  INV_X4 ts_sihw_not_so24_i(
      .A(q[7]), .ZN(ts_sihw_not_so24_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so25__si25_i(
      .A(ts_sihw_not_so25_), .B(q[7]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so25__si25_)
  );
  INV_X4 ts_sihw_not_so25_i(
      .A(q[8]), .ZN(ts_sihw_not_so25_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so26__si26_i(
      .A(ts_sihw_not_so26_), .B(q[8]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so26__si26_)
  );
  INV_X4 ts_sihw_not_so26_i(
      .A(q[9]), .ZN(ts_sihw_not_so26_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so27__si27_i(
      .A(ts_sihw_not_so27_), .B(q[9]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so27__si27_)
  );
  INV_X4 ts_sihw_not_so27_i(
      .A(q[10]), .ZN(ts_sihw_not_so27_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so28__si28_i(
      .A(ts_sihw_not_so28_), .B(q[10]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so28__si28_)
  );
  INV_X4 ts_sihw_not_so28_i(
      .A(q[11]), .ZN(ts_sihw_not_so28_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so29__si29_i(
      .A(ts_sihw_not_so29_), .B(q[11]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so29__si29_)
  );
  INV_X4 ts_sihw_not_so29_i(
      .A(q[12]), .ZN(ts_sihw_not_so29_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so30__si30_i(
      .A(ts_sihw_not_so30_), .B(q[12]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so30__si30_)
  );
  INV_X4 ts_sihw_not_so30_i(
      .A(q[28]), .ZN(ts_sihw_not_so30_)
  );
  MUX2_X2 ts_sihw_mux_sea0_not_so31__si31_i(
      .A(ts_sihw_not_so31_), .B(q[28]), .S(scan_en), .Z(ts_sihw_mux_sea0_not_so31__si31_)
  );
  INV_X4 ts_sihw_not_so31_i(
      .A(q[0]), .ZN(ts_sihw_not_so31_)
  );
  OR2_X4 ts_or_sea0_intstes0_i(
      .A1(scan_en), .A2(int_ltest_en), .ZN(ts_or_sea0_intstes0_)
  );
endmodule

