/* Generated by Tessent Shell 2022.4 at Tue Jun 10 16:36:24 IST 2025 */
module memlibc_memory_bist_assembly(BIST_CLK, m1_A1, m1_A2, m1_WEB1, m1_WEB2, m1_CSB1, 
                                    m1_CSB2, m1_I1, m1_I2, m1_O1, m1_O2);
  input  [15:0] m1_I1, m1_I2;
  input  [8:0] m1_A1, m1_A2;
  input  BIST_CLK, m1_WEB1, m1_WEB2, m1_CSB1, m1_CSB2;
  output [15:0] m1_O1, m1_O2;

  memlibc_memory_bist_assembly_mem_container mem_container_inst(
      .m1_A1(m1_A1), .m1_A2(m1_A2), .BIST_CLK(BIST_CLK), .m1_WEB1(m1_WEB1), .m1_WEB2(m1_WEB2), 
      .m1_CSB1(m1_CSB1), .m1_CSB2(m1_CSB2), .m1_I1(m1_I1), .m1_I2(m1_I2), .m1_mem_inst_O1(m1_O1), 
      .m1_mem_inst_O2(m1_O2)
  );
endmodule

module memlibc_memory_bist_assembly_mem_container(m1_A1, m1_A2, BIST_CLK, m1_WEB1, 
                                                  m1_WEB2, m1_CSB1, m1_CSB2, m1_I1, 
                                                  m1_I2, m1_mem_inst_O1, m1_mem_inst_O2);
  input  [15:0] m1_I1, m1_I2;
  input  [8:0] m1_A1, m1_A2;
  input  BIST_CLK, m1_WEB1, m1_WEB2, m1_CSB1, m1_CSB2;
  output [15:0] m1_mem_inst_O1, m1_mem_inst_O2;

  rd3_512x16 m1_mem_inst(
      .A1(m1_A1), .A2(m1_A2), .CE1(BIST_CLK), .CE2(BIST_CLK), .WEB1(m1_WEB1), .WEB2(m1_WEB2), 
      .OEB1(1'b0), .OEB2(1'b0), .CSB1(m1_CSB1), .CSB2(m1_CSB2), .I1(m1_I1), .I2(m1_I2), 
      .O1(m1_mem_inst_O1), .O2(m1_mem_inst_O2)
  );
endmodule

