
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 12 2025 15:21:44 IST (Mar 12 2025 09:51:44 UTC)

// Verification Directory fv/s298 

module dff(clk, q, d, ts_sea0, ts_extsi14);
  input clk, d, ts_sea0, ts_extsi14;
  output q;
  wire clk, d, ts_sea0, ts_extsi14;
  wire q;
  wire UNCONNECTED;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_extsi14), .Q
       (q), .QN (UNCONNECTED));
endmodule

module dff_26(clk, q, d, ts_sea0, ts_intno0);
  input clk, d, ts_sea0, ts_intno0;
  output q;
  wire clk, d, ts_sea0, ts_intno0;
  wire q;
  wire UNCONNECTED0;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno0), .Q
       (q), .QN (UNCONNECTED0));
endmodule

module dff_25(clk, q, d, ts_sea0, ts_intno13);
  input clk, d, ts_sea0, ts_intno13;
  output q;
  wire clk, d, ts_sea0, ts_intno13;
  wire q;
  wire UNCONNECTED1;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno13), .Q
       (q), .QN (UNCONNECTED1));
endmodule

module dff_24(clk, q, d, ts_sea0, ts_intno2);
  input clk, d, ts_sea0, ts_intno2;
  output q;
  wire clk, d, ts_sea0, ts_intno2;
  wire q;
  wire UNCONNECTED2;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno2), .Q
       (q), .QN (UNCONNECTED2));
endmodule

module dff_23(clk, q, d, ts_sea0, ts_intno3);
  input clk, d, ts_sea0, ts_intno3;
  output q;
  wire clk, d, ts_sea0, ts_intno3;
  wire q;
  wire UNCONNECTED3;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno3), .Q
       (q), .QN (UNCONNECTED3));
endmodule

module dff_22(clk, q, d, ts_sea0, ts_intno4);
  input clk, d, ts_sea0, ts_intno4;
  output q;
  wire clk, d, ts_sea0, ts_intno4;
  wire q;
  wire UNCONNECTED4;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno4), .Q
       (q), .QN (UNCONNECTED4));
endmodule

module dff_21(clk, q, d, ts_sea0, ts_intno5);
  input clk, d, ts_sea0, ts_intno5;
  output q;
  wire clk, d, ts_sea0, ts_intno5;
  wire q;
  wire UNCONNECTED5;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno5), .Q
       (q), .QN (UNCONNECTED5));
endmodule

module dff_20(clk, q, d, ts_sea0, ts_intno6);
  input clk, d, ts_sea0, ts_intno6;
  output q;
  wire clk, d, ts_sea0, ts_intno6;
  wire q;
  wire UNCONNECTED6;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno6), .Q
       (q), .QN (UNCONNECTED6));
endmodule

module dff_19(clk, q, d, ts_sea0, ts_intno7);
  input clk, d, ts_sea0, ts_intno7;
  output q;
  wire clk, d, ts_sea0, ts_intno7;
  wire q;
  wire UNCONNECTED7;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno7), .Q
       (q), .QN (UNCONNECTED7));
endmodule

module active_high_latch(CLK, D, Q);
  input CLK, D;
  output Q;
  wire CLK, D;
  wire Q;
  DLH_X1 Q_reg(.G (CLK), .D (D), .Q (Q));
endmodule

module dff_18(clk, q, d, ts_sea0, ts_intno8, ts_no9);
  input clk, d, ts_sea0, ts_intno8;
  output q, ts_no9;
  wire clk, d, ts_sea0, ts_intno8;
  wire q, ts_no9;
  wire UNCONNECTED8;
  active_high_latch ts_lockup_latchp_clkc1_intno9_i(.CLK (clk), .D (q),
       .Q (ts_no9));
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno8), .Q
       (q), .QN (UNCONNECTED8));
endmodule

module dff_17(clk, q, d, ts_sea0, ts_intno1);
  input clk, d, ts_sea0, ts_intno1;
  output q;
  wire clk, d, ts_sea0, ts_intno1;
  wire q;
  wire UNCONNECTED9;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno1), .Q
       (q), .QN (UNCONNECTED9));
endmodule

module dff_16(clk, q, d, ts_sea0, ts_intno10);
  input clk, d, ts_sea0, ts_intno10;
  output q;
  wire clk, d, ts_sea0, ts_intno10;
  wire q;
  wire UNCONNECTED10;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno10), .Q
       (q), .QN (UNCONNECTED10));
endmodule

module dff_15(clk, q, d, ts_sea0, ts_intno11);
  input clk, d, ts_sea0, ts_intno11;
  output q;
  wire clk, d, ts_sea0, ts_intno11;
  wire q;
  wire UNCONNECTED11;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno11), .Q
       (q), .QN (UNCONNECTED11));
endmodule

module dff_14(clk, q, d, ts_sea0, ts_intno12);
  input clk, d, ts_sea0, ts_intno12;
  output q;
  wire clk, d, ts_sea0, ts_intno12;
  wire q;
  wire UNCONNECTED12;
  SDFF_X2 q_reg(.CK (clk), .D (d), .SE (ts_sea0), .SI (ts_intno12), .Q
       (q), .QN (UNCONNECTED12));
endmodule

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67,
     ts_si, ts_so, scan_en);
  input GND, VDD, CK, G0, G1, G2, scan_en;
  input [0:0] ts_si;
  output G117, G118, G132, G133, G66, G67;
  output [0:0] ts_so;
  wire GND, VDD, CK, G0, G1, G2, scan_en;
  wire [0:0] ts_si;
  wire G117, G118, G132, G133, G66, G67;
  wire [0:0] ts_so;
  wire G10, G11, G12, G13, G14, G15, G22, G23;
  wire G29, G30, G34, G39, G44, G56, G86, G92;
  wire G98, G102, G107, G113, G119, G125, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  dff DFF_0(CK, G10, G29, scan_en, ts_si);
  dff_26 DFF_1(CK, G11, G30, scan_en, G10);
  dff_25 DFF_2(CK, G12, G34, scan_en, G23);
  dff_24 DFF_3(CK, G13, G39, scan_en, G12);
  dff_23 DFF_4(CK, G14, G44, scan_en, G13);
  dff_22 DFF_5(CK, G15, G56, scan_en, G14);
  dff_21 DFF_6(CK, G66, G86, scan_en, G15);
  dff_20 DFF_7(CK, G67, G92, scan_en, G66);
  dff_19 DFF_8(CK, G117, G98, scan_en, G67);
  dff_18 DFF_9(CK, G118, G102, scan_en, G117, ts_so);
  dff_17 DFF_10(CK, G132, G107, scan_en, G11);
  dff_16 DFF_11(CK, G133, G113, scan_en, G132);
  dff_15 DFF_12(CK, G22, G119, scan_en, G133);
  dff_14 DFF_13(CK, G23, G125, scan_en, G22);
  OAI211_X2 g1218__2398(.A (n_77), .B (n_84), .C1 (n_62), .C2 (G10),
       .ZN (G102));
  OAI211_X2 g1219__5107(.A (n_80), .B (n_69), .C1 (n_83), .C2 (G10),
       .ZN (G107));
  NOR2_X2 g1220__6260(.A1 (n_83), .A2 (G0), .ZN (G56));
  NOR2_X2 g1221__4319(.A1 (n_82), .A2 (G0), .ZN (G44));
  OAI211_X2 g1222__8428(.A (n_79), .B (n_74), .C1 (n_60), .C2 (G11),
       .ZN (G92));
  NOR2_X2 g1223__5526(.A1 (n_75), .A2 (G0), .ZN (G39));
  AOI21_X1 g1224__6783(.A (n_70), .B1 (n_68), .B2 (G118), .ZN (n_84));
  NAND2_X2 g1225__3680(.A1 (n_77), .A2 (n_78), .ZN (G86));
  NAND3_X2 g1226__1617(.A1 (n_81), .A2 (n_74), .A3 (n_60), .ZN (G98));
  XOR2_X1 g1227__2802(.A (n_72), .B (G14), .Z (n_82));
  OAI21_X2 g1228__1705(.A (n_76), .B1 (n_60), .B2 (n_49), .ZN (G113));
  AOI21_X2 g1229__5122(.A (n_73), .B1 (n_71), .B2 (G15), .ZN (n_83));
  NAND2_X1 g1230__8246(.A1 (n_68), .A2 (G117), .ZN (n_81));
  NAND2_X1 g1231__7098(.A1 (n_68), .A2 (G132), .ZN (n_80));
  NAND2_X1 g1232__6131(.A1 (n_68), .A2 (G67), .ZN (n_79));
  NAND2_X1 g1233__1881(.A1 (n_68), .A2 (G66), .ZN (n_78));
  NOR2_X2 g1234__5115(.A1 (n_65), .A2 (G0), .ZN (G30));
  NAND2_X1 g1235__7482(.A1 (n_68), .A2 (G133), .ZN (n_76));
  AOI211_X2 g1236__4733(.A (n_57), .B (n_64), .C1 (n_61), .C2 (G13),
       .ZN (n_75));
  NOR2_X2 g1237__6161(.A1 (n_66), .A2 (G0), .ZN (G34));
  AND2_X2 g1238__9315(.A1 (n_71), .A2 (n_67), .ZN (n_77));
  NOR2_X2 g1239__9945(.A1 (n_58), .A2 (G0), .ZN (G125));
  NOR2_X2 g1240__2883(.A1 (n_59), .A2 (G0), .ZN (G119));
  NOR3_X2 g1241__2346(.A1 (n_55), .A2 (n_53), .A3 (G14), .ZN (n_73));
  AOI21_X2 g1242__1666(.A (G23), .B1 (n_54), .B2 (n_52), .ZN (n_72));
  NAND2_X2 g1243__7410(.A1 (n_63), .A2 (G11), .ZN (n_74));
  INV_X4 g1244(.A (n_69), .ZN (n_70));
  OAI211_X2 g1245__6417(.A (n_56), .B (n_47), .C1 (n_55), .C2 (G12),
       .ZN (n_67));
  XOR2_X2 g1246__5477(.A (n_50), .B (G12), .Z (n_66));
  AOI22_X2 g1247__2398(.A1 (n_54), .A2 (n_53), .B1 (G11), .B2 (n_45),
       .ZN (n_65));
  NAND2_X2 g1248__5107(.A1 (n_64), .A2 (n_48), .ZN (n_71));
  NAND3_X2 g1249__6260(.A1 (n_63), .A2 (n_43), .A3 (G14), .ZN (n_69));
  NOR3_X2 g1250__4319(.A1 (n_51), .A2 (n_46), .A3 (G15), .ZN (n_68));
  NOR2_X2 g1251__8428(.A1 (n_56), .A2 (G15), .ZN (n_62));
  OAI21_X2 g1252__5526(.A (G10), .B1 (G11), .B2 (n_44), .ZN (n_61));
  NOR2_X2 g1253__6783(.A1 (n_53), .A2 (n_43), .ZN (n_64));
  AND2_X2 g1254__3680(.A1 (n_51), .A2 (n_47), .ZN (n_63));
  XNOR2_X1 g1255__1617(.A (G22), .B (G2), .ZN (n_59));
  XNOR2_X1 g1256__2802(.A (G23), .B (G1), .ZN (n_58));
  NOR3_X2 g1257__1705(.A1 (n_50), .A2 (n_44), .A3 (G13), .ZN (n_57));
  OR3_X2 g1258__5122(.A1 (G14), .A2 (G15), .A3 (G13), .ZN (n_60));
  INV_X2 g1259(.A (n_53), .ZN (n_52));
  AND2_X4 g1260__8246(.A1 (n_46), .A2 (G13), .ZN (n_56));
  NAND2_X2 g1261__7098(.A1 (n_43), .A2 (G22), .ZN (n_55));
  NOR2_X2 g1262__6131(.A1 (G11), .A2 (n_45), .ZN (n_54));
  NAND2_X2 g1263__1881(.A1 (n_44), .A2 (G13), .ZN (n_53));
  NAND2_X2 g1264__5115(.A1 (G11), .A2 (G12), .ZN (n_49));
  NOR2_X2 g1265__7482(.A1 (G10), .A2 (G0), .ZN (G29));
  NOR2_X2 g1266__4733(.A1 (G14), .A2 (G22), .ZN (n_48));
  NOR2_X2 g1267__6161(.A1 (G12), .A2 (G13), .ZN (n_51));
  NAND2_X2 g1268__9315(.A1 (G11), .A2 (G10), .ZN (n_50));
  INV_X1 g1269(.A (G15), .ZN (n_47));
  INV_X2 g1270(.A (G14), .ZN (n_46));
  INV_X2 g1271(.A (G10), .ZN (n_45));
  INV_X4 g1272(.A (G12), .ZN (n_44));
  INV_X2 g1273(.A (G11), .ZN (n_43));
endmodule

