
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 30 2025 16:42:52 IST (Apr 30 2025 11:12:52 UTC)

// Verification Directory fv/sram_sp_32768d_33w_16m_8b 

module sram_sp_32768d_33w_16m_8b(CLK, CEN, GWEN, A, D, WEN, Q);
  input CLK, CEN, GWEN;
  input [14:0] A;
  input [32:0] D, WEN;
  output [32:0] Q;
  wire CLK, CEN, GWEN;
  wire [14:0] A;
  wire [32:0] D, WEN;
  wire [32:0] Q;
  wire [4:0] \q_5bit[0] ;
  wire [4:0] \q_5bit[1] ;
  wire [4:0] \q_5bit[2] ;
  wire [4:0] \q_5bit[3] ;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire \cen_internal[0] , \cen_internal[1] , \cen_internal[2] ,
       \cen_internal[3] , n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_65, n_73, n_81, n_89, n_97;
  spram_8192_7 \gen_banks[0].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[0] ), .WEB (n_65), .A ({1'b0, A[11:0]}), .I
       ({2'b0, D[32:28]}), .O ({UNCONNECTED0, UNCONNECTED, \q_5bit[0]
       }));
  spram_8192_7 \gen_banks[0].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (n_97), .A ({1'b0,
       A[11:0]}), .I (D[6:0]), .O (Q[6:0]));
  spram_8192_7 \gen_banks[0].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (n_89), .A ({1'b0,
       A[11:0]}), .I (D[13:7]), .O (Q[13:7]));
  spram_8192_7 \gen_banks[0].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (n_81), .A ({1'b0,
       A[11:0]}), .I (D[20:14]), .O (Q[20:14]));
  spram_8192_7 \gen_banks[0].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[0] ), .WEB (n_73), .A ({1'b0,
       A[11:0]}), .I (D[27:21]), .O (Q[27:21]));
  spram_8192_7 \gen_banks[1].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[1] ), .WEB (n_65), .A ({1'b0, A[11:0]}), .I
       ({2'b0, D[32:28]}), .O ({UNCONNECTED2, UNCONNECTED1, \q_5bit[1]
       }));
  spram_8192_7 \gen_banks[1].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (n_97), .A ({1'b0,
       A[11:0]}), .I (D[6:0]), .O (Q[6:0]));
  spram_8192_7 \gen_banks[1].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (n_89), .A ({1'b0,
       A[11:0]}), .I (D[13:7]), .O (Q[13:7]));
  spram_8192_7 \gen_banks[1].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (n_81), .A ({1'b0,
       A[11:0]}), .I (D[20:14]), .O (Q[20:14]));
  spram_8192_7 \gen_banks[1].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[1] ), .WEB (n_73), .A ({1'b0,
       A[11:0]}), .I (D[27:21]), .O (Q[27:21]));
  spram_8192_7 \gen_banks[2].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[2] ), .WEB (n_65), .A ({1'b0, A[11:0]}), .I
       ({2'b0, D[32:28]}), .O ({UNCONNECTED4, UNCONNECTED3, \q_5bit[2]
       }));
  spram_8192_7 \gen_banks[2].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (n_97), .A ({1'b0,
       A[11:0]}), .I (D[6:0]), .O (Q[6:0]));
  spram_8192_7 \gen_banks[2].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (n_89), .A ({1'b0,
       A[11:0]}), .I (D[13:7]), .O (Q[13:7]));
  spram_8192_7 \gen_banks[2].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (n_81), .A ({1'b0,
       A[11:0]}), .I (D[20:14]), .O (Q[20:14]));
  spram_8192_7 \gen_banks[2].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[2] ), .WEB (n_73), .A ({1'b0,
       A[11:0]}), .I (D[27:21]), .O (Q[27:21]));
  spram_8192_7 \gen_banks[3].u_sram5_my_sram (.CEB (CLK), .OEB (1'b0),
       .CSB (\cen_internal[3] ), .WEB (n_65), .A ({1'b0, A[11:0]}), .I
       ({2'b0, D[32:28]}), .O ({UNCONNECTED6, UNCONNECTED5, \q_5bit[3]
       }));
  spram_8192_7 \gen_banks[3].u_sram7_0_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (n_97), .A ({1'b0,
       A[11:0]}), .I (D[6:0]), .O (Q[6:0]));
  spram_8192_7 \gen_banks[3].u_sram7_1_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (n_89), .A ({1'b0,
       A[11:0]}), .I (D[13:7]), .O (Q[13:7]));
  spram_8192_7 \gen_banks[3].u_sram7_2_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (n_81), .A ({1'b0,
       A[11:0]}), .I (D[20:14]), .O (Q[20:14]));
  spram_8192_7 \gen_banks[3].u_sram7_3_my_sram (.CEB (CLK), .OEB
       (1'b0), .CSB (\cen_internal[3] ), .WEB (n_73), .A ({1'b0,
       A[11:0]}), .I (D[27:21]), .O (Q[27:21]));
  NAND2BX1 g738__2398(.AN (WEN[0]), .B (GWEN), .Y (n_97));
  NAND2BX1 g739__5107(.AN (WEN[7]), .B (GWEN), .Y (n_89));
  NAND2BX1 g740__6260(.AN (WEN[21]), .B (GWEN), .Y (n_73));
  NAND2BX1 g741__4319(.AN (WEN[28]), .B (GWEN), .Y (n_65));
  NAND2BX1 g742__8428(.AN (WEN[14]), .B (GWEN), .Y (n_81));
  NAND2XL g1087__5526(.A (n_13), .B (n_18), .Y (Q[32]));
  NAND2XL g1088__6783(.A (n_11), .B (n_19), .Y (Q[31]));
  NAND2XL g1089__3680(.A (n_12), .B (n_17), .Y (Q[30]));
  NAND2XL g1090__1617(.A (n_14), .B (n_16), .Y (Q[29]));
  NAND2XL g1091__2802(.A (n_10), .B (n_15), .Y (Q[28]));
  AOI22XL g1092__1705(.A0 (n_5), .A1 (\q_5bit[2] [3]), .B0 (n_6), .B1
       (\q_5bit[3] [3]), .Y (n_19));
  AOI22XL g1093__5122(.A0 (n_5), .A1 (\q_5bit[2] [4]), .B0 (n_6), .B1
       (\q_5bit[3] [4]), .Y (n_18));
  AOI22XL g1094__8246(.A0 (n_5), .A1 (\q_5bit[2] [2]), .B0 (n_6), .B1
       (\q_5bit[3] [2]), .Y (n_17));
  AOI22XL g1095__7098(.A0 (n_5), .A1 (\q_5bit[2] [1]), .B0 (n_6), .B1
       (\q_5bit[3] [1]), .Y (n_16));
  AOI22XL g1096__6131(.A0 (n_5), .A1 (\q_5bit[2] [0]), .B0 (n_6), .B1
       (\q_5bit[3] [0]), .Y (n_15));
  AOI22XL g1097__1881(.A0 (n_8), .A1 (\q_5bit[0] [1]), .B0 (n_9), .B1
       (\q_5bit[1] [1]), .Y (n_14));
  AOI22XL g1098__5115(.A0 (n_8), .A1 (\q_5bit[0] [4]), .B0 (n_9), .B1
       (\q_5bit[1] [4]), .Y (n_13));
  AOI22XL g1099__7482(.A0 (n_8), .A1 (\q_5bit[0] [2]), .B0 (n_9), .B1
       (\q_5bit[1] [2]), .Y (n_12));
  AOI22XL g1100__4733(.A0 (n_8), .A1 (\q_5bit[0] [3]), .B0 (n_9), .B1
       (\q_5bit[1] [3]), .Y (n_11));
  AOI22XL g1101__6161(.A0 (n_8), .A1 (\q_5bit[0] [0]), .B0 (n_9), .B1
       (\q_5bit[1] [0]), .Y (n_10));
  OR2X2 g1102__9315(.A (CEN), .B (n_7), .Y (\cen_internal[0] ));
  OR2X2 g1103__9945(.A (CEN), .B (n_4), .Y (\cen_internal[2] ));
  OR3X2 g1105__2883(.A (CEN), .B (n_0), .C (n_3), .Y (\cen_internal[3]
       ));
  INVX1 g1107(.A (n_7), .Y (n_8));
  NOR2XL g1108__2346(.A (A[13]), .B (n_3), .Y (n_9));
  NAND2XL g1109__1666(.A (n_2), .B (n_0), .Y (n_7));
  INVX1 g1110(.A (n_4), .Y (n_5));
  OAI2BB1X1 g1111__7410(.A0N (A[12]), .A1N (A[13]), .B0 (n_1), .Y
       (n_6));
  NAND2XL g1112__6417(.A (n_2), .B (A[13]), .Y (n_4));
  NAND2XL g1113__5477(.A (n_1), .B (A[12]), .Y (n_3));
  NOR2XL g1114__2398(.A (A[12]), .B (A[14]), .Y (n_2));
  INVX1 g1115(.A (A[14]), .Y (n_1));
  INVX1 g1116(.A (A[13]), .Y (n_0));
  NAND2BX2 g2__5107(.AN (CEN), .B (n_9), .Y (\cen_internal[1] ));
endmodule

